### ISSUE TITLE
[功能建议] 一键清空 SYSTEM 外的内容；可拖动标签栏；复制回复

### ISSUE THREAD

**Issue by rockbenben** [Bin-Huang/chatbox#10]
## 一键清空 SYSTEM 外的内容

通常情况下，我会将多个常用提示词保存在右侧标签栏中。但是，由于使用次数过多，token 已经达到其上限。因此，旧的对话会干扰新的回复。希望增加一个功能，能够一键清空 SYSTEM 外的内容。

## 可拖动标签栏

标签栏内保存着不同的提示词，希望能够改变它们的排列顺序，使得使用更加方便。

## 一键复制回复

回复内容经常需要复制到其他地方，希望增加一个针对回复的复制按钮，能够轻松快捷地进行复制。

**Comment by Bin-Huang** [comment]
好的，加入 todo list

**Comment by Bin-Huang** [comment]
一键复制回复，这个功能已经发布了，试试最新版本：https://github.com/Bin-Huang/chatbox/releases

**Comment by rockbenben** [comment]
期待后续更新

**Comment by Bin-Huang** [comment]
忘记说了，一键清理系统消息以外的历史消息也在昨天发布了。

标签栏和其他issues重复，我先关闭了

**Comment by yy1781051483** [comment]
可拖动标签栏
标签栏内保存着不同的提示词，希望能够改变它们的排列顺序，使得使用更加方便。可以置顶某些标签栏
