### ISSUE TITLE
[Feature] Have "Ignore messages above" checkbox

### ISSUE THREAD

**Issue by thijse** [Bin-Huang/chatbox#1000]
**Problem Description**
Often, chats get longer and longer, requiring more and more token , especially for programming tasks, while the earlier chat items are not relevant anymore for the last responses

**Proposed Solution**
I would like to set "Ignore messages above" for a certain message. The items above should then probably look greyed out to make the difference clear

**Comment by Bin-Huang** [comment]
This idea is great, I plan to implement it.

**Comment by thijse** [comment]
Awesome! 

When I finally understood that the API does not store any history, but instead you send the history at every prompt, it changed how I looked at features for an LLM chat client, particularly around modifying the chat history, I think your client is one of the most full-featured in that respect. I have some other ideas as well, I hope you don't mind me posting those as feature requests?

**Comment by Bin-Huang** [comment]
> Awesome!
> 
> When I finally understood that the API does not store any history, but instead you send the history at every prompt, it changed how I looked at features for an LLM chat client, particularly around modifying the chat history, I think your client is one of the most full-featured in that respect. I have some other ideas as well, I hope you don't mind me posting those as feature requests?

Really looking forward to hearing more of your feature requests! 😍

**Comment by somehotnail** [comment]
> This idea is great, I plan to implement it.
How about context compression for chatGPT-Next-Web, which enables automatic summarization based on a set threshold to reduce token consumption.

**Comment by Bin-Huang** [comment]
It is already supported in the new version.
https://github.com/Bin-Huang/chatbox/releases
