### ISSUE TITLE
 Ctrl + Enter on Mac not working [BUG]

### ISSUE THREAD

**Issue by AndrewTriesToCode** [Bin-Huang/chatbox#1001]
Edit: user error

**Comment by Bin-Huang** [comment]
Hello, could you please provide more details on how you encountered this error? I would appreciate a detailed description of your actions and expectations.

**Comment by AndrewTriesToCode** [comment]
It was just me not understanding. I thought Ctl-Enter would generate another reply without me typing in a new prompt but I realize that is not the intended function. 

Would love to have that functionality though—just have it keep sending me responses without me having to submit a prompt each time.

**Comment by Bin-Huang** [comment]
Just click the "Reply Again Below" button. This is what you need. 😆

**Comment by AndrewTriesToCode** [comment]
Can that button be moved down to the bottom of the response, so I can have it. generate a follow up response that is added to the end of the chat and that includes its own prior response in the context. Like this:

1) My question
2) initial response from chatgpt
3) continued response from chatgpt (without me having to enter any new input after (2))
