### ISSUE TITLE
[Feature] 支持ollama后台

### ISSUE THREAD

**Issue by franksonet** [Bin-Huang/chatbox#1003]
**问题描述**
在mac和linux上用ollama来跑开源llm模型极其简便，但无法用chatbox调用

**解决思路**
在大模型选项中增加ollama，支持ollama的API格式

**Comment by giacomorebonato** [comment]
Duplicate of https://github.com/Bin-Huang/chatbox/issues/979

**Comment by Bin-Huang** [comment]
It is already supported in the new version.
在新版本已经支持了
https://github.com/Bin-Huang/chatbox/releases
