### ISSUE TITLE
[Feature] GPT4多模态支持，充分发挥G4能量

### ISSUE THREAD

**Issue by OliverVin** [Bin-Huang/chatbox#1007]
GPT4多模态支持大概什么时候可以得到支持，以充分发挥G4能量

**Comment by Bin-Huang** [comment]
Looks like this issue might be from an older version. If you're still seeing the problem in the latest release, go ahead and reopen this!

随着版本的更新，这个 issue 可能过时了。如果最新版本依然存在这个问题，请随时重新开启这个 issue
