### ISSUE TITLE
[BUG]使用chatglm3-6b-32k的模型接口报错API Error: {"detail":"Not Found"}

### ISSUE THREAD

**Issue by leeyis** [Bin-Huang/chatbox#1008]
**描述**
本地已部署chatglm3-6b-32k，且安装了openai兼容性模块，可以使用openai格式的接口，目前通过测试的脚本调用正常，但是配置在chatbox客户端就报错API Error: {"detail":"Not Found"}

**重现步骤**
1.点击设置进入配置页面
2.AI模型提供方选择“OpenAI API”
3.OpenAI API密钥留空
4.API域名填写“http://127.0.0.1:9000/v1”
5.其他所有参数保持默认，点击保存
6.回到聊天窗口提交任意prompt
**期望结果**
正常返回模型的回复内容

**实际结果**
报错API Error: {"detail":"Not Found"}

**截图**
设置如下：
![image](https://github.com/Bin-Huang/chatbox/assets/10876306/3df36a33-fecd-49d3-b1d4-dac8f1cf6ce5)
报错如下：
![image](https://github.com/Bin-Huang/chatbox/assets/10876306/fb2f860b-cc27-4efb-8851-c7e81e94fff8)
测试文件代码如下：
![image](https://github.com/Bin-Huang/chatbox/assets/10876306/1741c36c-98bc-4f8a-9e50-36a630b4aa56)
命令行调用结果如下：
![image](https://github.com/Bin-Huang/chatbox/assets/10876306/3b81b3d1-2915-4af4-950f-66a1884f954f)

**桌面端：**

-   操作系统：windows 11
-   应用程序版本：1.1.2

**Comment by Autumn-Whisper** [comment]
把v1去掉

**Comment by zzjw0611** [comment]
> 把v1去掉

去掉不行啊，404了
