### ISSUE TITLE
建议将对话记录可归纳管理

### ISSUE THREAD

**Issue by kickTiger** [Bin-Huang/chatbox#101]
## 建议
左侧的对话记录多了起来，就接近于无法管理了，建议如下：
1、对话可选择归档，就不会在左侧显示。可以去归档区查看。
2、对话可添加tags，进行分类。

### 1 对话归档：
a) 点击左侧对话记录中的三个点图标。
b) 在弹出窗口中，选择“归档”。
c) 已归档的对话将从左侧的列表中移除。
d) 您可以在“归档”标签下查看所有已归档的对话记录。

### 2 对话标签：
a) 点击左侧对话记录中的三个点图标。
b) 在弹出窗口中，选择“添加标签”。
c) 输入标签名称并点击“添加”。
d) 已添加标签的对话记录将根据标签名称归类。
e) 可以通过在左侧的搜索栏，点击 **标签名称tab面板** 来快速查找对话记录。

**Comment by ZhuoFan-Z** [comment]
支持！星标置顶已经有了，再加上归档就完美了

**Comment by woodgear** [comment]
+1 俺也觉得有归档功能就好了。
