### ISSUE TITLE
[Feature] 停止按钮的改进建议

### ISSUE THREAD

**Issue by wangbiye** [Bin-Huang/chatbox#1013]
作者对于停止按钮也改过多次了, 最近使用时还是有"追着点"的感觉, 主要发生在列表内容比较多生成答案会让列表滚动的时候, 建议加一个键盘快捷键吧

**Comment by pandacase** [comment]
赞成，暂停键的使用体验有点糟糕。以及在生成文本的过程中，整个客户端会变得非常卡，特别是这个时候如果尝试修改窗口大小，整个客户端会直接冻结住直到后台文本接收完毕

**Comment by Bin-Huang** [comment]
请问是什么版本呢？

**Comment by wangbiye** [comment]
@Bin-Huang 我提出问题的时候是 1.1.2 版本, 当列表内容比较多的时候, 边输出新内容边滚动的时候会有"追着点"的感觉, 虽然停止按钮那个工具栏跳动已经不明显了, 但还是有一点点跳动, 如果需要点停止的时候是因为意外发送了信息, 还有点手忙脚乱, 就不太好点

**Comment by Bin-Huang** [comment]
> 最新版好像不会了，只是文本生成速度变慢了

版本更新不会影响回答速度的，这个主要和模型服务有关。因为模型的资源紧张速度一直都是忽高忽低。

**Comment by Bin-Huang** [comment]
> @Bin-Huang 我提出问题的时候是 1.1.2 版本, 当列表内容比较多的时候, 边输出新内容边滚动的时候会有"追着点"的感觉, 虽然停止按钮那个工具栏跳动已经不明显了, 但还是有一点点跳动, 如果需要点停止的时候是因为意外发送了信息, 还有点手忙脚乱, 就不太好点

那我再看一下这个问题

**Comment by Bin-Huang** [comment]
新版本改进了很多，可以再试试看。
