### ISSUE TITLE
新的GPT4-TurboAPI支持

### ISSUE THREAD

**Issue by CyanWoods** [Bin-Huang/chatbox#1017]
这两天OpenAI公布了GPT4-Turbo，看上去性能更好而且价格也更低，请问作者有没有接入这个模型的计划。

**Comment by cocoonkid** [comment]
CyanWoods beat me to it. Yes please add gpt-4-1106-preview as option asap!!!! ❤️

**Comment by Chivier** [comment]
Yes, custom model cannot work for `gpt-4-1106-preview`.

<img width="1207" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/41494877/26da4134-7b42-4404-9ac1-36eb5fddbc5a">

**Comment by Chivier** [comment]
Sorry, it works now. Here is my settings
<img width="560" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/41494877/b0c8c8be-0223-4135-ba63-00837548ed40">

**Comment by DennisPing** [comment]
@Chivier Did you add the option yourself and recompile the code? Or did it automatically show up in the dropdown menu?

**Comment by ozgur-d** [comment]
token max limit should be 128.000

**Comment by cocoonkid** [comment]
Thanks, yes got it working too. RTFM lol

Yes, let's be able to adjust the token limit to 128k !

**Comment by baronliu** [comment]
However, I found that after setting it according to Chivier's method, after a period of time, the settings would be reset. I am using a Mac.

**Comment by Chivier** [comment]
I think the reason our settings are different is because of the chatbox version (and maybe system version).
<img width="844" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/41494877/5754c9eb-5dc5-4cc0-a32a-2f8e349a5992">
<img width="574" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/41494877/43e46432-be86-435a-96f5-3c801fc35e2b">

**Comment by kissint8** [comment]
Tks Chivier, it works.

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases
The new version has added relevant model options, give it a try!
