### ISSUE TITLE
[Feature]gpt-4-vision-preview support

### ISSUE THREAD

**Issue by CloudMusicCIO** [Bin-Huang/chatbox#1018]
It is my earnest desire for an expeditious implementation of the new 1106 model, inclusive of backing for the 'gpt-4-vision-preview' model, along with the facility for transmitting graphic-textual content.

**Comment by ft0907** [comment]
作者应该尽快出4.0-turbo的支持

**Comment by Bin-Huang** [comment]
I already updated it a week or two ago, please update it again.
