### ISSUE TITLE
[Feature]How to set username and password in Network Proxy

### ISSUE THREAD

**Issue by estorm2008** [Bin-Huang/chatbox#1030]
**Problem Description**
The proxy service I am using requires a username and password. The proxy server settings interface of the software only allows me to set the address, and does not provide an option to set a username and password.

**Proposed Solution**
Can the setting interface for Network Proxy be expanded to include options for entering a username and password?

**Comment by Bin-Huang** [comment]
I'm not sure if this will be successful, but it's worth a try: 
prototype://username:password@host:port

**Comment by estorm2008** [comment]
I'm using an HTTP proxy and followed your instructions, but I encountered the following error:
![002](https://github.com/Bin-Huang/chatbox/assets/22424728/97df4bb5-d92b-48a9-b3a0-bd87b48fd4a0)

The proxy server I set up is functioning normally. Here is the code I tested:

![001](https://github.com/Bin-Huang/chatbox/assets/22424728/2393c0c1-36c7-425c-9170-48da7d14575f)
