### ISSUE TITLE
[Feature] 建议支持自定义配置HTTP headers，便于接入第三方观测平台

### ISSUE THREAD

**Issue by toomanyopenfiles** [Bin-Huang/chatbox#1034]
支持更加灵活的HTTP headers配置，可以让chatbox的可扩展性增强，方便接入第三方AIOps平台。

**问题描述**
某些LLM可观测性平台（例如helicone.ai）的接入，需要提供额外的HTTP headers，当前chatbox不支持配置额外自定义的HTTP headers。

**解决思路**
1. 在chatbox的配置页中，除了可以配置自定义apikey和url之外，再提供一个kv列表，可以配置多个HTTP headers。
2. 在初始化OpenAI client时，将用户配置的自定义headers放入default_headers中

**附加上下文**
Helicone接入文档的示例：
https://docs.helicone.ai/getting-started/integration-method/openai-proxy
https://docs.helicone.ai/getting-started/integration-method/gateway

**Comment by Bin-Huang** [comment]
我不确定这是不是大多数人需要的，所以暂时没有这个计划

**Comment by nosqlcoco** [comment]
同样的需求，我在使用kserve部署deepseek模型，通过istio暴露deepseek推理服务，需要添加-H "Host: ${SERVICE_HOSTNAME}"

**Comment by kitroling** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by k15201363625** [comment]
+1 很需要！

**Comment by Kirushikesh** [comment]
Is this feature adding anytime soon?
