### ISSUE TITLE
[Feature] Move "stop generating" button (to keep it still)

### ISSUE THREAD

**Issue by JohanWinther** [Bin-Huang/chatbox#1035]
**Problem Description**
When the AI is streaming the answer the controls including the stop button move together with the content of the box, making it really hard to click the button.

**Proposed Solution**
The control box for each message is moved either to the top or to the left where it will not move depending on the content of the message.

**Additional Context**
![moving-button](https://github.com/Bin-Huang/chatbox/assets/28558941/e78bf8e2-a26d-4036-b803-c2615e426fd6)
The gif above shows a mild version of the problem. It is more evident when generating code or text that have a lot of line breaks.

**Comment by Bin-Huang** [comment]
This is indeed an issue that I have rarely noticed, but it deserves attention. Let me think about how it should be fixed.

**Comment by myboxi** [comment]
![Screenshot_2023-11-20 08 55 05_E2wn6c](https://github.com/Bin-Huang/chatbox/assets/62254500/8442e864-ed2b-43d0-a4a9-a737af1ce2fe)
and i just see the "stop generating" button but no text at all.
its the chatbox 3.5 ai.

will you ever run your own chatGPT4 on your own server? :D

**Comment by M-10777** [comment]
> This is indeed an issue that I have rarely noticed, but it deserves attention. Let me think about how it should be fixed.

还有一个问题：
当对话框中存在多行文本且ChatGPT正在生成回答时，这个小工具栏会出现明显的向下偏移，而不是紧跟在回答后面
ChatBox 1.2.1 Windows11 23H2

**Comment by myboxi** [comment]
Chatbot stops by longer answer. Like providing me code. In one string. Or longer answer

**Comment by Bin-Huang** [comment]
@myboxi This is related to your network and API.

**Comment by myboxi** [comment]
Ok but should not be a problem, 2 ping , 900mbit down up , 5ghz wifi, it’s ultra stable , and iam using your api chatbox 3.5Mit freundlichen Grüßen P. F.Am 12/12/2023 um 09:31 schrieb Benn Huang ***@***.***>:﻿
@myboxi This is related to your network and API.

**Comment by endolith** [comment]
I try to push the stop button to save tokens, but then it changes into a "re-generate" button right before I click it, and it ends up using even more tokens instead of less. :/  It shouldn't be in the same position as the regenerate button.
