### ISSUE TITLE
[BUG]设置有用户名和密码的代理服务器时出现错误

### ISSUE THREAD

**Issue by estorm2008** [Bin-Huang/chatbox#1037]
**Bug 描述**
按照 prototype://username:password@host:port 的格式设置了代理服务器，但是提示错误。

**重现步骤**
设置及错误截图

![002](https://github.com/Bin-Huang/chatbox/assets/22424728/c3b6b106-0a22-41ed-a36e-1338320d55b0)

而该代理服务器是正常，测试结果如下：
![001](https://github.com/Bin-Huang/chatbox/assets/22424728/8be54e36-cd22-4b31-a1c9-b80ff2eee5b4)

**桌面端（请填写以下信息）：**

-   操作系统：windows 10
-   应用程序版本：1.1.4

**Comment by Bin-Huang** [comment]
你好，这里的设置一般需要使用 SOCKS5 代理协议。如果你使用的是 API HOST 反向代理，可以在 AI 设置中设置。
