### ISSUE TITLE
System Instruction from Open ai's playground

### ISSUE THREAD

**Issue by ANONYMOUSEJR** [Bin-Huang/chatbox#1039]
**Problem Description**
I've used Openai's playground found the system instruction feature very useful...
Is there a possibility that it to here as well since it is pretty much the only thing left from the playground that wasn't implemented...
If it was forgive me and please point it out to me...

**Proposed Solution**
To implement it...

**Additional Context**
This is what i mean, just to be a bit more elaborate in my meaning:
![image](https://github.com/Bin-Huang/chatbox/assets/64444223/97930ed0-046f-4cc6-9958-02b60dc895b7)

**Comment by Bin-Huang** [comment]
In fact, Chatbox has supported system prompts since its first version. Every time you start a new conversation, you'll see the first default message. Edit this, and that's the system prompt.

**Comment by ANONYMOUSEJR** [comment]
> In fact, Chatbox has supported system prompts since its first version. Every time you start a new conversation, you'll see the first default message. Edit this, and that's the system prompt.

Thank you so much for clarifying.
Wish you the best!
