### ISSUE TITLE
[Feature] Locking chats for security/privacy.

### ISSUE THREAD

**Issue by ANONYMOUSEJR** [Bin-Huang/chatbox#1040]
**Problem Description**
The chats don't have the ability to be locked, this allows for an unauthorised person to access them.

**Proposed Solution**
The ability to lock chats or to have a boss key for the application like some torrenting programs.

**Additional Context**
N/A

**Comment by Bin-Huang** [comment]
Hello, personally, I believe that perhaps locking your own computer would be sufficient?
