### ISSUE TITLE
[Feature]为什么我在openai官网能够聊天，用chatbox就不能够呢？

### ISSUE THREAD

**Issue by Githubreo** [Bin-Huang/chatbox#1041]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":"insufficient_quota"}}

它显示这个信息
**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。
BTW 有没有人要一起share chatbox ai ?

**Comment by Bin-Huang** [comment]
这个错误的意思是，你的 OpenAI 账户没有余额了，这个错误是来自 OpenAI 的。官网能用不代表 API 能用，这在 OpenAI 是两套完全不同的收费体系。

**Comment by Githubreo** [comment]
原来如此，感谢
