### ISSUE TITLE
支持多个自定义模型，并支持下拉选择

### ISSUE THREAD

**Issue by WqyJh** [Bin-Huang/chatbox#1042]
**问题描述**

当前的模型选择可以选择一个自定义模型，并在下方输入框中输入一个自定义模型名称。显然这种方式仅支持一个自定义模型，而且不方便切换。

![image](https://github.com/Bin-Huang/chatbox/assets/15232241/0a38de5f-eb50-469b-9441-81876f7994fd)

**解决思路**

参考 https://github.com/Yidadaa/ChatGPT-Next-Web 的方案，输入框里可以输入多个自定义模型，用 `,` 分隔，然后将他们都展示到下拉列表中供选择。

![image](https://github.com/Bin-Huang/chatbox/assets/15232241/83f1c85b-8ff9-4255-b0c7-a0e3b7ddd265)

**附加上下文**

- OS：Windows 11

这个feature并不复杂，但是在最新的代码 v1.1.4 版本中并没有自定义模型相关的代码，只有几个写死在代码里的模型，请问是否需要额外的配置，才能编译出 release 版本功能一致的客户端。
![image](https://github.com/Bin-Huang/chatbox/assets/15232241/0c05527a-2790-4b64-b5f9-0c8e9c5b631b)

**Comment by heurainbow** [comment]
建议支持openai的v1/models来获取模型列表

**Comment by Bin-Huang** [comment]
这个功能已经有了，现在可以在输入时添加并记住模型选项。
