### ISSUE TITLE
建议在聊天栏 能快捷选择gpt的版本号

### ISSUE THREAD

**Issue by yimengfan** [Bin-Huang/chatbox#1046]
单个会话中问题有些gpt3.5搞不定，会切到4，有时候又忘了切回来，很贵

**Comment by QihanZhao** [comment]
![image](https://github.com/Bin-Huang/chatbox/assets/94861831/1c1e1bd2-d509-413e-b798-c39503b40132)
点击单个对话的标题，可以对单个对话进行设置

**Comment by yimengfan** [comment]
很多时候 不是根据单个会话来的，是根据当前问题，发现3.5不行  马上会切到4, 

> ![image](https://private-user-images.githubusercontent.com/94861831/286521054-1c1e1bd2-d509-413e-b798-c39503b40132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MDg5MjAsIm5iZiI6MTcwMTUwODYyMCwicGF0aCI6Ii85NDg2MTgzMS8yODY1MjEwNTQtMWMxZTFiZDItZDUwOS00MTNlLWI3OTgtYzM5NTAzYjQwMTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDA5MTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZGUxMGMxYTZlYzQwYWUyOTQ2MDc4NTk1NWNlMWU0NjAxODE3OTFiMDE4OGFlYzFiNjY4ZmZjYTc0Mjc2YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pY7fP8NXVsDaN8cuZ3VUAyjFDu3Znm9oDRlCrjUa5yE) 点击单个对话的标题，可以对单个对话进行设置

**Comment by Bin-Huang** [comment]
<img width="512" alt="image" src="https://github.com/user-attachments/assets/f7981807-694a-46ce-b319-90c8bb5bf66a">
最近版本更新里已经支持了
