### ISSUE TITLE
[BUG]使用第三方api域名生成图片报错

### ISSUE THREAD

**Issue by xueycn** [Bin-Huang/chatbox#1049]
遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 400, {"error":{"message":"relay error (request id: 202311261458288778029178LYGEA4J)","type":"one_api_error","param":"","code":"n_not_within_range"}}

**Comment by WooMai** [comment]
这不是 Chatbox 的问题，联系你的API提供商。

**Comment by ShinChven** [comment]
我也有这个问题

**Comment by aihu2020** [comment]
我也遇到了这个问题，官方请求地址是“/v1/images/generations”，调用没问题，chatbox调用报错“API Error: Status Code 400, {"error":{"message":"invalid value of n (request id: 20231127090305844458100unamSXy8)","type":"one_api_error","param":"","code":"n_not_within_range"}}”

**Comment by Bin-Huang** [comment]
这个不是 Chatbox 软件的问题。你使用的 API 提供商需要兼容 OpenAI 的生图接口。我看了下错误，这就是不兼容的表现。

**Comment by alongLFB** [comment]
![image](https://github.com/Bin-Huang/chatbox/assets/17883682/0cea93ce-9f39-4b50-af5c-f2a8e3dd43e2)

![image](https://github.com/Bin-Huang/chatbox/assets/17883682/6ce68c22-d842-4849-8b04-71cdd7a2a508)

作者你好 经过我刚才的测试与调试，我发现 有些 api 提供商 使用了 默认的参数 response_format 字段值 为 url 然后你的 Chatbox 使用了值 为 b64_json 所以导致这里不兼容 我等下看下你的代码 看看我是否可以提个 PR 增加绘图的一个返回格式的选项 这样 就可以完美的兼容了

**Comment by ShinChven** [comment]
> ![image](https://private-user-images.githubusercontent.com/17883682/286351829-0cea93ce-9f39-4b50-af5c-f2a8e3dd43e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjExNzQsIm5iZiI6MTcwMTIyMDg3NCwicGF0aCI6Ii8xNzg4MzY4Mi8yODYzNTE4MjktMGNlYTkzY2UtOWYzOS00YjUwLWFmNWMtZjJhOGUzZGQ0M2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYjljNjRiZTVmMTcxMGNkMmZmZjA4YTYxNDFkMDA2YzZkNGYwZDk4NjM0ZWMwNGRiMDQ0MWEzNGJhMWQzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kxVcE0GmAJoV9yhvQXUVJnPlqfRB3yaXuzgIvAesZ2s)
> 
> ![image](https://private-user-images.githubusercontent.com/17883682/286352420-6ce68c22-d842-4849-8b04-71cdd7a2a508.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjExNzQsIm5iZiI6MTcwMTIyMDg3NCwicGF0aCI6Ii8xNzg4MzY4Mi8yODYzNTI0MjAtNmNlNjhjMjItZDg0Mi00ODQ5LThiMDQtNzFjZGQ3YTJhNTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkOGQ0NWZkNGYwOWM1MmJjYTY3NzY4ZGQ1MTc0MTA3OTdhNmFkMWE4ODI3ZGRlMDQ1NDdlNzMxZmM4Njc4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GF2EQ-WiS1UyhEOO78A9lJlPSvDQk8WaI14KB9UaBjY)
> 
> 作者你好 经过我刚才的测试与调试，我发现 one-api 提供商 使用了 openai 画图的接口 使用都可以正常返回 但是在 chatbox 调用的时候 会报错 ![image](https://private-user-images.githubusercontent.com/17883682/286358422-36c21f26-c3ae-478d-8ef3-db28c6bdd38c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjExNzQsIm5iZiI6MTcwMTIyMDg3NCwicGF0aCI6Ii8xNzg4MzY4Mi8yODYzNTg0MjItMzZjMjFmMjYtYzNhZS00NzhkLThlZjMtZGIyOGM2YmRkMzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MDgzM2NjZTMwMzIwMzIyMjkwYTJhNmUwMTMwZDc0NjNhMzE0NjJhYjU1NWFmOGU2NjFlMjcwZTA3MGIxZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WgdSzJGP0mPlN3zZmu9bJzddIA_rX-hZNrd4IZ3E7D8)
> 
> 通过浏览器的 network 调试 发现没有看到 n 这个字段 ![image](https://private-user-images.githubusercontent.com/17883682/286359101-8c96bca0-ba85-4335-9f83-680cf2a3c22e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjExNzQsIm5iZiI6MTcwMTIyMDg3NCwicGF0aCI6Ii8xNzg4MzY4Mi8yODYzNTkxMDEtOGM5NmJjYTAtYmE4NS00MzM1LTlmODMtNjgwY2YyYTNjMjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OTE2NTE1YzA0NmMyYWM1YjBkNDM0YTJlYjZiZDdjYjg0NTgzODRiNTQwODFiNTA3MjBmMWNlNzQ4ODg5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lbX-3rqy-_DHa0qMqYYQ9yJYpfdKmr4dQUo9dTGQUGw)
> 
> 不确定是否这里的设置有bug 设置为1的时候 没有生效 ![image](https://private-user-images.githubusercontent.com/17883682/286358633-221be9de-235c-4bba-b9a3-4fef21dc1f82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjExNzQsIm5iZiI6MTcwMTIyMDg3NCwicGF0aCI6Ii8xNzg4MzY4Mi8yODYzNTg2MzMtMjIxYmU5ZGUtMjM1Yy00YmJhLWI5YTMtNGZlZjIxZGMxZjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYTJmOWQ1YjEzYThlOGU2OTFiMWNiMjBiMmE3MTljZmJhNzQwMzgyM2ViNzY0YTAxYTMyYjc5NjBkYzEyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTbI5BTVlGgCTVgvXBqRtA2LDPuYEqAeb5BN4ZVntvE)
> 
> 但因为没有网页端的源码 所以没法进行调试 麻烦作者再次确认下。

one-api 没有兼容 azure 的 dall-e api。我修了一下，还没合进去。

https://github.com/songquanpeng/one-api/pull/754

**Comment by alongLFB** [comment]
> > ![image](https://private-user-images.githubusercontent.com/17883682/286351829-0cea93ce-9f39-4b50-af5c-f2a8e3dd43e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjExNzQsIm5iZiI6MTcwMTIyMDg3NCwicGF0aCI6Ii8xNzg4MzY4Mi8yODYzNTE4MjktMGNlYTkzY2UtOWYzOS00YjUwLWFmNWMtZjJhOGUzZGQ0M2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYjljNjRiZTVmMTcxMGNkMmZmZjA4YTYxNDFkMDA2YzZkNGYwZDk4NjM0ZWMwNGRiMDQ0MWEzNGJhMWQzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kxVcE0GmAJoV9yhvQXUVJnPlqfRB3yaXuzgIvAesZ2s)
> > ![image](https://private-user-images.githubusercontent.com/17883682/286352420-6ce68c22-d842-4849-8b04-71cdd7a2a508.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjExNzQsIm5iZiI6MTcwMTIyMDg3NCwicGF0aCI6Ii8xNzg4MzY4Mi8yODYzNTI0MjAtNmNlNjhjMjItZDg0Mi00ODQ5LThiMDQtNzFjZGQ3YTJhNTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkOGQ0NWZkNGYwOWM1MmJjYTY3NzY4ZGQ1MTc0MTA3OTdhNmFkMWE4ODI3ZGRlMDQ1NDdlNzMxZmM4Njc4YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GF2EQ-WiS1UyhEOO78A9lJlPSvDQk8WaI14KB9UaBjY)
> > 作者你好 经过我刚才的测试与调试，我发现 one-api 提供商 使用了 openai 画图的接口 使用都可以正常返回 但是在 chatbox 调用的时候 会报错 ![image](https://private-user-images.githubusercontent.com/17883682/286358422-36c21f26-c3ae-478d-8ef3-db28c6bdd38c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjExNzQsIm5iZiI6MTcwMTIyMDg3NCwicGF0aCI6Ii8xNzg4MzY4Mi8yODYzNTg0MjItMzZjMjFmMjYtYzNhZS00NzhkLThlZjMtZGIyOGM2YmRkMzhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MDgzM2NjZTMwMzIwMzIyMjkwYTJhNmUwMTMwZDc0NjNhMzE0NjJhYjU1NWFmOGU2NjFlMjcwZTA3MGIxZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WgdSzJGP0mPlN3zZmu9bJzddIA_rX-hZNrd4IZ3E7D8)
> > 通过浏览器的 network 调试 发现没有看到 n 这个字段 ![image](https://private-user-images.githubusercontent.com/17883682/286359101-8c96bca0-ba85-4335-9f83-680cf2a3c22e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjExNzQsIm5iZiI6MTcwMTIyMDg3NCwicGF0aCI6Ii8xNzg4MzY4Mi8yODYzNTkxMDEtOGM5NmJjYTAtYmE4NS00MzM1LTlmODMtNjgwY2YyYTNjMjJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5OTE2NTE1YzA0NmMyYWM1YjBkNDM0YTJlYjZiZDdjYjg0NTgzODRiNTQwODFiNTA3MjBmMWNlNzQ4ODg5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lbX-3rqy-_DHa0qMqYYQ9yJYpfdKmr4dQUo9dTGQUGw)
> > 不确定是否这里的设置有bug 设置为1的时候 没有生效 ![image](https://private-user-images.githubusercontent.com/17883682/286358633-221be9de-235c-4bba-b9a3-4fef21dc1f82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjExNzQsIm5iZiI6MTcwMTIyMDg3NCwicGF0aCI6Ii8xNzg4MzY4Mi8yODYzNTg2MzMtMjIxYmU5ZGUtMjM1Yy00YmJhLWI5YTMtNGZlZjIxZGMxZjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzYTJmOWQ1YjEzYThlOGU2OTFiMWNiMjBiMmE3MTljZmJhNzQwMzgyM2ViNzY0YTAxYTMyYjc5NjBkYzEyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTbI5BTVlGgCTVgvXBqRtA2LDPuYEqAeb5BN4ZVntvE)
> > 但因为没有网页端的源码 所以没法进行调试 麻烦作者再次确认下。
> 
> one-api 没有兼容 azure 的 dall-e api。我修了一下，还没合进去。
> 
> [songquanpeng/one-api#754](https://github.com/songquanpeng/one-api/pull/754)

我没用 azure 的 dall-e api 我用的 就是 openai  的 dall-e api

**Comment by zhangbei59** [comment]
请问这个问题盖棺定论了吗，我今天使用第三方的转发api，并且使用Image Creator生图，也是报这个错。

`API Error: Status Code 400, {"error":{"message":"invalid value of n (request id: 202312140908572812121988DE02iYx)","type":"one_api_error","param":"","code":"n_not_within_range"}}`

问了api那边，直接说是客户端的问题。。

**Comment by Achuan-2** [comment]
@zhangbei59 +1,我也使用第三方的OPEN API，也是这个问题

**Comment by ShinChven** [comment]
你clone我的fork测一下，我自己用着挺好。

one-api 的 maintainer 上周没合我代码，你们快点去催。

**Comment by ShinChven** [comment]
我其实本来第一次提交代码就把这个问题解决了，结果合并的时候我的代码被别人的代码污染了。

**Comment by Achuan-2** [comment]
@ShinChven 想问问你是fork了one api 的repo，那chatbox怎么用呢

**Comment by ShinChven** [comment]
https://github.com/ShinChven/one-api

你们急的话，可以考虑部署我这个版本，等官方合并了再切换回去。

**Comment by zhangbei59** [comment]
> https://github.com/ShinChven/one-api
> 
> 你们急的话，可以考虑部署我这个版本，等官方合并了再切换回去。
哈哈，看着似乎有点重，话说这个东西跟我买的哪一家转发api后台一样哦

**Comment by ShinChven** [comment]
原来你们都不是自己部署的服务～

**Comment by ShinChven** [comment]
> 请问这个问题盖棺定论了吗，我今天使用第三方的转发api，并且使用Image Creator生图，也是报这个错。
> 
> `API Error: Status Code 400, {"error":{"message":"invalid value of n (request id: 202312140908572812121988DE02iYx)","type":"one_api_error","param":"","code":"n_not_within_range"}}`
> 
> 问了api那边，直接说是客户端的问题。。

我当时就是问了客户端说服务端问题，问了服务端说客户端问题，两边踢皮球，干脆自己解决。

**Comment by zhangbei59** [comment]
> > 请问这个问题盖棺定论了吗，我今天使用第三方的转发api，并且使用Image Creator生图，也是报这个错。
> > `API Error: Status Code 400, {"error":{"message":"invalid value of n (request id: 202312140908572812121988DE02iYx)","type":"one_api_error","param":"","code":"n_not_within_range"}}`
> > 问了api那边，直接说是客户端的问题。。
> 
> 我当时就是问了客户端说服务端问题，问了服务端说客户端问题，两边踢皮球，干脆自己解决。



用你这个可以绑定我第三方的转发api吗

**Comment by ShinChven** [comment]
等第三方更新吧。

**Comment by Bin-Huang** [comment]
首先，Chatbox 是百分百兼容 OpenAI API 接口的，这也是为什么官方接口在 Chatbox 中可以完全正常使用的原因。任何不兼容官方接口的，比如那些第三方 API，它们的问题不是 Chatbox 可以解决的，Chatbox 也没有义务去解决。
对于那些不想折腾的朋友，也推荐使用内置的 Chatbox AI。如果大家只是用来深度办公使用，Chatbox AI 肯定是比其他三方服务更加划算的，因为我完全是按照成本价格提供的。当初内置 Chatbox AI 的原因，就是我不想再处理这种三方兼容的问题，实在是没完没了。

**Comment by ShinChven** [comment]
https://github.com/songquanpeng/one-api/pull/821#issuecomment-1857237383

**Comment by ShinChven** [comment]
https://github.com/songquanpeng/one-api/pull/775#issuecomment-1859149955

<img width="1136" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/3351486/555351ac-2469-4b39-a217-dde1d74f0279">

one-api 对 Azure 渠道 DALL-E 模型的兼容已经修复。

**Comment by Achuan-2** [comment]
谢谢，第三方API确实可以用了

**Comment by zhangbei59** [comment]
已测试，第三方API目前已经可以正常生成图片了。
