### ISSUE TITLE
如何在linux上构建

### ISSUE THREAD

**Issue by Dumail** [Bin-Huang/chatbox#105]
这是一个非常棒的项目，但我无法在glibc版本较低的Linux系统上使用它，请问如何在自己的电脑上构建该项目的可执行程序

**Comment by goodsin78** [comment]
请问linux上使用需要安装什么依赖吗？我下载了Appimage安装包也给了权限，但运行没有反应。deb包也安装了，但安装后双击也同样毫无反应。系统是ubuntu。

**Comment by goodsin78** [comment]
是我系统的问题，缺少fuse库

**Comment by Bin-Huang** [comment]
> 是我系统的问题，缺少fuse库

分享你的经历，也许可以帮助更多一样的人。比如报错信息是什么，具体怎么解决？

**Comment by Dumail** [comment]
> 你好，可以直接下载 Linux 下的 AppImage 安装包。如果需要本地编译的话，需要 rust 和 node 环境。
> 
> ```shell
> # node.js 依赖
> npm install
> 
> # rust 依赖
> cargo install
> 
> # 运行开发模式
> npm run dev
> 
> # 编译当前系统的可执行文件
> npm run build
> ```

由于GLIBC版本只有2.28，因此也无法使用AppImage文件。尝试使用本地编译，但是在第二步时出现了"error: ~/chatbox is not a create root; specify a crate to install from crates.io, or use --path or --git to specify an alternate source" 的错误，请问是怎么回事呢？node版本是v16.14.0，npm版本是8.3.1，cargo版本是1.68.0，系统为deepin v20

**Comment by Smityz** [comment]
> > 是我系统的问题，缺少fuse库
> 
> 分享你的经历，也许可以帮助更多一样的人。比如报错信息是什么，具体怎么解决？

我也遇到了这个问题，我的解决方法如下
https://github.com/Bin-Huang/chatbox/issues/150

**Comment by wuyudi** [comment]
https://github.com/Bin-Huang/chatbox/blob/a64b57fe9bd030c590a9f9dc311a10a5c9647605/src-tauri/tauri.conf.json#L44

这里要加 openssl 依赖。

**Comment by kalufinnle** [comment]
解决方法:
```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
```
reference: https://stackoverflow.com/a/72633324

**Comment by iammrallblue** [comment]
> ```shell
> cargo
> ```

大兄弟, AppImage 是方便, 不過不是好用的, 還是要編譯一個deb

**Comment by dreamofheart1** [comment]
怎么没有人问在Windows上构建项目？
