### ISSUE TITLE
数学公式不能正常显示[BUG]

### ISSUE THREAD

**Issue by mghcool** [Bin-Huang/chatbox#1050]
**Bug 描述**
数学公式不能正常显示（可以使用mathjax来渲染）

**重现步骤**
打开一个新对话，对他说：帮我写一个旋转矢量转旋转矩阵的数学公式

**期望结果**
应该渲染出正常的数学公式
![20231127091452](https://github.com/Bin-Huang/chatbox/assets/49588462/88b34bc4-c39b-4253-8405-293ba1668044)

**实际结果**
只显示文本：[ R = I + (\sin \theta) K + (1 - \cos \theta) K^2 ]

**截图**
![20231127091556](https://github.com/Bin-Huang/chatbox/assets/49588462/301222a7-da51-4268-8888-5eff3cd7f00c)

**桌面端（请填写以下信息）：**

-   操作系统：[Win11]
-   应用程序版本：[1.2.0]

**Comment by ricklei2777** [comment]
<img width="1382" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/96427310/3d7937d1-52dd-4c7f-a62b-2444cbd14607">
改一下提示词：采用markdown写作，公式要用$$包围，行内数学符号要用$包围。
