### ISSUE TITLE
[BUG]更新1.2.0后，原来的对话列表被清空了，找不到对话了

### ISSUE THREAD

**Issue by wildywerewolf** [Bin-Huang/chatbox#1052]
更新1.2.0后，原来的对话列表被清空了，找不到对话了

**Comment by Bin-Huang** [comment]
这个问题很奇怪，按道理是不可能发生的。请问你的操作系统是？从哪里下载的安装包？打开应用后有什么异常？

**Comment by wildywerewolf** [comment]
系统是win10，更新至最新。
chatbox是从releases中的Windows链接进入下载的1.2.0，升级前版本1.1.4。默认安装位置，安装更新前正在正常使用，安装更新后没有任何异常报错，列表为空，仅有默认全新安装时存在于列表里的图片创建器。

**Comment by tushu** [comment]
今天早上打开软件。发现全部历史记录都没有了。昨晚关机时一切正常。我用的版本是1.2.0。

我觉得这个问题比较严重，因为我没有备份我的历史记录。


这种突然没有全部历史记录的情况，我记得在之前也发生过，但是当时我的历史记录不多，所以也没有放在心上。这次，我乱了。


此外，还有一个现象，就是首次打开软件的时候，之前填入的api的信息，全部没有了。这个我记得也发生过几次。

**Comment by tushu** [comment]
不敢再继续使用。

**Comment by Bin-Huang** [comment]
大家好，很抱歉给大家带来了不好的体验。经过排查 1.2.0 版本确实存在丢失数据的偶现问题，有概率会丢失聊天数据。**这个问题已经在 1.2.1 版本中紧急修复了，同时增加了必要措施来阻止类似问题，建议更新使用。**

**Comment by Bin-Huang** [comment]
这个问题理论上不会再出现了，未来也会考虑增加定时自动备份的功能，提供更充分的安全感
