### ISSUE TITLE
[Feature]提供显示并可以清空上下文数量的按扭

### ISSUE THREAD

**Issue by JerryWesler** [Bin-Huang/chatbox#1056]
**问题描述**
每次清空，其实只想清空历史上下文的数量，并不是想清空对话内容。既然有了对话内容搜索，其实就是想更多的保留对话本身。但是在一个对话框内，经常会有清空上下文的需求，更大程度节省字符开支。

**解决思路**
<img width="238" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/44219765/01e8d6f7-66d2-41c1-974a-4b5c48eb1d07">
在对话框内显示上下文使用数量，点击就重置为0

**Comment by Beeta** [comment]
支持，非常需要这个功能。有时候想人为的不要关联上下文，只能清理掉所有内容，得不偿失。

**Comment by Bin-Huang** [comment]
试试最新的上下文刷新按钮。可以保留历史消息的情况下，刷新上下文
