### ISSUE TITLE
[Feature] 是否能增加联网插件功能

### ISSUE THREAD

**Issue by JackWangSIA** [Bin-Huang/chatbox#1057]
非常感谢作者的工作。
不知道联网插件功能增加的难度大不大。
如果能联网，GPT就一下子强大很多~

**Comment by QihanZhao** [comment]
+1

**Comment by sunsky89757** [comment]
可以调用联网模型

**Comment by ElvisDream** [comment]
> 可以调用联网模型

请问是哪个模型？

**Comment by sellength** [comment]
联网模型是什么鬼？

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1238, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1238。这条 issue 先关闭了～～
