### ISSUE TITLE
[BUG] Images cannot be displayed in V1.2.0（ V1.2.0版本图像生成器无法显示图片 ）

### ISSUE THREAD

**Issue by QihanZhao** [Bin-Huang/chatbox#1058]
**Bug 描述**
The images cannot be displayed, as shown in the pictures below.

**截图**
- Windows
![image](https://github.com/Bin-Huang/chatbox/assets/94861831/47ee4c36-53f8-455c-a5e2-9df1b2f19873)
- MacOS
![image](https://github.com/Bin-Huang/chatbox/assets/94861831/3d0f65db-5868-407c-91cd-3468e718c992)

**桌面端**

-   操作系统：Windows10 & MacOS
-   应用程序版本：1.2.0

**Comment by QihanZhao** [comment]
Thank you for creating the Chatbox, which is both friendly and stable. In the latest version, the ability for users to generate images is a much-appreciated feature!
By the way, I would like to inquire about the API used for DALLE-3. Is it /v1/images/generations? Do I make requests to the host using the key I have filled in the settings?

**Comment by breakstring** [comment]
我这边刚才升级了倒是可以显示图片。

**Comment by Bin-Huang** [comment]
Fixed in v1.2.1
