### ISSUE TITLE
[BUG] Claude API error

### ISSUE THREAD

**Issue by vzaliva** [Bin-Huang/chatbox#1059]
**Bug Description**
I have Claude's API key, but attempts to use it result in error.

**Steps to Reproduce**

type anything in chat

**Expected Results**
claude's answer

**Actual Results**
```
Unknown Error. Please check your AI settings and account status, or [click here to view the FAQ document](https://chatboxai.app/redirect_app/faqs/en).

unsupported ai provider: claude
```
**Desktop (please complete the following information):**

-   Operating System: Linux
-   Application Version: 1.2.0

**Additional Context**
OpenAI API works OK.

**Comment by Bin-Huang** [comment]
I still remember this bug, and it has been fixed in subsequent versions.
