### ISSUE TITLE
[BUG] 新功能生成的图片加载不出来

### ISSUE THREAD

**Issue by wusp1994** [Bin-Huang/chatbox#1062]
![image](https://github.com/Bin-Huang/chatbox/assets/26253981/ac8e4812-2e1b-47d2-bab4-a8c267bf6bf3)

**Comment by Bin-Huang** [comment]
请问图片有显示成功过吗？从来没有显示过、还是突然就不再显示了？

**Comment by wordkathychen** [comment]
从来都没显示过

**Comment by Bin-Huang** [comment]
> 主要是我不太清楚服务器在哪里有的时候使用的速度等等没有第三方接口效果好 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Benn Huang ***@***.***&gt; 发送时间: 2023年12月4日 15:16 收件人: Bin-Huang/chatbox ***@***.***&gt; 抄送: wordkathychen ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [Bin-Huang/chatbox] [BUG] 新功能生成的图片加载不出来 (Issue #1062) STEVEN @.*** &nbsp;您好我的api提供方比较复杂，都是私人搭建的 您可以看下这个 sk-cdf1aedb853b45b5ad46ee2e554c3d87 带查询页面的接口地址：https://www.bluecatapi.com/ 金额：16美金 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Bin-Huang/chatbox" @.&gt;; 发送时间:&nbsp;2023年12月4日(星期一) 上午10:38 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [Bin-Huang/chatbox] [BUG] 新功能生成的图片加载不出来 (Issue #1062) 从来都没显示过 你使用的 AI 提供方是什么？如果是 OpenAI API 是官方的吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 这样就对了。有些劣质的提供方并没有兼容 OpenAI 的 Dall-E-3 接口，这样 Chatbox 肯定是没办法显示图片的。话说为什么不直接用内置 Chatbox AI 服务呢？反正也是按成本价格提供的，怎么都比这种划算吧…… — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

之前有过几天速度不稳定，后来解决了。

**Comment by wordkathychen** [comment]
亲，你的新版 1.21和oneapi的api不通用，导致报错，具体报错为无效令牌

**Comment by Bin-Huang** [comment]
> 亲，你的新版 1.21和oneapi的api不通用，导致报错，具体报错为无效令牌

这个报错应该是来自 oneapi 的吧，请问有更详细的错误信息吗？他们没有很好的兼容 OpenAI 接口，我这边没办法专门优化的
