### ISSUE TITLE
图片生成报分辨率错误

### ISSUE THREAD

**Issue by maodouzi123** [Bin-Huang/chatbox#1068]
我使用的APIkey是AIProxy提供的，他们是支持dall-e-3模型的，但是图片生成总是报这个错误，请问是我哪里设置错误了吗？
`API Error: Status Code 400, {"error":{"message":"Invalid Resolution,Only support 1024x1024,1024x1792,1792x1024","type":"invalid_request_error","param":null,"code":null}}
`

**Comment by Bin-Huang** [comment]
我不知道这个 API 提供商，但很明显他们没有正确兼容 OpenAI API 的接口。
