### ISSUE TITLE
问题：光标在代码块里无法使用滚轮

### ISSUE THREAD

**Issue by cvbnt** [Bin-Huang/chatbox#107]
version：0.2.1
平台：windows11 x64
对于这种出现左右滚动条的代码块，鼠标光标在代码块中，按住左键无法使用滚轮选中，只能手动拖动鼠标选中
![image](https://user-images.githubusercontent.com/11713048/226646028-6dc47ec2-c100-4a23-b790-f9e51992e72b.png)

**Comment by cvbnt** [comment]
> 按住 Shift 再滚轮，就可以横向滚动了

但是我想纵向滚动好像不行

**Comment by Bin-Huang** [comment]
是不是缺一个代码复制按钮？

**Comment by cvbnt** [comment]
> 是不是缺一个代码复制按钮？

确实需要
