### ISSUE TITLE
作者是否想加入google bard的api接口或者即将推出的goole gemini？

### ISSUE THREAD

**Issue by laohuan12138** [Bin-Huang/chatbox#1070]

**Comment by lgmazure** [comment]
+1

**Comment by lyndsea** [comment]
+1

**Comment by MichaelBelgium** [comment]
+1 for gemini

https://ai.google.dev/

https://blog.google/technology/ai/gemini-api-developers-cloud/

**Comment by gray0128** [comment]
+1

**Comment by Iuleoo** [comment]
+1

**Comment by moshouhot** [comment]
+1 for gemini

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

**Comment by Bin-Huang** [comment]
It is already supported in the new version.
在新版本已经支持了
https://github.com/Bin-Huang/chatbox/releases
