### ISSUE TITLE
[BUG]Mac升级V1.2.1后历史消息记录全部被清空

### ISSUE THREAD

**Issue by zhangfuliang66** [Bin-Huang/chatbox#1079]
<img width="1009" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/41914713/d6bf6686-de5d-4721-a773-83338221df28">

**Comment by Bin-Huang** [comment]
你好，请问是从哪个版本升级到 1.2.1 呢？

**Comment by zhangfuliang66** [comment]
我一直是自动重启升级，应该就是上一个版本1.2.0

**Comment by Bin-Huang** [comment]
那应该是 1.2.0 的问题，新版本修复了，具体可以看这里：

https://github.com/Bin-Huang/chatbox/issues/1052

**Comment by zhangfuliang66** [comment]
历史对话还能找回吗？

**Comment by Bin-Huang** [comment]
很抱歉，应该是不能了。这个问题以后不会发生了，同时未来会有定期自动备份，彻底规避这类问题……
