### ISSUE TITLE
I found a problem, when it replied to me, I couldn't scroll the window.

### ISSUE THREAD

**Issue by Voldeemort** [Bin-Huang/chatbox#108]
I found a problem, when it replied to me, I couldn't scroll the window.

**Comment by Bin-Huang** [comment]
I have been aware of this bug for some time, but unfortunately, I have not yet been able to find the time to address it. Rest assured, as soon as I have some free time, I will work on fixing it. I'm also hopeful that other contributors will step forward and offer their help.

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

Fixed
