### ISSUE TITLE
[BUG]Android端登入网页版使用Claude API报错。

### ISSUE THREAD

**Issue by lioensky** [Bin-Huang/chatbox#1084]
![QQ图片20231213204906](https://github.com/Bin-Huang/chatbox/assets/140802180/9c440a78-071b-4b30-9a80-218df022ebeb)
使用PC登入网页端没问题，仅在安卓端报错。
使用同一SSR线路。

**Comment by Bin-Huang** [comment]
已经在过去的版本更新中解决了
