### ISSUE TITLE
[Feature]Gemini Pro Support

### ISSUE THREAD

**Issue by a19901201** [Bin-Huang/chatbox#1085]
Gemini Pro can already obtain the API key. We hope to add ways to connect to the Gemini Pro API.
https://ai.google.dev/tutorials/rest_quickstart
https://makersuite.google.com/app/apikey

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

**Comment by Bin-Huang** [comment]
It is already supported in the new version.
在新版本已经支持了
https://github.com/Bin-Huang/chatbox/releases
