### ISSUE TITLE
[BUG] Latex formatting does not work on gpt4-models

### ISSUE THREAD

**Issue by honeyspoon** [Bin-Huang/chatbox#1089]
**Bug Description**
Output of the chatbot is not parsed when it's latek.

**Steps to Reproduce**
1. Set model to gpt-4
2. ask a math question "give me an example of a small group with an odd number of elemnts"
3. observe output

**Expected Results**
output should be formatted to math

**Actual Results**
It's not 

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
<img width="1010" alt="Screenshot 2023-12-14 at 5 29 24 PM" src="https://github.com/Bin-Huang/chatbox/assets/22123928/eac1f08e-725f-48e3-aac7-356b3c4f477b">

-   Operating System: macOS
-   Application Version: 1.2.1

**Comment by Az0s** [comment]
Experiencing this issue as well. Hoping for a fix soon

**Comment by honeyspoon** [comment]
Did some digging an it doesn't seem to be an issue with chatbox as it handle the output the same way for both models.

For latex to be converted by katex, it need to be wrapped in $.
gpt 3.5 seems to do it properly but gpt4 does not, but you can ask it to manually warp them in $ and it will work

not sure what the longterm fix for this is.
maybe manually detect latex string with a regex and auto wrap them in $ sign before passing them to katex.
