### ISSUE TITLE
gpt3.5之上的版本无法开启新对话

### ISSUE THREAD

**Issue by xp406181** [Bin-Huang/chatbox#109]
`API Request Failed:

Error from OpenAI: 404  {
    "error": {
        "message": "The model: `gpt-4-32k-0314` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}`

出现这个提示是啥意思，我还需要设置什么么？

**Comment by ttyy33** [comment]
有人问过这个问题，你参考下这个：https://github.com/Bin-Huang/chatbox/issues/96
把左侧当前的对话框删掉，重新建一个就可以了。另外，没有chat-4模型的权限，不要瞎点。

**Comment by xp406181** [comment]
您好，我已收到您的邮件。我将尽快给您回复。
