### ISSUE TITLE
希望快捷键回车键发送可以自由开关

### ISSUE THREAD

**Issue by hanke-cnc** [Bin-Huang/chatbox#1090]
因为用的gpt4,每次提问都是肉疼,又因为用的中文输入法,又又因为中文输入法下输入字母是按回车 ,有时候会误按导致发送,现在得小心翼翼的了,😭希望快捷键回车键发送可以自由开关,我自己点小飞机按钮发送

![安安](https://github.com/Bin-Huang/chatbox/assets/108179425/1ba30604-7e05-4bd6-aa76-41c399663d66)

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #939, so I'll close this to avoid duplicates. Feel free to add more thoughts there!
