### ISSUE TITLE
[Feature] Google Gemini is coming, wait for new version for ChatBOX with Gemini.

### ISSUE THREAD

**Issue by javenhmh** [Bin-Huang/chatbox#1091]
**Problem Description**

[Feature] Google Gemini is coming, wait for new version for ChatBOX with Gemini.

**Proposed Solution**
Google Gemini is coming, wait for new version for ChatBOX with Gemini.

**Additional Context**
Google Gemini is coming, wait for new version for ChatBOX with Gemini, thanks so much.

---

**问题描述**
谷歌人工智能 Gemini 发布了，支持 API，希望能够融合到 ChatBOX。

**解决思路**
在 ChatBOX 中支持 Google Gemini API。

**附加上下文**
在 ChatBOX 中支持 Google Gemini API，谢谢大家。

[Google Bard](https://bard.google.com)

[Google Gemini](https://deepmind.google)

**Comment by a19901201** [comment]
https://ai.google.dev/tutorials/rest_quickstart
https://makersuite.google.com/app/apikey

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

**Comment by Bin-Huang** [comment]
It is already supported in the new version.
在新版本已经支持了
https://github.com/Bin-Huang/chatbox/releases
