### ISSUE TITLE
[BUG] LaTeX公式部分渲染错误

### ISSUE THREAD

**Issue by 11D-Beyonder** [Bin-Huang/chatbox#1094]
**Bug Description**

LaTeX公式部分渲染错误

**Screenshots**

![image](https://github.com/Bin-Huang/chatbox/assets/58369870/337a7627-2312-4e01-8ef1-dd69a2fb102e)

**Desktop (please complete the following information):**

-   macOS Sonoma
-   Application Version: 1.2.1

**Comment by youfeng1024** [comment]
全平台都是一样的，应该是没做latex公式的渲染

**Comment by alexstore06** [comment]
See issue #1089. LaTeX must be wrapped in $ to be parsed. Adding "wrap LaTeX in $" or similar to your prompt should correct the issue.

**Comment by Bin-Huang** [comment]
Thank you for reporting this issue! I'm happy to let you know that it has been resolved in the latest version. Please update to the newest release to see the changes.

<img width="1288" src="https://github.com/Bin-Huang/chatbox/assets/20723142/808b27a1-5806-4964-adea-bd5f35775869">
