### ISSUE TITLE
希望设置的单个角色可以保留历史话题记录

### ISSUE THREAD

**Issue by Achuan-2** [Bin-Huang/chatbox#1095]
像utools的ChatGPT 好友设计的就很人性化，一个指令角色，可以保留历史的话题记录，就不会导致左侧的角色列表有重复
![image](https://github.com/Bin-Huang/chatbox/assets/60436214/d80c0e97-92c6-489b-aad5-a7d727d8e844)
现在的chatbox有点像官网的风格，左侧就会有很多对话，同一个指令难以在保留历史对话的情况下复用
![image](https://github.com/Bin-Huang/chatbox/assets/60436214/f72bea04-56af-4080-aefa-42acf969d83b)

**Comment by Bin-Huang** [comment]
很巧了不是，这两周我正好在开发这个

**Comment by Achuan-2** [comment]
哈哈，那期待下
