### ISSUE TITLE
[Feature] Add price usage

### ISSUE THREAD

**Issue by Trapper4888** [Bin-Huang/chatbox#1097]
**Problem Description**
I am finding it challenging to manage my usage of the model.

**Proposed Solution**
Add a price field alongside the token count for each message. This would require a price for in and out token for each models.
Then a counter with "price count from x to y" where two dates can be selected would allow tracking our usage.

---

**问题描述**
我发现管理我对模型的使用变得具有挑战性。

**解决思路**
在每条消息的令牌计数旁边添加一个价格字段。这将需要为每个模型的进出令牌设定一个价格。然后，一个从x日期到y日期的“价格计数”计数器可以让我们跟踪我们的使用情况。

**Comment by GreggRoll** [comment]
bump

**Comment by ishaan-jaff** [comment]
Hi @GreggRoll @Trapper4888  I'm the maintainer of LiteLLM https://github.com/BerriAI/litellm we allow you to do cost tracking for 100+ LLMs 

## Usage
Docs: https://docs.litellm.ai/docs/#calculate-costs-usage-latency
```python
from litellm import completion, completion_cost
import os
os.environ["OPENAI_API_KEY"] = "your-api-key"

response = completion(
  model="gpt-3.5-turbo", 
  messages=[{ "content": "Hello, how are you?","role": "user"}]
)

cost = completion_cost(completion_response=response)
print("Cost for completion call with gpt-3.5-turbo: ", f"${float(cost):.10f}")
```

We also allow you to create a self hosted OpenAI Compatible proxy server to make your LLM calls (100+ LLMs), track costs, token usage 
Docs: https://docs.litellm.ai/docs/simple_proxy 

I hope this is helpful, if not I'd love your feedback on what we can improve

**Comment by Bin-Huang** [comment]
Due to the need to support many model providers, and not all providers have similar interfaces, there is currently no development plan for this feature.
