### ISSUE TITLE
可否用 Tauri 代替 Electron？

### ISSUE THREAD

**Issue by v2less** [Bin-Huang/chatbox#11]
参考： <https://github.com/yetone/openai-translator>

完全用 Tauri 代替了笨重的 Electron，每个应用的体积从100MB+减少到5MB+！

**Comment by Bin-Huang** [comment]
好的，已经在考虑了。

**Comment by Bin-Huang** [comment]
我目前比较担心那些没有安装 chrome 浏览器的用户，使用 Tauri 的话会不会受到影响。你对这方面了解吗，想请教下？

**Comment by v2less** [comment]
不好意思，并不了解

**Comment by wuyudi** [comment]
> 我目前比较担心那些没有安装 chrome 浏览器的用户，使用 Tauri 的话会不会受到影响。你对这方面了解吗，想请教下？

不会，因为 tauri 在 windows 用的是 [webview2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)

**Comment by fukai7722** [comment]
没有运行环境，会提示用户下载安装的。

**Comment by orangelckc** [comment]
有轻量需求的朋友可以来看看这个[项目](https://github.com/bilibili-ayang/ChatGPT-Desktop)，这周末会发版

**Comment by Bin-Huang** [comment]
我昨晚在本地测试了一下 chatbox 的 tauri 版本，不管是安装包大小还是运行内存都减少了很多（原来的十分之一），而且我个人觉得 tauri 配套的工具链更加高效一些。未来应该是会很快迁移到 tauri 上的。

等我把最近的计划更新全部开发完，我会尽快迁移 electron API 使用到 tauri，还有解决跨平台编译的问题。

**Comment by Bin-Huang** [comment]
已经完成从 Electron 到 Tauri 的全部代码迁移，全部合并到 main 分支了，以后的版本都是基于 Tauri 了。 https://github.com/Bin-Huang/chatbox/pull/71

**Comment by julee** [comment]
> 已经完成从 Electron 到 Tauri 的全部代码迁移，全部合并到 main 分支了，以后的版本都是基于 Tauri 了。 #71

[v0.4.4](https://github.com/Bin-Huang/chatbox/releases/tag/v0.4.4) Windows 包这么大，是不是又用回 Electron 了？
