### ISSUE TITLE
能出一个解压即用的版本吗……我用老版本积累了很多的聊天记录

### ISSUE THREAD

**Issue by Pinkuburu** [Bin-Huang/chatbox#110]
就因为老的聊天记录还在，我还想保留着，安装版是不能继承聊天记录的吧？
我想要新版本解压覆盖……

**Comment by add2ws** [comment]
安装版不会覆盖以前的聊天记录啊

**Comment by Bin-Huang** [comment]
直接安装即可，聊天记录不会消失。如果你是从 v0.1.x 升级到 v0.2.x，可能会导致记录丢失。可以通过下面的方法恢复：

可以打开文件管理器，路径栏输入 %APPDATA%，把 chatbox 文件夹下的 config.json 文件复制到 xyz.chatboxapp.app 文件夹下就可以了（注意这样会覆盖掉新版本的数据）。
