### ISSUE TITLE
[Feature]建议支持Gamini API

### ISSUE THREAD

**Issue by whsheng** [Bin-Huang/chatbox#1100]
**Problem Description**
Google 的Gamini已经对外提供API，建议增加

---

**Comment by lchyn** [comment]
是Gemini Pro 吧， 不是 Gamini；
有个转换proxy 的开源项目 https://github.com/zhu327/gemini-openai-proxy ， 可以把Google Gemini 转换为OPENAI 的API,  可以参考

**Comment by Bin-Huang** [comment]
新版本已经支持了https://github.com/Bin-Huang/chatbox/releases
