### ISSUE TITLE
gpt3.5，都可以用，GPT4系列的，除了GPT4，其他的模型都不能用。plus 会员，API正常。

### ISSUE THREAD

**Issue by niu0700139** [Bin-Huang/chatbox#1104]
gpt-3.5-turbo
gpt-3.5-turbo-0301
gpt-3.5-turbo-0613
gpt-3.5-turbo-1106
gpt-3.5-turbo-16k
gpt-3.5-turbo-16k-0613
gpt-4
**gpt-4-0314
gpt-4-0613
gpt-4-1106-preview
gpt-4-32k
gpt-4-32k-0314
gpt-4-32k-0613**  加粗的模型都不能用，GPT-4可以用的，但是使用的是时候，提问：你是哪个模型。返回结果，说自己是GPT3。到底咋会事儿，搞不懂

**Comment by Bin-Huang** [comment]
这个属于 API 问题，不在客户端的范畴
