### ISSUE TITLE
[Feature]gpt-4-vision-preview使用需求

### ISSUE THREAD

**Issue by TC130** [Bin-Huang/chatbox#1105]
**问题描述**
现在聊天和画图功能比较完备，但工作过程中遇到大量识别图像/录音/视频的需求

**解决思路**
对接gpt-4-vision-preview

**Comment by Bin-Huang** [comment]
这个功能已经实现了，试试最新的版本

**Comment by allenwoods** [comment]
"当前模型 Azure OpenAI (gpt-4) 不支持发送图片。"在使用Azure OpenAI的时候，应该怎么才可以使用呢？已在AI Studio后台设置模型默认版本为“vision-preview”
