### ISSUE TITLE
[Other]希望能增加非连续对话的选项

### ISSUE THREAD

**Issue by Mirinda-greenapple** [Bin-Huang/chatbox#1106]
我的某些使用场景中每次提问的问题比较独立和上下文并无关联，但每次请求都会将前几次的问答带上，除了消耗token外对本次问答并无太大帮助，如果每次问答都新建一个对话的话会显得比较繁琐，希望能在新建会话时能选择是连续问答的会话还是非连续问答的会话。

**Comment by Bin-Huang** [comment]
这种情况我一般会刷新下上下文，更新到最新版本试试这个新功能
