### ISSUE TITLE
[BUG]数学公式未能正常可视化显示

### ISSUE THREAD

**Issue by newljs** [Bin-Huang/chatbox#1113]
**Bug 描述**
数学公式未能正常显示

**软件截图**
![Snipaste_2023-12-29_17-40-27](https://github.com/Bin-Huang/chatbox/assets/10069195/fb7e23a1-7db5-497c-88d8-8c050c29bc0a)

**原始gpt页面正常显示的效果**
![Snipaste_2023-12-29_17-42-55](https://github.com/Bin-Huang/chatbox/assets/10069195/f3cad174-851c-4fdb-9121-d388c7456ed2)

**Comment by alexstore06** [comment]
See issue #1089. LaTeX must be wrapped in $ to be parsed. Adding "wrap LaTeX in $" or similar to your prompt should correct the issue.

**Comment by Bin-Huang** [comment]
Thank you for reporting this issue! I'm happy to let you know that it has been resolved in the latest version. Please update to the newest release to see the changes.

<img width="1288" src="https://github.com/Bin-Huang/chatbox/assets/20723142/808b27a1-5806-4964-adea-bd5f35775869">
