### ISSUE TITLE
[BUG] 404 when chatting with ollama

### ISSUE THREAD

**Issue by donuts-are-good** [Bin-Huang/chatbox#1118]
**Bug Description**
I have ollama running on 192.168.1.6:11434, when I send requests via REST client, it responds and works. When I list the models in chatbox, I can see my models and select a model. When I send a test request, I get a 404 in chatbox and I see it in the API as a 404 on the POST request to /chat

**Steps to Reproduce**

1. run ollama exposed on the network 

<img width="604" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/96031819/30096e62-376c-4585-8c64-eb2ebb4e0f54">

2. in chatbox, open settings and input url to view list of models 

<img width="1277" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/96031819/24d54c02-83a3-47cc-bded-f89d22e28704">

in this photo, you can see the requests return status 200, which means chatbox is speaking to the api correctly, and is able to populate the dropdown box with a list of models

3. select the desired model and click save 

<img width="1276" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/96031819/2d887db1-ed3f-46f8-ab35-3ca19457cacb">

4. create a new chat, verify it is using the desired model, send test request 

<img width="689" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/96031819/367e604f-8c3b-43ff-8b2e-62ed71ade593">

this request fails as a 404

<img width="662" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/96031819/be05cc4b-e4a9-4c56-ae94-280728f1eabc">

**Expected Results**
I expected it to generate a response after sending the test message, or return useful errors or a link to error documentation about what the raw request was that failed. 

**Actual Results**
<img width="662" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/96031819/cea41791-baef-49e4-b8c8-552100f34c6b">

**Desktop (please complete the following information):**

-   Operating System: chatbox is running on macos (m2 air) locally, ollama is running on fedora (amd64, nvidia) on the network at 192.168.1.6. fedora and macos are recent versions.
-   Application Version: chatbox 1.2.2, ollama 0.1.13

**Comment by donuts-are-good** [comment]
Upgrading ollama to 0.1.17 fixes the issue, closing this ticket.

**Comment by AugustChen-yjh** [comment]
The Ollama reuqest Url is http://192.168.1.6:11434 rather than 192.168.1.6:11434, Please try again.
