### ISSUE TITLE
夸夸你 & context token number

### ISSUE THREAD

**Issue by abxm2** [Bin-Huang/chatbox#112]
必须夸夸你！
界面简单干净。可以设置context。

context的设置为什么最大是8192或者无限呢，API最大token不是4096吗？

**Comment by Bin-Huang** [comment]
根据 OpenAI CEO 提出来的新摩尔定律：“宇宙中的智能数量每18个月翻倍”，所以需要考虑未来。而人类对未来的想象力是无限的。

现在 Chatbox 很多特性都还没有开发完，期待更多人参与贡献～
