### ISSUE TITLE
[BUG] Unable to achieve the same UI when building Chatbox from the source code.

### ISSUE THREAD

**Issue by double-thinker** [Bin-Huang/chatbox#1123]
**Bug Description**
Not able to build (tauri and react versions) the same version that is deployed in the official webpage and GH releases.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

1. Clone `main` branch or `v1.2.2` tag.
2. Run `npm run tauri build` or `npm run start:react`

**Expected Results**
The UI should match with the one from downloaded from the webpage or GH releases. For example "My Copilots" section is missing.

**Actual Results**
The UI is similar, but not identical, to the official one and seems like not all features are available (e.g: My Copilots).

**Desktop:**

-   Operating System: macOS
-   Application Version: 1.2.2

**Comment by Bin-Huang** [comment]
See here: #803
