### ISSUE TITLE
Telegram讨论群欢迎大家前来讨论

### ISSUE THREAD

**Issue by lolieatapple** [Bin-Huang/chatbox#113]
创建了telegram群。大家有问题可以在里面一起沟通和讨论。
Chatbox 官方用户群：Telegram： https://t.me/+gWzem4HGSI5hYzg1
Chatbox 社区闲聊群：Telegram：https://t.me/ChatBoxApp

📢 欢迎来到 ChatBox Telegram 群 📢

🌟  ChatBox是一款开源的 ChatGPT API (OpenAI API) 跨平台桌面客户端。本群旨在分享、讨论和交流有关 ChatGPT 的使用经验、技巧和问题。本群涉及的主题包括开源的 ChatGPT API（OpenAI API）、跨平台桌面客户端、Prompt 调试与管理工具，以及 ChatGPT Plus 平替方案。

🔧 在这里，您可以：
1. 提问并寻求关于 ChatBox 的帮助；
2. 分享您在使用 ChatBox 过程中的心得和经验；
3. 了解最新的 ChatBox 功能、更新和改进；
4. 探讨 Prompt 调试和管理技巧；
5. 参与有关 ChatGPT Plus 平替方案的讨论。

📜 群规：
1. 请保持友善，互相尊重，遵守相关法律法规；
2. 请不要发送与本群主题无关的广告或垃圾信息；
3. 请遵守 Telegram 使用规定，不得发布不当言论或图片。
4. 请不要相信任何主动私聊你的人，谨防诈骗。

🤝 让我们共同努力，打造一个有益的 ChatGPT 社区！如有任何问题，请在群内留言，大佬们看到了就会回复。

**Comment by maderibu** [comment]
对的

**Comment by lolieatapple** [comment]
我来建一个telegram的，大家一定要注意安全，不要相信任何主动私聊的人。
https://t.me/ChatBoxApp

**Comment by lolieatapple** [comment]
📢 欢迎来到 ChatBox Telegram 群 📢

🌟 本群旨在分享、讨论和交流有关 ChatGPT 的使用经验、技巧和问题。本群涉及的主题包括开源的 ChatGPT API（OpenAI API）、跨平台桌面客户端、Prompt 调试与管理工具，以及 ChatGPT Plus 平替方案。

🔧 在这里，您可以：
1. 提问并寻求关于 ChatGPT 的帮助；
2. 分享您在使用 ChatGPT 过程中的心得和经验；
3. 了解最新的 ChatGPT 功能、更新和改进；
4. 探讨 Prompt 调试和管理技巧；
5. 参与有关 ChatGPT Plus 平替方案的讨论。

📜 群规：
1. 请保持友善，互相尊重，遵守相关法律法规；
2. 请不要发送与本群主题无关的广告或垃圾信息；
3. 请遵守 Telegram 使用规定，不得发布不当言论或图片。
4. 请不要相信任何主动私聊你的人，谨防诈骗。

🤝 让我们共同努力，打造一个有益的 ChatGPT 社区！如有任何问题，请随时联系群管理员。

**Comment by lolieatapple** [comment]
请开发者大大进群吧，我给你管理员权限，谢谢。

**Comment by Bin-Huang** [comment]
或者我晚些时候建一个官方的？

**Comment by Bin-Huang** [comment]
> 请开发者大大进群吧，我给你群超级权限，谢谢。

感谢好意，我用 telegram 不多，所以还是自己建了

**Comment by lolieatapple** [comment]
我发现关掉大家就看不到了，还是打开吧。哈哈。

**Comment by ttyy33** [comment]
> 我来建一个telegram的，大家一定要注意安全，不要相信任何主动私聊的人。 https://t.me/ChatBoxApp

你可以把这个改成开发者的群，这样大家就不用翻到下面去找了

**Comment by lolieatapple** [comment]
> 是这样子吗？

**Comment by ttyy33** [comment]
> > 是这样子吗？

对的

**Comment by Bin-Huang** [comment]
我等下会把开发者群的链接放到 README 里，这里 issues 先关闭了。@lolieatapple 你有兴趣当开发者群的管理员吗？我开发比较忙不经常看群～

**Comment by lolieatapple** [comment]
可以，给我个管理员吧，我平时都在线。
