### ISSUE TITLE
[Feature]latex公式渲染

### ISSUE THREAD

**Issue by EnochYe** [Bin-Huang/chatbox#1133]
**Problem Description**
回复带的latex公式不能渲染，希望能支持这个功能
![image](https://github.com/Bin-Huang/chatbox/assets/40822159/ff86ee25-8839-4cbb-9925-9e7b5af467b6)

**Proposed Solution**
希望能够正常渲染latex公式

**Additional Context**
chatbox这个产品真的太好用了，还做了ios和Android适配，祝作者早日做出商业化的部分！ 为爱发电真的不容易
附上一点心意
![IMG_5952](https://github.com/Bin-Huang/chatbox/assets/40822159/1789956d-bc64-43dd-93cc-e6c8299001e3)

**Comment by alexstore06** [comment]
See issue #1089. LaTeX must be wrapped in $ to be parsed. Adding "wrap LaTeX in $" or similar to your prompt should correct the issue.

**Comment by EnochYe** [comment]
wow I get it, thank you so much!
