### ISSUE TITLE
[Feature] mistral api

### ISSUE THREAD

**Issue by sibrash4** [Bin-Huang/chatbox#1134]
**Problem Description**

Integrate Mistrall's API into Chatbox to access their LLMs, enhancing the software's range and efficiency.

**Comment by yjhjstz** [comment]
+1

**Comment by leleogere** [comment]
It is already possible using the OpenAI API as they are compatible:
- Select `OpenAI API` in the menu
- Input `https://api.mistral.ai` in the "Host API" field
- Input your API key in the "OpenAI API key" field
- Expand the "Model & token" menu
- Select `Custom model` in the "Model" menu
- Input the name of the model you want to use in the "name" field (`mistral-tiny`, `mistral-small` or `mistral-medium`)

**Comment by sibrash4** [comment]
thanks that worked i had tried it before but what fixed it was using https://api.mistral.ai instead of the /completions one that was in the documentation i read

**Comment by aanwark** [comment]
> However, I don't think that it should be closed, as having a dedicated entry for Mistral AI in the settings would be more convenient for users, as it would allow to have 2 separate configs for OpenAI and Mistral, and switching between them without having to re-enter all details each time.

I completely agree, the solution with OpenAI API key is not ideal since it enforces the use of one or the other API.
