### ISSUE TITLE
[Feature] 建议支持enter和ctrl-enter两个快捷键自定义

### ISSUE THREAD

**Issue by Marstheway** [Bin-Huang/chatbox#1136]
**问题描述**
建议支持enter和ctrl-enter两个快捷键自定义。

**解决思路**
有的人希望输入较长的prompt，那么他有可能会在输入框中频繁使用Enter回车，但现在Enter默认是直接发给模型，这样就导致经常误操作。

建议：支持可自定义的配置选项。  使Enter为普通回车，Ctrl+Enter为向模型发送请求。  

**附加上下文**
无

**Comment by sheng-di** [comment]
+1
对于输入长文本、输入代码的情况下，很容易就误触了。

**Comment by kqme** [comment]
一直不支持Ctrl+Enter，已经转用其他软件了。

**Comment by Yuxuan7777** [comment]
+1+1
明明希望快捷键自定义赶紧提上日程，长文本输入很容易误触

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #939, so I'll close this to avoid duplicates. Feel free to add more thoughts there!
