### ISSUE TITLE
Latex support

### ISSUE THREAD

**Issue by dborro** [Bin-Huang/chatbox#1138]
Although chatgpt web version has latex support, my chatbox app seems to miss that feature. Is there that option in some place I can't find?

**Comment by alexstore06** [comment]
See issue #1089. LaTeX must be wrapped in $ to be parsed. I simply added "Wrap latex in $" to my prompt, and gpt4-turbo handled it fine.

**Comment by Bin-Huang** [comment]
Thank you for reporting this issue! I'm happy to let you know that it has been resolved in the latest version. Please update to the newest release to see the changes.

<img width="1288" src="https://github.com/Bin-Huang/chatbox/assets/20723142/808b27a1-5806-4964-adea-bd5f35775869">
