### ISSUE TITLE
[BUG] 安卓应用程序无法导出数据

### ISSUE THREAD

**Issue by Clarice0997** [Bin-Huang/chatbox#1140]
**Bug 描述**
安卓应用程序无法导出数据，点击了导出按钮没有反应

**重现步骤**

1. 进入“设置”
2. 点击 “其他”
3. 点击 ”数据备份与恢复“
4. 点击 ”导出勾选数据“
4. 发现了这个 bug

**期望结果**
能够将数据导出到指定手机存储文件夹中

**桌面端（请填写以下信息）：**

-   操作系统：Android 14
-   应用程序版本：v1.2.2

**Comment by Bin-Huang** [comment]
新版本已修复
