### ISSUE TITLE
[Feature] 话题列表功能

### ISSUE THREAD

**Issue by kangfenmao** [Bin-Huang/chatbox#1142]
# 问题描述

建议增加话题列表，方便同一个助手可以进行不同主题的会话

<img width="96" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/8253512/39a872ad-1bc6-4174-a62d-619233d03428">

当前这个按钮开启新会话功能可以继续优化，更好的方式是使用会话列表来管理

# 解决思路

增加话题列表，点击话题即可切换，可以参考 LobeChat

<img width="1675" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/8253512/c24a1933-e274-4962-aab7-6f843613d0fb">

**Comment by Bin-Huang** [comment]
这个功能一直都有的，点击右上角这里
<img width="232" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/7ce56cd1-6e50-442f-8e47-727148348a93">

![Uploading image.png…]()
