### ISSUE TITLE
windows客户端 GPT每次回复的内容前后会多出两个NULL

### ISSUE THREAD

**Issue by coderzhou-feng** [Bin-Huang/chatbox#1143]
![image](https://github.com/Bin-Huang/chatbox/assets/56922644/e515672b-0185-4bfe-8296-d1162b2f1a79)
windows客户端 GPT每次回复的内容前后会多出两个NULL

**Comment by Bin-Huang** [comment]
这应该与你的模型服务有关，与客户端无关
