### ISSUE TITLE
[Feature] Automatically name conversation

### ISSUE THREAD

**Issue by leleogere** [Bin-Huang/chatbox#1146]
**Problem Description**
It might be a bug, but when creating a new conversation, it is first named "Untitled", but as soon as I send the first message, the name vanishes and I end up with a bunch of unnamed conversations (see below).

![image](https://github.com/Bin-Huang/chatbox/assets/71326140/aea01573-379c-49ab-8ca6-834676607ec7)

**Proposed Solution**
I would be nice to be able to automatically name the conversations. The most basic idea would be to use the first words of the first message, but it would be nice to be able to have the option to use the currently used model to generate a title for the conversation based on the first message and answer.

**Comment by Bin-Huang** [comment]
Fixed in v1.3.4
