### ISSUE TITLE
[Feature] support latex

### ISSUE THREAD

**Issue by lore-ys** [Bin-Huang/chatbox#1153]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

need LaTeX support to enhance the readability of LaTeX.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

Some latex JS file may be helpful for displaying latex formular.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.
![Screenshot 2024-01-25 110658](https://github.com/Bin-Huang/chatbox/assets/112916358/adbb343f-a50e-41db-a5f3-937fc63e8be3)

---

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by alexstore06** [comment]
See issue #1089. LaTeX must be wrapped in $ to be parsed. Adding "wrap LaTeX in $" or similar to your prompt should correct the issue.

**Comment by Bin-Huang** [comment]
Thank you for reporting this issue! I'm happy to let you know that it has been resolved in the latest version. Please update to the newest release to see the changes.

<img width="1288" src="https://github.com/Bin-Huang/chatbox/assets/20723142/808b27a1-5806-4964-adea-bd5f35775869">
