### ISSUE TITLE
[Feature] Organize Chats in Folders

### ISSUE THREAD

**Issue by voidxd** [Bin-Huang/chatbox#1154]
**Problem Description**
Conversations that you want to refer back to can add up and be difficult to locate.

**Proposed Solution**
Possibility of assigning conversations folders/categories/tags, anything like that.

--
Thank you. This is a wonderful software you've made and it's become indispensable to me.

**Comment by Bin-Huang** [comment]
This issue duplicates #676. Closing for better organization. Thank you! 😆
