### ISSUE TITLE
[Feature] chatgpt-4-turbo-preview now accepts image inputs, allow image inputs to be passed through chatbox.

### ISSUE THREAD

**Issue by BrennanT** [Bin-Huang/chatbox#1155]
**Problem Description**
Chatgpt-4-turbo-preview accepts image inputs through the API. There is no way to add image inputs through chatbox.

**Proposed Solution**
Allow image inputs to be passed to chat API's that accept them.

**Comment by JustinGuese** [comment]
same

**Comment by JustinGuese** [comment]
ah yes it's actually an error on the side of openai :o the model's name is gpt-4-turbo-preview
when I'm entering it as a custom model it works!

<img width="570" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/9588843/d6ef58ce-0586-432c-9abc-c4b49cf17a4b">

**Comment by miaotouy** [comment]
The current method is to find an image hosting website to upload the picture, and then include the link to the image in the message.
