### ISSUE TITLE
[Feature] New model support

### ISSUE THREAD

**Issue by EaglePPP** [Bin-Huang/chatbox#1159]
Newer model released, please add gpt-4-turbo-preview

Models - OpenAI API
https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by JustinGuese** [comment]
you can add it as a custom model for now, remember the context Len 4096

<img width="570" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/9588843/624f7532-d606-4fda-8ac6-1a10deaad125">

**Comment by Bin-Huang** [comment]
This feature has been implemented, try the latest version.
