### ISSUE TITLE
在AI正在输出内容时或刚输出完成时，删除功能无法正常使用(BUG)

### ISSUE THREAD

**Issue by WUTONK** [Bin-Huang/chatbox#116]
在AI正在输出内容时，点击删除键无法清除之前的内容，或出现闪屏（清除后复显）的情况，在刚输出完成时点击删除，有时会出现删除后1-2秒重新显示被删除的聊天记录的情况
[演示视频](https://twitter.com/wutonk386/status/1638443998762393600?s=61&t=31vIh4xSI2dA3SDU5igpyQ)

环境: chatbox 0.21(for arm mac) MacBook Air2020(M1) macos:13.0 (22A380)

**Comment by Bin-Huang** [comment]
新版本已经支持 M1
