### ISSUE TITLE
[Other] How do you build ios/andriod app based on react? 

### ISSUE THREAD

**Issue by so2liu** [Bin-Huang/chatbox#1163]
I am only curious, how do you build ios/andriod app based on react? I know tauri mobile is still in alpha status and I cannot find related code. Thanks

**Comment by gtirloni** [comment]
https://reactnative.dev

**Comment by so2liu** [comment]
> https://reactnative.dev

I thought it would be tauri 2.0 alpha. React Native cannot reuse code in web

**Comment by Bin-Huang** [comment]
The mobile version uses different technology, you can view the details here: https://capacitorjs.com
