### ISSUE TITLE
[Feature] Image generation setting for amount of images generated.

### ISSUE THREAD

**Issue by cs-zp-rd** [Bin-Huang/chatbox#1168]
**Problem Description**
When I generate images, I hit my azure dall-e-3 instance request limit, because it only allows 1 or 2 images generated simultaniously on my pricing tier.

**Proposed Solution**
I would like to have a setting to choose how many images are generated per prompt.

**Comment by Bin-Huang** [comment]
![image](https://github.com/Bin-Huang/chatbox/assets/20723142/a29996ee-3271-443a-ad9b-18cd21ad42b2)
Click the image-creator conversation title, and you will see it.
