### ISSUE TITLE
输入字符过长会导致右上角重新生成和菜单按钮闪现到最后导致布局跳动

### ISSUE THREAD

**Issue by MonkeyCoder128** [Bin-Huang/chatbox#117]
<img width="1335" alt="Snipaste_2023-03-22_16-35-22" src="https://user-images.githubusercontent.com/42332199/226846284-27cd42d5-9203-47bf-804c-1b5eb9ded62b.png">

**Comment by Bin-Huang** [comment]
This issue has been resolved in the new version v0.6.3. If the problem still persists, you can reopen the issue at any time😊.
https://github.com/Bin-Huang/chatbox/releases


这个问题在新版本 v0.6.3 已经解决，如果问题还存在你可以随时重新开启这个 issues 😊。
https://github.com/Bin-Huang/chatbox/releases
