### ISSUE TITLE
The latest GitHub release is 1.2.2, but on chatboxai.app, it is 1.2.6.

### ISSUE THREAD

**Issue by x011** [Bin-Huang/chatbox#1177]
Hi,

I noticed that the version on the website is more recent than the one on GitHub. Can you please explain why there is a difference?

Thank you,
Peter

**Comment by TridentDoubleMint** [comment]
thats a good question

**Comment by emerson000** [comment]
Benn has addressed this previously. See response here: https://github.com/Bin-Huang/chatbox/issues/803#issuecomment-1797994508
