### ISSUE TITLE
[Feature] Add whisper for voice input

### ISSUE THREAD

**Issue by honeyspoon** [Bin-Huang/chatbox#1179]
**Problem Description**
Want voice input to practice language learning with llm

**Proposed Solution**
Many options
- bundle whisper.cpp
- ask user to install it, build and point to bin and model files.
- use open ai whisper

I think it can run locally without difficulty on most machines.

In terms of ui features we would need to add a microphone button next to the text section.
And a section in the settings to setup the path/creds..

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1239, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1239。这条 issue 先关闭了～～
