### ISSUE TITLE
[Feature] ChatBox integration with Cheshire-Cat Framework

### ISSUE THREAD

**Issue by pazoff** [Bin-Huang/chatbox#1185]
## Production ready AI assistant framework

The [Cheshire Cat](https://github.com/cheshire-cat-ai/core) is a framework to build custom AIs on top of any language model. 
If you have ever used systems like WordPress or Django to build web apps, imagine the Cat as a similar tool, but specific for AI.

## Why use the Cat

- ⚡️ API first, so you get a microservice to easily add a conversational layer to your app
- 🚀 Extensible via plugins (AI can connect to your APIs or execute custom python code)
- 🏛 Easy to use admin panel
- 🌍 Supports any language model (works with OpenAI, Google, Ollama, HuggingFace, custom services)
- 🐘 Remembers conversations and documents and uses them in conversation
- 🐋 Production ready - 100% [dockerized](https://docs.docker.com/get-docker/)
- 👩‍👧‍👦 Active [Discord community](https://discord.gg/bHX5sNFCYU) and easy to understand [docs](https://cheshire-cat-ai.github.io/docs/)

## Docs and Resources

- [Official Documentation](https://cheshire-cat-ai.github.io/docs/)
- [Discord Server](https://discord.gg/bHX5sNFCYU)
- [Website](https://cheshirecat.ai/)
- [YouTube tutorial - How to install](https://youtu.be/Rvx19TZBCrw)
- [Tutorial - Write your first plugin](https://cheshirecat.ai/write-your-first-plugin/)

## Admin Panel Demo

<video src="https://github.com/cheshire-cat-ai/core/assets/6328377/7bc4acff-34bf-4b8a-be61-4d8967fbd60f"></video>

## API
![image](https://github.com/Bin-Huang/chatbox/assets/28357700/4f774df4-0331-4139-9aa9-adc610a4aaef)

### It would be cool ChatBox to be able to connect to [Cheshire-Cat Framework](https://github.com/cheshire-cat-ai/core) and use its features (RAG, Forms, ease of extensibility via plugins)

**Comment by DiBenedettoGaetano** [comment]
hi @pazoff, did you try a method to do that? I'm try to do the same thing and connect ChatBox with Cheshire
