### ISSUE TITLE
[Feature] Ollama已经支持视觉模型了，咱们啥时候支持Ollama的视觉模型直接发送图片呢

### ISSUE THREAD

**Issue by MrYangyt** [Bin-Huang/chatbox#1189]
Ollama已经支持视觉模型了，咱们啥时候支持Ollama的视觉模型直接发送图片呢，现在尝试使用Ollama的视觉模型，无法发送图片，如果使用图片的本地url,也无法正常回答

**Comment by Bin-Huang** [comment]
之前的版本更新中已经支持了
