### ISSUE TITLE
Maintain custom LLM endpoints without manually swapping them around each time

### ISSUE THREAD

**Issue by mountee32** [Bin-Huang/chatbox#1199]
**Problem Description**
I want to support multiple LLM API endpoints, some local and some like openrouter.ai.  There's no current way to store the configs for all of these at the same time but have to manually edited each time to switch.

**Proposed Solution**
Allow adding MULTIPLE custom API LLM configurations

**Additional Context**
Ideally allow editing these MULTIPLE custom API LLM configurations in the UI but an interim solution of editing a config file manually could work

**Comment by miaotouy** [comment]
I'm the same way

**Comment by rushikb** [comment]
+1 — openrouter configuration makes it a lot easier to experiment with other / newer custom models!

**Comment by 22GNUs** [comment]
+1

**Comment by kaptainkangaroo** [comment]
+1

**Comment by coljac** [comment]
I think this is necessary. I imagine a common use case would be to use one model for general queries, but specialised models for code or experiments. Easily swapping, and having the model persist with the chat, would facilitate this.

**Comment by dreamshit** [comment]
I have three azure openai endpoints....

**Comment by Bin-Huang** [comment]
> I think the best would be to support multiple "User Models" each model being a combination of:
> 
> * Custom name (optional)
> * Type of API (OpenAI, Anthropic, Ollama, etc.)
> * API Key
> * Base URL
> * LLM Model name (from the list for given Type of API or custom string)
> * ...
> 
> The user could add and remove his User Models. This way it's possible to easily use the same Type of API with different URLs, but also different API Keys to the same API and provider. Some providers (e.g. Mistral) expose an OpenAI-like API which can be used while its native API is not available with Chatbox. With this solution it would be possible to e.g. keep both configurations for Mistral and OpenAI, which is one of my use cases. This approach is common for file clients like FileZilla, Cybeduck etc.

The feature is already included in Chatbox.

**Comment by tlvenn** [comment]
Hi @Bin-Huang, can you point out how to do this plz ? I was hoping to be able to define 2 different providers and have their models being merged in the select box but it only shows the "active" provider and i have to go to settings and switch to the other provider in order to use a model from that provider.

Am i missing something ?
Thanks in advance.
