### ISSUE TITLE
[功能建议]添加send发送快捷键

### ISSUE THREAD

**Issue by colordi** [Bin-Huang/chatbox#12]
目前我在macOS上使用起来回车用于换行，这比官方的直接发送出去好多了，但是可否加上一下组合键进行发送的快捷键，目前还只能手动点按，有点不太方便

**Comment by Bin-Huang** [comment]
你好，我猜测你可能使用了较早期的版本。其实发送快捷键已经更新两个版本了。经过大家的反馈和调整，现在是按回车发送，按 shift+回车键换行。

**Comment by Bin-Huang** [comment]
下载最新版本试一下，对于快捷键和使用习惯有任何的疑问和建议都可以发出来讨论一下。快捷键这块主要看大家的使用习惯。

**Comment by colordi** [comment]
感谢感谢！！

**Comment by Bin-Huang** [comment]
以后有快捷键的建议，可以再开个新issues讨论。
