### ISSUE TITLE
希望有适配APPLE SLICON芯片的版本

### ISSUE THREAD

**Issue by IntelHeartPrime** [Bin-Huang/chatbox#120]

**Comment by Bin-Huang** [comment]
可以先直接使用 x64 版本，也是可以运行的～

**Comment by IntelHeartPrime** [comment]
Cool, I know that,I am using the x86 version and it's good,  but I am still very expecting to wait for the M1 version

**Comment by xtremforce** [comment]
既然已经换上 tauri 了，我也希望作者可以加上 ARM64 了。就像最近用的这个工具 https://github.com/yetone/openai-translator/releases/latest，也是 tarui，实际在使用 aarch64 版对比 x64 版，启动速度上还是有肉眼能感受到的提升的。

**Comment by orangelckc** [comment]
come to see this repo https://github.com/ChatGPT-Desktop/ChatGPT-Desktop

**Comment by Bin-Huang** [comment]
新版本已经支持 M1
