### ISSUE TITLE
[Feature] Any easy way to access to Claude 3?

### ISSUE THREAD

**Issue by timnew** [Bin-Huang/chatbox#1201]
**Problem Description**
Any easy way to add Claude 3? The API should be the same, but just need to add new model names.

**Proposed Solution**
Maybe consider allow advanced user to add custom model name?

**Comment by bisslot** [comment]
Looking forward to Claude 3 API access！ 期待Claude 3 API 接入

**Comment by JusitnZhangJin** [comment]
Looking forward to Claude 3 API access！ 期待Claude 3 API 接入

**Comment by hkwz2023** [comment]
Just recharged the Claude API, also looking forward to it.

**Comment by Upsetin** [comment]
Looking forward to Claude 3 API access！ 期待Claude 3 API 接入

**Comment by heroghost** [comment]
能请求api.openai.com但是不能请求api.anthropic.com，提示跨域。哪位大神知道原因吗？

**Comment by cocoonkid** [comment]
Whoop! Whoop! Bring it on :-)

**Comment by Bin-Huang** [comment]
If you're encountering CORS errors, it's likely due to using the web version of Chatbox. There are virtually no technical workarounds for this issue within the browser webpage, so it's recommended that you download the desktop version of Chatbox.
