### ISSUE TITLE
CORS error on request to  https://api.anthropic.com

### ISSUE THREAD

**Issue by heroghost** [Bin-Huang/chatbox#1202]
I met a problem when try to request  https://api.anthropic.com. 
Access to fetch at 'https://api.anthropic.com/v1/messages' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Do you have any idea about this problem?

**Comment by Bin-Huang** [comment]
If you're encountering CORS errors, it's likely due to using the web version of Chatbox. There are virtually no technical workarounds for this issue within the browser webpage, so it's recommended that you download the desktop version of Chatbox.
