### ISSUE TITLE
[Feature] Integrate Claude3 Language Model Support in ChatBox

### ISSUE THREAD

**Issue by Upsetin** [Bin-Huang/chatbox#1204]
**Problem Description**

The current version of ChatBox does not support the recently released Claude3 language model from Anthropic. This limitation makes it difficult to leverage the improved capabilities and performance of the new model, which could potentially enhance the user experience and the quality of responses generated by the application.

**Proposed Solution**

Implement support for the Claude3 language model within the ChatBox application. This would involve integrating the necessary APIs and libraries provided by Anthropic to enable seamless communication with the Claude3 model. Additionally, the user interface should be updated to allow users to select the Claude3 model as an option when initiating a conversation or switching between models.

**Additional Context**

1. **Use Case**: Many users of ChatBox are interested in exploring the latest advancements in language models, and the ability to utilize Claude3 would cater to this demand. Enabling support for Claude3 would position ChatBox as a cutting-edge application that stays up-to-date with the latest developments in the field.

2. **Performance Improvements**: According to Anthropic's documentation, Claude3 offers improved performance and accuracy compared to previous versions, including better handling of context, increased knowledge retention, and more natural conversation flow. Integrating Claude3 could potentially enhance the overall user experience within ChatBox.

3. **API Documentation**: Anthropic provides comprehensive documentation and resources for integrating their language models, including Claude3. Following their guidelines and best practices would ensure a smooth and efficient implementation process.

4. **Compatibility**: It is essential to ensure that the integration of Claude3 does not break or negatively impact the existing functionality of ChatBox. Thorough testing and validation should be conducted to maintain compatibility with other supported language models and features.

By addressing this feature request, ChatBox would remain a competitive and relevant application in the rapidly evolving field of conversational AI, providing users with access to the latest advancements and enabling a more engaging and productive conversational experience.

**Comment by hfun2017** [comment]
加一,  希望开发者可以支持Claude3模型

**Comment by chrber04** [comment]
I'm sorry but it's hilarious to me you used AI to generate the issue post. I love AI man

**Comment by Bin-Huang** [comment]
This feature has been implemented, try the latest version.
