### ISSUE TITLE
[Feature] support claude 3

### ISSUE THREAD

**Issue by Illusion-95** [Bin-Huang/chatbox#1211]
**Problem Description**
cannot support Claude 3.

**Proposed Solution**
add support Claude 3 API in it.

**Additional Context**
none

---

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by chrber04** [comment]
yes please should be relatively easy update, I assume

**Comment by chrber04** [comment]
Just wanted everyone to know that claude 3 is now supported in the latest version (v1.3.0). Logs: https://chatboxai.app/help-center/changelog
