### ISSUE TITLE
[BUG] README instructions don't match package.json

### ISSUE THREAD

**Issue by SethFalco** [Bin-Huang/chatbox#1217]
**Bug Description**

Minor issue, but the README instructs us to run `npm start`, but no `start` script is defined in the `package.json` file.

Instead, either the command in `package.json` should be renamed to `start`, or the README should be updated to refer to `start:react`.

**Steps to Reproduce**

1. Follow the steps in the README to run locally from source

**Expected Results**

Application runs

**Actual Results**

NPM displays an error as no script for `npm start` exists.

**Screenshots**
N/A

**Desktop (please complete the following information):**

-   Operating System: postmarketOS
-   Application Version: `main` (3dcb600f31a5b982955af7327940cd8dc4b6d121)

**Additional Context**
N/A

**Comment by Rony-dot** [comment]
- Shows the following error when we run `npm start` as per the `Readme` file.
![image](https://github.com/Bin-Huang/chatbox/assets/60981539/8fbfca47-3950-4f10-909f-f50829371c2c)

- But works correctly when we run ` npm run start:react`

**Comment by CyberShadow** [comment]
> * But works correctly when we run ` npm run start:react`

This doesn't work for me either.

```
$ npm run start:react 

> chatbox@0.0.1 start:react
> react-scripts start


There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "eslint": "^5.16.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

  /home/vladimir/work/extern/chatbox/node_modules/eslint (version: 8.46.0) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "eslint" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /home/vladimir/work/extern/chatbox/node_modules/eslint is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls eslint in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed eslint.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!
```

The message has instructions that seem to explain how to fix the problem, but these instructions seem to be addressed to chatbox's developer (@Bin-Huang), not the user.

**Comment by 0wwafa** [comment]
same here.

**Comment by coljac** [comment]
I can't find a workaround for the eslint dependency issue; removing all references in package.json doesn't help.

**Comment by jalr4ever** [comment]
same issue in macos

**Comment by Bin-Huang** [comment]
I've been prepping a major code update for the past few weeks, please hang tight for a bit longer.

**Comment by coljac** [comment]
I did get it to run with tauri, sort of, but just got a blank screen and a warning about being version 0.0.1. I guess we'll have to wait for a bit - I don't think the source reflective of the build at the moment.

**Comment by guoapeng** [comment]
I think the main branch is unstable not a ready to release branch. 
To bring the app up, I made a branch based on a latest release tag as the following and then build the project again and start it. it works.

```bash

git checkout -b newbranch v1.3.10
git checkout newbranch
npm install
npm run build:react
npm run start:react

```

then open http://localhost:3000 on browser, the UI is display normally.

**Comment by Bin-Huang** [comment]
In this PR, I've updated the codebase to a newer version, and simpler and more reliable build instructions.

https://github.com/Bin-Huang/chatbox/pull/1428
