### ISSUE TITLE
为什么调用GPT3.5模型，但是AI答自己是3

### ISSUE THREAD

**Issue by kinawater** [Bin-Huang/chatbox#122]
![image](https://user-images.githubusercontent.com/22518112/226967151-2928ab8a-9e75-419e-84be-90916a3c0207.png)
![image](https://user-images.githubusercontent.com/22518112/226967285-3b394d92-f9e9-40f0-814a-a3808a7fba41.png)
![image](https://user-images.githubusercontent.com/22518112/226967482-5ad95dba-48d7-42a1-81a8-aa1b428de593.png)
已经有点蒙了，三个地方显示的模型都不一样

**Comment by kinawater** [comment]
我估计是他自己的问题，我直接curl请求也是这个结果
![image](https://user-images.githubusercontent.com/22518112/226971056-e6f10904-7aa2-4e26-939d-ed1418d0ecb2.png)

**Comment by Bin-Huang** [comment]
是的，有时候模型会自己乱说话。比如我第一次问他它会不会中文，它用中文和我说它是个模型不会中文……
