### ISSUE TITLE
[BUG] Claude API 400: text content blocks must be non-empty

### ISSUE THREAD

**Issue by Sheldontao** [Bin-Huang/chatbox#1222]
<img width="466" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/36765652/c85035d0-8f8f-4869-a464-35fac82fe76a">

**桌面端（请填写以下信息）：**

-   操作系统： macOS
-   应用程序版本：1.3.0

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Sheldontao** [comment]
原本是可以用的，切换了3.0，再切换回来就不可以了。

**Comment by Bin-Huang** [comment]
I want to know, is this a problem that occurs only when sending pictures, not text?

**Comment by Bin-Huang** [comment]
请问这个问题只会发生在发送图片但不包含文本的情况下吗？

**Comment by Sheldontao** [comment]
You organization has been disabled(结束体验gg)

**Comment by Bin-Huang** [comment]
Fixed in v1.3.1

**Comment by siwuxei** [comment]
依旧有问题，1.3.1没有修复
'''
API Error: Status Code 404, {"error":{"message":"Invalid URL (POST /v1/messages)","type":"invalid_request_error","param":"","code":""}}
'''

**Comment by Bin-Huang** [comment]
> 依旧有问题，1.3.1没有修复 ''' API Error: Status Code 404, {"error":{"message":"Invalid URL (POST /v1/messages)","type":"invalid_request_error","param":"","code":""}} '''

这应该是配置错误，在设置里点击回滚到默认域名。如果你使用的某些代理服务，那么就是代理服务的错误。

**Comment by siwuxei** [comment]
感谢回复！使用了代理，但是该代理在几个网页端是可以使用Claude的
