### ISSUE TITLE
[BUG] Claude API domain is not correct

### ISSUE THREAD

**Issue by ifengz** [Bin-Huang/chatbox#1223]
in the latest chatbox version, with the same key in claude 1 model and domain https://api.anthropic.com/, will have an error 400
but in the previous chatbox version, the same API key for the Claude 1 model worked correctly without any issues.

**Comment by Bin-Huang** [comment]
Thanks for bringing this to my attention! It looks like this issue has been reported before in #1221, so I'm going to close this one to keep the conversation centralized over there. Please feel free to add any additional comments or insights you have to the existing thread.

Thanks again for your contribution!

**Comment by goforwork** [comment]
<img width="764" alt="image" src="https://github.com/user-attachments/assets/77820b31-09d8-4aaf-a706-283ce0987e64">
have the same problem. I download the app from official site. The version is v1.3.17

**Comment by Bin-Huang** [comment]
> <img alt="image" width="764" src="https://private-user-images.githubusercontent.com/28641986/353467665-77820b31-09d8-4aaf-a706-283ce0987e64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDk5ODUsIm5iZiI6MTcyMjQwOTY4NSwicGF0aCI6Ii8yODY0MTk4Ni8zNTM0Njc2NjUtNzc4MjBiMzEtMDlkOC00YWFmLWE3MDYtMjgzY2UwOTg3ZTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA3MDgwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0MGEwZjNiZjg0NDVkY2JiMjk3NWZkODMzMDA2ODA3YTczMGY5NDkwODVlNTUxZDZiNmJlMmQyMmQ3MTk3YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GnvpI9jJpg1EyGA1hsgcIFxBGNFyTat-SywS30xfeVQ"> have the same problem. I download the app from official site. The version is v1.3.17

Looks like the error isn't a bug, but due to a missing API KEY. Have you correctly configured the Claude API's API KEY in your settings?
