### ISSUE TITLE
使用claude会提示如下错误，但是我在浏览器上访问正常，api-key也是最新生成的。

### ISSUE THREAD

**Issue by fu7100** [Bin-Huang/chatbox#1224]
遇到了来自 Claude 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 400, {"type":"error","error":{"type":"invalid_request_error","message":"messages: text content blocks must be non-empty"}}

**Comment by aaronxliu** [comment]
同样的问题

**Comment by Bin-Huang** [comment]
这里有个重复 issues，我们在这里讨论吧～ #1222
