### ISSUE TITLE
[BUG]Androidapp的设置中的快捷键页面无法使用

### ISSUE THREAD

**Issue by xinghe6** [Bin-Huang/chatbox#1228]
如标题所说，快捷键页面的设置都无法自由开启或关闭（本身就显示的是电脑端快捷键）其中有一些影响Android使用的选项，比如回车发送消息无法关闭（导致我无法在消息中换行）

**Comment by Bin-Huang** [comment]
最近的几个版本已经修复了问题，可以试试看
