### ISSUE TITLE
[BUG] 升级了1.3.0之后变得不可用

### ISSUE THREAD

**Issue by ali50m** [Bin-Huang/chatbox#1229]
原来使用的是1.2.6版本,使用的openai服务(填写了定制的url和key), 使用一直正常. 升级了1.3.0之后,AI问答就不可用了.一直提示下面的错误:
```
遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 429, {"statusCode":429,"message":"ThrottlerException: Too Many Requests"}
```

即使是重新设置一遍url和api key, 也是同样的结果. 重新安装1.2.6之后又正常了.

**Comment by Bin-Huang** [comment]
请先看一遍错误信息，这里提到了 `ThrottlerException: Too Many Requests ` 很明显是因为 OpenAI 认为你的请求超速了（请求频率过高），所以暂时不可用。和软件没有任何关系啊。

**Comment by jasoncow007** [comment]
同样，升级chatbox之后出现这样的问题
