### ISSUE TITLE
你好，作者，请问什么时候出中文版，不懂英文，还有个模型问题需要咨询

### ISSUE THREAD

**Issue by meyingjian** [Bin-Huang/chatbox#124]
你好，作者，请问什么时候出中文版，不懂英文，但是是用于写文案的！
![image](https://user-images.githubusercontent.com/33636687/227040341-30a80065-8f05-4924-846e-cfdf868144ab.png)
这几个GPT4和GPT3.5有什么不同？
望您从百忙空中解答一下谢谢！

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/Chatbox-v0.2.3

新版本支持中文了。建议你不了解的话，直接用默认的模型（3.5），因为 GPT-4 需要在 ChatGPT 官方网站上进行预约排队。
