### ISSUE TITLE
[BUG]winrar解压出来的无法运行提示

### ISSUE THREAD

**Issue by 1353604736** [Bin-Huang/chatbox#1240]
![2024-03-17_101550](https://github.com/Bin-Huang/chatbox/assets/12869582/336487c2-b8d2-4341-a929-7121c49d7304)

**Comment by Bin-Huang** [comment]
提供的安装包是可以正常使用的，建议不要解压

**Comment by 1353604736** [comment]
> 提供的安装包是可以正常使用的，建议不要解压

但是很多需要绿色版，或指定安装目录
