### ISSUE TITLE
[BUG]上下图标会被代码块遮挡几个像素，平台 windows

### ISSUE THREAD

**Issue by qdanyan** [Bin-Huang/chatbox#1242]
**Bug 描述**
上下图标会被代码块遮挡几个像素

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：

**截图**
![image](https://github.com/Bin-Huang/chatbox/assets/160691801/fb96e441-20c0-4626-932b-a4d059ce064f)

**桌面端（请填写以下信息）：**

-   操作系统：[Windows]
-   应用程序版本：[1.3.1]
-  语言：[简体中文]
- 字体大小：[14]
- 桌面分辨率：[1920 x 1080]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
新版本已解决～
