### ISSUE TITLE
[Feature] Auto title generation for Claude model / 自动标题生成

### ISSUE THREAD

**Issue by henrychiu1997** [Bin-Huang/chatbox#1244]
In current version(1.3.1), conversations with Claude3 model do not automatically generate titles. Would it be possible to consider supporting automatic title generation?

---

目前版本（v1.3.1）中，基于Claude3发起的对话没有自动生成标题，是否能考虑支持自动标题生成。

**Comment by Bin-Huang** [comment]
Fixed in v1.3.4
