### ISSUE TITLE
[BUG] Very Frequent Application Crashes on Windows 

### ISSUE THREAD

**Issue by Skier23** [Bin-Huang/chatbox#1249]
**Bug Description**
ChatBox freezes and crashes about once every 2-3 minutes or so on Windows

**Steps to Reproduce**
Use the app for more than a few minutes on windows

**Expected Results**
No crashes

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**

-   Operating System: Windows 10
-   Application Version: 1.3.1

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

---

**Comment by Bin-Huang** [comment]
Thank you for reporting this issue! I'm happy to let you know that it has been resolved in the latest version. Please update to the newest release to see the changes.
