### ISSUE TITLE
[Feature] iOS: 不支持 OpenRouter API

### ISSUE THREAD

**Issue by luo10m** [Bin-Huang/chatbox#1251]
**问题描述**

Windows v1.3.1 支持OpenRouter API
iOS v1.2.2 不支持 OpenRouter API, 按 Windows 版本同样配置，响应为：
"A network error has occurred. Please check your current network status and the connection with https://openrouter.ai."
此时，用浏览器访问 https://openrouter.ai 是通畅的。

**解决思路**
请更新 iOS 版本以支持 OpenRouter API

**Comment by Bin-Huang** [comment]
可以升级到最新版本试一下。新版本会自动兼容各种配置错误的情况。
