### ISSUE TITLE
[BUG] Cannot get the stream response in Android Client (Version 1.3.1)

### ISSUE THREAD

**Issue by Nerooo-g** [Bin-Huang/chatbox#1253]
**Bug Description**
Outputs are not displayed in real-time; they only appear after the completion of responses.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

1. Go to the text box and edit the prompts.
2. Click on sending.
3. Observe the bug.

**Expected Results**
The application should stream responses, showing outputs as they are being generated.

**Actual Results**
Outputs are not displayed until after the responses have been fully generated, consistent with the initial bug description.

**Screenshots**
N/A

**Desktop (please complete the following information):**

-   Operating System: [Android 14]
-   Application Version: [1.3.1]

**Additional Context**
N/A

**Comment by Bin-Huang** [comment]
Thank you for reporting this issue! I'm happy to let you know that it has been resolved in the latest version. Please update to the newest release to see the changes.

**Comment by Nerooo-g** [comment]
Hey, this bug is still there in the latest version. I uninstall and reinstall it, but prompts still can't get the stream response.

**Comment by Bin-Huang** [comment]
Which model provider are you using? If you are using Azure OpenAI, this model provider itself does not support streaming reply.

**Comment by Nerooo-g** [comment]
> Which model provider are you using? If you are using Azure OpenAI, this model provider itself does not support streaming reply.

No, the official OpenAI API key has been set. I believe it is unrelated to the model, as Gemini is also not functioning properly.
