### ISSUE TITLE
[BUG]mac会空回复，而且无错误码

### ISSUE THREAD

**Issue by Autumn-Whisper** [Bin-Huang/chatbox#1255]
**Bug 描述**
mac突然开始空回复，反复重载也无效，而且无错误码。

**重现步骤**
突然发生,在其他设备上尝试重现失败

**期望结果**
正常给出回复。

**实际结果**
空回复。

**截图**
<img width="1205" alt="截屏2024-03-23 下午5 10 30" src="https://github.com/Bin-Huang/chatbox/assets/128019548/a16e96bc-e67f-4dfc-827b-edadde4bcce4">

**桌面端（请填写以下信息）：**

-   操作系统：macOS

-   应用程序版本：1.3.1

**其他上下文**
无

**Comment by Bin-Huang** [comment]
从截图上，似乎你使用了某些三方服务，一般是三方服务引起的问题。
