### ISSUE TITLE
mac升级到2.0之后的版本运行异常

### ISSUE THREAD

**Issue by yay2008** [Bin-Huang/chatbox#126]
升级到2.0之后的版本 启动之后 
![image](https://user-images.githubusercontent.com/4987371/227096912-c68d3fa4-ba75-48a4-bdc5-bdd83f36b24c.png)
api key 不能保存
mac os 版本 10.14.6

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/Chatbox-v0.2.3

试试最新版本～

**Comment by yay2008** [comment]
试过了 不行

**Comment by Bin-Huang** [comment]
也可以试试重装一下？

**Comment by yay2008** [comment]
重装也试过了 不行 重新装回0.1.3就正常 是不是更换了Tauri引起的兼容问题

**Comment by Bin-Huang** [comment]
正在处理中

**Comment by Bin-Huang** [comment]
请升级最新版本
