### ISSUE TITLE
[Feature] TTS chat implementation

### ISSUE THREAD

**Issue by elendil7** [Bin-Huang/chatbox#1260]
Thank you for your work so far. Still using chatbox to this day 😄 

I think this will be a useful part of ChatGPT API to accommodate:
As per: https://platform.openai.com/docs/guides/text-to-speech

Kind regards

**Comment by Bin-Huang** [comment]
Thanks for bringing this to my attention! It looks like this issue has been reported before in #1239, so I'm going to close this one to keep the conversation centralized over there. Please feel free to add any additional comments or insights you have to the existing thread.

Thanks again for your contribution! 👍👍❤️❤️
