### ISSUE TITLE
[BUG] 返回内容包含null

### ISSUE THREAD

**Issue by Jasonsey** [Bin-Huang/chatbox#1263]
复现：

1. 利用[api-for-open-llm](https://github.com/xusenlinzy/api-for-open-llm/blob/master/docs/VLLM_SCRIPT.md) 本地维护了openai服务，模型使用qwen14b
2. chatbox中配置对应的端口地址
3. 返回内容会自动在结尾添加一个null
   ![2024-03-27_15-34](https://github.com/Bin-Huang/chatbox/assets/26242648/bf1572e6-7528-4f5d-8486-61e5a517c41d)

分析：

- 使用langchain的api方式访问不会出现这个null

导致的后果：

- 如果模型返回是markdown的代码块格式，那么这个尾巴的null会破坏内容的渲染

希望达到的效果：

- 看看是不是客户端字符处理的bug，或者是否可以屏蔽这个null

**Comment by marlonfan** [comment]
我也出现了。这是为什么

**Comment by Bin-Huang** [comment]
看上去应该不是客户端的问题，如果本地三方服务尽可能兼容 openai 的接口一般都不会出现这个问题

**Comment by codebysandwich** [comment]
本地llama模型不会出现这个现象，使用第三方api实现llama模型时候会出现（只能选openai api兼容）。不知道是不是三方的llama api不能完全兼容 openai api的原因。不知道是否有好的解决办法
