### ISSUE TITLE
[BUG]升级道1.3.3之后，请求错误

### ISSUE THREAD

**Issue by xiangshiyun** [Bin-Huang/chatbox#1267]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**

![bug](https://github.com/Bin-Huang/chatbox/assets/67108234/94dc093c-8602-4bad-9965-f797e1d8b68b)

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**

-   Operating System: windows 10
-   Application Version: 1.3.3

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

---

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：

1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**

-   操作系统：[例如 macOS]
-   应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
仔细看下错误信息，是因为你的账户请求太频繁了，OpenAI 报出的限速错误

**Comment by xiangshiyun** [comment]
> 仔细看下错误信息，是因为你的账户请求太频繁了，OpenAI 报出的限速错误

并没有啊，升级之后需要 重新设置账户吗？
![image](https://github.com/Bin-Huang/chatbox/assets/67108234/4e7e443b-94bf-4801-8ede-e61353aa59fd)

**Comment by Bin-Huang** [comment]
也有可能是你的账户其他人也在使用。从错误上看，和软件没有任何关系。

**Comment by Bin-Huang** [comment]
不想折腾的话，也可以试试 Chatbox AI
