### ISSUE TITLE
[Feature]保存多个API域名、密钥配置

### ISSUE THREAD

**Issue by CookSleep** [Bin-Huang/chatbox#1268]
**问题描述**
正在使用多个服务商提供的API，每次想切换一下都需要重新输入API域名、密钥……很麻烦。

**解决思路**
添加API域名、密钥配置保存功能

**附加上下文**
A服务商的某个模型不能用了，我可以立即切换至之前填写好的B服务商的API域名、密钥配置，无需手动重新输入，方便快捷！

**Comment by runc** [comment]
我也有此需求，目前每一种chat窗口，只支持切换模型，不支持设置endpoint，可以考虑同时支持多个厂商的endpoint

**Comment by chiguabaobao** [comment]
支持，希望老板能更新这个功能。现在大部分都是买的代理key，国产模型和GPT来回切换。能在单个聊天窗口那里增加一个和系统配置一样的界面，允许自主配置单个聊天窗口的URL和KEY就方便很多了。

**Comment by cn-hexin** [comment]
支持 还希望能增加自定义模型名的记忆功能  有时也要切这个

**Comment by Zheng-Zong** [comment]
支持喵

**Comment by Bin-Huang** [comment]
最近半年的版本更新里已经包含了上诉所有的需求，包括保存多个 API 域名和密钥、记忆自定义模型名称等。建议升级看看。
