### ISSUE TITLE
[Feature] 希望OpenAI 渠道的**自定义模型**支持传图片

### ISSUE THREAD

**Issue by ChasLui** [Bin-Huang/chatbox#1269]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

---

**问题描述**
我使用第三方OpenAI Key平台, 支持claude-3-haiku模型,但是协议走的OpenAI, 导致我想要多模态无法使用

**解决思路**
取消限制只有gpt-4-vision-preview才能传图片的限制

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by Bin-Huang** [comment]
新版本已经支持了
