### ISSUE TITLE
多轮对话的token estimate问题

### ISSUE THREAD

**Issue by HXX97** [Bin-Huang/chatbox#127]
调用OpenAI的API进行多轮对话时，需要把前置的message和response都传入请求，这些内容的token也将被累积计费： https://platform.openai.com/docs/guides/chat/introduction

而ChatBox终的token estimate似乎只显示当前输入内容的token长度，而非累积的token长度。是否可以增加一个累积token estimate?

![image](https://user-images.githubusercontent.com/23658059/227100158-7965c12b-7cd7-428c-95b0-c07207cc42fa.png)

**Comment by Bin-Huang** [comment]
😊😊This feature has been implemented in the new version v0.6.3.
https://github.com/Bin-Huang/chatbox/releases

😊😊这个功能在新版本 v0.6.3 已经实现
https://github.com/Bin-Huang/chatbox/releases
