### ISSUE TITLE
[Feature]【查看历史话题】功能，希望以话题的主题命名，而非“对话名”+“时间戳”

### ISSUE THREAD

**Issue by Charagol** [Bin-Huang/chatbox#1271]
>首先区分"**对话**"与"**话题**"概念：“对话”陈列在Chatbox左侧，一个“**对话**”中可以有无数个“**话题**”，你可以Alt+R开始新“**话题**”。
---

**问题描述**

很感谢开发者的努力，【查看历史话题】功能能够允许你继续之前对话，但在寻找历史话题的时候，话题命名格式是 [对话名称]+ [当前时间]。如  #翻译助手 2024/3/31 10:36:47 
问题在于：这对**想寻找特定话题**以继续对话造成了不小的困难。

**解决思路**

1. 话题命名格式中 [对话名称] 部分我认为可以取消，因为只有在当前对话中，才能打开对应的【查看历史话题】，自然该部分为冗余。
2. 建立【新对话】时，对话名称默认为“Untitled”，在你开始交流之后会根据第一个话题的主体生成【对话】名称。这是否也可以调用在每个【话题】的命名中？从而在【查看历史话题】功能中查找更方便
3. 当开始【新话题】时，支持对该话题的手动更名，该更名与【查看历史话题】中的命名同步。

**附加上下文**
图一：功能【查看历史话题】
![image](https://github.com/Bin-Huang/chatbox/assets/69426969/a4d996ec-2f0c-42ff-9d64-0e7d48828f22)

---
图2：解决思路-3：手动命名话题——希望能够手动修改选中蓝色部分
![image](https://github.com/Bin-Huang/chatbox/assets/69426969/0c399673-8b74-439b-9b08-067c22da096a)

**Comment by Bin-Huang** [comment]
v1.3.4 版本已经实现
