### ISSUE TITLE
[Feature] 设置 显示内 添加 对话的“侧边矩”调节选项

### ISSUE THREAD

**Issue by talking-toaster** [Bin-Huang/chatbox#1273]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

---

**问题描述**
当前使用网页版，常用的屏幕都为16：9，而默认对话侧边矩很小，导致非常不方便查看长段的文字。
而app版本的长宽比比较接近，就没有这个问题。
![image](https://github.com/Bin-Huang/chatbox/assets/49156890/ec517907-054b-4032-a819-692366c06c9b)

**解决思路**
在设置->显示内添加 `对话侧边矩`调节选项
![image](https://github.com/Bin-Huang/chatbox/assets/49156890/68822b02-e1c7-4bf8-a2b5-2194262812a7)

**附加上下文**
希望调节选项能达到类似chatgpt的显示效果，左右留有侧边矩
![image](https://github.com/Bin-Huang/chatbox/assets/49156890/cf31c022-4e5a-406b-883b-6df954f72675)

**Comment by Bin-Huang** [comment]
最近半年里的更新已经包括这个功能，点击右上方的切换按钮。
