### ISSUE TITLE
[BUG] 遇到了来自 Claude 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者点击这里查看常见问题文档。  API Error: Status Code 400, {"type":"error","error":{"type":"invalid_request_error","message":"messages: roles must alternate between \"user\" and \"assistant\", but found multiple \"user\" roles in a row"}}

### ISSUE THREAD

**Issue by qiaozhi0809** [Bin-Huang/chatbox#1275]
遇到了来自 Claude 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 400, {"type":"error","error":{"type":"invalid_request_error","message":"messages: roles must alternate between \"user\" and \"assistant\", but found multiple \"user\" roles in a row"}}

**Comment by Hevsy** [comment]
I have the same issue

**Comment by Bin-Huang** [comment]
Fixed in v1.3.4
