### ISSUE TITLE
gpt4接口使用异常

### ISSUE THREAD

**Issue by liaoyiqiao** [Bin-Huang/chatbox#128]
试了各种model_name均调用失败。web端的gpt4能正常使用

API 请求失败：

Error from OpenAI: 404  {
    "error": {
        "message": "The model: `gpt-4-32k-0314` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

**Comment by TomHolger** [comment]
一样的问题GPT3.5是正常的

**Comment by alovin** [comment]
因为官方目前只对企业用户开放了GPT-4的API，所以在软件中选择GPT-4也用不了，会报错。个人用户想用GPT-4，得进OpenAI的官网进行体验。

**Comment by TomHolger** [comment]
> 因为官方目前只对企业用户开放了GPT-4的API，所以在软件中选择GPT-4也用不了，会报错。个人用户想用GPT-4，得进OpenAI的官网进行体验。

OK，了解了

**Comment by Bin-Huang** [comment]
> 因为官方目前只对企业用户开放了GPT-4的API，所以在软件中选择GPT-4也用不了，会报错。个人用户想用GPT-4，得进OpenAI的官网进行体验。

补充一下，你的账户要去排队 GPT-4，排到了才能用。个人也是可以的。

**Comment by hukiwang** [comment]
已经收到了 openai 通知开放了 gpt4 的接口权限，但仍然在glarity中选择gpt4 时报错。
