### ISSUE TITLE
[BUG] Google Gemini 'Specific model settings' missing

### ISSUE THREAD

**Issue by AndyDurden** [Bin-Huang/chatbox#1287]
Providers 'OpenAI API' and 'Claude' have 'Specific model settings' to select the model, context window, and temperature. This is missing for the 'Google Gemini' provider. Screenshots attached.

Also thanks for your work on this project, it is very helpful!

![image](https://github.com/Bin-Huang/chatbox/assets/4941485/7fcd056b-ac1b-4686-9824-404138f7fede)
![image](https://github.com/Bin-Huang/chatbox/assets/4941485/78372f6c-3dc9-42c5-b8d4-92426948468b)

**Comment by Bin-Huang** [comment]
Fixed in v1.3.4
