### ISSUE TITLE
[Feature] 启用chromium的文本查找功能

### ISSUE THREAD

**Issue by jeffgyf** [Bin-Huang/chatbox#1289]
**问题描述**
目前的文本查找功能不够好，无法在页面中高亮，只能跳转到大概的位置。希望能启用chromium内置的文本查找功能。

**解决思路**
启用chromium内置的文本查找功能。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。
![image](https://github.com/Bin-Huang/chatbox/assets/16674327/745a7217-2a83-4d7d-b190-344d11d4a756)

**Comment by Bin-Huang** [comment]
你好，我之前调研时没找到 chromium “内置文本查找” 的相关信息，如果你了解的话方便给我一些链接吗？

**Comment by jeffgyf** [comment]
> 你好，我之前调研时没找到 chromium “内置文本查找” 的相关信息，如果你了解的话方便给我一些链接吗？

可以试试这个吗？https://www.npmjs.com/package/electron-find
