### ISSUE TITLE
[Feature]为自定义模型增加图像上传开关

### ISSUE THREAD

**Issue by CookSleep** [Bin-Huang/chatbox#1290]
**问题描述**
我正在使用一些API服务商提供的带有图像识别功能的模型，我需要通过设置自定义OpenAI模型来调用它们，可是自定义模型不允许上传图片

**解决思路**
为自定义模型增加图像上传开关

**附加上下文**
在填写了自定义OpenAI模型后，在参数中将自定义图片上传开关解锁，可以自行选择开关图片上传功能

**Comment by meowlgm** [comment]
没错, 新的gpt4模型可以解析图片了, 开放这个功能后, 出现新的模型就可以不必依赖客户端的更新了.

**Comment by Bin-Huang** [comment]
抱歉刚看到，下个版本会增加

**Comment by laomen123123** [comment]
有对多模态大模型的图片支持了吗

**Comment by Bin-Huang** [comment]
新版本 v1.3.6 已经可以发送图片给自定义模型了

**Comment by wwjCMP** [comment]
> 新版本 v1.3.6 已经可以发送图片给自定义模型了

使用ollama 部署的 llava 模型接受不到图片

**Comment by ldwnt** [comment]
> > 新版本 v1.3.6 已经可以发送图片给自定义模型了
> 
> 使用ollama 部署的 llava 模型接受不到图片

+1

**Comment by ldwnt** [comment]
> 新版本 v1.3.6 已经可以发送图片给自定义模型了

![image](https://github.com/user-attachments/assets/563851c1-cb60-42cb-8fa2-ae02d67d9fc8)

**Comment by heianhu** [comment]
![Uploading IMG_3450.png…]()
The api of Azure seems unable to upload images, even with the GPT-4O.

**Comment by Bin-Huang** [comment]
> > 新版本 v1.3.6 已经可以发送图片给自定义模型了
> 
> ![image](https://private-user-images.githubusercontent.com/7655486/354874874-b81de753-9ce3-486f-9c7a-67a111786912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzE4NTIsIm5iZiI6MTcyNjgzMTU1MiwicGF0aCI6Ii83NjU1NDg2LzM1NDg3NDg3NC1iODFkZTc1My05Y2UzLTQ4NmYtOWM3YS02N2ExMTE3ODY5MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjBUMTEyNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRlYzhhNDU3ODQwYWEyY2EzYTdjNDA5YjUwODIxZTMwM2NhNjkwZTRmMDQ5ZDBkMTFhYzhiZmQzOTlhODk5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QYfZ0EfiNto2UV3_NL_1ffgRtuwJvHlfw836eptTEh8)

llava 也是支持的，要升级到最新的版本。

**Comment by heianhu** [comment]
Hi @Bin-Huang ,

I am the interface for AzureOpenAI. I have tried submitting images within a chat created in Azure, and they were accepted. However, through the Chatbox client, it still seems that images cannot be uploaded, even though I am using version 1.4.2.
![image](https://github.com/user-attachments/assets/9945ee8e-488d-4c47-b423-5cf9fa95d6a1)
![image](https://github.com/user-attachments/assets/f56d70d4-f4ba-4efb-a59f-3fde9b7df096)
