### ISSUE TITLE
This app is no longer compatible with your device. Contact the developers for more info.

### ISSUE THREAD

**Issue by johnd0e** [Bin-Huang/chatbox#1294]
On the app page at Google Play I see this message.
I have 1.2.5 installed at the moment.
So what is changed?

My android version: 10
And I have tried to download APK manually, but installation failed.

**Comment by Bin-Huang** [comment]
This is actually a requirement from Google Play. I'd suggest updating your system version to resolve this issue.

**Comment by johnd0e** [comment]
> I'd suggest updating your system version

You mean I should bye new phone. Nice.
But there is no problem with other apps, so I really doubt that Google Play demands from developers drop Android 10 support.

**Comment by Bin-Huang** [comment]
Check out this link：
https://support.google.com/googleplay/android-developer/answer/11926878?hl=en&sjid=1199090224211626346-AP

**Comment by johnd0e** [comment]
1. There is not only targetSdkVersion, but also minSdkVersion. So even if your app it targeted for Android 14 - it should be able to run in Android 10 as well.

2. Google Play requirements do not prevent developers to build apps with different parameters, and distribute them e.g. via GitHub Releases.
