### ISSUE TITLE
可以添加个代理嘛

### ISSUE THREAD

**Issue by ttyy33** [Bin-Huang/chatbox#13]
想通过socket代理本机ip访问，谢谢

**Comment by lhj5426** [comment]
同求 没socket 代理设置用不了  clash 没有接管系统代理
会返回 API Request Failed:
Failed to fetch

**Comment by Bin-Huang** [comment]
好的，安排

**Comment by abhpc** [comment]
> 好的，安排

多谢大佬啊，什么时候上线呢？现在国内确实得用代理了，最好支持socks5。

**Comment by Bin-Huang** [comment]
我个人对代理的优先级不是很高，而且最近一直要修复其他的问题。可能需要等待几天或者一周。有其他人感兴趣实现这个代理功能吗？

**Comment by abhpc** [comment]
> 我个人对代理的优先级不是很高，而且最近一直要修复其他的问题。可能需要等待几天或者一周。有其他人感兴趣实现这个代理功能吗？

好的，谢谢。可惜我是做底层的，不太懂app的开发。等大佬更新了~O(∩_∩)O哈哈~

**Comment by Bin-Huang** [comment]
> > 我个人对代理的优先级不是很高，而且最近一直要修复其他的问题。可能需要等待几天或者一周。有其他人感兴趣实现这个代理功能吗？
> 
> 好的，谢谢。可惜我是做底层的，不太懂app的开发。等大佬更新了~O(∩_∩)O哈哈~

其实我是做后端的，我也是第一次开发桌面应用

**Comment by Nicolas-XF** [comment]
同求，不然整个网络全代理速度太感人了，呵呵

**Comment by ttyy33** [comment]
> index.ts
> 
> 添加一段硬编码，临时解决了代理的问题：
> 
> ```
> // Create the browser window.
> const mainWindow = new BrowserWindow({
>     height: 1000,
>     width: 1400,
>     webPreferences: {
>         preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
>         nodeIntegration: true,
>     },
> });
> 
> // 设置代理
> mainWindow.webContents.session.setProxy({
>     proxyRules: 'socks5://localhost:8888',
>     proxyBypassRules: 'localhost',
> });
> 
> // and load the index.html of the app.
> mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
> ```

清温这个自己编译成exe文件

**Comment by ttyy33** [comment]
> 同求 没socket 代理设置用不了 clash 没有接管系统代理 会返回 API Request Failed: Failed to fetch

用clash的tun模式和proxifier组合起来，可以让chatbox正常访问，终于可以间接解决了，苦恼了好久

**Comment by nwangwei** [comment]
> 

yarn package
or
npm run package

意思就是打包，然后会生成一个安装exe，或者绿色的zip，我就用zip那个。

不是package就是make，可以搜索下

**Comment by ttyy33** [comment]
> 

打包 老是报错，不折腾了，对于一个小白，挺坑的

**Comment by ttyy33** [comment]
> index.ts
> 
> 添加一段硬编码，临时解决了代理的问题：
> 
> ```
> // Create the browser window.
> const mainWindow = new BrowserWindow({
>     height: 1000,
>     width: 1400,
>     webPreferences: {
>         preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
>         nodeIntegration: true,
>     },
> });
> 
> // 设置代理
> mainWindow.webContents.session.setProxy({
>     proxyRules: 'socks5://localhost:8888',
>     proxyBypassRules: 'localhost',
> });
> 
> // and load the index.html of the app.
> mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
> ```

你可以出一个打包的教程，发一个蓝奏云或者腾讯在线文档的链接，教教我们这些小白

**Comment by ttyy33** [comment]
> > 同求 没socket 代理设置用不了 clash 没有接管系统代理 会返回 API Request Failed: Failed to fetch
> 
> 用clash的tun模式和proxifier组合起来，可以让chatbox正常访问，终于可以间接解决了，苦恼了好久

**Comment by Bin-Huang** [comment]
既然大家这么需要，那我做个简单的调查。如果你需要这个功能，就点击下面的【爱心】。超过 10 个我就马上开发，超过 50 个我今晚就开发。

**Comment by abhpc** [comment]
> 既然大家这么需要，那我做个简单的调查。如果你需要这个功能，就点击下面的【爱心】。超过 10 个我就马上开发，超过 50 个我今晚就开发。

大佬，爱心够10个了，赶紧上吧，O(∩_∩)O哈哈~

**Comment by renjieQ** [comment]
问题是，这个不需要代理吧？我部署到本地，只要正确输入apikey,都能得到返回值的

**Comment by ttyy33** [comment]
> 问题是，这个不需要代理吧？我部署到本地，只要正确输入apikey,都能得到返回值的

国内看地区，大部分访问不了，所以需要这个

**Comment by fantuandai** [comment]
> > 问题是，这个不需要代理吧？我部署到本地，只要正确输入apikey,都能得到返回值的
> 
> 国内看地区，大部分访问不了，所以需要这个

我都是用梯子，不然用不了

**Comment by leonchanithotmail** [comment]
> 既然大家这么需要，那我做个简单的调查。如果你需要这个功能，就点击下面的【爱心】。超过 10 个我就马上开发，超过 50 个我今晚就开发。

来看这条issue的小伙伴，请给大佬的回复点个爱心，还是很多人需要的。^-^

**Comment by fan123199** [comment]
正好需要，今天openai的key就要下来了。听说用国内IP访问，容易被封锁，所以还是需要代理

**Comment by lhj5426** [comment]
代理问题解决了
![image](https://user-images.githubusercontent.com/30548000/227028640-0bfa2ab3-8dd4-4f9d-9831-073a1e0485fc.png)
我问了GPT有什么办法 它告诉了我3个软件
然后我找了第一个 
这是教程
https://www.youtube.com/watch?v=ZPi56hSm__E
总算是可以不全局代理然后还可以用CHATBOX了

**Comment by ttyy33** [comment]
> 代理问题临时解决办法 ![image](https://user-images.githubusercontent.com/30548000/227028640-0bfa2ab3-8dd4-4f9d-9831-073a1e0485fc.png) ![image](https://user-images.githubusercontent.com/30548000/227041495-cab1593f-8906-4ff6-bcab-b2f4896d7062.png)
> 
> 我问了GPT有什么办法 它告诉了我3个软件 然后我找了第一个 这是教程 https://www.youtube.com/watch?v=ZPi56hSm__E 总算是可以不全局代理然后还可以用CHATBOX了

我试了一下chrome是可以的，但是chatbox不行，你可以加官方的群，
Chatbox 官方用户群：Telegram： https://t.me/+gWzem4HGSI5hYzg1来这里聊一下

**Comment by lhj5426** [comment]
> > 代理问题临时解决办法 ![image](https://user-images.githubusercontent.com/30548000/227028640-0bfa2ab3-8dd4-4f9d-9831-073a1e0485fc.png) ![image](https://user-images.githubusercontent.com/30548000/227041495-cab1593f-8906-4ff6-bcab-b2f4896d7062.png)
> > 我问了GPT有什么办法 它告诉了我3个软件 然后我找了第一个 这是教程 [https://www._youtube_.com/watch?v=ZPi56hSm__E](https://www.youtube.com/watch?v=ZPi56hSm__E) 总算是可以不全局代理然后还可以用CHATBOX了
> 
> 我试了一下chrome是可以的，但是chatbox不行，你可以加官方的群， Chatbox 官方用户群：Telegram： [https://t.me/+gWzem4HGSI5hYzg1来这里聊一下](https://t.me/+gWzem4HGSI5hYzg1%E6%9D%A5%E8%BF%99%E9%87%8C%E8%81%8A%E4%B8%80%E4%B8%8B)

https://user-images.githubusercontent.com/30548000/227139496-22eacf49-7572-4f7a-8b89-5c563dfb69ef.mp4


没毛病的 是可以用的

**Comment by oicq1699** [comment]
其实用vscode还是蛮简单的
0、安装好vscode,nodejs
1、先clone 源代码
2、用vscode 打开文件夹
3、点vscode，左侧最上那个资源管理器，将左侧分栏切到资源管理器
4、看资源管理器下方有一子栏目叫npm 脚本的
5、首先运行npm 脚本里的 install ,如果这一步都报错，可能需要设置代理，自己搜怎么设置vscode代理和npm 代理
6、运行make 还是 package(具体哪个忘了），如果打包成功，会出一个out目录，这个目录下双击chatbox.exe应该就能运行了
7、改代码，再运行mark还是package.

**Comment by abhpc** [comment]
> 既然大家这么需要，那我做个简单的调查。如果你需要这个功能，就点击下面的【爱心】。超过 10 个我就马上开发，超过 50 个我今晚就开发。

作者在考虑加socks5代理了吗？

**Comment by wansenlyt** [comment]
还是挺期待能有代理配置。

**Comment by YuefengLi** [comment]
公司电脑没法开 clash 全局代理……
proxifier 没有免费版本……
楼上有个 hardcode `BrowserWindow` 的我搜了下貌似是 electron 的。但是目前这个项目已经 refactor 成 tauri 的了。
tauri issue 里有讨论代理，但好像目前还没有实现。


陷入苦恼中

**Comment by abhpc** [comment]
> 既然大家这么需要，那我做个简单的调查。如果你需要这个功能，就点击下面的【爱心】。超过 10 个我就马上开发，超过 50 个我今晚就开发。

已经超过50个爱心啦

**Comment by abhpc** [comment]
问了一下ChatGPT：tauri如何通过socks5代理上网？

要在Tauri应用程序中使用SOCKS5代理服务，您需要进行以下操作：

1. 在Tauri应用程序中启用Electron的代理服务并指定SOCKS5代理：

   ```javascript
   const { app } = require('@electron/remote');
   app.commandLine.appendSwitch('proxy-server', 'socks5://host:port');
   ```

   其中，`host` 和 `port` 分别是 SOCKS5 代理服务器的主机名和端口号。

2. 安装 Socks5 Client 库：

   ```
   npm install socks5-client
   ```

3. 在您的代码中使用 Socks5 Client 库构建 Socks5 代理请求：

   ```javascript
   const Socks5Client = require('socks5-client');

   const socket = new Socks5Client({
     socksHost: 'host',  // SOCKS5 代理服务器主机名
     socksPort: port,    // SOCKS5 代理服务器端口号
     socksUsername: 'username',  // SOCKS5 代理服务器用户名（如果有）
     socksPassword: 'password'   // SOCKS5 代理服务器密码（如果有）
   });

   // 使用 socket 发送 HTTP 请求
   net.connect(
     {
       host: 'example.com',
       port: 80
     },
     () => {
       // 处理连接成功的逻辑
     }
   );
   ```

可以根据实际情况修改 Socks5Client 的参数，如 Socks5 代理服务器的用户名密码等。根据以上步骤，您的 Tauri 应用程序将会通过指定的 SOCKS5 代理服务器进行网络请求。

**Comment by huangsida** [comment]
linux ubuntu环境，使用proxychains 代理socks5，还是上不了。有能用别的方式代理上去的么？

**Comment by xiefeihong** [comment]
期望可以添加一个支持socks5的代理功能，linux下支持tun的代理软太少

**Comment by zhyf08** [comment]
这个需求呼声很高啊

**Comment by Bin-Huang** [comment]
大家好，我这里解释下为什么还没有开发这个功能。

首先，如果你本地设置了规则代理、并且把 openai 域名加入规则，就可以实现网络代理，不需要 Chatbox 额外支持。

如果 Chatbox 实现了代理功能，就可能有用户使用了一些不正规的机场，这种行为很容易被 OpenAI 直接封号。这些用户可能会错怪 Chatbox 导致他们封号（既然他们敢使用这些机场，就意味着他们没办法做出正确的原因判断）。这会大幅增加解释成本。

大家有什么想法？

**Comment by abhpc** [comment]
> 大家好，我这里解释下为什么还没有开发这个功能。
> 
> 首先，如果你本地设置了规则代理、并且把 openai 域名加入规则，就可以实现网络代理，不需要 Chatbox 额外支持。
> 
> 如果 Chatbox 实现了代理功能，就可能有用户使用了一些不正规的机场，这种行为很容易被 OpenAI 直接封号。这些用户可能会错怪 Chatbox 导致他们封号（既然他们敢使用这些机场，就意味着他们没办法做出正确的原因判断）。这会大幅增加解释成本。
> 
> 大家有什么想法？

很有道理，支持！

**Comment by ximm12a** [comment]
> clash for windows 可以通过 tun 模式 + *.openai.com 添加到 Fake IP Filter 中进行代理

谢谢，终于用上了。好方法！
clash，要用最新版。

**Comment by ShunLu91** [comment]
感谢作者的方法！这里贡献一个v2ray软件配置pac模式下Chatbox自动走代理的方法：
步骤：设置-高级设置-Pac-点击“保存设置并从GFW List更新”
效果：点击“浏览Pac文件”，能找到一行："||openai.com",即可。重新打开v2ray和Chatbox软件，即可在Pac模式下使用

**Comment by ayakasuki** [comment]
> 大家好，我这里解释下为什么还没有开发这个功能。
> 
> 首先，如果你本地设置了规则代理、并且把 openai 域名加入规则，就可以实现网络代理，不需要 Chatbox 额外支持。
> 
> 如果 Chatbox 实现了代理功能，就可能有用户使用了一些不正规的机场，这种行为很容易被 OpenAI 直接封号。这些用户可能会错怪 Chatbox 导致他们封号（既然他们敢使用这些机场，就意味着他们没办法做出正确的原因判断）。这会大幅增加解释成本。
> 
> 大家有什么想法？

其实这个理由也有点牵强。比如用户本身用全局代理，那个飞机场有问题同样会封也会怪罪你头上。不如直接写个免责声明的小字在旁边。不应该由用户自己去用别的软件别的模式去，因为有些人飞机场是直接没作用在本地，但是是直接走ip+端口的proxy的

**Comment by zhyf08** [comment]
> > 大家好，我这里解释下为什么还没有开发这个功能。
> 
> > 
> 
> > 首先，如果你本地设置了规则代理、并且把 openai 域名加入规则，就可以实现网络代理，不需要 Chatbox 额外支持。
> 
> > 
> 
> > 如果 Chatbox 实现了代理功能，就可能有用户使用了一些不正规的机场，这种行为很容易被 OpenAI 直接封号。这些用户可能会错怪 Chatbox 导致他们封号（既然他们敢使用这些机场，就意味着他们没办法做出正确的原因判断）。这会大幅增加解释成本。
> 
> > 
> 
> > 大家有什么想法？
> 
> 
> 
> 其实这个理由也有点牵强。比如用户本身用全局代理，那个飞机场有问题同样会封也会怪罪你头上。不如直接写个免责声明的小字在旁边。不应该由用户自己去用别的软件别的模式去，因为有些人飞机场是直接没作用在本地，但是是直接走ip+端口的proxy的

同意楼上的看法，提示一下风险，感觉有代理还是方便些。没中转之前我完全用不了chatbox,一次都没成功过，这几天用nginx反向代理openai.com之后才能正常使用，我这个办法比较繁琐。
感谢作者提供了这么好用的软件

**Comment by BBkinga** [comment]
是不是修复了，现在clash点开直接就能用，也不用开tun

**Comment by LAkimoto** [comment]
> 

我也发现了，今天clash不开系统代理也能直接用了

**Comment by ttyy33** [comment]
> 
不开代理也能用？那你走的国内的ip吧

**Comment by BBkinga** [comment]
> > 
> 
> 不开代理也能用？那你走的国内的ip吧

要开的，clash开规则模式，不用开tun，也不用开全局。无法使用我感觉是因为节点问题，api.openai.com对节点要求比较高，同一个节点能用网页端，调用这个就失败，我装的另一个chrome插件chatgpt for google，用api的形式也是同样的表现。

**Comment by KervynH** [comment]
> 大家好，我这里解释下为什么还没有开发这个功能。
> 
> 首先，如果你本地设置了规则代理、并且把 openai 域名加入规则，就可以实现网络代理，不需要 Chatbox 额外支持。
> 
> 如果 Chatbox 实现了代理功能，就可能有用户使用了一些不正规的机场，这种行为很容易被 OpenAI 直接封号。这些用户可能会错怪 Chatbox 导致他们封号（既然他们敢使用这些机场，就意味着他们没办法做出正确的原因判断）。这会大幅增加解释成本。
> 
> 大家有什么想法？

我觉得没有必要花过多口舌解释，因为即便不在 chatbox 里面设置代理他们也会用 clash 之类的东西开个 tun 透明代理或者系统代理，同样也避免不了机场造成的问题。如果真的要解释，就只要说一句 chatbox 只是一个本地的套壳，所有联网的服务都来自 openai，代理只是给个入口而已。

单独设置代理的功能还是很有必要的，有的时候只有一两个软件需要走代理，单独设置就不需要开系统代理过度影响网络环境。而且 chatgpt 又重度依赖代理，所以能单独设置 http 或者 socks5 代理的功能我觉得是 chatbox 的刚需，就类似于 telegram 客户端的代理功能那样。

**Comment by ayakasuki** [comment]
> > 大家好，我这里解释下为什么还没有开发这个功能。
> > 首先，如果你本地设置了规则代理、并且把 openai 域名加入规则，就可以实现网络代理，不需要 Chatbox 额外支持。
> > 如果 Chatbox 实现了代理功能，就可能有用户使用了一些不正规的机场，这种行为很容易被 OpenAI 直接封号。这些用户可能会错怪 Chatbox 导致他们封号（既然他们敢使用这些机场，就意味着他们没办法做出正确的原因判断）。这会大幅增加解释成本。
> > 大家有什么想法？
> 
> 我觉得没有必要花过多口舌解释，因为即便不在 chatbox 里面设置代理他们也会用 clash 之类的东西开个 tun 透明代理或者系统代理，同样也避免不了机场造成的问题。如果真的要解释，就只要说一句 chatbox 只是一个本地的套壳，所有联网的服务都来自 openai，代理只是给个入口而已。
> 
> 单独设置代理的功能还是很有必要的，有的时候只有一两个软件需要走代理，单独设置就不需要开系统代理过度影响网络环境。而且 chatgpt 又重度依赖代理，所以能单独设置 http 或者 socks5 代理的功能我觉得是 chatbox 的刚需，就类似于 telegram 客户端的代理功能那样。

是这样的，毕竟有时候真的只需要一个软件走。规则再怎么也会有疏漏。并不想让其他软件也通过clash的规则然后再直连，多了一遍流程，延迟随之增加，哪怕少。并且我们本身可能并不喜欢用clash本地，而是部署在了软路由/docker这种，就连浏览器都只是在快捷方式加了启动命令行http-proxy选项

**Comment by Bin-Huang** [comment]
这个功能其实我很早前已经开发完了，我会在最近发布出来。

**Comment by Bin-Huang** [comment]
希望大家理解我对这个功能的犹豫

**Comment by Bin-Huang** [comment]
希望大家理解我对这个功能的犹豫

**Comment by KervynH** [comment]
> 这个功能其实我很早前已经开发完了，我会在最近发布出来。

辛苦了。期待上线！

**Comment by xiefeihong** [comment]
我将这个项目fork了一下，添加了代理功能，有兴趣的话可以看看
项目地址：https://github.com/xiefeihong/chatbox

**Comment by zkheartboy** [comment]
> 希望大家理解我对这个功能的犹豫

一直关注代理功能，太感谢了

**Comment by carboncool** [comment]
辛苦了，非常期待上线！感谢！

**Comment by Bin-Huang** [comment]
没想到这个功能有这么多讨论。其实真的很简单，出了某种原因我这里简单讲一下解决方案。

**方法一：（推荐）**

打开 Chatbox 设置窗口，展开 “Proxy/代理” 栏，在输入框中填入 `https://proxy2.chatbox.run`，即可正常使用

**方法二：**

将 openai.com 添加到你的代理工具名单，一般热门的工具会积极维护 PAC，你拉取最新的 PAC 文件后可能发现工具已经支持了。这样你的工具会代理 openai.com 的流量。

希望可以帮助到大家

**Comment by hongzhizhou** [comment]
> 我将这个项目fork了一下，添加了代理功能，有兴趣的话可以看看 项目地址：https://github.com/xiefeihong/chatbox
> 
> ![屏幕截图 2023-05-05 140907](https://user-images.githubusercontent.com/19567642/236388643-d79acb96-2686-46f6-9b7e-de55f991ad24.png)

没有macos的包吗？

**Comment by xiefeihong** [comment]
> > 我将这个项目fork了一下，添加了代理功能，有兴趣的话可以看看 项目地址：https://github.com/xiefeihong/chatbox
> > ![屏幕截图 2023-05-05 140907](https://user-images.githubusercontent.com/19567642/236388643-d79acb96-2686-46f6-9b7e-de55f991ad24.png)
> 
> 没有macos的包吗？

1.0.1版本有mac x64版本，但是没测试过，你可以试试

**Comment by jqgsninimo** [comment]
> 没想到这个功能有这么多讨论。其实真的很简单，出了某种原因我这里简单讲一下解决方案。
> 
> **方法一：（推荐）**
> 
> 打开 Chatbox 设置窗口，展开 “Proxy/代理” 栏，在输入框中填入 `https://proxy2.chatbox.run`，即可正常使用
> 
> **方法二：**
> 
> 将 openai.com 添加到你的代理工具名单，一般热门的工具会积极维护 PAC，你拉取最新的 PAC 文件后可能发现工具已经支持了。这样你的工具会代理 openai.com 的流量。
> 
> 希望可以帮助到大家

macOS 版本是不是还未实现内置代理？

**Comment by CoREse** [comment]
不断地说要做要放，做了又不放，不断地食言。一边问着大家的看法，大家把需求给你通过投票都表达得明明白白了，却又因为“你觉得不需要”而不加，既然一开始就不想加这个功能又何必问大家呢？
