### ISSUE TITLE
[Feature] Add groq API

### ISSUE THREAD

**Issue by EnzoAndree** [Bin-Huang/chatbox#1308]
**Problem Description**
I don't see an option to use the groq API.

**Proposed Solution**
Do you plan to add support for the groq api?

**Additional Context**
Currently the groq API has llama3-70b available for free, it is super fast and useful for certain tasks.

**Comment by cgoder** [comment]
+1

**Comment by qkxie** [comment]
You could use openai model to call groq. 

![image](https://github.com/Bin-Huang/chatbox/assets/134578340/b820228d-6744-4f56-a135-c5eb0ea38212)

**Comment by ouening** [comment]
> You could use openai model to call groq.
> 
> ![image](https://private-user-images.githubusercontent.com/134578340/325105233-b820228d-6744-4f56-a135-c5eb0ea38212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzUyOTUsIm5iZiI6MTcxMzk3NDk5NSwicGF0aCI6Ii8xMzQ1NzgzNDAvMzI1MTA1MjMzLWI4MjAyMjhkLTY3NDQtNGY1Ni1hMTM1LWM1ZWIwZWEzODIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNjA5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGE4YTAwODg3ZGZlMTkxZWU0ZDRhNzg3YTU1NWY3NWIwOTA2MjIwMWFlYzk0NGRkNGVhYTgzOTQ4NjFjYzg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Omg7kh0VPab7HAvNp1lG_I0S7kXybMcaoARQUXw5GFw)

厉害了，之前按照groq官网的介绍base url使用`https://api.groq.com/openai/v1`死活连不上，按照您的配置进行设置就没问题，chatbox就可以愉快地使用groq、Gemini和ollama模型了，对比了好多其他的UI（jan、open-webui、nextchat、lobechat等）还是这个chatbox稳定好用

**Comment by Bin-Huang** [comment]
<img width="867" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/79cf0cd4-773b-41a6-9482-558ad97d6259">
Try the latest version v1.3.6, it now includes support for Groq.

**Comment by wenxingdi** [comment]
> > You could use openai model to call groq.
> > ![image](https://private-user-images.githubusercontent.com/134578340/325105233-b820228d-6744-4f56-a135-c5eb0ea38212.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NzUyOTUsIm5iZiI6MTcxMzk3NDk5NSwicGF0aCI6Ii8xMzQ1NzgzNDAvMzI1MTA1MjMzLWI4MjAyMjhkLTY3NDQtNGY1Ni1hMTM1LWM1ZWIwZWEzODIxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNFQxNjA5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGE4YTAwODg3ZGZlMTkxZWU0ZDRhNzg3YTU1NWY3NWIwOTA2MjIwMWFlYzk0NGRkNGVhYTgzOTQ4NjFjYzg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Omg7kh0VPab7HAvNp1lG_I0S7kXybMcaoARQUXw5GFw)
> 
> 厉害了，之前按照groq官网的介绍base url使用`https://api.groq.com/openai/v1`死活连不上，按照您的配置进行设置就没问题，chatbox就可以愉快地使用groq、Gemini和ollama模型了，对比了好多其他的UI（jan、open-webui、nextchat、lobechat等）还是这个chatbox稳定好用

你们的还能用吗？为啥我怎么配置都不行。开了魔法了。
![1](https://github.com/user-attachments/assets/07e271ba-2916-45ae-ba8f-74134962ef29)
![2](https://github.com/user-attachments/assets/78baebfb-5d63-4f0f-a966-303ac695fcca)
