### ISSUE TITLE
[BUG] **非常严重**的BUG：页面最底部一条消息总会被莫名其妙遮住

### ISSUE THREAD

**Issue by CookSleep** [Bin-Huang/chatbox#1313]
****Bug** 描述**
页面最底部一条消息总会被莫名其妙遮住

**重现步骤**
只需要与Bot正常交流，直到最后一条消息在屏幕最底部

**期望结果**
应当展示最后一条消息

**实际结果**
最后一条消息莫名其妙地被遮住了，**滑动也无法查看**，但是从查找消息内容那里是能看到消息仍然存在的，在系统提示足够长的时候，点一下**开启新话题**按钮能看到最后一条消息，如果不够长就会导致连新话题消息也看不到

**截图**
![PixPin_2024-04-24_15-51-59](https://github.com/Bin-Huang/chatbox/assets/151028412/a4b321bf-2ab1-4cde-97d8-7aaa5966355f)

**桌面端（请填写以下信息）：**

-   操作系统：Window
-   应用程序版本：1.3.5

**其他上下文**
未开启任何浏览器插件

**Comment by Bin-Huang** [comment]
1

**Comment by CookSleep** [comment]
> 我应该偶尔也遇到过，但忘记怎么复现了

我这里简直是每次都能稳定触发😭

**Comment by Bin-Huang** [comment]
中午在网页版本里修复了一下，现在应该不会了。桌面版本和手机版本会在本周末更新。
