### ISSUE TITLE
[Feature] 话题功能增强

### ISSUE THREAD

**Issue by kangfenmao** [Bin-Huang/chatbox#1317]
**问题描述**
Chatbox 目前提供话题功能，新建话题后当前聊天列表会增加新话题标签，这虽然可以满足话题需求，但是也会有两个问题出现。

1. 不能选择之前的某个话题继续聊天
2. 话题标题没有用 AI 自动生成，看起来不够清晰

**解决思路**
如果想要软件更加易用，可以考虑如下解决办法

1. 话题下面的聊天记录进行区分，选择话题后只能看到当前话题的聊天内容
2. 使用 AI 总结的能力，当用户点击新话题后，将之前的话题总结成为一句话作为话题标题

**附加上下文**
虽然调用 AI 总结会话内容会消耗 token，但是可以清晰知道自己这段话题的聊天内容。并且在选择话题后，能够继续之前的对话

**Comment by Bin-Huang** [comment]
<img width="736" alt="截屏2024-04-28 10 42 33" src="https://github.com/Bin-Huang/chatbox/assets/20723142/b129a18e-aa9b-49f6-8180-4513630b2d9f">

试着升级到最新版本，你提到的功能实际上已经实现了。
1. 话题会自动命名
2. 点击话题标签或者右上方按钮，可以看到话题抽屉
3. 在话题抽屉，点击任意一个话题，可以跳转到该话题的聊天记录
4. 点击展开按钮，你可以切换到该话题进行聊天。
