### ISSUE TITLE
安卓客户端使用ollama的时候找不到模型

### ISSUE THREAD

**Issue by fengmao86552** [Bin-Huang/chatbox#1318]
我用ubuntu通过ollama安装了2个llama3 8B的模型，通过windows可以访问正常
但是通过安卓客户端填写ollama的IP，在模型选项卡上显示未空。
![ollamawindows](https://github.com/Bin-Huang/chatbox/assets/56593596/be4491c6-d555-4751-abb2-681a3519e6ae)
![Screenshot_2024-04-28-17-46-15-039_xyz chatboxapp chatbox](https://github.com/Bin-Huang/chatbox/assets/56593596/5ebdc0ac-b23f-4875-b9d3-a92c5a1dcc3d)

**Comment by kmyface** [comment]
我也是遇到这个问题.

**Comment by Bin-Huang** [comment]
这个是 Ollama 设置的问题。可以升级 Chatbox 到最新版本，里面有详细教程。

**Comment by JPZ4-5** [comment]
> 这个是 Ollama 设置的问题。可以升级 Chatbox 到最新版本，里面有详细教程。
@Bin-Huang 不好意思，我更新了安卓和电脑版的1.3.13，也遇到了这个问题。我实在没找到所说的教程在哪里，也下载了googleplay版本的最新安卓（1.3.12），确实没找到。

如果解决了的话，希望楼里的朋友能教教怎么解决的，非常感谢！！ @kmyface @fengmao86552
