### ISSUE TITLE
无法读取PDF文件[BUG]

### ISSUE THREAD

**Issue by Galaxy-228** [Bin-Huang/chatbox#1324]
你好，我是chatbox的忠实用户。最近几天在使用chatbox时候发现卡顿，并且无法读取PDF文件。
请方便时优化。谢谢。
![图片](https://github.com/Bin-Huang/chatbox/assets/53716512/5b5b61cd-d961-4bf6-bdaf-0098f2158e45)

**Comment by Bin-Huang** [comment]
看上去可能是服务抖动导致的问题，这种情况最简单的方式可能是重试。如果问题持续出现，欢迎重新打开这个 issue
