### ISSUE TITLE
[Feature] new openai model gpt-4o support?

### ISSUE THREAD

**Issue by shawhu** [Bin-Huang/chatbox#1346]
**Problem Description**
Please support the new model gpt4o

**Proposed Solution**
Please support the new model gpt4o

**Comment by DenisSergeevitch** [comment]
Just pass a custom model name: `gpt-4o` and it will work

**Comment by Bin-Huang** [comment]
Added in the latest version v1.3.8

**Comment by INDEX108** [comment]
> Added in the latest version v1.3.8
May I ask if chatboxAI 4 can use gpt4o?

**Comment by Bin-Huang** [comment]
@INDEX108  After a thorough evaluation of GPT-4o, Chatbox AI 4 will immediately switch to GPT-4o and offer a larger token quota. Currently, it seems that GPT-4o performs slightly worse than GPT-4-turbo on difficult coding tasks.
