### ISSUE TITLE
[BUG] 1.3.8 更新后Deepseek-v2 chat 出错

### ISSUE THREAD

**Issue by FoolMark** [Bin-Huang/chatbox#1347]
API Error: Status Code 422, Failed to deserialize the JSON body into the target type: messages[0].content: invalid type: sequence, expected a string at line 1 column 40

**Comment by YiweiBao** [comment]
我也出现了这个问题，希望修复

**Comment by Bin-Huang** [comment]
我应该没有改到这个部分？原来没问题的版本是多少？

**Comment by FoolMark** [comment]
应该就是上一个版本 我前几天刚安装的

**Comment by chenm1xuexi** [comment]
我也出现了这个问题，1.3.6版本是正常的，模型的响应结果的 json 反序列化是不是有改动？

**Comment by chenm1xuexi** [comment]
再提一个问题，就是我现在想把版本会退到1.3.6 ，但是我发现从release去下载1.3.6版本 但是最后给我下载的还是1.3.8 这个作者看一下

**Comment by LyazS** [comment]
不要自动更新啊，起码我还能用回旧版本

**Comment by YiweiBao** [comment]
为什么我会在这里……发自我的 iPhone在 2024年5月14日，下午6:50，AirzoStorm ***@***.***> 写道：﻿
不要自动更新啊，起码我还能用回旧版本

**Comment by Owen718** [comment]
我也遇到了一样的问题，希望修复。

API Error: Status Code 422, Failed to deserialize the JSON body into the target type: messages[0].content: invalid type: sequence, expected a string at line 1 column 40

**Comment by Owen718** [comment]
> 我也遇到了一样的问题，希望修复。
> 
> API Error: Status Code 422, Failed to deserialize the JSON body into the target type: messages[0].content: invalid type: sequence, expected a string at line 1 column 40

更新后无法使用，之前一切正常
