### ISSUE TITLE
[BUG]不支持发送文件

### ISSUE THREAD

**Issue by Rainismer** [Bin-Huang/chatbox#1351]
windows app提示：当前模型 gpt-4-turbo 不支持发送文件。目前支持的模型：Chatbox AI 4？

**Comment by Joackk** [comment]
gpt-4o也是，4和4o不是支持发送文件吗，官网的倒是能正常发

**Comment by zhou20120904** [comment]
+1 建议写一个新的issue，用[Features]标签
