### ISSUE TITLE
[Feature]希望右上角“关闭”时可以进入托盘区挂起，而不是直接退出软件

### ISSUE THREAD

**Issue by yahoozhu** [Bin-Huang/chatbox#1363]
**问题描述**
每次关闭软件要重新启动，就算用快启软件也不够高效，让软件霸占任务栏待命实在无法习惯

**解决思路**
希望关闭时可以直接进入托盘区，而不是彻底退出软件，目前只能通过第三方软件来实现这个功能，但是非原生的进入托盘后需要两次快捷键才能激活到前台也很难受

**Comment by heloook** [comment]
需要啊，每次关闭后都需要重新启动，消耗了时间
