### ISSUE TITLE
希望你不是在开玩笑！我已经买了一年的E会员！

### ISSUE THREAD

**Issue by cream-sec** [Bin-Huang/chatbox#1364]
<img width="888" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/29266660/bbe8f43d-1016-44dc-ad98-174670c3a4db">
我做了什么？

**Comment by Bin-Huang** [comment]
这应该是正常现象，因为所有模型都是基于过去某个时间节点之前的数据进行训练的。同时为了最好的性能，也没有在 prompt 层做过多的设置。如果你希望退款，可以直接联系 hi@benn.app
