### ISSUE TITLE
[Feature]为openai模型加入文件问答功能

### ISSUE THREAD

**Issue by zhou20120904** [Bin-Huang/chatbox#1367]
**问题描述**
希望可以支持将以前只支持chatbox-ai的文件上传带到openai模型里

**解决思路**
[这里](https://platform.openai.com/docs/assistants/tools/file-search)有详细文档

**附加上下文**
[这里](https://platform.openai.com/docs/assistants/tools/file-search/supported-files)提到了所有可上传的格式

**Comment by Bin-Huang** [comment]
新版本已经实现文本文件的解析和上传了。目前 openai 似乎对 assistant api 没有进一步迭代和维护，所以暂时不打算支持这个接口。
