### ISSUE TITLE
[Other]3.5的api key报错。我是刚注册的账号

### ISSUE THREAD

**Issue by wangrui333** [Bin-Huang/chatbox#1376]
遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 429, { "error": { "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.", "type": "insufficient_quota", "param": null, "code": "insufficient_quota" } }

**Comment by Bin-Huang** [comment]
请错误中的查看问题文档链接。这是账户报错，和客户端没有任何关系。
