### ISSUE TITLE
0.2.3版，我调用API失败

### ISSUE THREAD

**Issue by xinxinzai2** [Bin-Huang/chatbox#138]
提示：
API Request Failed:

Load failed

我用自己生成的API，还换了几个都不行，有朋友遇到过吗？

**Comment by Mingming-xia** [comment]
我也是呀，不知道咋回事呀

**Comment by Blanchot-satou** [comment]
同

**Comment by Blanchot-satou** [comment]
同，mac端0.2.3无法调用api，测试了好多个都无法使用，更换为0.2.0也一样提醒Load failed

**Comment by kangfenmao** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/8253512/227695520-9b192d63-d441-4286-8e0b-21daab19afd6.png">

**Comment by Bin-Huang** [comment]
最新版本修复了问题

**Comment by JinChengneng** [comment]
> 最新版本修复了问题

@Bin-Huang 您好，version 0.2.7 中这个问题仍然存在。


```
API Request Failed:

Error parsing item: {"id":"chatcmpl-6xtNpx.
Error Details: SyntaxError: Unterminated string in JSON at position 22
```
