### ISSUE TITLE
[BUG]安卓客户端使用第三方OpenAI API出现网络错误

### ISSUE THREAD

**Issue by xcgx-yangtzeu** [Bin-Huang/chatbox#1382]
**Bug 描述**
目前安卓客户端似乎存在一些问题导致第三方OpenAI API无法使用。已存在多个版本。
出现 Network Error:Failed to fetch
已核实不是api或网络问题，Windows桌面端完全正常（同网络条件以及使用恢复配置保证完全一致的配置）。

**其他上下文**
当前版本API域名输入框存在一个另外的bug。
在编辑域名类似https://api.openai.com时
从https://[这里]api.openai.com开始删除，删除到http[这里]api.openai.com时
再往下会将输入框内容自动变为
https://httapi.openai.com

**Comment by xcgx-yangtzeu** [comment]
附上API的请求日志
 - - [27/May/2024:15:14:52 +0800] ＂OPTIONS /v1/chat/completions HTTP/1.1＂ 404 130 ＂https://localhost/＂ ＂Mozilla/5.0 (Linux; Android 14; 2211133C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36＂
 - - [27/May/2024:15:15:23 +0800] ＂POST /v1/chat/completions HTTP/1.1＂ 429 188 ＂-＂ ＂Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) xyz.chatboxapp.app/1.3.11 Chrome/108.0.5359.215 Electron/22.3.27 Safari/537.36＂
 - 可以看到安卓端使用OPTIONS请求 返回了404，而windows直接正常POST请求，获得了正常返回

**Comment by qsjl11** [comment]
遇到了同样问题

**Comment by AndySpider** [comment]
安卓手机，设置国内星火模型，报错failed to fetch
![Screenshot_2024-09-11-17-24-11-06_cf711141874c5270552379f98746f87c](https://github.com/user-attachments/assets/f93bff0f-23e8-4f78-8774-c611814b1ff8)

**Comment by Bin-Huang** [comment]
新版本修复了这个问题。添加成自定义模型提供方，然后开启“网络兼容模式”
