### ISSUE TITLE
每次关闭再打开都需要重新输入key

### ISSUE THREAD

**Issue by xiyusullos** [Bin-Huang/chatbox#139]

**Comment by inf-wu** [comment]
同遇到该问题，关闭后出现软件重置。重装仍无法解决

**Comment by HenMie** [comment]
手动删除`%APPDATA%\xyz.chatboxapp.app\config.json`，再重新打开试试

**Comment by zycbuyao996** [comment]
同样有这个问题，而且prompts都没了

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/Chatbox-v0.2.6
这个版本做了修复
