### ISSUE TITLE
[Other] 阿里云通义千问模型，已经开放API了

### ISSUE THREAD

**Issue by somehandforme** [Bin-Huang/chatbox#1391]
https://dashscope.aliyun.com/?spm=a2c6h.12873639.article-detail.11.340638davkPqne

**Comment by lgc653** [comment]
如果使用最新的“自定义模型”功能，因为“自定义模型”没有top_p的选项，通义千问会提示“"Range of top_p should be (0.0, 1.0)”，希望作者能加个选项，谢谢

**Comment by MOXCOOT** [comment]
请问是电脑端可以使用吗，我这边电脑端也可以使用，但是iOS和iPadOS都会报network error

**Comment by Bin-Huang** [comment]
新版本已经可以修改 top_p 了
