### ISSUE TITLE
[Feature] The ability to change model's avatar in a chats

### ISSUE THREAD

**Issue by DJ-LEXX-GIT** [Bin-Huang/chatbox#1392]
It would be great if you added the ability to change a model's avatar in a chats. The user can already change his own avatar and he can also add an avatar for a new copilot, but the ability to add a custom avatar for a model in any chat would be much appreciated. Thank you for such an amazing software!

**Comment by LIPUU** [comment]
too

**Comment by DJ-LEXX-GIT** [comment]
The feature has been added by the author in update 1.3.15. Thank you!
