### ISSUE TITLE
[BUG] npm start missing?!

### ISSUE THREAD

**Issue by 0wwafa** [Bin-Huang/chatbox#1396]
I did git clone this repository
then npm install
then npm start
and I got:
```
npm start
npm error Missing script: "start"
npm error
npm error Did you mean one of these?
npm error   npm star # Mark your favorite packages
npm error   npm stars # View packages marked as favorites
npm error
npm error To see a list of scripts, run:
npm error   npm run
```

**Comment by CyberShadow** [comment]
https://github.com/Bin-Huang/chatbox/issues/1217

**Comment by Bin-Huang** [comment]
In this PR, I've updated the codebase to a newer version, and simpler and more reliable build instructions.

https://github.com/Bin-Huang/chatbox/pull/1428
