### ISSUE TITLE
API调用失败，且点击“COPY”无法复制内容

### ISSUE THREAD

**Issue by Moriarty1024** [Bin-Huang/chatbox#140]
# 系统
Manjaro
# 软件版本
0.2.3
# 描述1
经常显示API调用失败，有的时候甚至已经生成一半回答了，突然显示API调用失败。报错信息为：Error parsing item: {"id":"chatcmpl-6xR7T6pSqfWcad","object":"chat.completion.chunk","created":16796,"model":"gpt-3.5-.
Error Details: SyntaxError: JSON Parse error: Unterminated string

# 描述2
点击COPY按钮无法复制文字

**Comment by Bin-Huang** [comment]
已修复，升级最新版本
