### ISSUE TITLE
为什么不能文件上传

### ISSUE THREAD

**Issue by baizhougod** [Bin-Huang/chatbox#1400]
4o 已经支持分析文件，但是在 chatbox 里面上传文件时提示不支持是为什么呢？什么时候支持呢？

**Comment by gaojiachang** [comment]
顶一个 很烦人 4o模型不能上传文件

**Comment by ncpmeplmls0614** [comment]
支持，应该放开。
或者不放开也希望直接说出来，大家就不用眼巴巴等了，直接去找别的客户端用。

**Comment by baizhougod** [comment]
> 支持，应该放开。 或者不放开也希望直接说出来，大家就不用眼巴巴等了，直接去找别的客户端用。

有没有别的客户端免费支持，找了好久没找到，开不开源都行

**Comment by ncpmeplmls0614** [comment]
> > 支持，应该放开。 或者不放开也希望直接说出来，大家就不用眼巴巴等了，直接去找别的客户端用。
> 
> 有没有别的客户端免费支持，找了好久没找到，开不开源都行

我还没找，我的意思是，如果chatbox不打算放开。要说一下，否则我天天等着它支持，很烦的。。。

他提前说，为了会员和自家的AI，不支持传文件，那我就趁早找别的客户端去，如果找一圈，免费的都没有，那我再去看收费的。

**Comment by Bin-Huang** [comment]
我觉得有一点需要纠正：gpt-4o 模型本身就不支持文件上传。模型本质只提供了聊天和图片上传，本身没有直接提供文件上传的能力。而且chatbox ai的文件解析上传和策略是在服务器上自己开发的，本身也存在成本。所以不存在故意不公开api模型功能的说法。

目前 chatbox 有支持本地文件解析的计划，指的是在本地完成文件解析、编排存储、发送模型，这样可以实现大家想要的 gpt4o 上传文件的需求。但说实话，本地解析的技术方案比较有限，效果绝对比不上服务器。另一个实现思路是直接调用 openai 的 assistant api，首先效果不是最好，其次对其他模型不兼容，也对大部分人用的三方API不兼容，而且几乎要大改chatbox的聊天逻辑，所以只能是本地文件解析的备选方案。

整体看，本地文件解析有开发计划，但始终还在规划中，工作量也比较大，所以优先级靠后。我觉得作为一个主要功能完全免费的软件，大家在提建议的时候最好不要带有恶意揣测的语气比较好～～

**Comment by Bin-Huang** [comment]
新版本已经支持了文本文件的上传，包括 csv 和代码文件。

**Comment by seaurching** [comment]
如何让 chatbox 把文件上传给 mcp server而不是上传给模型
