### ISSUE TITLE
附上自己的配置文件[Minimax.GLM,Qwen,Deepseek,Yi]

### ISSUE THREAD

**Issue by BlackPool888** [Bin-Huang/chatbox#1408]
附上自己的配置文件,小白用

## Minimax
`
API域名:https://api.minimax.chat
API路径:/v1/text/chatcompletion_v2
模型:abab6.5-chat
`

## Glm4
`
API域名:https://open.bigmodel.cn
API路径:/api/paas/v4/chat/completions
模型:glm-4
`
## Qwen-max
`
API域名:https://dashscope.aliyuncs.com/compatible-mode
API路径:/v1/chat/completions
模型:qwen-max
`

## Deepseek
`
API域名:https://api.deepseek.com
API路径:/v1/chat/completions
模型:deepseek-chat
`

## Yi-large
`
API域名:https://api.lingyiwanwu.com
API路径:/v1/chat/completions
模型:yi-large
`

**Comment by lchyn** [comment]
按照你的配置设置了，然而还是错误。1.3.12 - 2024.06.11 版本 / WIN 11

**QWEN 报错：**
遇到了来自 Custom Provider 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 400, {"error":{"code":"invalid_parameter_error","param":null,"message":"Range of top_p should be (0.0, 1.0)","type":"invalid_request_error"}}

**GLM报错**
遇到了来自 Custom Provider 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 400, {"error":{"code":"1210","message":"API 调用参数有误，请检查文档。"}}

**Comment by lchyn** [comment]
顺便说下，Deepseek 和 Minimax 没有问题

**Comment by BlackPool888** [comment]
top_p请选在0和1之间的浮点数

**Comment by jasoncow007** [comment]
deepseek有版本区分么比如v2,v3

**Comment by BlackPool888** [comment]
> deepseek有版本区分么比如v2,v3

现在都是v3，不需要区分，统一都是deepseek-chat

**Comment by zvictorliu** [comment]
minimax api 应该选 claude 兼容吗，为什么获取到的还是 claude 的模型
