### ISSUE TITLE
[BUG]通义千问不适用自定义方案

### ISSUE THREAD

**Issue by zhoujian-ucas** [Bin-Huang/chatbox#1409]
![1718349605353](https://github.com/Bin-Huang/chatbox/assets/67574129/8964f118-d4a1-4faf-be55-61acbcba7a81)
必须按照图示的方法才可以。不然它会报错
API Error: Status Code 400, {"error":{"code":"invalid_parameter_error","param":null,"message":"Range of top_p should be (0.0, 1.0)","type":"invalid_request_error"}}

**Comment by Bin-Huang** [comment]
新版本已经修复了
