### ISSUE TITLE
是否可以考虑导出/备份,  导入/恢复对话的功能

### ISSUE THREAD

**Issue by maxwzg** [Bin-Huang/chatbox#141]
如果在多台设备上使用,  缺少这个功能, 会导致使用过程的连续性中断, 这对应ChatGPT这种有上下文关系的应用来说非常重要!

更进一步的, 如果能提供一个云同步的功能, 那就更好了

**Comment by Bin-Huang** [comment]
请问你为什么会有多台设备使用的场景呢？

**Comment by maxwzg** [comment]
比如我在公司电脑上使用,  回家后需要在家中台式机上继续使用,  再比如公司有两天电脑, 一台PC, 一台Mac, 需要在两天电脑中切换

**Comment by Bin-Huang** [comment]
This feature has already been implemented. Give it a try after updating.
https://github.com/Bin-Huang/chatbox/releases
