### ISSUE TITLE
无法提供结果

### ISSUE THREAD

**Issue by mubuyan** [Bin-Huang/chatbox#1417]
不管写什么都无法显示结果
<img width="740" alt="螢幕截圖 2024-06-18 20 42 50" src="https://github.com/Bin-Huang/chatbox/assets/169733323/68b9cfbe-216e-4f90-857e-dceac7c08638">

**Comment by Bin-Huang** [comment]
看样子很像是使用了什么第三方的 API 服务，这个报错和三方服务有关，和 Chatbox 没有任何关系的。
