### ISSUE TITLE
[Feature] New claude model

### ISSUE THREAD

**Issue by viraptor** [Bin-Huang/chatbox#1419]
**Problem Description**

The Claude 3.5 model is not available in the settings yet.

**Proposed Solution**

Provide the `claude-3-5-sonnet-20240620` model option.

Additionally it would be great to be able to specify a custom model name, so that we don't need to wait for a new chatbox release when they come out.

**Comment by rodion-m** [comment]
@Bin-Huang your attention is required :)

**Comment by bnjreece** [comment]
> Additionally it would be great to be able to specify a custom model name

Yes

**Comment by coljac** [comment]
> > Additionally it would be great to be able to specify a custom model name
> 
> Yes

Indeed. I was going to make a pull request, except there seem to be a few issues with the current state of the source making setting up the dev environment hard at the moment.

**Comment by coljac** [comment]
> The Claude 3.5 model is not available in the settings yet.

Note, this is available in the web version, so @Bin-Huang is obviously on  to it.

![ksnip_20240622-130758](https://github.com/Bin-Huang/chatbox/assets/191407/225cfb68-5a61-4b29-b469-98237c921310)

**Comment by a10kiloham** [comment]
Ios soon please!!

**Comment by Bin-Huang** [comment]
Claude 3.5 sonnet is now available on Chatbox v1.3.13. iOS and Android versions are also rolling out! 🚀
