### ISSUE TITLE
[Feature] 现在的自定义模型提供方功能很好，但每次只能填写一个模型是十分糟糕的！请增加模型列表

### ISSUE THREAD

**Issue by CookSleep** [Bin-Huang/chatbox#1420]
**问题描述**
 现在的自定义模型提供方功能很好，但每次只能填写一个模型是十分糟糕的！请增加模型列表

**解决思路**
在添加自定义模型提供方的模型填写处支持```gpt-4o,gpt-4turbo,claude-3-5-sonnet-20240620```这样的格式，并将其转化为列表，以便在设置或对话专属设置中快速切换同一个模型服务商的不同模型！

**Comment by kero990** [comment]
原来真的只能填一个啊，我还以为是我不会用
我还第一次见一个客户端模型只能填一个

**Comment by CHEN1016** [comment]
是不是可以直接获取提供方可用的模型列表，one-api的服务都有这个接口的吧

**Comment by wangxiangg1** [comment]
确实

**Comment by gavinzhudev** [comment]
非常支持这个功能
