### ISSUE TITLE
[BUG]关于图像生成

### ISSUE THREAD

**Issue by Anonyame** [Bin-Huang/chatbox#1423]
**Bug Description**

**Steps to Reproduce**
Just use my own API to generate the Pic.

**Expected Results**
Work well and can tune the resolution.

**Actual Results**
Raise the error and can't generate any Pic.

**Screenshots**
Error raised.
<img width="1333" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/68003312/58fb89cf-0ab3-4ce7-ad87-682d2d572683">

**Desktop (please complete the following information):**

-   Operating System: macOS
-   Application Version: 1.3.13

**Additional Context**
Nope. The App didn't crash.

---

**Bug 描述**

**重现步骤**
使用我自己的API生成图片。

**期望结果**
可以正确生成，并且分辨率可调。

**实际结果**
报错且不生成任何图片。

**截图**
报错。
<img width="1333" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/68003312/58fb89cf-0ab3-4ce7-ad87-682d2d572683">

**桌面端（请填写以下信息）：**

-   操作系统：macOS
-   应用程序版本：1.3.13

**其他上下文**
没有。软件并为崩溃。

**Comment by Anonyame** [comment]
同时我发现目前最新版本比GitHub上的最新Release更新。请问目前该软件是已经转向闭源了吗？开源代码库还会继续维护更新吗？

**Comment by Bin-Huang** [comment]
看上去似乎你的代理或者三方服务商在参数上没有兼容 OpenAI API，和软件没有关系～
