### ISSUE TITLE
[Feature] Add StableHorde, Reverse proxy and OpenRouter Support

### ISSUE THREAD

**Issue by tukangcode** [Bin-Huang/chatbox#1424]
**Problem Description**
Chatbot don't offer Stablehorde, reverse proxy and openrouter that use by many.

**Proposed Solution**
Adding thoose 3 to chatbox and model selector

**Additional Context**
https://stablehorde.net/
https://openrouter.ai/
Reverse proxy example : https://api.discord.rocks/

---

**Comment by Bin-Huang** [comment]
Have you tried the custom model provider? You can add any model compatible with the OpenAI API to Chatbox.

**Comment by brycepg** [comment]
For anyone who find this it does indeed work for openrouter:

![Image](https://github.com/user-attachments/assets/1b69337c-fe62-4dfd-829b-770f6e7f53ab)
