### ISSUE TITLE
[BUG] Android 1.3.13 (1.3.14) 选择ollama无法获得模型列表

### ISSUE THREAD

**Issue by JPZ4-5** [Bin-Huang/chatbox#1427]
经初步尝试，1.3.14似乎仍存在这个问题
---

非常感谢这个项目！桌面端和安卓端迄今为止的使用感受都十分不错，随时随地能够通过chatbox使用大模型十分方便！但是最近在安卓端尝试接入ollama时遇到了问题。

经初步判断，此问题与 #1318 #1382(最新回复) #1426 是类似的。

**Bug 描述**
Android 1.3.13 选择模型提供方时，若选择ollama，无法获得模型列表。

**重现步骤**
我的ollama部署在远端集群，使用作业系统部署。
安卓端使用ssh -L进行端口映射，浏览器访问127.0.0.1:11434显示Ollama is running
 
1. 在遇到 #1318 前，作业脚本的设置主要为：
```shell
export OLLAMA_HOST=0.0.0.0:11434
./ollama serve
``` 
在这个情况遇到了与 #1318 一模一样的情况，即桌面端（windows版 1.3.12 & 1.3.13）能够正常使用ollama模型，并获得模型列表的情况下，安卓端（Google Play版1.3.12 & 直接下载的1.3.13版）都出现了**选择模型提供方时，若选择ollama，无法获得模型列表**的情况。

在此情况下，我尝试了[Ollama-app](https://github.com/JHubi1/ollama-app)与[ChattUI](https://github.com/Vali-98/ChatterUI)，经验证，均能通过Ollama的Host test，并读取到集群上已安装的Ollama模型。

2. 此时，我的安卓端在Chatbox客户端和[Lobechat](https://github.com/lobehub/lobe-chat)的[网页端](https://chat-preview.lobehub.com/)均无法读取Ollama模型。

3. 阅读 #1318 后，注意到软件中的***详细教程***指向[如何将 Chatbox 连接到远程 Ollama 服务：逐步指南](https://chatboxai.app/zh/help-center/connect-chatbox-remote-ollama-service-guide)。注意到，事实上Lobechat与Chatbox提供的解决方法一致。经修改后，我的作业脚本的主要相关设置为：
```shell
export OLLAMA_ORIGINS=*
export OLLAMA_HOST=0.0.0.0:11434
./ollama serve
``` 
此后重新提交作业并在安卓端进行端口映射。此后，安卓手机上，浏览器能够访问127.0.0.1:11434显示Ollama is running，ChatterUI、Ollama app、Lobechat均能获得Ollama的模型列表，但Chatbox仍然获取不到😟。

***Chatbox Windows端从头至尾工作正常***

**期望结果**
Chatbox安卓端能够正常获取到远程主机上Ollama的列表模型，并进行正常交互。

**实际结果**
Chatbox安卓端无法获取到Ollama的列表模型，无法使用。

**截图**
![1](https://github.com/Bin-Huang/chatbox/assets/103734362/a50b7409-e701-4507-9ce6-2f3f3dec271a)
![2](https://github.com/Bin-Huang/chatbox/assets/103734362/c47a913e-df6e-43c2-923d-dc95e1d84920)
![3](https://github.com/Bin-Huang/chatbox/assets/103734362/2fef14e4-d990-44a2-8790-fc741c05b969)
![4](https://github.com/Bin-Huang/chatbox/assets/103734362/a9e224a8-f2e6-4be6-8fb9-349d9223b506)
![5](https://github.com/Bin-Huang/chatbox/assets/103734362/6d1d5fe3-0f5a-4e3d-b1a1-c1f666dbb3e4)
![6](https://github.com/Bin-Huang/chatbox/assets/103734362/9df414c3-f0a2-45a6-8229-de1cafaef6f6)

**桌面端：**

-   操作系统：Windows 10
-   应用程序版本：1.3.12 & 1.3.13

**安卓端：**

- 安卓版本：Android 14
- 应用程序版本：Google Play 1.3.12 & 直链 1.3.13

这是个非常棒的项目，希望大大们看看能不能解决这个问题！

**Comment by xuexiaojingquan** [comment]
确实，升级到1.3.14后，问题依然存在。

**Comment by kindzhon** [comment]
me too.

**Comment by Bin-Huang** [comment]
这个问题昨晚已经定位并修复了，会在下个安卓版本中发布

**Comment by kindzhon** [comment]
1.3.16没问题了。

**Comment by JPZ4-5** [comment]
fixed in 1.3.16

**Comment by kindzhon** [comment]
但是网页版https://web.chatboxai.app/还是不行。

**Comment by algerkong** [comment]
> fixed in 1.3.16

1.9.8也不行啊

**Comment by RedQueen76** [comment]
> > fixed in 1.3.16
> 
> 1.9.8也不行啊

我也是我也是，请问现在有办法吗 谢谢

**Comment by JPZ4-5** [comment]
@algerkong @RedQueen76 检查是否在安卓端的浏览器访问ollama服务器正常。
能显示Ollama is running，安卓端Chatbox应当可以正常与Ollama Server通信。

**Comment by JPZ4-5** [comment]
我现在用的google play版，用tmux开的隧道，没有这个问题。

不知道是通信问题还是显示问题，server端有get /api/ps的记录吗？

新开issue吧。

**Comment by algerkong** [comment]
> 我现在用的google play版，用tmux开的隧道，没有这个问题。
> 
> 不知道是通信问题还是显示问题，server端有get /api/ps的记录吗？
> 
> 新开issue吧。

/api/ps   的models是空的  但是我看代码里  获取的 api/tags 是有模型的  现在就是安卓端没有模型显示

![Image](https://github.com/user-attachments/assets/56a11a0e-a117-487e-b780-5073fc99b4dc)
