### ISSUE TITLE
希望支持deepseek

### ISSUE THREAD

**Issue by arenick001** [Bin-Huang/chatbox#1432]

**Comment by JoeChen2me** [comment]
可以通过选择自定义提供商的方式实现对deepseek的支持
 可以参照我下图的设置来完成对deepseek的支持。
![supportdeepseek](https://github.com/Bin-Huang/chatbox/assets/72426664/a073dc2c-f6b6-4e68-a1f7-af229299cdde)  
理论上，可以支持任何兼容openai调用风格的api，例如通义千文，deepseek，kimi

**Comment by woaidianqian** [comment]
deepseek官网推荐应用排第一的就是deepseek

**Comment by arenick001** [comment]
thx
