### ISSUE TITLE
[BUG] Chatbox(v1.3.14) 连接DeepSeek出现422

### ISSUE THREAD

**Issue by Cyan2077** [Bin-Huang/chatbox#1437]
刚下载的Chatbox(v1.3.14)，连接DeepSeek 出现422错误。之前看到有人也出现过类似错误，但是这个最新版本好像又出现了

API Error: Status Code 422, Failed to deserialize the JSON body into the target type: messages[0].content: invalid type: sequence, expected a string at line 1 column 40

![image](https://github.com/Bin-Huang/chatbox/assets/151855984/b3c302e6-1332-4f7e-bd0d-f912ae357015)

**Comment by Hydway** [comment]
Hi @Cyan2077 , this config works for me on v1.3.14
![image](https://github.com/Bin-Huang/chatbox/assets/35193904/8bb4240e-4729-4306-bd50-8f46875f9865)

**Comment by Cyan2077** [comment]
非常可惜，安照你上图的设置，仍然没办法解决这个问题。还是会出现一样的422报错（见第一张图）

**Comment by Bin-Huang** [comment]
原因是因为你使用的模型并不支持图片，所以当发送图片的时候，模型报错了。
