### ISSUE TITLE
[BUG] win11 应用界面只能全屏显示

### ISSUE THREAD

**Issue by watersir** [Bin-Huang/chatbox#1438]
**Bug 描述**
win11 专业版 只能全屏显示

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：

1. 打开 chatbox
2. 应用右上角没有对应的 最小化 全屏 关闭按钮
3. 拖动应用界面上方边框，无反应

**期望结果**
希望应用右上角有对应的 最小化 全屏 关闭按钮 按钮

**截图**
![image](https://github.com/Bin-Huang/chatbox/assets/28620701/e1f53b99-690d-49f5-990e-3efb234806d6)

**桌面端（请填写以下信息）：**

-   操作系统：win11 专业版 ，版本号 23H2， 操作系统版本 22631.3737
-   应用程序版本: 1.3.14

**Comment by heloook** [comment]
同样的问题

**Comment by heloook** [comment]
按F11，好了

**Comment by watersir** [comment]
> 按F11，好了

好的 我试试哈
