### ISSUE TITLE
[BUG] ollama llava:7b  is a  vision model, but chatbox said it's not.

### ISSUE THREAD

**Issue by nne998** [Bin-Huang/chatbox#1446]
**Bug Description**

ollama llava:7b is a vision model （ https://ollama.com/library/llava ）, but chatbox said it's not.
 
**how to reproduce** 
chat with an image

**Comment by JPZ4-5** [comment]
occurred when testing llava:34B, too

**Comment by chllei** [comment]
refer to #1390, please consider image support in ollama mode

**Comment by ldwnt** [comment]
so is this a bug or due to biz choice

**Comment by nne998** [comment]
fixed by  v1.4.0
