### ISSUE TITLE
[BUG]AppImage 1.3.15 crashes on start

### ISSUE THREAD

**Issue by timrichardson** [Bin-Huang/chatbox#1451]
When starting Chatbox-1.3.15-x86_64.AppImage on Ubuntu 24.04 I get:

tim@black:~/Applications$ ./Chatbox-1.3.15-x86_64.AppImage 
[25618:0718/080927.442894:FATAL:credentials.cc(127)] Check failed: . : Permission denied (13)
Trace/breakpoint trap (core dumped)

**Comment by timrichardson** [comment]
Also, same error when running in dev mode, from branch master:


 xyz.chatboxapp.app@0.0.1 dev
> npm start


> xyz.chatboxapp.app@0.0.1 start
> ts-node ./.erb/scripts/check-port-in-use.js && npm run start:renderer


> xyz.chatboxapp.app@0.0.1 start:renderer
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts

Starting preload.js builder...
Starting Main Process...
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:1212/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.41.12:1212/
<i> [webpack-dev-server] Content not from webpack is served from '/home/tim/repositories/chatbox/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'

> xyz.chatboxapp.app@0.0.1 start:main
> cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only .


> xyz.chatboxapp.app@0.0.1 start:preload
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.preload.dev.ts

[27552:0718/081552.323977:FATAL:credentials.cc(127)] Check failed: . : Permission denied (13)

**Comment by Bin-Huang** [comment]
I've restarted the build pipeline and recompiled the Linux AppImage package. You can download it again from the official website https://chatboxai.app/ to check if the issue has been resolved.

**Comment by timrichardson** [comment]
this is an invalid report sorry. I turned off apparmor service while debugging something else and forgot to turn it back on
