### ISSUE TITLE
[BUG] Android14 Chatbox1.3.15闪退

### ISSUE THREAD

**Issue by JPZ4-5** [Bin-Huang/chatbox#1453]
**Bug Description**
Android14 Chatbox1.3.15闪退

**Steps to Reproduce**
卸载旧版本后重装仍然闪退。
点击图标后，进入加载动画后闪退，无法进入软件。清除缓存，清除数据无法解决问题。

**Expected Results**
正常使用软件。

**Actual Results**
点击图标后闪退。

**Screenshots**
即，点击软件图标后，立马就弹回手机桌面。

**Desktop (please complete the following information):**

-   Operating System: Android 14, OneUI 6.1
-   Application Version: Android ver. 1.3.15

**Comment by sylar003** [comment]
I had a same issue

**Comment by masm611** [comment]
遇到了相同的问题
奇怪，安卓兼容应该做得不错的，为什么这次出问题呢？

I have already met the same question.
It is strange that Android did well in adaption, but why did it failed this time?

**Comment by LittleLittleChris** [comment]
我也是 安卓14 荣耀90GT

**Comment by Iamsensen** [comment]
使用play商店更新后遇到了同样的问题闪退没办法使用

**Comment by JPZ4-5** [comment]
fixed in Chatbox Android 1.3.16
