### ISSUE TITLE
[BUG] Android app instantly quits

### ISSUE THREAD

**Issue by MMEurope** [Bin-Huang/chatbox#1460]
**Bug Description**
Can't start the app on OnePlus 12. Latest version Android. Instantly quits.

**Comment by rodion-m** [comment]
The same thing on the latest Google Pixel 7. @Bin-Huang it's an incident, please fix it.

**Comment by Nikolay-Andreychuk** [comment]
Same on Samsung Galaxy S23

**Comment by Bin-Huang** [comment]
Yes, this issue does exist. I submitted a fix on the day the problematic version was released, but Google Play has been blocking my update due to various review issues (some of which are misunderstandings on their part). Still struggling with the review process...

**Comment by rodion-m** [comment]
What about releasing apk in this case?

**Comment by Bin-Huang** [comment]
Just checked Google Play and the latest version has been released. The new version 1.3.18 should have fixed that issue. And the APK is also available on the official website: https://chatboxai.app/
