### ISSUE TITLE
[Feature] COPY button at bottom of long code block. 

### ISSUE THREAD

**Issue by Fe2-O3** [Bin-Huang/chatbox#1462]
**Problem Description**
in long code blocks its too cumbersome to scroll to the top to only copy the code block not extra text.  
**Proposed Solution**
For long code blocks of over say, 50 lines, add a copy bar like the top to the bottom of the code block.

**Additional Context**
Copying long code is hard to scroll to know where to copy.  Copy at bottom is good for long code blocks.

---

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by Bin-Huang** [comment]
Thanks for your feedback! I've fixed this issue and it will be included in the next app update.

If you need it right away, you can try the web version which already has the fix: https://web.chatboxai.app/
