### ISSUE TITLE
[BUG] 自动预览生成物(Artifacts)无法正常显示

### ISSUE THREAD

**Issue by ricklei2777** [Bin-Huang/chatbox#1467]
**Bug 描述**

自动渲染生成物（例如，带有CSS、JS、Tailwind的 HTML）时候不显示，为空白。

**重现步骤**
无需复现，任意对话均不可实现预览。

**期望结果**
此处应该正常出现预览。

**实际结果**
预览选项为空白，无任何显示。

**截图**
<img width="611" alt="image" src="https://github.com/user-attachments/assets/d02b0255-b7de-4b76-b90d-d91289d15f2e">
<img width="1637" alt="image" src="https://github.com/user-attachments/assets/21bfaac0-0ba5-42b3-8826-7ca415e99c6d">
<img width="1637" alt="image" src="https://github.com/user-attachments/assets/277bd6b8-1b8a-4155-b5cc-5e0e2293a248">
<img width="1637" alt="image" src="https://github.com/user-attachments/assets/921c065e-fa2b-4703-88ff-295200e764ef">

**桌面端：**

-   操作系统: [macOS 14.4.1]
-   应用程序版本: [1.3.17]

**其他上下文**

我的问题和回答如下：
Q：用TailwindCSS样式设计一个简单的登录页面
A：当然可以！下面是一个使用 Tailwind CSS 设计的简单登录页面的示例。这个页面包含一个登录表单，包含电子邮件和密码输入框，以及一个登录按钮。

### HTML 代码

```html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <title>登录页面</title>
</head>
<body class="bg-gray-100 flex items-center justify-center min-h-screen">

    <div class="bg-white p-8 rounded-lg shadow-md w-96">
        <h2 class="text-2xl font-bold text-center mb-6">登录</h2>
        <form>
            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="email">
                    电子邮件
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" type="email" placeholder="请输入电子邮件" required>
            </div>
            <div class="mb-6">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
                    密码
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="请输入密码" required>
                <p class="text-red-500 text-xs italic hidden">请输入有效的密码。</p>
            </div>
            <div class="flex items-center justify-between">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    登录
                </button>
            </div>
        </form>
        <p class="mt-4 text-center text-gray-600 text-sm">
            还没有账户？ <a href="#" class="text-blue-500 hover:text-blue-700">注册</a>
        </p>
    </div>

</body>
</html>
```

### 说明

1. **Tailwind CSS 引入**：通过 CDN 引入 Tailwind CSS。
2. **页面结构**：
   - 页面使用 `flex` 和 `min-h-screen` 使其居中。
   - `bg-white` 和 `shadow-md` 为登录框提供了白色背景和阴影效果。
3. **表单元素**：
   - 每个输入框都有适当的边距和样式。
   - 使用 `focus:outline-none` 和 `focus:shadow-outline` 提升用户体验。
4. **按钮**：
   - 登录按钮具有 hover 效果。
5. **注册提示**：页面底部提供注册的链接。

### 使用方法

将上述代码复制并粘贴到一个 HTML 文件中，然后在浏览器中打开即可查看效果。你可以根据需要进一步自定义样式和功能。

**Comment by Bin-Huang** [comment]
这个问题已经解决了，请升级到最新版本

**Comment by Kilosoft** [comment]
I have the same problem, empty artifact view window. I'm using 1.9.0 

![Image](https://github.com/user-attachments/assets/8974475f-b640-4c25-87f8-150f50ecf254)
