### ISSUE TITLE
v0.2以后窗口大小不能缩放

### ISSUE THREAD

**Issue by Garmax** [Bin-Huang/chatbox#147]
v0.1时代的窗口大小是可以zoom in zoom out的，v0.2以后就没有了，有些时候页面过大，文本显示范围会很小，可否添加回来

**Comment by kunl** [comment]
调整大小后，放在后台，窗口会变成默认大小。

**Comment by Bin-Huang** [comment]
I feel like this issue is a bit outdated, so I went ahead and closed it. But if you think it's necessary, feel free to create a new issue at any time.
