### ISSUE TITLE
[Feature] Chat Width

### ISSUE THREAD

**Issue by thugposter** [Bin-Huang/chatbox#1470]
**Problem Description**
Chat width is not adjustable. This is frustrating with large monitors.

**Proposed Solution**
 Please either make the width a flexbox, or make it explicitly adjustable.

**Comment by SMUsamaShah** [comment]
![image](https://github.com/user-attachments/assets/2210786f-2bf3-42e9-b450-c17e2146fbad)

**Comment by thugposter** [comment]
ah yes.
