### ISSUE TITLE
Allow Image-Only Submissions Without Requiring Text Input(允许仅提交图像而不要求文本输入)

### ISSUE THREAD

**Issue by oceanuo** [Bin-Huang/chatbox#1477]
**Problem Description**  
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

When I upload an image and press enter, nothing happens. The image cannot be sent unless I type something in the text box before clicking send. I would prefer to be able to send the image alone without the need to enter any text. 

**Proposed Solution**  
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

Allow the image to be sent directly when I press enter, even if the text box is empty. The solution could involve sending the image with an empty text field (i.e., just sending the `image_url`).

**Additional Context**  
Please provide any additional context or information that would help better understand your feature request, such as screenshots, examples, or use cases.

---

**问题描述**  
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

当我上传图片后按下回车键时，图片不会被发送。除非我在文本框中输入一些文字并点击发送，否则无法发送图片。我希望可以直接发送图片，而不需要输入任何文字。

**解决思路**  
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

允许在文本框为空时，按下回车键后直接发送图片。这个解决方案可以是仅发送图片的 `image_url`，而不需要附加文本。

**附加上下文**  
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by Bin-Huang** [comment]
The feature you mentioned is already available in the latest version. Please update the app to try it out

**Comment by oceanuo** [comment]
Okay, thank you
