### ISSUE TITLE
无法自定义多种模型

### ISSUE THREAD

**Issue by Geek-Bob** [Bin-Huang/chatbox#1488]
**问题描述**
无法自定义多种模型，在很多时候会在不同情况选择不同模型回答问题

**解决思路**
可以自定义配置多种模型，然后在回答界面可以选择模型

**附加上下文**
![image](https://github.com/user-attachments/assets/ff22f360-d7d5-4cab-83df-f4e7fc10aa57)

**Comment by Bin-Huang** [comment]
新版本应该是很方便切换模型的：可以配置多个模型提供方来实现。
