### ISSUE TITLE
为什么chatbox速度那么快，自己搭的却很慢？

### ISSUE THREAD

**Issue by mykunfree** [Bin-Huang/chatbox#149]
安装chatbox，提问题给chatgpt响应速度1-2秒，但是自己搭的项目 比如类似下面这样的 
https://github.com/fanchunke/chatgpt-wecom  响应速度是10秒以上，想问下，为什么chatbox 会那么快呢？ 是因为做对了什么？

**Comment by Bin-Huang** [comment]
请遵守 issues 礼仪。没有建设性的 issues 将直接关闭。需要联系作者的，请通过其他方式。
