### ISSUE TITLE
gtp-4o-mini and Ollama values/options.

### ISSUE THREAD

**Issue by DefamationStation** [Bin-Huang/chatbox#1491]
gpt-4o-mini has the wrong values 

it needs to be

    'gpt-4o-mini': {
        maxTokens: 16_384,
        maxContextTokens: 128_000,
    },
    'gpt-4o-mini-2024-07-18': {
        maxTokens: 16_384,
        maxContextTokens: 128_000,
    },
    
    
    
    
    and also 
    
    Ollama needs to be like below to have repeat_penalty and num_ctx parameters in each message and in options
    
   import { Message } from 'src/shared/types'
import Base, { onResultChange } from './base'
import { ApiError } from './errors'

// import ollama from 'ollama/browser'

interface Options {
    ollamaHost: string
    ollamaModel: string
    temperature: number
    num_ctx: number
    repeat_penalty: number
}

export default class Ollama extends Base {
    public name = 'Ollama'

    public options: Options
    constructor(options: Options) {
        super()
        this.options = options
    }

    getHost(): string {
        let host = this.options.ollamaHost.trim()
        if (host.endsWith('/')) {
            host = host.slice(0, -1)
        }
        if (!host.startsWith('http')) {
            host = 'http://' + host
        }
        if (host === 'http://localhost:11434') {
            host = 'http://127.0.0.1:11434'
        }
        return host
    }

    async callChatCompletion(rawMessages: Message[], signal?: AbortSignal, onResultChange?: onResultChange): Promise<string> {
        const messages = rawMessages.map(m => ({ role: m.role, content: m.content }))
        const res = await this.post(
            `${this.getHost()}/api/chat`,
            { 'Content-Type': 'application/json' },
            {
                model: this.options.ollamaModel,
                messages,
                stream: true,
                options: {
                    temperature: this.options.temperature,
                    num_ctx: this.options.num_ctx,
                    repeat_penalty: this.options.repeat_penalty,
                }
            },
            signal,
        )
        let result = ''
        await this.handleNdjson(res, (message) => {
            const data = JSON.parse(message)
            if (data['done']) {
                return
            }
            const word = data['message']?.['content']
            if (! word) {
                throw new ApiError(JSON.stringify(data))
            }
            result += word
            if (onResultChange) {
                onResultChange(result)
            }
        })
        return result
    }

    async listModels(): Promise<string[]> {
        const res = await this.get(`${this.getHost()}/api/tags`, {})
        const json = await res.json()
        if (! json['models']) {
            throw new ApiError(JSON.stringify(json))
        }
        return json['models'].map((m: any) => m['name'])
    }
}

**Comment by Bin-Huang** [comment]
I have fixed this issue.
