### ISSUE TITLE
sglang启动服务，chatbox输出第一个字符是null

### ISSUE THREAD

**Issue by colinsongf** [Bin-Huang/chatbox#1497]
nullHello! How can I assist you today? Is there something specific you'd like to talk about or ask about? I'm here to provide information, answer questions, or engage in conversation on a wide range of topics.

**Comment by Bin-Huang** [comment]
这一般是服务没有百分百兼容 OpenAI API 接口输出导致的。不过我会在下个版本里添加相关的兼容。
