### ISSUE TITLE
[BUG] 经常会有乱码符号 （MacOS）

### ISSUE THREAD

**Issue by nne998** [Bin-Huang/chatbox#1499]
操作系统： macos
版本：v 1.4.0 (旧版本也一样会出现）
 LLM: Openai、ollama  都会出现

如下：

<img width="653" alt="image" src="https://github.com/user-attachments/assets/f8e51be2-6c81-416c-9beb-d670294d3ada">

**Comment by liaoweiguo** [comment]
为什么close，问题还在啊
