### ISSUE TITLE
增加标题搜索功能

### ISSUE THREAD

**Issue by clark874** [Bin-Huang/chatbox#15]
可以设置自定义的标题属性、标签、分组，并提供全局搜索能力。这样才能实现对chatgpt plus的超越，否则当下并无太多区别。

**Comment by Bin-Huang** [comment]
已经在计划中了，这其实也是我早期的想法

**Comment by Bin-Huang** [comment]
This feature has already been implemented. Give it a try after updating.
https://github.com/Bin-Huang/chatbox/releases
