### ISSUE TITLE
解决在 ubuntu 22.04 下无法启动 chatbox 的方法

### ISSUE THREAD

**Issue by Smityz** [Bin-Huang/chatbox#150]
## 运行环境:
ubuntu 22.04

## 如何复现:
```
sudo dpkg -i chatbox_0.2.7_amd64.deb
```
使用 dpkg 安装 deb 之后点击图表无法启动应用

## 问题原因:
在终端中输入
```
> chatbox
chatbox: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```
发现缺少动态库

## 解决方法:
```
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
```
安装动态库
Ref: https://stackoverflow.com/a/72633324

**Comment by loveplay1983** [comment]
Ubuntu 18.04 shows `chatbox: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by chatbox)
`, I have tried to compile it from src and `make install`, but when I check the version, it is still `2.27`, please help me out. Do I need to upgrade my ubuntu to the latest distribution?

**Comment by loveplay1983** [comment]
> 

I ended up with a fresh installation of the latest ubuntu which is 22.04, it is now working.

**Comment by FrankJIE09** [comment]
ubuntu 22.04可行
```
wget https://mirrors.ustc.edu.cn/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
sudo dpkg -i libssl1.1_1.1.0g-2ubuntu4_amd64.deb
```

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复，试试最新版本
https://github.com/Bin-Huang/chatbox/releases
