### ISSUE TITLE
Anthropic API: requests with an origin header no longer be supported after September 13, 2024

### ISSUE THREAD

**Issue by allen2peace** [Bin-Huang/chatbox#1500]
**Problem Description**
Claude officially sent me an email recently, reminding me that the current way to call the Anthropic API is no longer available in the future, is there any plan to update it?

The content of the email is shown in the screenshot below:

**Screenshots**
![image](https://github.com/user-attachments/assets/47a58d9a-d2b1-4452-ab8c-b9f771ad2604)

**Comment by Bin-Huang** [comment]
I've checked Chatbox's source code and found that it doesn't include any origin header in the requests. Everything seems to be working fine on that end.

Just a thought - if you've shared this API key with other applications before, it's possible those apps might be causing the origin-related requests you're seeing.
