### ISSUE TITLE
[BUG] 无法调用豆包(doubao) API， 出现CORS

### ISSUE THREAD

**Issue by ThemanRonin** [Bin-Huang/chatbox#1509]
![image](https://github.com/user-attachments/assets/7667b7e8-d8e1-40d6-b005-d1387cbb7bb2)
![image](https://github.com/user-attachments/assets/daa0dbbb-7f31-4297-8298-7a95784518d6)
![image](https://github.com/user-attachments/assets/29455962-e722-48d7-815e-7b509cbd005a)
![image](https://github.com/user-attachments/assets/c720dbbf-57f7-4ecc-8810-e7b4f04cfd96)

**Comment by jayvzh** [comment]
试了最新电脑版1.5.1已经可以用豆包了，但是android版还不行，一直API Error: Status Code 400, invalid proxy headers

**Comment by Bin-Huang** [comment]
新版本已经修复了这个问题。网页端和手机端，请将豆包添加成自定义模型提供方，然后打开新增的“网络兼容模式”功能
