### ISSUE TITLE
建议[Other]

### ISSUE THREAD

**Issue by guoruixing1** [Bin-Huang/chatbox#151]
windows中生成的结果中可以加入搜索框就更好了，方便查找；将gpt升级到3.5就完美了。哈哈

**Comment by xp406181** [comment]
咦，现在不就是3.5turbo么

**Comment by expfukck** [comment]
其实就联网搜索功能

**Comment by Bin-Huang** [comment]
没看懂你的意思，搜索本地聊天记录还是类似谷歌的网页搜索

**Comment by guoruixing1** [comment]
> 没看懂你的意思，搜索本地聊天记录还是类似谷歌的网页搜索
是搜索本地聊天记录的噻
