### ISSUE TITLE
[BUG] 官網下載的1.4.1版本被檢測有 Trojan ，請再確認一下是否有誤？

### ISSUE THREAD

**Issue by chinlung** [Bin-Huang/chatbox#1526]
您好，

最新從官網（https://chatboxai.app/zh-TW）下載的 1.4.1 mac 版本會被掃毒檢測到有 Trojan ，同個檔案丟到virustotal也有掃到（https://www.virustotal.com/gui/file/527c26e4f9d528f9f438f2707d8bf4a46ed62eae1d813ee1c7628aadfb8dcaf7?nocache=1）

<img width="681" alt="CleanShot 2024-09-14 at 16 25 09@2x" src="https://github.com/user-attachments/assets/eb1b4b82-5fbb-4648-985f-285242f51e3d">

請再確認一下是否有誤？

謝謝

**Comment by JaminYe** [comment]
我尝试从 https://chatboxai.app/zh-TW 下载了Chatbox-1.4.1.dmg,Chatbox-1.4.1-arm64.dmg并没有出现问题
https://www.virustotal.com/gui/file/e0b6bf4a48f4d1e708cd5bba6d9ae101fc53b7f549e95ffa2a5f9d241c54b450
https://www.virustotal.com/gui/file/9c755dcd59f9790cb6094ecd5d5a057779b7ac1fcd8e18e3579df052ca124aa1
你可以对比一下文件的md5是否一致

**Comment by chinlung** [comment]
請將app用「顯示套件內容」查看，找尋Resources/app.asar檔案再送去virustotal掃描看看。我是因為在執行時，該檔案被防毒軟體查報後才知道這個檔案，但也有可能是誤判？？只是想要確認一下是否是誤報？
![CleanShot 2024-09-14 at 16 18 18@2x](https://github.com/user-attachments/assets/3c2d3656-687e-485d-a8a0-3de7e1a6babf)

**Comment by Bin-Huang** [comment]
可以基本确定是误报。类似的情况在几个月前也出现过，很奇怪的是同一个安装包在几天后重新扫描却一切正常了。
