### ISSUE TITLE
[BUG]API 请求失败：Error Details: SyntaxError: Unterminated string in JSON at position 77

### ISSUE THREAD

**Issue by lnbiuc** [Bin-Huang/chatbox#153]
**Bug 描述**
1. 错误的响应

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
3. 点击 "......"
4. 滚动到 "......"
5. 发现了这个 bug。

**期望结果**
返回正常回答

**实际结果**
API 请求失败：
Error parsing item: {"id":"chatcmpl-6yY4ET6hRqPnAgA1jg7hpLLkUnUmB","object":"chat.completion.chun.
Error Details: SyntaxError: Unterminated string in JSON at position 77

**截图**
![image](https://user-images.githubusercontent.com/85148161/227836055-87c25ed5-6263-4afe-b8ef-374e10596395.png)

**桌面端（请填写以下信息）：**
- windows10
- 应用程序版本：0.2.7

**其他上下文**
使用了自己的api和key，可以确保自己的api和key在其他客户端可以正常使用

**Comment by jihao** [comment]
API 请求失败： 
```
Error parsing item: {"id":"chatcmpl-6zHnIOgli03KVPsLMYDBIrkQ99Mep","object.
Error Details: SyntaxError: Unterminated string in JSON at position 54
```

和反向代理有关系吗？

**Comment by Bin-Huang** [comment]
一般这种情况都和反向代理有关。服务器正确配置不会有这个问题。
