### ISSUE TITLE
[Feature] 增加“自动生成标题”开关设置

### ISSUE THREAD

**Issue by MurphyLo** [Bin-Huang/chatbox#1533]
o1 模型发布后是否可以考虑一下增加一个设置项，允许用户关闭自动生成标题功能？这个模型的补全太多了，而且不确定性很强，输出数个字的标题的情况下也可能产生数 ktokens 的补全开销。

**Comment by Bin-Huang** [comment]
很早就有这个功能了，更新一下，在设置里找一找
