### ISSUE TITLE
[Feature] A global shortcut to show/hide it to tray.

### ISSUE THREAD

**Issue by ofey404** [Bin-Huang/chatbox#154]
I'm so addicted to chatbox that I keep it on my desktop all the time.

I want this feature: It can hide in the system tray and can be summoned to the desktop as soon as I press a shortcut.

I would try to solve this if I have time.

**Comment by Bin-Huang** [comment]
Try cmd+` on Mac or ctrl+` on Windows, this shortcut was added a long time ago.

**Comment by Brugman** [comment]
> ctrl+` on Windows

On Win 10 this only minimizes the app. It does not hide itself in the system tray, which is much better for apps that you want to have at the ready all day.
