### ISSUE TITLE
[BUG] 1.4.2版本更新后 IOS 系统 连接蓝牙键盘，无法回车键提交输入

### ISSUE THREAD

**Issue by Melonan** [Bin-Huang/chatbox#1546]
**Bug 描述**

从App Store 进行 1.4.2版本更新后， IOS 系统 连接蓝牙键盘，无法回车键提交输入

环境：Ipad 2020

**期望结果**
版本更新之前可以直接回车进行提交，shift+回车为换行
更新后直接回车 也是换行，必须屏幕点击提交按钮

**Comment by Bin-Huang** [comment]
你好，出于设计考虑，决定将回车键用于换行了。有些用户喜欢换行、有些用户喜欢发送，所以我只能先妥协下，以后可能会有两种方式的切换开关。
