### ISSUE TITLE
[Feature] 单独会话聊天模式

### ISSUE THREAD

**Issue by GaryChangCN** [Bin-Huang/chatbox#155]
**Problem Description**
Chat Session Menu sidebar in left has take up too much space， and can't be closed.

**Proposed Solution**
open a simple window when Double click Session button, like MacOS iMessage

-----------------------

**问题描述**
现在打开软件，左侧的对话菜单栏占据了很大的位置，并且不能折叠，很多时候只是想单独聊天。

**解决思路**
类似 MacOS 的短信，双击会话按钮可以进入一个单独聊天模式

**附加上下文**
例如
<img width="686" alt="image" src="https://user-images.githubusercontent.com/12539978/227872861-bcce6ccc-f54c-415c-b450-5a717adb2c6b.png">

**Comment by Bin-Huang** [comment]
很早之前的版本已经实现了，可以更新一下，先关闭了这条 issues 了。
