### ISSUE TITLE
[Feature] Code Highlight in Questions collapsed

### ISSUE THREAD

**Issue by yngwi** [Bin-Huang/chatbox#1557]
**Problem Description**

Reading back threads with long user-posted code snippets gets cumbersome as I‘m mostly not interested in them very much. It would be great if the markdown-code-highlight boxes could be collapsed so that only the first few lines are visible (if longer than that).

**Proposed Solution**
Make code boxes in user questions/posts collapsible

**Additional Context**

**Comment by Bin-Huang** [comment]
The feature you mentioned is already available in the latest version. Please update the app to try it out!
