### ISSUE TITLE
Same functionality for selecting models on Azure OpenAI API as with OpenAI API

### ISSUE THREAD

**Issue by liama86** [Bin-Huang/chatbox#1558]
**Problem Description**
When using an Azure OpenAI API key in Chatbox, it's currently only possible to configure and use a single model when selecting the Azure OpenAI API type, whereas when using the OpenAI API you can use many different models within the chat by selecting the model from the drop down menu above the text entry box.
**Proposed Solution**
I would like it that you can configure multiple different deployments when using the Azure OpenAI API which you can then select from in the drop-down menu.

**Additional Context**
Something else that doesn't work with the current implementation of Azure OpenAI API is the o1-preview model so it would be good that it was also supported. Thanks! :)

**Comment by Bin-Huang** [comment]
The latest version has what you need. Try upgrading!

**Comment by liama86** [comment]
@Bin-Huang I checked, it doesn't look like anything has changed in the Azure OpenAI settings, it's still only possible to configure one deployment.

**Comment by Bin-Huang** [comment]
@liama86 You can hit the 'Add' button to create more deployment options:
<img width="590" alt="image" src="https://github.com/user-attachments/assets/9a63a597-4d03-41a0-aec7-d83a4de07db4">

**Comment by liama86** [comment]
@Bin-Huang ohh, thanks, it works! Unfortunately it doesn't seem to support o1-preview,  should that be another feature request?
