### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ClementLi233** [Bin-Huang/chatbox#156]
![屏幕截图 2023-03-27 165354](https://user-images.githubusercontent.com/129049281/227892346-c3d56ac7-7b8c-4dbc-8ddc-d5f2252f5447.png)
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
清晰简洁地描述这个 bug 是什么。
![image](https://user-images.githubusercontent.com/129049281/227892562-62329a11-a30e-45a4-9fcb-bb1ebbca188a.png)
**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 双击运行安装程序
2. 点击 下一步
3.完成后双击打开
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。
![image](https://user-images.githubusercontent.com/129049281/227892992-62e4e3ca-1f0d-43db-8bc9-5c0cb06385b6.png)

**桌面端（请填写以下信息）：**
- 操作系统：[Win11 专业版21H2]
- 应用程序版本：[chatbox_0.2.7_x64_en-US]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

无法关闭此界面，无法退出，只能通过任务管理器强制退出。

**Comment by zeisscai** [comment]
试试看用geek uninstall 卸载，重新安装

**Comment by ClementLi233** [comment]
用geek uninstall卸载了，
![image](https://user-images.githubusercontent.com/129049281/228108999-54312cb0-4a5c-4364-99db-fb20c318d214.png)
重新安装了 还是一样的兼容性问题

**Comment by ClementLi233** [comment]
![image](https://user-images.githubusercontent.com/129049281/228109293-6d44dc86-4666-450c-a501-92fe0125f61f.png)

**Comment by Bin-Huang** [comment]
试试用管理员权限打开

**Comment by ClementLi233** [comment]
也不行

Benn Huang ***@***.***> 于2023年3月30日周四 22:17写道：

**Comment by Bin-Huang** [comment]
很早之前的版本已经解决了，可以更新一下，先关闭了这条 issues 了。
