### ISSUE TITLE
[Feature] 希望支持添加多个key

### ISSUE THREAD

**Issue by lgf5090** [Bin-Huang/chatbox#1578]
有的免费模型有请求限制所以会有多个账户， 希望在model select旁边增加一个 apiKey select可以选择，这样会方便很多， 而不是添加多个provider

![image](https://github.com/user-attachments/assets/7fb8c1bd-d2b2-40f3-b133-4a27a13a779b)

**Comment by Bin-Huang** [comment]
目前多个 provider 应该已经可以满足需求了，添加 api key 的切换有些过于小众，反而会增加其他用户的理解成本，所以大概率不会考虑实现这个功能。
