### ISSUE TITLE
[Feature] Support prompts

### ISSUE THREAD

**Issue by ofey404** [Bin-Huang/chatbox#158]
There are 2 similar issues on supporting prompts: #9 #84 .

And there are some awesome prompts that can boost users' productivity dramatically.

- [f/awesome-chatgpt-prompts](https://github.com/f/awesome-chatgpt-prompts)
- ...

For the user experience design, we may consider referring to the unofficial ChatGPT client.

![image](https://user-images.githubusercontent.com/35857538/228111821-fb165118-1b02-4735-a891-8fffeb9c77a1.png)

**Comment by Bin-Huang** [comment]
This issue has already been resolved in previous versions, so you might want to try upgrading to see if it's fixed.
