### ISSUE TITLE
[BUG] Status Code 400, invalid proxy headers

### ISSUE THREAD

**Issue by astahle11** [Bin-Huang/chatbox#1582]
**Bug Description**
I was using the app last night and it was working fine; this morning I started receiving the following error when using Claude 3-5. I also tried this with Opus and had the same issue. To my knowledge, I haven't changed any settings. I checked my anthropic dashboard and everything seems fine in my account.

> An error has occurred with Claude, which is usually caused by incorrect settings or account issues. Please check your AI settings and account status, or click here to view the FAQ document.
> 
> API Error: Status Code 400, invalid proxy headers
> 
> tokens used: unknown, model: claude-3-5-sonnet-20240620

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

1. Opened a pre-existing chat I had been using
2. Send question
3. Error 400 received

**Desktop (please complete the following information):**

-   Operating System: Android 14
-   Application Version: AP2A.240905.003.F1

**Additional Context**
ChatGPT chats do not have the same issue and are working fine.

---

**Comment by hasaranga** [comment]
I'm also getting this error for custom data provider. It comes for both ios and android versions. But the pc version is working fine.

**Comment by dmrlsn** [comment]
> I'm also getting this error for custom data provider. It comes for both ios and android versions. But the pc version is working fine.

Same here. PC version works fine, Android / iOS shows this error

**Comment by hasaranga** [comment]
@Bin-Huang please fix this issue!

**Comment by dmrlsn** [comment]
Okay, looks like we've hit a regression. My buddy's iPhone was still running v1.4.1 and Claude was working like a boss. We pushed the update to the latest build, and now Claude's borked, throwing a 400 error. I tried to roll back on Android, but I can't track down a working legacy APK anywhere.  If anyone's still running an older Android build and can reproduce, that'd be clutch for debugging..

**Comment by lincbal4** [comment]
Same issue

**Comment by Bin-Huang** [comment]
Hi everyone,

Thanks for letting me know about this issue. I've fixed the problem, but it took a few days to get the update out because of the app store review processes.

The good news is that the new Android version is now available for download. For iOS users, please hang tight for a bit longer - it's still in review.

**Comment by astahle11** [comment]
Thank you!

**Comment by SkippyAFC** [comment]
Hello. I received an iOS update today but an unfortunately still receiving the same error message.
![image](https://github.com/user-attachments/assets/5405f8f9-cc44-4171-96c8-cededcc054c7)

**Comment by hasaranga** [comment]
I'm still getting that error when using sambanova as openapi provider.

**Comment by SkippyAFC** [comment]
> Hello. I received an iOS update today but an unfortunately still receiving the same error message. ![image](https://private-user-images.githubusercontent.com/186169892/379751318-5405f8f9-cc44-4171-96c8-cededcc054c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MzMwNDEsIm5iZiI6MTcyOTgzMjc0MSwicGF0aCI6Ii8xODYxNjk4OTIvMzc5NzUxMzE4LTU0MDVmOGY5LWNjNDQtNDE3MS05NmM4LWNlZGVkY2MwNTRjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQwNTA1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTNkOWY3MmJiZGFkMmQ4ZDZiZTE0NjE2OTJhNjY5MDRhMTVkMGI0MTk3NjI0ZjRjNDQ2ZTFmZmExY2MxNmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hEuR2QOLd8YsXg4E3AXNlFsQ6tLG3kmQLmAuMJenhE4)

I just have another update pushed from the App Store today (that said it was from yesterday) and it did fit the Claude error. Thank you!

**Comment by matsymbols** [comment]
The mac app also gets the same 404 error on Sambanova API url. On AnythingLLM the same setup works:
Base URL: https://api.sambanova.ai/v1
I tried different ways of adding the URL but no luck.

**Comment by Bin-Huang** [comment]
> The mac app also gets the same 404 error on Sambanova API url. On AnythingLLM the same setup works: Base URL: https://api.sambanova.ai/v1 I tried different ways of adding the URL but no luck.

@matsymbols It seems this is more of a configuration issue. The 404 error means the server was reached but the requested path wasn't found. I think this error is different from the issue we're discussing here and is likely related to how the API endpoint is set up.

**Comment by Bin-Huang** [comment]
Finally, I published the updates on both the App Store and Google Play after working hard on it. The issue mentioned here has been resolved.
