### ISSUE TITLE
[BUG] 运行npm run dev出现19 Errors：Uncaught runtime errors: × ERROR Cannot read properties of undefined (reading 'invoke') TypeError: Cannot read properties of undefined (reading 'invoke')     at DesktopPlatform.getLocale (http://222.195.72.114:1212/renderer.dev.js:178719:39)     at http://222.195.72.114:1212/renderer.dev.js:176051:99     at http://222.195.72.114:1212/renderer.dev.js:176056:15 ERROR Cannot read properties of undefined (reading 'invoke') TypeError: Cannot read properties of undefined (reading 'invoke')     at DesktopPlatform.getLocale (http://222.195.72.114:1212/renderer.dev.js:178719:39)     at http://IP/renderer.dev.js:176051:99     at http://IP/renderer.dev.js:176056:15

### ISSUE THREAD

**Issue by Li-Haoqing** [Bin-Huang/chatbox#1583]
![image](https://github.com/user-attachments/assets/46c16509-514d-4103-87c5-9e793d11d2ab)
![image](https://github.com/user-attachments/assets/1eb495e9-332d-44a4-833a-25c5a0945d1b)
![image](https://github.com/user-attachments/assets/59aaf41b-adbc-476e-b625-426297bef878)

**Comment by Bin-Huang** [comment]
本地无法复现。但是看报错应该是在 electron 环境之外运行，如果缺少 electron 确实会报这样的错误的。

**Comment by Jackysonwang** [comment]
这是在网页端出现的报错吗，我有一样的问题

**Comment by gavid0124** [comment]
![Image](https://github.com/user-attachments/assets/e4747e8c-2675-4851-9218-2b4da4339f62)
我也有同样的问题，本地和服务器都是这个错误，本地是windows11系统，服务器端是Ubuntu系统，克隆的git代码，通过npm run dev命令启动的。

**Comment by 1-bytes** [comment]
> 本地无法复现。但是看报错应该是在 electron 环境之外运行，如果缺少 electron 确实会报这样的错误的。

所以应该要怎么修正呢？现在我也遇到了同样的问题

**Comment by jiweiyeah** [comment]
> > 本地无法复现。但是看报错应该是在 electron 环境之外运行，如果缺少 electron 确实会报这样的错误的。
> 
> 所以应该要怎么修正呢？现在我也遇到了同样的问题

+1

**Comment by a-l-o-n-g** [comment]
> 本地无法复现。但是看报错应该是在 electron 环境之外运行，如果缺少 electron 确实会报这样的错误的。

+1，如何本地运行web端呢

**Comment by cshuting** [comment]
+1

**Comment by xuhaimeixu** [comment]
+1

**Comment by NJCHello** [comment]
+1
