### ISSUE TITLE
[Feature] Add latest Anthropic's Claude 3.5 Sonnet model

### ISSUE THREAD

**Issue by Tafkas** [Bin-Huang/chatbox#1586]
Add the latest [Claude 3.5 Sonnet](https://docs.anthropic.com/en/docs/about-claude/models#model-names) (`claude-3-5-sonnet-20241022`, alias: `claude-3-5-sonnet-latest`) model

**Comment by DenisSergeevitch** [comment]
why it takes so looong

**Comment by abrichr** [comment]
Looks like it may be implemented server-side (note the presence of "openai" but not "anthropic"):

https://github.com/Bin-Huang/chatbox/blob/51118329925c4926aeada35f94b0008780a33c76/src/shared/types.ts#L64

Would love to be wrong on this if anyone knows better!

**Comment by jeffgyf** [comment]
check the model selection dropdown besides the message sending button
![image](https://github.com/user-attachments/assets/115c21e5-3417-42ef-b0f7-5af340146c13)

**Comment by Bin-Huang** [comment]
Just like they said above, the new model is actually already in the dropdown menu left by the send button! I posted about it on X(Twitter) a while back, but it looks like quite a few people missed that update haha 😄

**Comment by yevhenii-sir** [comment]
> @Bin-Huang Just like they said above, the new model is actually already in the dropdown menu left by the send button! I posted about it on X(Twitter) a while back, but it looks like quite a few people missed that update haha 😄

Is there any way to make it so that when creating a chat, I don't have to select it again? Because it's not in the settings, it's only available in the chat dropdown list.
![image](https://github.com/user-attachments/assets/35cb0c8b-7eea-43ce-8fdd-efc2191b545c)
![image](https://github.com/user-attachments/assets/efd2ec16-2dc2-4cb0-bc13-3a097dd3abd5)

**Comment by Bin-Huang** [comment]
This was caused by a bug. I have fixed the issue and it will be included in the next update.
