### ISSUE TITLE
[BUG] Chatbox AI Code 500 Error

### ISSUE THREAD

**Issue by owenxie-oss** [Bin-Huang/chatbox#1587]
**Bug Description**
开发者，你好！

今天在使用Chatbox AI的时候经常性遇到"API Error: Status Code 500, {"error":"Internal Server Error"}"错误提示。
进行中的对话会进入再起不能的状态，重开对话以后，可以暂时摆脱这个问题，但是使用时间稍长以后（仅仅处理了几篇文档），又会出现同样的提示。
因为是利用Chatbox AI高效处理大量的文档，这样的话，不停发生中途中断又要从头开始上传文档，变得很麻烦，还白白消耗了Token。

我目前是在Windows客户端使用，model用的是Chatbox AI 4。

之前同样的任务我作了好几次，不知道为何今天就不行了，如果是Token用尽了，也应该弹出的是Token用尽的提示。

还有能不能开放一个不限流量的套餐啊？或者按Token使用量收费也可以，经常用着用着就用干了，之前的工作没法延续，只能从头开始。

谢谢！

**Comment by Bin-Huang** [comment]
你好，这个问题已经修复了，感谢反馈。以后有任何问题，欢迎随时发送到 hi@benn.app

**Comment by owenxie-oss** [comment]
> 你好，这个问题已经修复了，感谢反馈。以后有任何问题，欢迎随时发送到 [hi@benn.app](mailto:hi@benn.app)

开发者，您好！

感谢修复与回复，此前我也试图发邮件联系，但是一直没有收到过反馈，我想通过你设置的页面管理自己的订阅，也收不到确认邮件，我的邮件地址是owen.xie@gmail.com，能否烦请帮助检查一下，谢谢！

**Comment by Bin-Huang** [comment]
> > 你好，这个问题已经修复了，感谢反馈。以后有任何问题，欢迎随时发送到 [hi@benn.app](mailto:hi@benn.app)
> 
> 开发者，您好！
> 
> 感谢修复与回复，此前我也试图发邮件联系，但是一直没有收到过反馈，我想通过你设置的页面管理自己的订阅，也收不到确认邮件，我的邮件地址是[owen.xie@gmail.com](mailto:owen.xie@gmail.com)，能否烦请帮助检查一下，谢谢！

好的，我邮件联系你
