### ISSUE TITLE
[BUG]安装后打开显示兼容性问题，然后还无法关闭窗口用的是win10系统

### ISSUE THREAD

**Issue by weizhenyu85** [Bin-Huang/chatbox#159]

**Comment by stackWang** [comment]
兼容性问题
一个不兼容的[软件]尝试与 Microsoft Edge 一起[加载]尽管这种问题通常由过期的程序所知，但也可能是由恶意软件引起的。建议安装最新版的程序，并且确保反恶意软件的运行和及时更新。

错误代码: STATUS_INVALID_IMAGE_HASH

**Comment by wwhoo** [comment]
window11，打开报错
![2023-03-31_115538](https://user-images.githubusercontent.com/33834049/229019014-01bdf245-79bd-442f-92d9-11196529351e.png)

**Comment by wwhoo** [comment]
window11打开报错，也根据网上的提示修改了注册表，可还是不行，参考修改注册表如下链接：
https://www.xitongbuluo.com/jiaocheng/73507.html
https://zhuanlan.zhihu.com/p/133243870/

**Comment by wwhoo** [comment]
修改注册表后并且重启电脑，打开还是报错

**Comment by wwhoo** [comment]
![image](https://user-images.githubusercontent.com/33834049/229019721-7eb24b53-9af4-4d2c-a6aa-eb0ba6222cab.png)
![image](https://user-images.githubusercontent.com/33834049/229019755-56f2fba5-08e4-41b5-9184-2f5a296116aa.png)

**Comment by xldistance** [comment]
修改兼容性，兼容win7运行就可以打开了

**Comment by Bin-Huang** [comment]
新版本做了相关的修复，看下有没有解决问题？

https://github.com/Bin-Huang/chatbox/releases

**Comment by ljlike** [comment]
> 新版本做了相关的修复，看下有没有解决问题？
> 
> https://github.com/Bin-Huang/chatbox/releases

下载了最新版本，还是报错

**Comment by Bin-Huang** [comment]
你好，新版本做了修复，下载最新版本再试一下？https://github.com/Bin-Huang/chatbox/releases
