### ISSUE TITLE
[BUG] OLLAMA isn't supported / doesn't work on the web version

### ISSUE THREAD

**Issue by WizzardHub** [Bin-Huang/chatbox#1594]
**Bug Description**
OLLAMA doesn't work on web version.

**Steps to Reproduce**
Go to settings, select OLLAMA, set your endpoint url.

**Expected Results**
No models will be shown.
However when using the mobile app or the desktop app models are being shown.

**Screenshots**
![Sans titre](https://github.com/user-attachments/assets/033abe7d-2fb9-4127-8308-c79f2816fc30)

**Desktop (please complete the following information):**

-   Operating System: Windows 11
-   Application Version: latest

**Additional Context**
Running APP on Android 15 from the play store.

**Comment by Bin-Huang** [comment]
This is most likely due to CORS (cross-origin) restrictions in web browsers, which makes it difficult to connect to OLLAMA through the web version.

For now, I recommend using either the mobile app or desktop application to connect to OLLAMA, as they work perfectly without these limitations.
