### ISSUE TITLE
增加对话内代码的展示样式

### ISSUE THREAD

**Issue by kangyiwen** [Bin-Huang/chatbox#16]
可以参考： https://github.com/cogentapps/chat-with-gpt   这个也是 TypeScript 开发的，样式比较好看，关键是代码展示比较好。

希望 chatbox 也可以增加代码样式。谢谢

**Comment by Bin-Huang** [comment]
<img width="976" alt="image" src="https://user-images.githubusercontent.com/20723142/224519406-1db90da3-4236-48a2-b50a-dfa32db6196a.png">

其实一直都是有代码样式的，你遇到了什么问题？

**Comment by Bin-Huang** [comment]
从最早的版本 v0.0.1 就支持 markdown 了

**Comment by kangyiwen** [comment]
![image](https://user-images.githubusercontent.com/76672577/224525055-704566ad-1e0d-45a9-9426-550ceb09685d.png)

![image](https://user-images.githubusercontent.com/76672577/224525092-63344712-1367-4de5-b469-cf5079aa09ab.png)

0.0.7 版本，请问是我电脑设置不一样吗？

**Comment by Bin-Huang** [comment]
不是的，有时候 openai 会回复纯文本。你可以指定让他用 markdown 回复你。比如：“写一段 base64 解码的 python 代码，用 markdown 回复我”

**Comment by kangyiwen** [comment]
谢谢   还有这招。
