### ISSUE TITLE
[BUG]ipad客户端（v1.6.0）使用第三方转发的openai接口提示网络错误

### ISSUE THREAD

**Issue by amibaren** [Bin-Huang/chatbox#1600]
**Bug Description**
ipad版本使用第三方转发的openai接口提示网络错误。同样配置和版本（v1.6.0 - 2024.11.03）在windows上一切正常。
上个版本和1.6版都有这个问题，但前几个版本是正常的。

**Steps to Reproduce**
配置API Key和第三方转发的BaseURL后，与夸夸机进行简单交互。

1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
正常回复用户问题

**Actual Results**
提示网络错误

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**

-   Operating System: [ipd ios 18.1]
-   Application Version: [v1.6.0 - 2024.11.03]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

**Comment by Bin-Huang** [comment]
一般是配置问题。如果配置正确的话，建议添加为自定义提供方，然后开启网络兼容模式。
