### ISSUE TITLE
[BUG] iOS, Appstore的下载链接在中国区不可用

### ISSUE THREAD

**Issue by anthonygao** [Bin-Huang/chatbox#1601]
**Bug 描述**
中国区的apple账号不能下载app.

**重现步骤**
用中国大陆的账号登录appstore, 搜索不到chatbox ai;
通过浏览器打开ios下载链接无法跳转到appstore下载页面.

**期望结果**
中国区可用.

**其他上下文**
实际的链接是: https://apps.apple.com/us/app/chatbox-ai-best-ai-client-top/id6471368056
包含us区.

**Comment by Bin-Huang** [comment]
不是不想上架，是没办法上架。只能继续争取……
