### ISSUE TITLE
对话设置应该同样加入上下文的信息数量上限

### ISSUE THREAD

**Issue by Hasuki360** [Bin-Huang/chatbox#1604]
有些对话不需要太长的关联 比如翻译 总结类 如果联系了上下文会造成token浪费

**Comment by Bin-Huang** [comment]
这个设置一直都有，点击会话标题进入会话设置，在专属模型设置里。

**Comment by Hasuki360** [comment]
> 这个设置一直都有，点击会话标题进入会话设置，在专属模型设置里。

试了下，原来在官方提供方的情况下有这个功能，但第三方提供方的情况下就没有了选项

**Comment by Bin-Huang** [comment]
感谢反馈，确实没有。现在已经加上了，会在下个版本中更新。如果急用的话，也可以使用已经更新的网页版本：https://web.chatboxai.app/
