### ISSUE TITLE
!使用第三方api注意!

### ISSUE THREAD

**Issue by ColaMiku** [Bin-Huang/chatbox#1606]
当你使用第三方openai api时,请**不要**在API域名后添加“/”
例如：https://api.example.com/
请**不要**填写 https://api.example.com/
请**不要**在api域名后添加斜杠( / )
这将导致返回word count: 0 (消耗你的token并返回空对话内容)
`（仅供参考）`

**Comment by Bin-Huang** [comment]
感谢分享。我认为最好在应用层面兼容下，这样才能防止未来更多人输入时的错误。下个版本会包括这个更新。
