### ISSUE TITLE
[BUG]version16.0版本使用 Mermaid 生成的流程图现在内容为空，且不能复制流程图代码，只有png图片

### ISSUE THREAD

**Issue by aiyinluya** [Bin-Huang/chatbox#1607]
具体错误表现如下：
![image](https://github.com/user-attachments/assets/619e8dfa-fa24-467e-9169-30ba450fb430)

**Comment by huminglong** [comment]
+1

**Comment by Bin-Huang** [comment]
感谢反馈，问题已经修复了，会在下个版本中包含。如果比较急用的话，可以先使用网页版本： https://web.chatboxai.app/

**Comment by aiyinluya** [comment]
强的很




---- 回复的原邮件 ----
| 发件人 | Benn ***@***.***> |
| 日期 | 2024年11月07日 21:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Bin-Huang/chatbox] [BUG]version16.0版本使用 Mermaid 生成的流程图现在内容为空，且不能复制流程图代码，只有png图片 (Issue #1607) |

感谢反馈，问题已经修复了，会在下个版本中包含。如果比较急用的话，可以先使用网页版本： https://web.chatboxai.app/
