### ISSUE TITLE
[BUG]windows 10 下重新打开软件配置信息清空的问题以及临时解决方法

### ISSUE THREAD

**Issue by zeisscai** [Bin-Huang/chatbox#161]
**Bug Description**
聊天记录，API key，等设置无法保存，每次重新开启后都会丢失

**Desktop (please complete the following information):**
- windows 10 专业版 
- 0.2.3和0.2.7

**截图**
![d30b52b8ffc6bab7c948fbed9755eabf](https://user-images.githubusercontent.com/29810018/228159058-596b6e08-dac4-4576-8641-3bcea58bec97.jpg)
因为我和同学都遇到这个问题，当时没有好的截图，只能找到这张图了，抱歉。

**临时解决方法**
用geek uninstall 卸载并清理相关文件，然后重装

**Comment by Bin-Huang** [comment]
你好，我看到这个软件版本（0.2）已经有点老了，可以试一下最新的版本吗？我应该已经修复过了

**Comment by zeisscai** [comment]
是的，新版本已经解决。感谢您！
