### ISSUE TITLE
[Feature] 改进对ollama 0.4 中的vision 模型的支持

### ISSUE THREAD

**Issue by wwjCMP** [Bin-Huang/chatbox#1610]
**问题描述**

对新版本的ollama 0.4 中的vision 模型支持不是很好。用的是llama3.2 的10B模型，直接进行图像对话和通过chatbox进行对话，回答质量差别很大。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by Bin-Huang** [comment]
看上去是模型的原因，当模型处理图像时一般都会降智。
