### ISSUE TITLE
[Feature] 自定义模型应该和其他模型一样可以在对话界面设置上下文和温度

### ISSUE THREAD

**Issue by wwjCMP** [Bin-Huang/chatbox#1615]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

---

**问题描述**
自定义模型应该和其他模型一样可以在对话界面设置上下文和温度。单独将这些自定义模型的上下文和温度统一为默认没有必要吧？

**Comment by aarontianqx** [comment]
支持，这点不太方便，每次都要去改综合配置
