### ISSUE TITLE
[BUG] 网页版刷新后一直reload

### ISSUE THREAD

**Issue by plustliang** [Bin-Huang/chatbox#1627]
**Bug Description**
网页版本，一直reload

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

1. 进入网页版：https://web.chatboxai.app
2. 删掉侧边栏默认的对话列表
3. 设置好中文
4. F5刷新网页，然后网页就一直reload了

**Expected Results**
正常显示

**Actual Results**
一直reload

**Desktop (please complete the following information):**

-   Operating System: windows11、chrome(版本 131.0.6778.70（正式版本） （64 位）)

**Comment by xcmake** [comment]
我在网页版也遇到了同样的问题

**Comment by Bin-Huang** [comment]
我非常重视这个问题，所以已经修复了。因为我至今没有复现问题，所以只是修复了一些可能的地方。如果问题还存在的话请告诉我～

**Comment by plustliang** [comment]
> 我非常重视这个问题，所以已经修复了。因为我至今没有复现问题，所以只是修复了一些可能的地方。如果问题还存在的话请告诉我～

目前看，没有复现了。
