### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Moriarty1024** [Bin-Huang/chatbox#163]
**Bug 描述**
总是出现`API Request Failed`，尤其是当返回文本较长的时候

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 软件默认参数没有改动
2. 在IT Expert下输入*告诉我C语言中关于文件输入输出的内容，详细一点，最好有实例代码*
3. 会生成文字，但是生成一半的时候会停止，并返回错误信息*Error parsing item: {"id":"chatcmpl-6yzfNXh9T0ahWv4U0X3plz9oevY2b","object":"chat.completion.chunk","created":1379964417,"model":"gpt-3.5-.
Error Details: SyntaxError: JSON Parse error: Unterminated string*

**期望结果**
希望能够完整的返回需要的信息

**截图**
![image](https://user-images.githubusercontent.com/37505758/228189063-04983c20-4ea3-456a-b025-9ede35fd03b2.png)

**桌面端（请填写以下信息）：**
- 操作系统：Manjaro
- 应用程序版本：0.2.7

**这一问题之前我已经提了issue，但是情况依然存在。我使用其他类似软件没有出现类似现象**

**Comment by Moriarty1024** [comment]
@Bin-Huang

**Comment by Bin-Huang** [comment]
是这样的，我在使用中从来没有遇到过这个问题。而且我尝试用一些工具来模拟弱网环境，同样没有遇到这种问题。我怀疑可能和你的代理服务器的配置有关，能不能提供更多细节来方便我复现，比如代理服务器的配置文件？

**Comment by Bin-Huang** [comment]
这个问题已经修复过了，更新版本试试
