### ISSUE TITLE
[Other] 大家顶起来，支持博主做最牛的第三方客户端

### ISSUE THREAD

**Issue by RandyChen1985** [Bin-Huang/chatbox#164]
现在第三方客户端是百家争鸣，希望博主做出牛逼的客户端，实现自己的事业，
想要的一些功能：
- 漂亮的UI，logo，包括聊天的背景界面，机器人和user的色块区分
- 消息的导出&备份
- 分享功能，分享生成图片或文字，带排版，支持分享到社交平台。
- 聊天界面显示最后一次的聊天时间，类似微信里面。
- 本地搜索？
- 多终端平台同步
- 内置提示词

**Comment by Bin-Huang** [comment]
我会一直开发的，但个人开发速度总是有限，期待大家的共同贡献！
