### ISSUE TITLE
[Other]已经设置了无限制上下文，但依然在对话中报错

### ISSUE THREAD

**Issue by JQ88888** [Bin-Huang/chatbox#1642]
![问题反馈](https://github.com/user-attachments/assets/baa1e1ad-cd9f-47a0-9e53-5b64d30a2f45)

<img width="597" alt="image" src="https://github.com/user-attachments/assets/ff0da3fe-e4fc-4ca3-bcec-6fe02498ef19">

如上图所示，已经设置了无限制上下文，但是依然在对话中报错，无论提问的是什么问题都会报错。

**Comment by Bin-Huang** [comment]
你好，这个错误的意思是模型只能支持 8192 tokens 的上下文，而你当前的上下文太多了。因此你正确的设置应该是降低上下文的消息上限，比如我觉得改成 4 获得 6 对你来说是合适的。
