### ISSUE TITLE
[Feature]自定义api如何同时支持多个模型？

### ISSUE THREAD

**Issue by wuduher** [Bin-Huang/chatbox#1647]
如题

**Comment by sparkTesal** [comment]
同问，自定义模型只能加一个也太蠢了

**Comment by Bin-Huang** [comment]
<img width="575" alt="image" src="https://github.com/user-attachments/assets/b58f8a25-63bd-4b2d-90ec-e75646e96e62">
你好，一直都是可以的，这个功能很早就有了
