### ISSUE TITLE
[Feature] 记住窗口位置和大小

### ISSUE THREAD

**Issue by netjune** [Bin-Huang/chatbox#1651]
**Problem Description**
每次启动后, 窗口都比较大, 不太适合我的屏幕, 调整大小后, 重启, 记不住上次调整的大小

可以增加一个选项, 记住窗口大小和位置

**Comment by Bin-Huang** [comment]
你好，窗口保持这个功能很早就开发了，而且在我知道的大部分用户中都是可以正常工作的。可以详细介绍下你的运行环境吗，比如操作系统和版本？这样我可以更快的定位和排查问题

**Comment by wanzhiyu** [comment]
> 你好，窗口保持这个功能很早就开发了，而且在我知道的大部分用户中都是可以正常工作的。可以详细介绍下你的运行环境吗，比如操作系统和版本？这样我可以更快的定位和排查问题

 您好，我遇到了同样的问题，我的问题描述在这个Issue（https://github.com/Bin-Huang/chatbox/issues/1640#issue-2688790708）里面，主要出现在双屏显示器上，不知道是不是和 @netjune 相同的问题

**Comment by netjune** [comment]
> 你好，窗口保持这个功能很早就开发了，而且在我知道的大部分用户中都是可以正常工作的。可以详细介绍下你的运行环境吗，比如操作系统和版本？这样我可以更快的定位和排查问题

我的系统是Linux Mint 22标准桌面环境, 单屏幕, 但有多个虚拟桌面(workspace)

**Comment by netjune** [comment]
> 你好，窗口保持这个功能很早就开发了，而且在我知道的大部分用户中都是可以正常工作的。可以详细介绍下你的运行环境吗，比如操作系统和版本？这样我可以更快的定位和排查问题

知道原因了, 我用的是github上的社区版, 换成官网下载的版本就可以了
