### ISSUE TITLE
[Other]

### ISSUE THREAD

**Issue by brian479974** [Bin-Huang/chatbox#1655]
網路錯誤。請檢查目前的網路狀態，以及與 https://api.x.ai 的連接情況。

Network Error: Load failed

目前這個連線這個設置在桌機版是沒有問題的，但是在手機版就會出現這個錯誤

**Comment by Bin-Huang** [comment]
建议在手机版本中打开“网络兼容模式”，可能可以解决问题

**Comment by brian479974** [comment]
有照著您的建議打開設置，還是不能使用...
