### ISSUE TITLE
[Feature]一个使用上的问题

### ISSUE THREAD

**Issue by Rock-Ayl** [Bin-Huang/chatbox#1657]
**问题描述**
chatBox for mac ,version=1.7.0 ，截至到当前版本。
对话右上角按钮下拉菜单【清空所有消息】【删除当前会话】这两个很容易点错。
我只是经常习惯性的【清空所有消息】，但是偶尔几次会不小心点到【删除当前会话】。
这会导致，没有任何再次确认的提示下直接删除了对话，感觉有点不太合理吧。

**解决思路**
【删除当前会话】这个按钮加一个再次确认的弹窗提示

**附加上下文**
<img width="272" alt="image" src="https://github.com/user-attachments/assets/43ab64ff-62f8-4c79-b218-42fe85040308">

**Comment by Bin-Huang** [comment]
你好，新版本会加上二次确认。
