### ISSUE TITLE
grok模型，API Error: Status Code 404（有大佬知道怎么解决吗）

### ISSUE THREAD

**Issue by HEXI02** [Bin-Huang/chatbox#1661]
<img width="572" alt="c57c9265cac05817e153a0e105b1a79" src="https://github.com/user-attachments/assets/5a6bec3f-83e2-4a26-960a-a9b24b6d4fa2">

**Comment by speeder2005** [comment]
same here.  coask.  I follow a youtube video to setup this. Got the same error as yours.

**Comment by speeder2005** [comment]
I found the issue. make sure the API path is "/v1/chat/completions" .  somehow the default for me doesn't have the /v1".  Not the same as the youtube video shows.  But after I insert /v1, problem solved.   Hope you have the same luck.

**Comment by changshaa** [comment]
the issue is API path as mentioned like "speeder2005"

**Comment by HEXI02** [comment]
> 我发现了问题。确保 API 路径为 “/v1/chat/completions” 。不知何故，我的默认值没有 /v1”。与 youtube 视频显示的不同。但是在我插入 /v1 之后，问题解决了。希望你有同样的运气。

是这样解决的，感谢
