### ISSUE TITLE
[Other]AZure OpenAI API 配置后无法工作

### ISSUE THREAD

**Issue by TuanTuan** [Bin-Huang/chatbox#1663]
你好， 我把AZure OpenAI 的api 配置

![azure](https://github.com/user-attachments/assets/aba45633-45d2-4dd9-9c2d-2d22f7b0ca17)

配置到chatbox 1.7.0 后

![chatbox](https://github.com/user-attachments/assets/cee79640-c991-41be-98cb-1c248ea7c58a)

一直返回错误 API Error: Status Code 404, {"error":{"code":"DeploymentNotFound","message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

同样的配置，我配置在nextchat 里面，是可以工作的， 是哪里配置错误了么？

**Comment by Bin-Huang** [comment]
在终结点的设置中，去掉 /openai/deployments.... 后面这些

**Comment by TuanTuan** [comment]
非常感谢，改成portal中的名字后可以使用了，我之前以为是在chatbox里面自定义的名字。
