### ISSUE TITLE
qq

### ISSUE THREAD

**Issue by gold74386** [Bin-Huang/chatbox#1666]
遇到了来自 Custom Provider 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 403, <!doctype html> <html> <body> <p>This service is not available in your region.</p> </body> </html>

**Comment by Bin-Huang** [comment]
错误的意思是：“服务在你的地区不提供”。所以这是网络问题，和软件没有关系～
