### ISSUE TITLE
[BUG] 发送按钮与输入框大小不一致

### ISSUE THREAD

**Issue by yanghuaizhi** [Bin-Huang/chatbox#169]
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/6992819/228255972-82e975e5-2584-4566-b46f-707bdc2cf6ab.png">

发送按钮与输入框大小不一致
总体体验很棒，太感谢了。

**Comment by GotoFox** [comment]
额，提交完回家了才看到有这个 fix，已提交push，待 @Bin-Huang 大佬通过

**Comment by Bin-Huang** [comment]
已修复了
