### ISSUE TITLE
[Feature] Support for O1

### ISSUE THREAD

**Issue by gaiar** [Bin-Huang/chatbox#1696]
**Problem Description**
The current implementation lacks interaction with O1 via API. As I understand it, the interface should be the same as with O1-Preview.

**Comment by Bin-Huang** [comment]
Actually, the chatbox can connect to O1 models. Could you clarify which interface settings you're referring to? This would help me better understand what you're looking for.

![image](https://github.com/user-attachments/assets/4b0284cd-f6e6-4d16-85d4-4e97c7570eed)

**Comment by gaiar** [comment]
https://platform.openai.com/docs/models#o1
i'm talking about these models

**Comment by gaiar** [comment]
so I don't see o1 in the list (not preview one)
<img width="336" alt="image" src="https://github.com/user-attachments/assets/a2e971cd-8769-4aa3-a78a-c484555e1e75" />

**Comment by RooobinYe** [comment]
> Actually, the chatbox can connect to O1 models. Could you clarify which interface settings you're referring to? This would help me better understand what you're looking for.实际上，聊天框可以连接到 O1 模型。你能澄清一下你所指的接口设置吗？这将帮助我更好地理解你在寻找什么。
> 
> ![image](https://private-user-images.githubusercontent.com/20723142/397762774-4b0284cd-f6e6-4d16-85d4-4e97c7570eed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODk3MTIsIm5iZiI6MTczNDc4OTQxMiwicGF0aCI6Ii8yMDcyMzE0Mi8zOTc3NjI3NzQtNGIwMjg0Y2QtZjZlNi00ZDE2LTg1ZDQtNGU5N2M3NTcwZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDEzNTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlYzg4ZDhjNzMyZDFmY2IzM2MzNDhlY2ZkMTQyYTAyMGQ1ODQ1NjRmMGQ2ZDAwN2UzMmY0MDU1OWY1OGZjN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iW6_5yQUa-ameXzGRbqjaDLIGu0rki9BgGDLN-j7uQ8)

事实上 o1 目前无法读图 （我确定是 chatbox 的问题 因为我在 openwebui 上可以读图 是不是因为 o1 不是流式传输的原因呢？）

是否需要新开一个 issue？
