### ISSUE TITLE
[BUG] Deploynment name causing images in the prompt to fail

### ISSUE THREAD

**Issue by ofinke** [Bin-Huang/chatbox#1705]
**Bug Description**
When calling AzureOpenAI deploynment of GPT4o model, where the deploynment in the azure  is named "gpt-4", the app refuses to send images into the service stating, that the gpt-4 model doesnt support it.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

1. In Azure deploy instance of GPT4o with a name "gpt-4"
2. In Chatbox try to call this instance with a image in the text prompt
3. Observe the bug.

**Expected Results**
Expected result is that the model can handle the image as GPT4o supports it. I expect the app behaviour to be agnostic to a deploynment name.

**Actual Results**
The app refuses to sen the image into the API as it thinks, that I'm using GPT4 model. However, the model I'm using is GPT4o, just the deploynment name is called "gpt-4". Unnecessary check.

**Screenshots**
![obrazek](https://github.com/user-attachments/assets/e13131bd-0a5a-4eaf-a842-a514630efd94)

**Desktop (please complete the following information):**

-   Operating System: Windows 11
-   Application Version: desktop app, version 1.8.1

**Additional Context**
Please remove this unnecessary check and let API response handle image support :)

**Comment by Bin-Huang** [comment]
GPT-4 doesn't actually work with images. You'll probably need to set up GPT-4o if you want to handle images. That's when they first added support for multiple input types like images and text.

**Comment by ofinke** [comment]
@Bin-Huang I'm sorry but you misunderstood the problem.

The **model I am using is GPT4o**, which suports images. **However, the name for the deploynment we used in Azure is gpt4**, which we did due to redundancy. You can see on the image bellow, that we are using GPT4o under the name of GPT4 and because the name of the deploynment is not GPT4o, the app assumes it is GPT4. In Azure you can name model deploynments whatever you want

![obrazek](https://github.com/user-attachments/assets/b7d13c0f-3bd5-428f-99c2-4e64fafb522b)
