### ISSUE TITLE
[Feature] 输入框字数上限是否可自定义

### ISSUE THREAD

**Issue by imzoet** [Bin-Huang/chatbox#1712]
**问题描述**
目前输入框字数上限貌似是1000个字符，当我输入大量内容时会被截断，是否可以开发这一选项，让我可以输入超过1000个字符

**Comment by Amamiya23** [comment]
大量内容建议你上传文本文件，然后用少量文字描述

**Comment by Bin-Huang** [comment]
记得是没有字数限制的

**Comment by imzoet** [comment]
抱歉，描述有误，应该是从剪切板可粘贴的最大字符数，如果复制了很多字符，那么粘贴到对话框里超过一定数量的字符将不会被粘贴
