### ISSUE TITLE
在我的win7系统电脑上，我安装不了chatbox,每个版本我都尝试了，希望你能告诉我问题答案。谢谢

### ISSUE THREAD

**Issue by kokolisy** [Bin-Huang/chatbox#172]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by ttyy33** [comment]
win7好像用不了，得win10及其以上

**Comment by KingingWang** [comment]
我win11也安装不了
The installer has encountered an unexpected error installing
this package.This may indicate a problem with this
package.The error code is 2503.

**Comment by ttyy33** [comment]
> 我win11也安装不了 The installer has encountered an unexpected error installing this package.This may indicate a problem with this package.The error code is 2503.

你重新下载一个安装包，试试呢

**Comment by Bin-Huang** [comment]
新版本已经兼容 Window7 了。
The new version is now compatible with Windows 7.

https://github.com/Bin-Huang/chatbox/releases
