### ISSUE TITLE
[BUG] win 10安装

### ISSUE THREAD

**Issue by goog** [Bin-Huang/chatbox#173]
**Bug 描述**
安装过程很慢 前期出现powershell 弹窗

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统：win10
- 应用程序版本：chatbox_0.2.8_x64_en-US

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by goog** [comment]
是不是病毒 还是有点粗糙？

**Comment by JIou1** [comment]
在收到邮件之后我又继续安装了一次，结果这次正常使用 我使用了美国的节点并输入 key 正常使用 非常感谢您的开发。

Jay Cheng ***@***.***> 于2023年3月30日周四 11:20写道：

**Comment by JIou1** [comment]
哦 我好像搞错了。。。我以为你是开发者，现在这个在win10可以使用的 至于病毒 好像没有这个现象

lin You ***@***.***> 于2023年3月30日周四 16:27写道：
