### ISSUE TITLE
[BUG] 部分文字不会开启换行

### ISSUE THREAD

**Issue by devyujie** [Bin-Huang/chatbox#174]
**Bug 描述**
这一段文字被当做代码了估计，没有开启换行。

**重现步骤**
让它写一封申请/信

**期望结果**
和正常文字一样，换行。

**实际结果**
/

**截图**
![image](https://user-images.githubusercontent.com/48620527/228429714-e98fcb26-087f-44f7-9587-90f30fb645d6.png)

**桌面端（请填写以下信息）：**
- 操作系统：Windows 10 LTSC 1809
- 应用程序版本：0.2.8

**其他上下文**
/

**Comment by minmik528** [comment]
same issue

**Comment by Bin-Huang** [comment]
很早之前的版本已经实现了，可以更新一下，先关闭了这条 issues 了。
