### ISSUE TITLE
[Feature]能否像Voice Control for ChatGPT插件那样增加文本朗读的功能？

### ISSUE THREAD

**Issue by Celipeace** [Bin-Huang/chatbox#176]
**问题描述**
能否像Voice Control for ChatGPT插件那样增加文本朗读的功能

**解决思路**
1. 能够使用语音输入
2. 能够自动朗读ChatGPT的回答
3. 可以设置自动朗读开关
4. 可以设置语音包

**Comment by Bin-Huang** [comment]
重复issues，先关闭了～
#19
