### ISSUE TITLE
请问如何切换gpt版本，一直无法切换到gpt4，plus用户。

### ISSUE THREAD

**Issue by laosanzhang** [Bin-Huang/chatbox#177]
请问如何切换gpt版本，一直无法切换到gpt4，plus用户。

**Comment by Salmonberry** [comment]
> 请问如何切换gpt版本，一直无法切换到gpt4，plus用户。
点击Setting>Model&Token 再选择model

**Comment by eric09230** [comment]
即便是plus用戶，gpt4的api功能也需要另外申請才能使用
