### ISSUE TITLE
在win7安装，弹出‘’there is a problem with tihs window installer package. a problem run as part of the setup did not finish as expected"

### ISSUE THREAD

**Issue by sjszwcj** [Bin-Huang/chatbox#178]
please give me a new installer package. thank you very much.

**Comment by qhdesnldop474** [comment]
same question

**Comment by Bin-Huang** [comment]
新版本已经兼容 Window7 了。
The new version is now compatible with Windows 7.

https://github.com/Bin-Huang/chatbox/releases
