### ISSUE TITLE
建议增加：在输入框，按 上 键，出现上一次的提示词

### ISSUE THREAD

**Issue by kangyiwen** [Bin-Huang/chatbox#18]
命令行打多了，不自己的在输入框按上，希望出现上一次的命令，然后再修改。

谢谢。

**Comment by Bin-Huang** [comment]
这个建议很好，我试着开发一下

**Comment by Bin-Huang** [comment]
想问下，你会在什么情况频繁地重复输入之前的内容？

**Comment by kangyiwen** [comment]
上一句和下一句需要微调的情况下，例如：

请写一篇500字文章。

改成 

请写一篇1000字文章

**Comment by Bin-Huang** [comment]
这个场景其实也可以直接编辑原来的消息，然后重新生成。

**Comment by Bin-Huang** [comment]
这个功能在之前的更新中已经实现了
