### ISSUE TITLE
[BUG]  Error 429请问怎么解决

### ISSUE THREAD

**Issue by Valerie8899** [Bin-Huang/chatbox#182]
API 请求失败：

Error from OpenAI: 429  {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

**Comment by JIou1** [comment]
没钱了

**Comment by Bin-Huang** [comment]
这是你的 OpenAI 账户问题，你的使用超过账户限制了，请检查你的账户。
