### ISSUE TITLE
[BUG] 必须等待ai输出完才能滑动及其他动作

### ISSUE THREAD

**Issue by 145600g** [Bin-Huang/chatbox#184]
ai没输出完不能滑动也不能切换对话，希望可以改善一下，
另外可以多选删除就好了

**Comment by Hacker-C** [comment]
刚想说这个问题，结果没有输出完之前，无法往前滑动，本意是想看看已经生成部分的内容的，这样每次都需要等待，然后才能从头看起。

**Comment by wuyudi** [comment]
https://github.com/Bin-Huang/chatbox/issues/52

**Comment by ynz9kh** [comment]
表示非常需要相关选项进行设置。早期的版本不会随着回答的输出而自动滑动界面，现在的效果虽说不错，可是有些不方便即使查看已经输出的内容，需要一直等待到所有回答输出完整。

**Comment by kalufinnle** [comment]
#52  #108

**Comment by Bin-Huang** [comment]
新版本已经修复了
