### ISSUE TITLE
[BUG] 404错误是怎么回事，我选的3.5呀

### ISSUE THREAD

**Issue by yuyistar** [Bin-Huang/chatbox#187]
API 请求失败：

Error from OpenAI: 404  {
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

**Comment by jdonee** [comment]
我也遇到过类似问题，我尝试改用gpt-4去咨询问题，然后它就出现这个错误，然后改回gpt-3.5,它还是报这个错误，当我退出程序后重新进入才能继续使用。

**Comment by AlanDeYong** [comment]
hi I encountered the same bug, cannot use other models. also when i check my api usage it is showing gpt-3.5-turbo-0301, even though gpt-3.5-turbo is selected.... please help

**Comment by Bin-Huang** [comment]
最新版本已经修复
