### ISSUE TITLE
建议增加语音转文本,文本转语音的功能, 这样可以多一个维度和gpt对话

### ISSUE THREAD

**Issue by SR023** [Bin-Huang/chatbox#19]
语音转文本的开源实现:
https://pypi.org/project/SpeechRecognition/

文本转语音
可以考虑api或者本地语音合成
https://github.com/kuangdd/ttskit

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1239, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1239。这条 issue 先关闭了～～
