### ISSUE TITLE
可否增加本地代理功能。

### ISSUE THREAD

**Issue by aimjoke** [Bin-Huang/chatbox#191]
能不能增加一个使用本地代理功能？
像这样：
![1234](https://user-images.githubusercontent.com/43093839/228621821-0bfc797c-b8a1-402d-8e51-5594dfa5521f.png)

**Comment by zhimiyouwu33** [comment]
希望能添加socks5代理选项！

**Comment by srliuhao** [comment]
同求。现在必须开全局代理才可以用。
上次作者不是说呼声高就加么，不要赖皮，你都刚发了0.2.8版本了，有空换图标赶紧加代理啊，加油，生产队的驴都歇够了

**Comment by SumTaron** [comment]
> 同求。现在必须开全局代理才可以用。 上次作者不是说呼声高就加么，不要赖皮，你都刚发了0.2.8版本了，有空换图标赶紧加代理啊，加油，生产队的驴都歇够了

其实在PAC文件里 把api.openai.com域名加进去,就可以不用开全局代理 也能使用了...

**Comment by ANM-WYX** [comment]
用clash编辑规则，把openai的相关域名都设置好代理就行了，ssr用pac也行
