### ISSUE TITLE
增加选项, 是否检查更新 [BUG]

### ISSUE THREAD

**Issue by lovitus** [Bin-Huang/chatbox#195]
开发者你好:

每次打开, 都要有更新弹窗很影响使用效率, 看完弹窗都忘了要做什么了.
希望
- 增加 " 自动检查新版本" 选项.
- 增加 "检查新版本" 手动更新

希望考虑. 谢谢

**Comment by Bin-Huang** [comment]
还是有必要及时更新的，有很多潜在的bug影响使用。可能是之前更新太快了，我最近尽量减少弹窗频次了。

**Comment by JSCSZZSS** [comment]
确实，老版本用的挺好的不想更新，但是每次打开都会弹窗，有没有办法禁掉弹窗啊

**Comment by lovitus** [comment]
> 确实，老版本用的挺好的不想更新，但是每次打开都会弹窗，有没有办法禁掉弹窗啊

大家已经发过一些issues了关于弹窗更新，  以及打包webview的问题。
虽然有部分人觉得更新烦人， 以及webview可以在异常的时候提示用户下载或者其他处理方式，或者额外提供未包含webview的release。

但是可能作者考虑另一大部分用户的方便，或者自己的偏好， 所以是目前的处理方式。
加上这又是开源应用。

通过禁用一些请求可以阻止弹窗， 但是还是建议跟着作者更新， 或者开一个fork。

**Comment by Bin-Huang** [comment]
我现在都没眼看以前的老版本，最近修了不少BUG……
