### ISSUE TITLE
如果添加本地代理 [Other]

### ISSUE THREAD

**Issue by Nicolas-XF** [Bin-Huang/chatbox#197]
怎么设置成本地代理模式 ，http://127.0.0.1:7890 ，开全局有点痛苦
![image](https://user-images.githubusercontent.com/21361330/228714058-9e4c74c1-6840-4562-a493-2d5da0c61d5c.png)

**Comment by dalei229339** [comment]
I have the same question

**Comment by hhhh124hhhh** [comment]
I have the same question

**Comment by hhhxxxddd** [comment]
I have the same question

**Comment by FrankHuy** [comment]
Try add openai.com to your PAC config.

**Comment by Bin-Huang** [comment]
重复issues，先关闭了
#13
