### ISSUE TITLE
[bug]"Invalid URL (POST /v1/chat/completions)

### ISSUE THREAD

**Issue by TANGMOQI** [Bin-Huang/chatbox#199]
Error from OpenAI: 404  {
  "error": {
    "message": "Invalid URL (POST /v1/chat/completions)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

Encountered such a problem，How can I solve it

**Comment by TANGMOQI** [comment]
接口404，报Invalid URL (POST /v1/chat/completions)，有人遇到这个问题么

**Comment by TANGMOQI** [comment]
![image](https://user-images.githubusercontent.com/88825169/228794080-cdf33c47-581d-4581-8315-c874a16177d0.png)
还不到4097

**Comment by TANGMOQI** [comment]
![image](https://user-images.githubusercontent.com/88825169/228794590-0dffda50-54e8-4f7f-9187-ec88fa5444b2.png)

**Comment by Bin-Huang** [comment]
把 Proxy 设置重置吧，地址格式错了
