### ISSUE TITLE
希望可以自定义api地址

### ISSUE THREAD

**Issue by gqfjob** [Bin-Huang/chatbox#2]
网络环境访问不了openai，自己搭建的反代，希望能够加入一项设置，填写自己的反代地址

**Comment by Bin-Huang** [comment]
#1 
计划中了，今晚十二点会发更新
Currently, in the works, the update is scheduled to be released at midnight tonight

**Comment by Bin-Huang** [comment]
v0.0.5 已经发布了

https://github.com/Bin-Huang/chatbox/releases

**Comment by kangyiwen** [comment]
希望把反代源代码也开源 ：）
