### ISSUE TITLE
生成对话中，切换到其他对话会跳转回正在生成的对话

### ISSUE THREAD

**Issue by lyz66046861** [Bin-Huang/chatbox#20]
如题

**Comment by Bin-Huang** [comment]
This issue has been resolved in the new version v0.6.3. If the problem still persists, you can reopen the issue at any time😊.
https://github.com/Bin-Huang/chatbox/releases


这个问题在新版本 v0.6.3 已经解决，如果问题还存在你可以随时重新开启这个 issues 😊。
https://github.com/Bin-Huang/chatbox/releases
