### ISSUE TITLE
[Feature] 提供紧凑界面模式

### ISSUE THREAD

**Issue by iven** [Bin-Huang/chatbox#200]
**问题描述**

现在的界面字体、间距之类的都比较大（至少 Mac 上是这样），虽然比较美观，不过在小屏上显示的内容很有限，希望提供紧凑一些的界面，以显示更多的信息量。

**解决思路**

改进现有界面的紧凑程度，或者提供不同的主题或者选项。

**附加上下文**

Chatbox 和 Opencat 的对比：
<img width="1440" alt="图片" src="https://user-images.githubusercontent.com/56165/228750955-1f73fac7-be90-42e3-a4a4-be252e24afc8.png">

**Comment by Bin-Huang** [comment]
我最近正在着手改进了，你有什么好的想法或者css代码可以直接和我讲，或者在issues讨论。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Iven Hsu ***@***.***&gt;
发送时间: 2023年3月30日 14:56
收件人: Bin-Huang/chatbox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Bin-Huang/chatbox] [Feature] 提供紧凑界面模式 (Issue #200)





 
问题描述
 
现在的界面字体、间距之类的都比较大（至少 Mac 上是这样），虽然比较美观，不过在小屏上显示的内容很有限，希望提供紧凑一些的界面，以显示更多的信息量。
 
解决思路
 
改进现有界面的紧凑程度，或者提供不同的主题或者选项。
 
附加上下文
 
Chatbox 和 Opencat 的对比：

**Comment by yeahqiao96** [comment]
![image](https://user-images.githubusercontent.com/93234012/229088662-45001d64-532f-49e7-b8e3-e2b8bf3222fa.png)
我还挺喜欢这个风格的~~是初期版本的吧~~

**Comment by Bin-Huang** [comment]
试试最新版本
