### ISSUE TITLE
[BUG]是不是不支持win7？安装不成功

### ISSUE THREAD

**Issue by yuyistar** [Bin-Huang/chatbox#201]
有办法解决吗。还是本身就不能支持win7
![微信截图_20230330152822](https://user-images.githubusercontent.com/14964575/228762771-29b79bbd-b7bb-41a0-87b0-b7da1c46299c.jpg)
![微信截图_20230330152920](https://user-images.githubusercontent.com/14964575/228762783-915a0298-2b6e-4279-8a2d-db1842341b71.jpg)

**Comment by smilechow9** [comment]
同样的问题，win7 64 装不了

**Comment by hbsx** [comment]
我的win764也安装报错

**Comment by Bin-Huang** [comment]
新版本已经兼容 Window7 了。
The new version is now compatible with Windows 7.

https://github.com/Bin-Huang/chatbox/releases
