### ISSUE TITLE
[BUG]can not bulid the program

### ISSUE THREAD

**Issue by EthanLinNabu** [Bin-Huang/chatbox#202]
**期望结果**
在windows 11 執行npm run build 可以執行

**实际结果**
顯示以下問題
---
> chatbox@0.0.1 build
> tauri build

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', src\interface\rust.rs:762:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by llllllllllx** [comment]
https://tauri.app/zh-cn/v1/guides/getting-started/prerequisites/
