### ISSUE TITLE
[BUG]在Ubuntu 18.04下无法正常启动

### ISSUE THREAD

**Issue by valaxkong** [Bin-Huang/chatbox#205]
**Bug 描述**
在Ubuntu 18.04下无法正常启动。

AppImage报错如下：
chatbox: error while loading shared libraries: libOpenGL.so.0: cannot open shared object file: No such file or directory

deb版本安装后运行无反应

**桌面端（请填写以下信息）：**
- 操作系统：Linux 18.04
- 应用程序版本：0.2.8

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复，试试最新版本
https://github.com/Bin-Huang/chatbox/releases
