### ISSUE TITLE
[BUG]API 请求失败：  Failed to fetch，这是什么问题呢？

### ISSUE THREAD

**Issue by qq11109071** [Bin-Huang/chatbox#207]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
一般是你的网络环境问题，是不是没有解决网络“问题”？
