### ISSUE TITLE
[BUG]黑夜模式，然后点击空白处（设置页面以外地方），软件就变成了白天模式

### ISSUE THREAD

**Issue by TANGMOQI** [Bin-Huang/chatbox#208]
![image](https://user-images.githubusercontent.com/88825169/228794730-4da46c61-eb9a-4ed1-873c-59acdf0cd633.png)
黑夜模式，然后点击空白处（设置页面以外地方），软件就变成了白天模式
![image](https://user-images.githubusercontent.com/88825169/228794955-5bf9a84d-5731-40f3-a90b-420524b2cfc6.png)

**Comment by Bin-Huang** [comment]
我最近也发现了这个问题，@shulandmimi 感兴趣修复一下吗？

**Comment by shulandmimi** [comment]
当然

可以分配给我

**Comment by rustyhu** [comment]
> ![image](https://user-images.githubusercontent.com/88825169/228794730-4da46c61-eb9a-4ed1-873c-59acdf0cd633.png) 黑夜模式，然后点击空白处（设置页面以外地方），软件就变成了白天模式 ![image](https://user-images.githubusercontent.com/88825169/228794955-5bf9a84d-5731-40f3-a90b-420524b2cfc6.png)

从0.2.1到0.2.7 碰到类似问题，我都是设置的时候点击取消变成白天模式（刚试了下点击设置页面以外地方就相当于取消并退出设置），点保存是正常的。
