### ISSUE TITLE
the ability to scroll through a chat while gpt is generating the code[Feature]

### ISSUE THREAD

**Issue by agmuntianu** [Bin-Huang/chatbox#210]
**Problem Description**
when gpt generates code block , I would like to immediately copy paste them , or inspect changes suggested, the autoscroll while GPT is giving and answer makes that impossible.

**Proposed Solution**
Add a setting checkbox to enable/disable autoscroll

**Additional Context**
The way ChatGPT does it , where if you scroll upwards the autoscroll gets turned off is also an option

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

Fixed

**Comment by agmuntianu** [comment]
Thank you !
