### ISSUE TITLE
[BUG]对一些简单问题可以回复，稍微复杂就会出现API 请求失败

### ISSUE THREAD

**Issue by ypwcharles** [Bin-Huang/chatbox#211]
**Bug 描述**
对一些简单问题可以回复，稍微复杂就会出现API 请求失败

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
发送hello、你好等一些简单问题可以正常回复，但是问稍微复杂一点的问题就会直接报错

**期望结果**
能够回复答案

**实际结果**
API 请求失败：

Error parsing item: {"id":"chatcmpl-************（api隐去了）
Error Details: SyntaxError: Unterminated string in JSON at position 40

API 请求失败：

Error parsing item: {"id":"chatcmpl-**************（api隐去了）","object":"chat.completion.chunk",.
Error Details: SyntaxError: Expected double-quoted property name in JSON at position 80

API 请求失败：

Error parsing item: data:.
Error Details: SyntaxError: Unexpected token 'd', "data:" is not valid JSON

**截图**
![image](https://user-images.githubusercontent.com/92324143/228826959-541552f2-b15b-4da3-801f-12f76b0aa501.png)

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 2.0.1]

**其他上下文**
使用了https://github.com/easychen/openai-api-proxy/blob/master/FUNC.md 这里的教程在腾讯云函数搭建了新加坡的反向代理

**Comment by kalufinnle** [comment]
> Error parsing item: {"id":"chatcmpl-**************（api隐去了）","object":"chat.completion.chunk",. Error Details: SyntaxError: Expected double-quoted property name in JSON at position 80
> 
> API 请求失败：
> 
> Error parsing item: data:. Error Details: SyntaxError: Unexpected token 'd', "data:" is not valid JSON

proposed fix: Verify that there are no extra or misplaced characters, such as "data:" in the JSON data.
For manually parsed JSON data, consider using a JSON validation tool to check for any syntax issues.

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复，试试最新版本
https://github.com/Bin-Huang/chatbox/releases
