### ISSUE TITLE
[BUG] Windows10安装不了

### ISSUE THREAD

**Issue by Mr-LiuDC** [Bin-Huang/chatbox#213]
**Bug 描述**
Windows 10 安装不了。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 下载的最新Windows版本程序。
2. 双击安装提示如图。

**截图**
![1680178553378](https://user-images.githubusercontent.com/18117854/228833472-299a68d6-27e8-416f-8cc6-f05f72bb74f9.png)

**桌面端（请填写以下信息）：**
- 操作系统：Windows10
- 应用程序版本：v0.2.8

**Comment by linzeyang** [comment]
Win10刚装的，没出现你的情况呀
Win10 家庭版 22H2

**Comment by boby2023zzb** [comment]
我的也可以正常运行呀！

**Comment by JIou1** [comment]
我的昨天晚上出现过这个问题 ，
 我把系统更新了之后今天下午安装可以正常使用

**Comment by FighterLuo** [comment]
要64位系统，32位不支持

**Comment by Mr-LiuDC** [comment]
我是 64 位 Windows 10 专业版，今天下载的最新 0.2.9 版还是有这个问题，我的另外一台电脑可以正常使用。
```
操作系统名称	Microsoft Windows 10 专业版
版本            10.0.19044 内部版本 19044
```
![1680321065796](https://user-images.githubusercontent.com/18117854/229264377-b384eaf9-dc56-4026-af9e-19aa872579b7.png)

**Comment by kalufinnle** [comment]
> 我是 64 位 Windows 10 专业版，今天下载的最新 0.2.9 版还是有这个问题，我的另外一台电脑可以正常使用。
> 
> ```
> 操作系统名称	Microsoft Windows 10 专业版
> 版本            10.0.19044 内部版本 19044
> ```
> 
> ![1680321065796](https://user-images.githubusercontent.com/18117854/229264377-b384eaf9-dc56-4026-af9e-19aa872579b7.png)

专业版会对自动对文件夹设置权限 (Microsoft Installer Registar msc Config), 解决方法:

以管理员身份运行安装程序：
右键点击安装程序文件，选择“以管理员身份运行”。这将确保安装程序具有访问系统文件夹和文件所需的权限。

检查文件夹权限：
确保试图安装Windows 10的文件夹具有正确的权限。要做到这一点：

a. 右键点击安装文件夹，选择“属性”。
b. 转到“安全”选项卡。
c. 确保“SYSTEM”用户、您的用户帐户和“管理员”对文件夹具有完全控制权限。如果没有，请点击“编辑”并授予必要的权限。

重新下载安装文件：
错误可能是由于安装文件损坏。从github release下载一份新的安装文件，然后再次尝试安装过程。

确保Windows安装程序服务正常运行：

a. 按Windows键 + R，输入“services.msc”并按Enter。
b. 在列表中找到“Windows安装程序”服务，右键单击它，然后选择“属性”。
c. 确保“启动类型”设置为“手动”，并且服务正在运行。如果没有运行，请点击“启动”运行该服务。

暂时禁用防病毒软件：
某些防病毒软件可能会干扰安装过程。尝试暂时禁用防病毒软件，然后再次尝试安装。完成安装后，重新启用防病毒软件。

执行clean-boot：
干净启动可确保没有第三方软件干扰安装过程。执行clean-boot的方法：

a. 按Windows键 + R，输入“msconfig”并按Enter。
b. 转到“服务”选项卡，选中“隐藏所有Microsoft服务”框，然后点击“全部禁用”。
c. 转到“启动”选项卡，点击“打开任务管理器”，禁用所有启动项，然后关闭任务管理器。
d. 在系统配置窗口中点击“确定”，然后重新启动计算机。

clean-boot启动后，尝试再次安装过程。如果安装成功，启用之前禁用的服务和启动项将系统恢复正常。

**Comment by Mr-LiuDC** [comment]
> > 我是 64 位 Windows 10 专业版，今天下载的最新 0.2.9 版还是有这个问题，我的另外一台电脑可以正常使用。
> > ```
> > 操作系统名称	Microsoft Windows 10 `**专业版**`
> > 版本            10.0.19044 内部版本 19044
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![1680321065796](https://user-images.githubusercontent.com/18117854/229264377-b384eaf9-dc56-4026-af9e-19aa872579b7.png)
> 
> 专业版会对自动对文件夹设置权限 (Microsoft Installer Registar msc Config), 导致无法顺利安装
> 
> @Mr-LiuDC
> 
> **-----------------------------------------_解决方法:_------------------------------------------------**
> 
> 以管理员身份运行安装程序： 右键点击安装程序文件，选择“以管理员身份运行”。这将确保安装程序具有访问系统文件夹和文件所需的权限。
> 
> 检查文件夹权限： 确保试图安装Windows 10的文件夹具有正确的权限。要做到这一点：
> 
> a. 右键点击安装文件夹，选择“属性”。 b. 转到“安全”选项卡。 c. 确保“SYSTEM”用户、您的用户帐户和“管理员”对文件夹具有完全控制权限。如果没有，请点击“编辑”并授予必要的权限。
> 
> 重新下载安装文件： 错误可能是由于安装文件损坏。从github release下载一份新的安装文件，然后再次尝试安装过程。
> 
> 确保Windows安装程序服务正常运行：
> 
> a. 按Windows键 + R，输入“services.msc”并按Enter。 b. 在列表中找到“Windows安装程序”服务，右键单击它，然后选择“属性”。 c. 确保“启动类型”设置为“手动”，并且服务正在运行。如果没有运行，请点击“启动”运行该服务。
> 
> 暂时禁用防病毒软件： 某些防病毒软件可能会干扰安装过程。尝试暂时禁用防病毒软件，然后再次尝试安装。完成安装后，重新启用防病毒软件。
> 
> 执行clean-boot： 可确保没有第三方软件干扰安装过程。执行clean-boot的方法：
> 
> a. 按Windows键 + R，输入“msconfig”并按Enter。 b. 转到“服务”选项卡，选中“隐藏所有Microsoft服务”框，然后点击“全部禁用”。 c. 转到“启动”选项卡，点击“打开任务管理器”，禁用所有启动项，然后关闭任务管理器。 d. 在系统配置窗口中点击“确定”，然后重新启动计算机。
> 
> clean-boot启动后，尝试再次安装过程。如果安装成功，启用之前禁用的服务和启动项将系统恢复正常。

总算搞定了，按照你的设置还是不行。Google了下，在系统盘的 `Windows` 目前创建了一个空的 `Installer` 目录就行了
