### ISSUE TITLE
[BUG] 不支持gpt-4模型

### ISSUE THREAD

**Issue by Luoshuiai** [Bin-Huang/chatbox#215]
![image](https://user-images.githubusercontent.com/57760243/228893284-d74c0205-506e-4e19-b940-6d308e06a4b6.png)
![image](https://user-images.githubusercontent.com/57760243/228893315-22be6372-635e-4e06-9c40-b65f408e22be.png)

账号API已经支持了gpt-4，但是选择模型后使用的依然是gpt-3.5

**Comment by mmsoon** [comment]
我发现新建一个对话就可以了。好像是把模型绑定到对话里去了

**Comment by wpy1533399** [comment]
确实不支持gpt4的模型,输入周敦颐的爱莲说,给的答案就是瞎写的

**Comment by SnailDove** [comment]
> ![image](https://user-images.githubusercontent.com/57760243/228893284-d74c0205-506e-4e19-b940-6d308e06a4b6.png) ![image](https://user-images.githubusercontent.com/57760243/228893315-22be6372-635e-4e06-9c40-b65f408e22be.png)
> 
> 账号API已经支持了gpt-4，但是选择模型后使用的依然是gpt-3.5

me too

**Comment by SnailDove** [comment]
> 我发现新建一个对话就可以了。好像是把**模型绑定到对话**里去了

## 但是新建对话框，依然出现错误
API Request Failed:
Copy Error from OpenAI: 404  
```json
{
    "error": {
        "message": "The model: `gpt-4` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
```

**Comment by okaypan** [comment]
遇到同样的问题，期待解决

**Comment by Peakara** [comment]
同上，not exist

**Comment by lin65505578** [comment]
同上，

**Comment by lananjiankang** [comment]
同上，账号API已经支持了gpt-4，但是选择模型后使用的依然是gpt-3.5，新建对话后出现错误，求chatbox接入chatgpt4方法。

**Comment by vvvictory98** [comment]
同上，{"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}

**Comment by Bin-Huang** [comment]
下载最新版本，已经修复

**Comment by Bin-Huang** [comment]
上面报错 `The model: gpt-4 does not exist ` 的是因为你们账户不支持 GPT4

**Comment by ChrisHsu6** [comment]
是的，之前誤會API都支援GPT4
後來才發現要要加入wait list排隊
拿到許可前都不支援GPT4
排隊網址
https://openai.com/waitlist/gpt-4-api
