### ISSUE TITLE
[BUG]Error from OpenAI: 429

### ISSUE THREAD

**Issue by h836921360** [Bin-Huang/chatbox#217]
Error from OpenAI: 429  {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
已填写API密钥但无法使用，模型选择3.5

**Comment by Bin-Huang** [comment]
你的OpenAI账户达到限制了，和chatbox没有关系
