### ISSUE TITLE
[BUG]每次打开版本号上都有这个蓝点，我理解不是有更新才会有这个么？

### ISSUE THREAD

**Issue by yeahqiao96** [Bin-Huang/chatbox#220]
![image](https://user-images.githubusercontent.com/93234012/229004734-8c9d53e8-6914-452f-99e4-b9f33452aafa.png)
每次打开版本号上都有这个蓝点，我理解不是有更新才会有这个么？
其他遇到的问题还有：
1、选择暗黑模式后，再次打开设置，直接点取消，会恢复到白天模式
我的系统是macos，另外希望增加的特性还有：
1、全局呼出快捷键
2、本地代理

**Comment by duofengzhiling** [comment]
我的win10系统，也出现了的这个问题，只要点了设置，之后，就会恢复到白天模式.

**Comment by Sheldontao** [comment]
+1

**Comment by Bin-Huang** [comment]
夜间主题的问题已经修复了，可以更新下
