### ISSUE TITLE
[BUG]重命名对话时只能输入英文，没法输入中文

### ISSUE THREAD

**Issue by Mr-LiuDC** [Bin-Huang/chatbox#221]
**Bug 描述**
将左侧对话Title重名时只能英文输入法进行英文输入，切换为中文输入法后没法输入中文，只能在其他地方写好中文后贴过来。
我也遇到某些网站也有这个问题。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 点击左侧对话，进行重命名
2. 可以输入英文内容
3. 不能输入中文内容

**截图**
如果可行，添加截图以帮助解释问题。
![Video_20230331103146](https://user-images.githubusercontent.com/18117854/229008586-532e36b2-39f2-4894-b539-07235111397d.gif)

**桌面端（请填写以下信息）：**
- 操作系统：Windows 10
- 应用程序版本：0.2.9

**Comment by Bin-Huang** [comment]
新版本已经修复了
