### ISSUE TITLE
可以新增流量代理的功能吗？[Feature]

### ISSUE THREAD

**Issue by jxxhwy** [Bin-Huang/chatbox#222]
可以新增流量代理的功能吗？目前的只是API的代理，哪怕是有个代理的多选列表也好

**Comment by duanluan** [comment]
![image](https://user-images.githubusercontent.com/14957667/229018943-986a66fa-1cd3-45c6-988b-68d4abb5f23e.png)

**Comment by Bin-Huang** [comment]
issues 重复了，这个关闭了。
#191
