### ISSUE TITLE
[BUG]Install on WIN7 is not supported

### ISSUE THREAD

**Issue by haifeng695** [Bin-Huang/chatbox#224]
**Bug Description**
Fail to install on WIN7.

**Steps to Reproduce**
Just install on WIN7.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统：[Windows 7 专业版 Service Pack 1]
- 应用程序版本：[chatbox 0.2.9]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

新版本已经兼容 Window7 了。
The new version is now compatible with Windows 7.
