### ISSUE TITLE
[Feature]建议增加"额度"显示，无需登录只需api_key即可查询，内见调用方式

### ISSUE THREAD

**Issue by yeahqiao96** [Bin-Huang/chatbox#225]
调用方式如下：

GET https://api.openai.com/dashboard/billing/credit_grants

request:
[header] k="Authorization" v="Bearer {{api_key}}"

response:
{
  "object": "credit_summary",
  "total_granted": 5.0,
  "total_used": 0.03,
  "total_available": 4.97,
  "grants": {
    "object": "list",
    "data": [
      {
        "object": "credit_grant",
        "id": "...",
        "grant_amount": 5.0,
        "used_amount": 0.03,
        "effective_at": 1680048000.0,
        "expires_at": 1688169600.0
      }
    ]
  }
}

**Comment by Bin-Huang** [comment]
很抱歉，因为要支持太多的模型，不是所有模型服务都提供类似接口，所以暂时没有这个计划
