### ISSUE TITLE
[Feature]希望增加阻止继续生成对话的功能

### ISSUE THREAD

**Issue by MrGongqi** [Bin-Huang/chatbox#228]
我了解到有的时候和chatgpt进行的对话并不是自己想要的，这个时候就想阻止chatbox继续输出对话，可以节省时间和节省token。就像chatgpt 网页上的“Prevent ..."功能

**Comment by hiNISAL** [comment]
#230

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

新版本已解决问题
