### ISSUE TITLE
功能建议：希望增加左侧chat列表移动功能，可以手动调整顺序

### ISSUE THREAD

**Issue by kangyiwen** [Bin-Huang/chatbox#23]
功能建议：希望增加左侧chat列表移动功能，可以手动调整顺序

![image](https://user-images.githubusercontent.com/76672577/224582188-2ad959f0-8999-4e9e-bbe1-fc7f77c1e2a7.png)

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/issues/15

感谢反馈，和其他 issues 重复了，我先关闭了哈。在这个 issues 中讨论这个功能。
