### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by backendcloud** [Bin-Huang/chatbox#232]
![image](https://user-images.githubusercontent.com/15382060/229086858-a88195eb-1634-4c09-89f8-8f890f880b82.png)

markdown格式的表格显示不了线条

官方web界面显示如下
![image](https://user-images.githubusercontent.com/15382060/229087230-15be3b7b-f323-4f5c-803e-df7a886607cd.png)

**Comment by 656696888** [comment]
大佬，请问我的为什么总是提示失败，请求失败，开了全局，该怎么解决，是api格式不对么
API 请求失败：

复制
Error from OpenAI: 401  {
    "error": {
        "message": "Incorrect API key provided: sk-1PyDr***************************************jQjK. You can find your API key at https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}

**Comment by Bin-Huang** [comment]
@656696888 这个是账户问题，和软件没有关系。你可以试试最新版本内置的AI服务，开箱即用的
