### ISSUE TITLE
[Feature] 希望增加绿色免安装版本

### ISSUE THREAD

**Issue by xuanyuanaosheng** [Bin-Huang/chatbox#233]
**问题描述**
笔记本没有admin权限，希望提供免安装版本

**Comment by WuDi-ZhanShen** [comment]
> **问题描述** 笔记本没有admin权限，希望提供免安装版本

可以将msi文件解压，解压后会得到一个exe单文件，这个就是和安装之后得到的exe单文件完全一样的，直接运行即可

**Comment by chenshaoju** [comment]
0.6.1 版本开始已经没有 .msi 安装包了。

不知道是否能考虑一下绿色/Portable版？

**Comment by WuDi-ZhanShen** [comment]
> 0.6.1 版本开始已经没有 .msi 安装包了。
> 
> 不知道是否能考虑一下绿色/Portable版？

我记得果核剥壳里有绿色版chatbox，更新的还挺快的，可以去试试

**Comment by chenshaoju** [comment]
研究了一下新版的安装包，搞清楚了，以下是操作步骤，方便后人：

1.用解压软件打开下载回来的 .exe 安装包，将 `$PLUGINSDIR\app-64.7z\` 压缩包/目录中的全部内容解压到期望的路径中。
![image](https://github.com/Bin-Huang/chatbox/assets/515763/b00fd3d6-9308-4896-98ad-7e7643566ecf)

2.进入解压的目录，找到 Chatbox.exe ，右击，创建快捷方式，然后在“目标”结尾增加 ` --user-data-dir=.\userdata` ，.exe 和 - 号之间有个英文半角空格。
![image](https://github.com/Bin-Huang/chatbox/assets/515763/ee1f8779-8365-4390-96ea-2f1997888ed7)

3.若需要导入旧版数据，先执行一次 Chatbox.exe （若旧版本小于 0.6.1，注意：不是创建的快捷方式），然后退出，再进入 C:\Users\<当前Windows用户名>\AppData\Roaming\xyz.chatboxapp.app\ ，将里面的东西复制到 chatbox.exe 所在目录下的 userdata 目录中，若没有该目录，手动新建即可。
![image](https://github.com/Bin-Huang/chatbox/assets/515763/2c787d01-ed72-4b80-b546-3bb0bc285b86)


4.双击创建的 Chatbox 快捷方式即可。

5.若在盘符或路径会变化的环境中，创建一个批处理并执行即可 `Chatbox.exe --user-data-dir=.\userdata` ：
![image](https://github.com/Bin-Huang/chatbox/assets/515763/2165de54-4413-4c1d-8915-164fd6f98880)

**Comment by WuDi-ZhanShen** [comment]
非常好工作，爱来自瓷器

> 研究了一下新版的安装包，搞清楚了，以下是操作步骤，方便后人：
> 
> 1.用解压软件打开下载回来的 .exe 安装包，将 `$PLUGINSDIR\app-64.7z\` 压缩包/目录中的全部内容解压到期望的路径中。 ![image](https://user-images.githubusercontent.com/515763/252243644-b00fd3d6-9308-4896-98ad-7e7643566ecf.png)
> 
> 2.进入解压的目录，找到 Chatbox.exe ，右击，创建快捷方式，然后在“目标”结尾增加 ` --user-data-dir=.\userdata` ，.exe 和 - 号之间有个英文半角空格。 ![image](https://user-images.githubusercontent.com/515763/252240664-ee1f8779-8365-4390-96ea-2f1997888ed7.png)
> 
> 3.若需要导入旧版数据，先执行一次 Chatbox.exe （若旧版本小于 0.6.1，注意：不是创建的快捷方式），然后退出，再进入 `C:\Users\<当前Windows用户名>\AppData\Roaming\xyz.chatboxapp.app\` ，将里面的东西复制到 chatbox.exe 所在目录下的 userdata 目录中，若没有该目录，手动新建即可。 ![image](https://user-images.githubusercontent.com/515763/252243120-2c787d01-ed72-4b80-b546-3bb0bc285b86.png)
> 
> 4.双击创建的 Chatbox 快捷方式即可。
> 
> 5.若在盘符或路径会变化的环境中，创建一个批处理并执行即可 `Chatbox.exe --user-data-dir=.\userdata` ： ![image](https://user-images.githubusercontent.com/515763/252242078-2165de54-4413-4c1d-8915-164fd6f98880.png)

非常好工作，爱来自瓷器！

**Comment by Bin-Huang** [comment]
> **问题描述** 笔记本没有admin权限，希望提供免安装版本

@xuanyuanaosheng 0.6.1 后安装不需要 admin 权限了。

**Comment by Bin-Huang** [comment]
❤️️很棒的分享 @chenshaoju

**Comment by leo4stone** [comment]
![image](https://github.com/Bin-Huang/chatbox/assets/10969261/db85e44d-78e7-4e6b-b0ec-f9491c3acd13)
解压后直接运行exe会报错。😮‍💨

**Comment by chenshaoju** [comment]
@leo4stone 安装程序解压后，在 `$PLUGINSDIR` 目录里有两个压缩包，一个是 app-64.7z ，一个是是 app-arm64.7z ，如果你解压了错误的压缩包，就会遇到这个问题。
