### ISSUE TITLE
能否增加一个停止回复的按钮

### ISSUE THREAD

**Issue by peteisacat** [Bin-Huang/chatbox#239]
当chatgpt正在回复我时，如果回复内容过长，我希望能有一个按钮，点击后chatgpt停止回复我，这样我就可以继续进行输入对话，不用等待。

我看到在chat.openai.com网页上是有这个停止按钮的。

请问，本软件可以加吗？谢谢！

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

新版本已解决问题
