### ISSUE TITLE
功能建议：点开对话内连接，在本窗口打开没法返回，希望用默认浏览器打开

### ISSUE THREAD

**Issue by kangyiwen** [Bin-Huang/chatbox#24]
点开对话内连接，在本窗口打开没法返回，希望用默认浏览器打开

![image](https://user-images.githubusercontent.com/76672577/224582462-56c766b4-cec0-4007-9e74-4112bf08adf3.png)

**Comment by Bin-Huang** [comment]
忘记说了，最新版本已经修复了。
