### ISSUE TITLE
[Other]

### ISSUE THREAD

**Issue by HKZ773999** [Bin-Huang/chatbox#245]
能不能支持下对应的代码高亮，现在全是文本，看不清代码。

**Comment by hiNISAL** [comment]
代码高亮是支持的，如果没出现高亮，基本上原因是接口响应的内容虽然是代码，但是没有标记代码块（markdown ```）。

**Comment by HKZ773999** [comment]
@hiNISAL 我用 C语音 Java 都会代码高亮，但是 iOS OC 语言没有代码高亮

**Comment by Bin-Huang** [comment]
你让 AI 用 markdown 格式回复你，然后就能看到代码高亮。
