### ISSUE TITLE
求：建个微信群

### ISSUE THREAD

**Issue by kangyiwen** [Bin-Huang/chatbox#25]
[Bin-Huang](https://github.com/Bin-Huang)，希望多多交流，求建个微信群

**Comment by bernardatgh** [comment]
建好了吗 能分享下群吗 谢谢

**Comment by hbsx** [comment]
TG更好

**Comment by Bin-Huang** [comment]
I feel like this issue is a bit outdated, so I went ahead and closed it. But if you think it's necessary, feel free to create a new issue at any time.
