### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 1zhiye** [Bin-Huang/chatbox#250]
在上一次回答未完成时，再次输入问题会出现屏幕闪动。
具体内容是，每次软件都会自动定位到chatgpt最新生成的文字位置，这样会导致：
1.多次输入复杂问题，回答内容长，导致聊天界面在多个回答之间反复切换
2.还是回答内容长，不能自己调整聊天界面位置，每次有新的文字生成会自动跳转界面到最新的位置，以至于在当前屏幕不能完全显示这个回答内容时，必须得等到内容生成完才能从头阅读。

**Comment by hiNISAL** [comment]
#230 
该Feature中修复，等待REVIEW

**Comment by Bin-Huang** [comment]
最新版本已修复
