### ISSUE TITLE
[BUG]怎么在Windows上编译？

### ISSUE THREAD

**Issue by Mr-LiuDC** [Bin-Huang/chatbox#253]
**Bug 描述**
自己打算试着实现代理的功能，在 Windows10 上编译不成功，希望对于 Windows 系统下的开发编译给个简要文档。。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. yarn install 后执行编译
```
User shell undefined not supported, skipping completion install
✔ Checking your system
✖ Resolving Forge Config

Electron forge was terminated:                                        
You must depend on "electron-prebuilt-compile" in your devDependencies
```
2. 安装 `electron-prebuilt-compile` 后执行编译
```
$ ./make.sh
User shell undefined not supported, skipping completion install
✔ Checking your system
✖ Resolving Forge Config

Electron forge was terminated:
You must depend on an EXACT version of "electron-prebuilt-compile" not a range (got "^8.2.0")
```
3. 固定 `electron-prebuilt-compile` 版本后编译
```
$ ./make.sh
User shell undefined not supported, skipping completion install
✔ Checking your system
✖ Resolving Forge Config

Electron forge was terminated:
Failed to locate makeable Electron application
```

**Comment by GYingx** [comment]
我也遇到这个无法编译的问题了。。。。。

**Comment by captain-miao** [comment]
Windows 可以借助 GitHub Action 编译，我改了可以填写自定义 URL 的版本：[Chatbox-v0.4.0](https://github.com/captain-miao/chatbox/releases/tag/Chatbox-v0.4.0)

**Comment by shawhu** [comment]
这个东西是react加上tauri
package.json里面有dependency的描述。
基本上就是先去把tauri和react（或者nextjs）先搞搞清楚，自己创建一个并且npm run dev能跑出来。证明环境没问题。

然后就可以照类似的办法跑这个了
npm install
npm run dev   可以跑出来
npm run build  可以build成exe

如果提示有少包，少那个自己装下就好了

编译时候注意要有自己的key，否则tauri签名会失败，整个过程没有问题。他的repo相当完美，毫无编译错误
