### ISSUE TITLE
win7安装失败

### ISSUE THREAD

**Issue by showna** [Bin-Huang/chatbox#254]
![chatbox](https://user-images.githubusercontent.com/11702403/229330411-46aca2ab-9ffa-4544-9da3-289347a97978.JPG)

**Comment by linux121** [comment]
一样win7失败

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

新版本已经兼容 Window7 了。
The new version is now compatible with Windows 7.
