### ISSUE TITLE
account deactivated

### ISSUE THREAD

**Issue by jingyong2016** [Bin-Huang/chatbox#257]
大家注意了，不是针对博主，是最近open封号了，我昨晚用的box，今天账号就被停用了。上推看了一下，很多使用别的项目的人一样被封号，最近还是少用api吧

**Comment by dongdongmao** [comment]
Chatbox可能需要添加代理功能

**Comment by jingyong2016** [comment]
嗯嗯，辛苦作者，box真得很好用，现在只能再吃一段原网页的苦了


| |
jingyongzhu2016
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 4/2/2023 14:56 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Bin-Huang/chatbox] account deactivated (Issue #257) |

Chatbox可能需要添加代理功能

**Comment by Bin-Huang** [comment]
不是封号哦。API 是一种云服务，如果你是官方注册的 API 账户，同时绑定了信用卡，访问 IP 是美国的话，就不会遇到这个问题。现在是 OpenAI 在清理黑产、薅羊毛账户。
