### ISSUE TITLE
[Feature]建议添加窗口大小位置记忆功能。

### ISSUE THREAD

**Issue by 1353604736** [Bin-Huang/chatbox#258]
**问题描述**
问答聊天界面尽可能可以看的更广，且想要窗口化，方便快速切换其他窗口的需求

**解决思路**
单选框，记忆上次窗口位置和长宽

**附加上下文**
勾选后关闭软件，重新打开后还是上次的位置和大小

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/v1.0.4
