### ISSUE TITLE
增加一个代理选项如何

### ISSUE THREAD

**Issue by pyjhhh** [Bin-Huang/chatbox#259]
增加一个代理选项如何，建议增加一个代理设置界面，方便软件单独走独立代理

**Comment by xiefeihong** [comment]
对，在linux中可以设置tun模式的代理软件太少了

**Comment by xiefeihong** [comment]
对，在linux中可以设置tun模式的代理软件太少了，并且设置了tun之后所有流量都走代理，其他程序都被强制走代理，会带来很多问题

**Comment by RockTraveler** [comment]
is possible to  support HTTP proxy?

**Comment by Bin-Huang** [comment]
#13

**Comment by ZhuYichuan** [comment]
可以用使用 Proxifier 来进行app 流量的代理
参考youtube  [视频地址](https://www.youtube.com/watch?v=ZPi56hSm__E)
