### ISSUE TITLE
The issue is related to interface optimization.

### ISSUE THREAD

**Issue by unreal-alex** [Bin-Huang/chatbox#261]
The use of deep blue links on a black interface can make it difficult to read the text. It is hoped that adjustments can be made to improve the visibility.
![b56f14934c85d64aedd0d4ad072b67e](https://user-images.githubusercontent.com/69709300/229360083-bb98b152-c38a-4c70-bd71-79a0ec8cb8ae.png)

**Comment by Bin-Huang** [comment]
This issue has already been resolved in previous versions, so you might want to try upgrading to see if it's fixed.
