### ISSUE TITLE
[BUG]  在linux客户端中提问长问题会报错

### ISSUE THREAD

**Issue by xiefeihong** [Bin-Huang/chatbox#264]
### 输入较长的问题，回复信息较长的情况下会出现错误代码：
以下是两个回复示例：

```
Error parsing item: {"id":"chatcmpl-70tTLQuZKu3bvFpAU5fp87JgkWomE","object":"chat.completion.chunk","created":1680447591,"model":"gpt-3.5-.
Error Details: SyntaxError: JSON Parse error: Unterminated string
```

```
Error parsing item: {"id":"chatcmpl-70sOkAJKhgMx9CEcvcNVniigSikWw","object":"chat.completion.chunk","created":1680443462,"model":"gpt-3.5-.
Error Details: SyntaxError: JSON Parse error: Unterminated string
```

软件版本：chatbox_0.2.9_amd64.AppImage
系统类型：Linux
系统架构：x86_64
内核版本：6.2.9-300.fc38.x86_64
系统版本：Fedora 38 (Cinnamon 5.6.8)

**Comment by xiefeihong** [comment]
长问题稳定报错，输入“hi”或者“你好”不会报错

**Comment by xiefeihong** [comment]
> ### 输入较长的问题，回复信息较长的情况下会出现错误代码：
> 以下是两个回复示例：
> 
> ```
> 分析项目时出错：{“id”：“chatcmpl-70tTLQuZKu3bvFpAU5fp87JgkWomE”，“object”：“chat.completion.chunk”，“created”：1680447591，“model”：“gpt-3.5-.
> 错误详情：语法错误：JSON解析错误：未终止的字符串
> ```
> 
> ```
> 分析项目时出错：{“id”：“chatcmpl-70sOkAJKhgMx9CEcvcNVniigSikWw”，“object”：“chat.completion.chunk”，“created”：1680443462，“model”：“gpt-3.5-.
> 错误详情：语法错误：JSON解析错误：未终止的字符串
> ```
> 
> 软件版本：chatbox_0.2.9_amd64.AppImage 系统类型：Linux 系统架构：x86_64 内核版本：6.2.9-300.fc38.x86_64 系统版本：Fedora 38 (Cinnamon 5.6.8)

长问题稳定报错，输入“hi”或者“你好”不会报错

**Comment by Moriarty1024** [comment]
我也是这样

**Comment by ypwcharles** [comment]
我也是这样，不过是windows环境，你有用反向代理吗

**Comment by xiefeihong** [comment]
> 我也是这样，不过是windows环境，你有用反向代理吗

有使用代理，不代理的话是完全用不了的

**Comment by Bin-Huang** [comment]
这种问题一般都是和代理有关。代理服务器的不佳实现会导致这个问题。以前也有一条 issues 讨论过这个问题，并且有人给出了代理服务器的配置信息，可以搜索参考下。

**Comment by lidaobing** [comment]
@Bin-Huang 能提供一下之前issue的链接么？

另外，opencat 这类软件没有这个问题

**Comment by ypwcharles** [comment]
> @Bin-Huang 能提供一下之前issue的链接么？
> 
> 另外，opencat 这类软件没有这个问题

我之前用的是腾讯云函数来代理，这样的代理方式对于chatbox来说，好像就是没有办法很好的工作。
所以我今天在vultr上新买了个vps来专门做代理，用了自己的域名加上ssl证书指向vps
然后就一切正常了
参考链接：
https://mailberry.com.cn/2023/03/proxy-pass-openai-api-allowing-direct-usage-of-chatgpt-in-china/
https://mailberry.com.cn/2023/04/solve-chatgpt-api-502-bad-gateway-issue/
https://crazystar.net/2023/03/05/how-to-use-nginx-proxy-openai-with-eventsource/
