### ISSUE TITLE
[BUG] 主界面左下角的版本号右上角有一个蓝色的点

### ISSUE THREAD

**Issue by xiefeihong** [Bin-Huang/chatbox#265]
主界面左下角的版本号右上角会有一个蓝色的点，看起来像是版本更新的提示，点一下就没有了，每次重启软件都会再次显示

**Comment by yeahqiao96** [comment]
我也遇到了同样的问题，看起来应该是判断是否有新版本的逻辑上存在问题导致，虽然不影响使用，但错误的提醒还是会让人不舒服

**Comment by yeahqiao96** [comment]
我也遇到了同样的问题，看起来应该是判断是否有新版本的逻辑上存在问题导致，虽然不影响使用，但错误的提醒还是会让人产生了稍许困扰，总想点一下来消除它

**Comment by magicdmer** [comment]
这个的确是个bug，没法通过这个判断到底有没有新版本

**Comment by mikoli524** [comment]
已经下载了最新的0.3.0版本，依然会显示，有点难受。

**Comment by Bin-Huang** [comment]
之前的版本已经解决了，可以更新一下，先关闭了这条 issues 了。
