### ISSUE TITLE
wind 7 安装失败！

### ISSUE THREAD

**Issue by yuanqi99** [Bin-Huang/chatbox#266]
There is a problem with this Windows Installer package .A program run as part of the setup did not finish asexpected. Contact your support personnel or packagevendor.

**Comment by Ga00look** [comment]
我的也是

**Comment by Bin-Huang** [comment]
新版本已经兼容 Window7 了。
The new version is now compatible with Windows 7.

https://github.com/Bin-Huang/chatbox/releases
