### ISSUE TITLE
[BUG]API请求失败

### ISSUE THREAD

**Issue by 181670198** [Bin-Huang/chatbox#267]
**Bug Description**
Error from OpenAI: 429  {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

API确认没有错误，没有过期。
网络全局翻墙，可以访问openai官网

![屏幕截图 2023-04-03 105116](https://user-images.githubusercontent.com/55872132/229400859-75ecbac3-46fb-4072-9787-03893b4ab461.png)

**Comment by Bin-Huang** [comment]
重复issues。是你账户的问题。没有绑卡，没有余额。

#145

**Comment by Bin-Huang** [comment]
这个问题是因为 OpenAI 近期开始清理免费 API 账户，所有没有绑卡、没有余额的账户都会出现这种情况。注意，即使你是 ChatGPT Plus 用户，只要没有给 API 账户绑卡，一样会出现同样的问题！

这种 issues 已经重复回答五六次了，请大家提前搜索、不要重复提类似的 issues。
