### ISSUE TITLE
不支持 gpt plus 吗

### ISSUE THREAD

**Issue by djkcyl** [Bin-Huang/chatbox#27]
感觉用量大的话 api 性价比太低了，plus 的定价策略就很合适，想问问有没有支持 plus 的计划

**Comment by Bin-Huang** [comment]
好奇你是怎么使用的？只是有点好奇量为什么可以这么大……

**Comment by djkcyl** [comment]
写公文之类的，都是大段大段的文本

**Comment by Bin-Huang** [comment]
暂时没有支持的计划哈～
