### ISSUE TITLE
作者有没有想法写个手机端的

### ISSUE THREAD

**Issue by 18230** [Bin-Huang/chatbox#271]
作者有没有想法写个手机端的

**Comment by leonlincc** [comment]
支持这个想法，有个手机端确实会更加方便。

**Comment by tuzixiansheng** [comment]
我觉得这个想法很好，希望作者早日可以出手机端，花钱那我也愿意下载。

**Comment by cvbnt** [comment]
iOS有OpenCat，Android有ChatBoost，当然我还是非常支持作者搞个三端同步的

**Comment by a8840803** [comment]
> 

ChatBoost在哪里下载

**Comment by tuzixiansheng** [comment]
> > 
> 
> ChatBoost在哪里下载

+1

**Comment by cvbnt** [comment]
> > 
> 
> ChatBoost在哪里下载

Google Play上有

**Comment by nufeng1999** [comment]
![Screenshot_2023-04-18-01-56-40-95.jpg](https://user-images.githubusercontent.com/28748029/232570947-063ab8da-5303-4e7f-9782-a1637386655e.jpg)

chatbox的一个分支移植
https://github.com/nufeng1999/chatai

**Comment by tuzixiansheng** [comment]
> ![Screenshot_2023-04-18-01-56-40-95.jpg](https://user-images.githubusercontent.com/28748029/232570947-063ab8da-5303-4e7f-9782-a1637386655e.jpg)
> 
> chatbox的一个分支移植 https://github.com/nufeng1999/chatai

链接打不开

**Comment by nufeng1999** [comment]
> > ![Screenshot_2023-04-18-01-56-40-95.jpg](https://user-images.githubusercontent.com/28748029/232570947-063ab8da-5303-4e7f-9782-a1637386655e.jpg)
> > 
> > chatbox的一个分支移植 https://github.com/nufeng1999/chatai
> 
> 链接打不开
> 

https://github.com/nufeng2000/chatai

**Comment by cloudZQY** [comment]
> iOS有OpenCat，Android有ChatBoost，当然我还是非常支持作者搞个三端同步的

Opencat要是能自由编辑就好了，他的这个计费的功能确实好用

**Comment by Bin-Huang** [comment]
Chatbox 官方的网页版本 https://web.chatboxapp.xyz/ 已经兼容手机浏览器了。可以先用用看看。

建议不要使用第三方网页版本，可能会出现 API KEY 盗取的安全问题。
