### ISSUE TITLE
[Feature]更好的阅读使用体验需求。

### ISSUE THREAD

**Issue by leonlincc** [Bin-Huang/chatbox#274]
**问题描述**
我有在一些小屏幕的设备上使用这个程序，因为屏幕分辨率比较小，那么左边的话题列表看起来就占用太多，让我右边的对话比较少。

**解决思路**
左边的话题提供一个话题缩进的功能，当前聊天列表的字体大小可以自己选择。

**Comment by Bin-Huang** [comment]
很早之前的版本已经实现字体大小调节了，可以更新一下，先关闭了这条 issues 了。
