### ISSUE TITLE
图片不能显示[BUG]

### ISSUE THREAD

**Issue by KingJadeLight** [Bin-Huang/chatbox#277]
**Bug 描述**
有时候回复会说有图片，但是图片不能显示。有两种情况，如下图所示。

**截图**
<img width="184" alt="image" src="https://user-images.githubusercontent.com/106169959/229593121-bb5b4db3-4c34-4006-a425-2c5769ca11aa.png">
<img width="179" alt="image" src="https://user-images.githubusercontent.com/106169959/229593212-0f86314d-19bd-4854-a983-c7b1e04d2832.png">

**桌面端**
- 操作系统：macOS
- 应用程序版本：0.2.9

**Comment by Bin-Huang** [comment]
一般是因为图片链接不存在。AI 很多时候并不能回复正确的图片链接。你可以通过下面的步骤排查：点击消息右边的悬浮菜单，点击编辑按钮，你可以在原始文本中看到图片链接，然后用浏览器访问链接查看图片是否存在。
