### ISSUE TITLE
功能改进建议：停止按钮相关

### ISSUE THREAD

**Issue by 1353604736** [Bin-Huang/chatbox#279]
**问题描述**
停止回复按钮在窗口左右较窄时会跟随chatgpt动态输出上移频繁，导致可能会点不到的情况

**解决思路**
建议改成静止的：移动到发送并排一起，且只在机器人回复时显示停止按钮

**Comment by Bin-Huang** [comment]
目前就是机器人回复时显示停止按钮。UI 上暂时不考虑和发送放一起
