### ISSUE TITLE
无法定位程序输入点 GetPackageFamilyName 于动态链接库  KERNEL32.dll

### ISSUE THREAD

**Issue by xzxz520cs** [Bin-Huang/chatbox#28]
Win7的问题吗？

**Comment by Bin-Huang** [comment]
很有可能。我还没有测试过这么老的版本，还有其他 window7 用户遇到这种问题吗？

**Comment by surferbig** [comment]
我也是WIN7 看可能是WIN7的问题

**Comment by WANGUYANG** [comment]
程序无法找到入口 无法定位程序输入点GetCurrentThread于动态链接库api-ms-win-core-processthreads-l1-1-1.dll上，win7

**Comment by Bin-Huang** [comment]
新版本已经兼容 Window7 了。
The new version is now compatible with Windows 7.

https://github.com/Bin-Huang/chatbox/releases
