### ISSUE TITLE
[Other]0.2.9版本后就出现Chrome下载告警，是做了什么改动么？

### ISSUE THREAD

**Issue by anniextra** [Bin-Huang/chatbox#280]
0.2.9版本之后，下载安装文件后就被Chrome告警，我尝试了Edge一样也告警，认为安装软件不安全。期间是做了什么功能改动么？

**Comment by Bin-Huang** [comment]
猜测是 Window 系统。只是用户体验的BUG修复，没有做其他改动。安全识别的规则我不了解，不过一般没有证书的开源软件都会出现类似的提示。如果你觉得不安全，可以阅读源码，源码才是安全最强大的保障。
