### ISSUE TITLE
[BUG]3.5模型经常会失忆？

### ISSUE THREAD

**Issue by leonlincc** [Bin-Huang/chatbox#281]
不知道是不是模型的问题还是什么别的问题，我在一个话题列表里面跟她聊，聊着聊着她就忘了上面跟他聊的内容了，目前不知道是哪方面的问题。求教！

**Comment by Mercury-GM** [comment]
这个涉及到GPT的context等内容，简单说就是上下文的token长度限制。
gpt-3.5-turbo的长度是4096个token，每个token对应不同的文本字符消耗（举个简单但并不准确的例子，比如简体中文汉字是每2个token/1个汉字，英文字符是每1个token/1个英文字符）。
文本长度超出这个限制之后，模型开始逐渐丢失先前的一部分内容，这个是OpenAI目前的模型的特点，并不是Bug，因为涉及到成本和计算量等等原因。
如果你想要更长的token模型，可以去官网填写GPT4 API的waitlist申请（不过目前GPT4 API也应该只开放了8K版本 32K版本还没开放）。

**Comment by Mercury-GM** [comment]
Github上有很多项目会用一些特殊的方式以软性地突破token限制，你可以看看。

**Comment by Bin-Huang** [comment]
上面说的很详细。其实每个模型能记住的上下文都有限。
