### ISSUE TITLE
[Feature]希望增加一个不联系上下文的功能（节能模式），可以主动开启

### ISSUE THREAD

**Issue by yangsk23** [Bin-Huang/chatbox#282]
**问题描述**
gpt4的api太贵了，会话数多的时候，能达到一次3-5ktoken，属实用不起，虽然能限制上下文中的最大 Token 数，但是如果问题描述过长就会提示报错

**Comment by Bin-Huang** [comment]
将 Max Message Count in Context / 上下文的消息数量上限 调至最低即可
