### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by fightlord** [Bin-Huang/chatbox#283]
win10系统，安装0.3.0或以前版本成功后，点击运行，出现“不兼容”提示
<img width="464" alt="捕获" src="https://user-images.githubusercontent.com/33091263/229669769-9214dcb2-85e4-4989-bcda-6d1086908c0c.PNG">

**Comment by Bin-Huang** [comment]
试试超级管理员权限运行

**Comment by Bin-Huang** [comment]
I feel like this issue is a bit outdated, so I went ahead and closed it. But if you think it's necessary, feel free to create a new issue at any time.
