### ISSUE TITLE
[Feature]Add  HTTP or SOCKS proxies

### ISSUE THREAD

**Issue by killinitzero** [Bin-Huang/chatbox#284]
Problem Description
I am using the ChatBox Git project for development, but I am unable to use it when connected to a network with a firewall or restricted internet access. This is because the ChatBox tool does not currently support HTTP or SOCKS proxies, which are necessary for accessing the internet in these types of network environments.

Proposed Solution
I would like to request that the ChatBox Git project add functionality for HTTP and SOCKS proxies. This would allow users to connect to the internet through a proxy server, bypassing the restrictions of the network they are on. This would greatly improve the accessibility and flexibility of the ChatBox tool.

Additional Context
As a developer, I often work in environments with restricted internet access, which makes it difficult for me to use the ChatBox tool. Adding support for HTTP and SOCKS proxies would make it possible for me to use the tool in these environments, increasing my productivity and making my work easier. Thank you for considering my request.

**Comment by chenshaxiong** [comment]
近期使用"轻松访问"时, 还需要配置代理服务器, 否则会产生网络错误,

**Comment by Bin-Huang** [comment]
Try upgrade it

**Comment by AZ777xx** [comment]
Are proxies with authentication supported?
