### ISSUE TITLE
API 请求失败

### ISSUE THREAD

**Issue by wuyz000** [Bin-Huang/chatbox#289]
**Bug Description**
API 请求失败：

Error from OpenAI: 400  {
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 4530 tokens (2482 in the messages, 2048 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
when send message, often shown

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
<img width="715" alt="image" src="https://user-images.githubusercontent.com/89956132/229703081-56860471-c219-4951-8ba0-b377a4d44f73.png">

**Desktop (please complete the following information):**
- Operating System: macOS
- Application Version: 12.6.3

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by fscarmen** [comment]
我也是同样的问题，mac 0.3.0 版本，之前是可以正常的。

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/62703343/229727899-f4bfe2de-cdc3-43ab-bddb-0371c6e0d718.png">

**Comment by fscarmen** [comment]
> 你们都不是同一个问题……好吧，也算是同一个问题了。你们是不是修改了设置用的 model&token 部分，重置回去吧。对于这些专业设置，建议不要随便修改。

我重置回去，仍然不行哦

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/62703343/229778502-8109b024-ff84-478d-ac42-208fafb791df.png">

**Comment by 2h0000** [comment]
> 你们都不是同一个问题……好吧，也算是同一个问题了。你们是不是修改了设置用的 model&token 部分，重置回去吧。对于这些专业设置，建议不要随便修改。

这个上下文超出限制是不是没有办法的，不能问答案太长的问题吗
截图：
![QQ图片20230405082236](https://user-images.githubusercontent.com/125747262/229950861-e44d1105-a9c6-495b-b8c9-08176c35dc3e.png)
![213](https://user-images.githubusercontent.com/125747262/229951022-fe3c510a-fc1f-4f0b-bccd-2ce4bc87597b.png)
