### ISSUE TITLE
Android  客户端？

### ISSUE THREAD

**Issue by LifeNT** [Bin-Huang/chatbox#29]
能否移植到安卓？

**Comment by Bin-Huang** [comment]
考虑中

**Comment by asaketsu** [comment]
JUST DO IT

**Comment by LifeNT** [comment]
chatbox是目前我使用的所有调用API的客户端里面最流畅的，希望能尽快移植安卓。

**Comment by Bin-Huang** [comment]
如果要做移动客户端的话，可以实现全设备的历史消息和prompt同步，确实也是有价值的。有人对这个感兴趣吗？

**Comment by LifeNT** [comment]
数据才是最宝贵的，现在大家更多的出于尝试的心态在使用chatgpt，但从长远看，如何保存、备份、交换聊天记录会是第三方软件的主要竞争点，请参考我提的另一个需求：输出聊天报告功能。
如果能以一定标准导出聊天记录将是非常好的帮助，毕竟越往后，大家都要花钱使用chatgpt了。
另外，如果能以某种标准格式备份聊天记录，在不同软件间共享数据也是非常有用的。

**Comment by ironald** [comment]
> 如果要做移动客户端的话，可以实现全设备的历史消息和prompt同步，确实也是有价值的。有人对这个感兴趣吗？

非常有，有这个打算吗需要多久

**Comment by bravekingzhang** [comment]
https://github.com/bravekingzhang/flutter_chat_box
我写了一个 flutter版本的，支持桌面版本，移动端，做了些简单的适配，一起来维护呀！

**Comment by nufeng1999** [comment]
> 能否移植到安卓？

![Screenshot_2023-04-18-01-56-40-95.jpg](https://user-images.githubusercontent.com/28748029/232570947-063ab8da-5303-4e7f-9782-a1637386655e.jpg)

**Comment by Bin-Huang** [comment]
官方版本，即将到来

**Comment by wang-keyan** [comment]
> 官方版本，即将到来

移动端官方版本出来了吗？期待

**Comment by nagasun** [comment]
> 可以先用移动端的网页版本 https://web.chatboxai.app/

这个版本数据是存在哪里的？

**Comment by Bin-Huang** [comment]
> > 可以先用移动端的网页版本 https://web.chatboxai.app/
> 
> 这个版本数据是存在哪里的？

浏览器本地

**Comment by Bin-Huang** [comment]
安卓版本已经在内测了，可以在这里了解进度：
https://github.com/Bin-Huang/chatbox/issues/686

**Comment by lovitus** [comment]
> 如果要做移动客户端的话，可以实现全设备的历史消息和prompt同步，确实也是有价值的。有人对这个感兴趣吗？

等了快一年了, 作者还考虑webdav吗?
