### ISSUE TITLE
将对话右上角的暂停 重复等handle放在右下角

### ISSUE THREAD

**Issue by liceal** [Bin-Huang/chatbox#290]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
![image](https://user-images.githubusercontent.com/33884851/229705165-0d7999bc-cc14-4c73-b452-f9870bccc03e.png)
对话右上角的handle会在文本过长后往上移动，想中断时，需要及时按下，不然会移动位置。

**解决思路**
![image](https://user-images.githubusercontent.com/33884851/229705097-a186a344-9459-43d5-a375-8a7a5777fe35.png)
```
position: sticky;
bottom: 0;
right: 0;
```

**Comment by Bin-Huang** [comment]
新版本已经放到消息下方了。
