### ISSUE TITLE
您好,可能您创建软件是使用1080P以上的分辨率,而我的电脑是1366*768的,打开会显得有点大,每次手动调整多少有点麻烦,目前位置软件的其他功能非常好用,非常感谢您的努力,谢谢

### ISSUE THREAD

**Issue by hank6245** [Bin-Huang/chatbox#291]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by Bin-Huang** [comment]
可以设置字体大小，如果没有的话升级一下
