### ISSUE TITLE
建议可以接入其他网站的API

### ISSUE THREAD

**Issue by Alfred5544** [Bin-Huang/chatbox#293]
gpt-3截止时间是2021年，建议可以接入其他网站的API,类似于Google的，
参照https://github.com/circlestarzero/EX-chatGPT，
是不是可以解决可以搜索近期消息的问题？

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1238, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1238。这条 issue 先关闭了～～
