### ISSUE TITLE
OpenAI

### ISSUE THREAD

**Issue by yy-424Git** [Bin-Huang/chatbox#294]
额，不太会，最好能出一个简单的使用手册。
设置里面的OpenAI key填的是账号还是密码啊？

**Comment by yy-424Git** [comment]
OpenAi Key获取到了，添加到chatbox里面的设置中了，还是不好用

**Comment by yy-424Git** [comment]
显示这个You exceeded your current quota, please check your plan and billing details

**Comment by Bin-Huang** [comment]
其实原因已经在错误里了。API 账户和 ChatGPT 账户是 OpenAI 两套独立的账户体系。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。
这个问题和软件没有任何关系。
如果你不想折腾 API 账户的各种问题的话，强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0
