### ISSUE TITLE
linux 版的 arm64 似乎缺了

### ISSUE THREAD

**Issue by wuyudi** [Bin-Huang/chatbox#30]
发现 0.0.4 有 [chatbox_0.0.4_arm64.deb](https://github.com/Bin-Huang/chatbox/releases/download/v0.0.4/chatbox_0.0.4_arm64.deb)

但是 0.0.8 就没了。只有一个 x64 zip 和 amd64 的包。

**Comment by Bin-Huang** [comment]
你试下能用吗？主要是我没有arm机器编译。

**Comment by wuyudi** [comment]
我也没有，就是看到之前有，现在没了，问问（

**Comment by murphytsai** [comment]
@Bin-Huang 能提供 build 的方法嗎？可以供有 arm 機器的人協助編繹，Thanks.

**Comment by Bin-Huang** [comment]
This issue has been resolved in the new version v0.6.3. If the problem still persists, you can reopen the issue at any time😊.
https://github.com/Bin-Huang/chatbox/releases


这个问题在新版本 v0.6.3 已经解决，如果问题还存在你可以随时重新开启这个 issues 😊。
https://github.com/Bin-Huang/chatbox/releases
