### ISSUE TITLE
[BUG] 使用nginx反代api时，会出现API请求失败

### ISSUE THREAD

**Issue by deadcativan** [Bin-Huang/chatbox#300]
我用docker在本机跑了个nginx反代了https://api.openai.com ，然后在设置的代理里，把API域名设置为本机http://localhost:8080 。
对话时会返回如下错误：
```
API 请求失败：

复制
Error parsing item: {"id":"chatcmpl-71f7wi4gofdPC3HYiRf4n0x.
Error Details: SyntaxError: Unterminated string in JSON at position 39
```

但用postman发起api request是没问题的。看了一下response的body和header，也没发现什么异常。

nginx的配置如下：

```
server {
    listen       80;
    server_name  localhost;

    location / {
        proxy_pass        https://api.openai.com;
        proxy_set_header  Host api.openai.com;
        proxy_ssl_server_name   on;
        proxy_ssl_session_reuse off;
    }
}
```

然后我把nginx部署到云上，再另外开一台新的VM安装chatbox来测试，还是一样的问题。

另外通常部署好之后，第一句对话是正常的，第二句开始就会出现这个问题了，这是就算重启nginx，也不能恢复。

**Comment by Bin-Huang** [comment]
你好，这个问题应该是很早期的版本才有的，可以升级看看。
