### ISSUE TITLE
[BUG] 提问今天是哪一天？出现问题

### ISSUE THREAD

**Issue by jokerwen1** [Bin-Huang/chatbox#301]
![image](https://user-images.githubusercontent.com/89336685/229925457-40ebab50-7a44-47df-9a13-2f7c7c2c1ea4.png)

**Comment by xiaole51** [comment]
模型切换到turbo-0310会得到改善， 而且比默认模型回答准确率更高。

**Comment by jokerwen1** [comment]
> 模型切换到turbo-0310会得到改进，并且比默认模型回复准确率更高。
切换了，还是不行
![image](https://user-images.githubusercontent.com/89336685/230039828-2c62c437-890d-41fd-a7d6-1f828f74b105.png)
![image](https://user-images.githubusercontent.com/89336685/230039914-9d2d9463-7957-4cff-aeaf-07aca5d3d27e.png)

**Comment by Bin-Huang** [comment]
模型训练自 2021 年，所以AI会这么理解
