### ISSUE TITLE
新加的停止按钮我根本追不上它

### ISSUE THREAD

**Issue by taohe009** [Bin-Huang/chatbox#303]
新加的停止按钮我根本追不上它，因为输出的字的滚动速度实在是太快了，右侧的按钮就跟着上去了，这就成了一个鸡肋功能，其他复制、引用、编辑、删除功能都是在生成完结果后使用的，所以滚上去也不用追，而只有停止按钮最尴尬了，追不上去，按不了，除非输出内容非常少，才能来得及按这个按钮，我希望改成和ChatGPT一样位置的停止按钮吧

**Comment by taohe009** [comment]
没人看到吗？这个是很重要的问题

**Comment by Bin-Huang** [comment]
已经改到消息下方了。
