### ISSUE TITLE
win 10安装了软件，但是不能用；兼容性也不行。

### ISSUE THREAD

**Issue by mentha-hapl** [Bin-Huang/chatbox#304]
win 10安装了软件，但是不能用；兼容性也不行；
操作系统  win 10；
应用程序 0.3.0；
试过低版本也不行；
安装好 chatbox；点击运行 一闪就关闭了；

**Comment by mentha-hapl** [comment]
win 10 has the software installed, but it doesn't work; neither does compatibility

**Comment by simpleisall** [comment]
我的win 10 直接装不上

**Comment by Bin-Huang** [comment]
你好，新版本做了修复，下载最新版本再试一下？https://github.com/Bin-Huang/chatbox/releases
