### ISSUE TITLE
希望能够增加语音功能

### ISSUE THREAD

**Issue by kebiao1987** [Bin-Huang/chatbox#306]
希望能增加语音功能类似于谷歌的插件Voice Control,并且能够抓取互联网上面的最新信息

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1239, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1239。这条 issue 先关闭了～～
