### ISSUE TITLE
字体太大了，能否设置里增加调整字体的选项[Other]

### ISSUE THREAD

**Issue by fzred** [Bin-Huang/chatbox#307]
如题，运行环境是 macOS

**Comment by lovitus** [comment]
是的, 字体太大了, 特别用老电脑, 开了缩放以后,  一屏显示不了几个字, 会话列表也看不全.
- 如果能减少元素间的空白填充
- 或者页面能整体缩小就好了

**Comment by LucasIsGood** [comment]
我在mac上还感觉字体小了, 要是还能修改字体就好了

**Comment by zhengchen1025** [comment]
我也觉得小了，希望可以调整字号

**Comment by Bin-Huang** [comment]
字体大小已经实现很久了，试试最新版本
