### ISSUE TITLE
[BUG] 使用 Cloudflare Workers中转api.openai.com，导致API Request Failed问题

### ISSUE THREAD

**Issue by heeyfan** [Bin-Huang/chatbox#308]
前提条件：
1、参照  https://github.com/noobnooc/noobnooc/discussions/9  该链接，设置使用自己的域名【api.mydomain.com】 代替 api.openai.com；
2、根据之前closed的 issue  : https://github.com/Bin-Huang/chatbox/issues/7 ,设置了相关的禁用缓冲等操作；
3、自己的域名【api.mydomain.com】 未被墙，可以正常网络访问

触发条件：
最新的win版本 0.3.0版本，win电脑不使用代理软件，比如 Clash等软件，设置自己的key以及域名【api.mydomain.com】等，有很大概率会触发下面的报错提示：（一些几个字的回复不会报错，稍微长一点，或者回复里面有代码相关的，很容易触发报错）
API Request Failed:

Copy
Error parsing item: {"id":"chatcmpl-71sub2.
Error Details: SyntaxError: Unterminated string in JSON at position 22

但是：

相同的条件，我只要把电脑代理软件打开，域名【api.mydomain.com】走代理，则不会触发报错。

但是相同的key，以及域名【api.mydomain.com】，在其他web端软件比如chatHub等，不使用Clash代理，同样的问题都不会导致报错。
在Android相关的软件（AMA等）也不会报错，

 还请大佬@Bin-Huang帮忙看看，这个软件很好用，所以请看看是哪里的问题。

**Comment by Bin-Huang** [comment]
> Error parsing item: {"id":"chatcmpl-71sub2.
> Error Details: SyntaxError: Unterminated string in JSON at position 22

出现这个错误代表网络已经连通了，但是代理似乎没有很好地处理 streaming。我看下客户端怎么兼容一下

**Comment by meetingxu** [comment]
> 前提条件： 1、参照 [noobnooc/noobnooc#9](https://github.com/noobnooc/noobnooc/discussions/9) 该链接，设置使用自己的域名【api.mydomain.com】 代替 api.openai.com； 2、根据之前closed的 issue : #7 ,设置了相关的禁用缓冲等操作； 3、自己的域名【api.mydomain.com】 未被墙，可以正常网络访问
> 
> 触发条件： 最新的win版本 0.3.0版本，win电脑不使用代理软件，比如 Clash等软件，设置自己的key以及域名【api.mydomain.com】等，有很大概率会触发下面的报错提示：（一些几个字的回复不会报错，稍微长一点，或者回复里面有代码相关的，很容易触发报错） API Request Failed:
> 
> Copy Error parsing item: {"id":"chatcmpl-71sub2. Error Details: SyntaxError: Unterminated string in JSON at position 22
> 
> 但是：
> 
> 相同的条件，我只要把电脑代理软件打开，域名【api.mydomain.com】走代理，则不会触发报错。
> 
> 但是相同的key，以及域名【api.mydomain.com】，在其他web端软件比如chatHub等，不使用Clash代理，同样的问题都不会导致报错。 在Android相关的软件（AMA等）也不会报错，
> 
> 还请大佬@Bin-Huang帮忙看看，这个软件很好用，所以请看看是哪里的问题。

请问朋友，我也是跟你用的同样的方式，Android端有什么可以使用的软件，支持自定义域名和自己的key的？

**Comment by heeyfan** [comment]
> > 前提条件： 1、参照 [noobnooc/noobnooc#9](https://github.com/noobnooc/noobnooc/discussions/9) 该链接，设置使用自己的域名【api.mydomain.com】 代替 api.openai.com； 2、根据之前closed的 issue : #7 ,设置了相关的禁用缓冲等操作； 3、自己的域名【api.mydomain.com】 未被墙，可以正常网络访问
> > 触发条件： 最新的win版本 0.3.0版本，win电脑不使用代理软件，比如 Clash等软件，设置自己的key以及域名【api.mydomain.com】等，有很大概率会触发下面的报错提示：（一些几个字的回复不会报错，稍微长一点，或者回复里面有代码相关的，很容易触发报错） API Request Failed:
> > Copy Error parsing item: {"id":"chatcmpl-71sub2. Error Details: SyntaxError: Unterminated string in JSON at position 22
> > 但是：
> > 相同的条件，我只要把电脑代理软件打开，域名【api.mydomain.com】走代理，则不会触发报错。
> > 但是相同的key，以及域名【api.mydomain.com】，在其他web端软件比如chatHub等，不使用Clash代理，同样的问题都不会导致报错。 在Android相关的软件（AMA等）也不会报错，
> > 还请大佬@Bin-Huang帮忙看看，这个软件很好用，所以请看看是哪里的问题。
> 
> 请问朋友，我也是跟你用的同样的方式，Android端有什么可以使用的软件，支持自定义域名和自己的key的？

AMA，在Google play里面下载，中文名叫 问天

**Comment by heeyfan** [comment]
> > Error parsing item: {"id":"chatcmpl-71sub2.
> > Error Details: SyntaxError: Unterminated string in JSON at position 22
> 
> 出现这个错误代表网络已经连通了，但是代理似乎没有很好地处理 streaming。我看下客户端怎么兼容一下

谢谢，有的时候，回答的内容都快完成了，界面上已经输出很多了，突然一下子，回答的内容都消失，然后就提示上面的错误信息。

**Comment by heeyfan** [comment]
0.3.4版本好像已解决这个问题，未出现该问题了
