### ISSUE TITLE
[功能建议] 希望增加快捷键打开和隐藏应用

### ISSUE THREAD

**Issue by akunlee** [Bin-Huang/chatbox#31]
本来是一直在用浏览器插件，但是觉得每次在浏览器搜索框提问太麻烦，所以就想自己搞一个，打算用react+vite+electron,结果发现作者已经开发了，感觉这个对很多人来说应该挺实用的。

**Comment by Bin-Huang** [comment]
我最近还在修复一些问题，这个功能你感兴趣实现吗？

**Comment by orangelckc** [comment]
可以来看看这个[项目](https://github.com/bilibili-ayang/ChatGPT-Desktop)，这周末会发版，集成了自定义快捷键设置等一系列功能

**Comment by Bin-Huang** [comment]
😊😊This feature has been implemented in the new version v0.6.5.
https://github.com/Bin-Huang/chatbox/releases
