### ISSUE TITLE
[BUG]M2芯片无法打开.dmg的安装包

### ISSUE THREAD

**Issue by PinelliaTime** [Bin-Huang/chatbox#310]
**Bug 描述**
MacBook M2芯片无法安装dmg文件

**期望结果**
软件能够安装成功

**实际结果**
软件安装失败

**截图**
![image](https://user-images.githubusercontent.com/41352992/230073459-2ea485da-9071-4af1-bf39-8a5db3df342f.png)

**桌面端（请填写以下信息）：**
- 操作系统：macOS 12.5
- 应用程序版本：V0.3.0

**Comment by Bin-Huang** [comment]
新版本已经支持 M1
