### ISSUE TITLE
[Other]Failed to fetch

### ISSUE THREAD

**Issue by CCSSPP2023** [Bin-Huang/chatbox#311]
![QQ截图20230405213439](https://user-images.githubusercontent.com/129965803/230097140-37fd0127-9231-472a-a4b5-dc170504671a.png)
中国大陆，开梯子不开梯子都这样，请问怎么解决，很多人都遇到这种情况。麻烦解答下，谢谢

**Comment by jokerwen1** [comment]
> ![QQ截图20230405213439](https://user-images.githubusercontent.com/129965803/230097140-37fd0127-9231-472a-a4b5-dc170504671a.png) 中国大陆，开梯子不开梯子都这样，请问怎么解决，很多人都遇到这种情况。麻烦解答下，谢谢

我今天早上也出现了这个情况，卸载重装了就行了

**Comment by tuzixiansheng** [comment]
> > ![QQ截图20230405213439](https://user-images.githubusercontent.com/129965803/230097140-37fd0127-9231-472a-a4b5-dc170504671a.png) 中国大陆，开梯子不开梯子都这样，请问怎么解决，很多人都遇到这种情况。麻烦解答下，谢谢
> 
> 我今天早上也出现了这个情况，卸载重装了就行了

我卸载重装，但是没有什么用，还是提示获取失败。
