### ISSUE TITLE
希望能支持API2D的key的请求[Other]

### ISSUE THREAD

**Issue by Loxonl** [Bin-Huang/chatbox#318]
由于绑定信用卡的问题，导致很多人转到API2D上去申请他们的代理key，但目前chatbox用API2D的key会提示API请求失败，很多其他软件支持了，希望chabotx能支持下

**Comment by lxlx5189** [comment]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/7411343/230272942-12fd6571-5303-42a2-bf9a-d664772a1b7b.png">
这是目前的效果

**Comment by liuruidong4** [comment]
同求= = 呜呜呜 大佬好了滴滴我一下

**Comment by liuruidong4** [comment]
已经可以了

**Comment by Loxonl** [comment]
> 已经可以了

咋可以的啊？我这升级到0.3.4还是不行啊，两个代理地址都试过不行

**Comment by liuruidong4** [comment]
> > 已经可以了
> 
> 咋可以的啊？我这升级到0.3.4还是不行啊，两个代理地址都试过不行
![image](https://user-images.githubusercontent.com/30995673/230817477-bebea594-84ae-4113-a55d-1def930206a7.png)

![image](https://user-images.githubusercontent.com/30995673/230817506-63d8ea12-dba8-46c2-bb54-90d21263faf9.png)
