### ISSUE TITLE
使用Mac版10次左右，帐号被禁用

### ISSUE THREAD

**Issue by wayne-china** [Bin-Huang/chatbox#32]
<img width="596" alt="image" src="https://user-images.githubusercontent.com/2786694/224657681-b5956c0a-3aa9-4e96-ad81-ac076d5e2a10.png">

**Comment by LifeNT** [comment]
最近openai对新注册用户都进一步收紧了控制，好像美国几大免税州代理IP都申请不到了，我看有人都在推荐改用英国IP申请了，然后要确认一下API是否是你一个人在使用（检查一下有没有泄露？），如果是多人使用，被封禁的风险是显而易见的。

**Comment by Bin-Huang** [comment]
> 最近openai对新注册用户都进一步收紧了控制，好像美国几大免税州代理IP都申请不到了，我看有人都在推荐改用英国IP申请了，然后要确认一下API是否是你一个人在使用（检查一下有没有泄露？），如果是多人使用，被封禁的风险是显而易见的。

确实是这样
