### ISSUE TITLE
[BUG] UI问题

### ISSUE THREAD

**Issue by devyujie** [Bin-Huang/chatbox#320]
**Bug 描述**
这个浮动需要改一下

**重现步骤**
/

**期望结果**
/

**实际结果**
/

**截图**
![1](https://user-images.githubusercontent.com/48620527/230291802-43633dc3-18e7-46d3-9636-d92980e2989d.gif)

**桌面端（请填写以下信息）：**
- 操作系统：Windows10
- 应用程序版本：0.3.1

**其他上下文**
/

**Comment by Bin-Huang** [comment]
0.3.2 还会吗？

**Comment by wsdy10000** [comment]
在文字过多的情况会把聊天框挤出去

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/Chatbox-v0.3.3

**Comment by myworksfun** [comment]
作者高产啊 👍

**Comment by l3ony2k** [comment]
@Bin-Huang v0.3.3 还存在这个问题。

**Comment by jackdiy** [comment]
希望下一版本可以自己调整UI中字体的大小，另外优化表格的显示，就像ChatGPT官方网页版那样

**Comment by NanTeng** [comment]
0.34 这个问题依旧存在！

**Comment by NanTeng** [comment]
@Bin-Huang 0.34问题依旧存在

**Comment by Bin-Huang** [comment]
最新版本呢？

**Comment by Bin-Huang** [comment]
This issue has been resolved in the new version v0.6.3. If the problem still persists, you can reopen the issue at any time😊.
https://github.com/Bin-Huang/chatbox/releases


这个问题在新版本 v0.6.3 已经解决，如果问题还存在你可以随时重新开启这个 issues 😊。
https://github.com/Bin-Huang/chatbox/releases
