### ISSUE TITLE
[BUG] macos 10.15.7 界面不正常。

### ISSUE THREAD

**Issue by leonlincc** [Bin-Huang/chatbox#321]
左边选择话题后，有些会在右边显示，有些直接就没有在右边。但是向下划动却能看到一个全屏的话题在下面显示。然后需要选择其他的话题，还需要划动屏幕上面空白的地方到上一页进行选择。

这个应该是页面bug，可能的操作方法是直接给左边的话题列表加一个左缩进或者隐藏的功能按钮，然后再次点击该按钮出现话题选择即可。

**Comment by Bin-Huang** [comment]
紧急修复了，安装最新版本试试

**Comment by Wangjunkun** [comment]
我也遇到了该问题

<img width="1336" alt="Image" src="https://github.com/user-attachments/assets/69a39877-9f77-43cc-820d-56fb17a1dd35" />
