### ISSUE TITLE
v0.3.2紧凑UI，让我想放弃chatbox

### ISSUE THREAD

**Issue by garywu520** [Bin-Huang/chatbox#322]
Chatbox作为一个客户端， 这个紧凑UI 在我这个M1 16寸大屏看着非常不爽......

**Comment by Bin-Huang** [comment]
0.3.2 存在一个布局Bug，正在修复中了

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/Chatbox-v0.3.3
