### ISSUE TITLE
[BUG]UI问题

### ISSUE THREAD

**Issue by EXBC-TSJH** [Bin-Huang/chatbox#324]
ui拉伸有问题

安装打开chatbox0.3.2版本后出现如图的ui问题

![image](https://user-images.githubusercontent.com/82747575/230322741-67df9370-4cac-413b-b4a7-04523540e0b5.png)

在win10 x64位运行

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

这是 0.3.2 的一个BUG，已经修复了
