### ISSUE TITLE
希望能自定义 enter 和修饰键 shift ， ctrl 的行为 [Feature]

### ISSUE THREAD

**Issue by lovitus** [Bin-Huang/chatbox#325]
经常因为ctrl按键操作过快， 发出去不生成消息 （识别成 ctrl + enter）。
并且 在其他程序习惯 enter换行，  ctrl+enter 发送。
所以在chatbox使用过程一直都很难调整肌肉习惯。

能否让用户自定义以下按键/组合键？
（正常发送/换行/发送不生成)
- enter
- shift+enter
- ctrl+enter

**Comment by Thanatos-L** [comment]
求求了求求了，我也想要

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #939, so I'll close this to avoid duplicates. Feel free to add more thoughts there!
