### ISSUE TITLE
[BUG]Win 11安装打开运行时，提示存在兼容性问题

### ISSUE THREAD

**Issue by Hanlen520** [Bin-Huang/chatbox#326]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
Win 11安装打开运行时，提示存在兼容性问题

**重现步骤**
安装后直接打开

**期望结果**
可以正常打开

**实际结果**
提示错误，无法加载

**截图**
![image](https://user-images.githubusercontent.com/35830128/230355074-6624d193-ede4-4be4-9278-7cd00c41d595.png)

**桌面端（请填写以下信息）：**
- 操作系统：Windows 11
- 应用程序版本：0.3.3

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by fankangsong** [comment]
Windows 10 系统，同样的问题。

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复，试试最新版本
https://github.com/Bin-Huang/chatbox/releases
