### ISSUE TITLE
[暗色模式配色]

### ISSUE THREAD

**Issue by chaojiakeji** [Bin-Huang/chatbox#327]
**问题描述**
当前暗色模式下的黑色背景色看得的有些难受

**解决思路**
希望暗色可以增加一个颜色#202124，或自定义背景色。

**附加上下文**
<img width="702" alt="截屏2023-04-06 18 55 16" src="https://user-images.githubusercontent.com/49504856/230357131-4762868f-a74c-4d39-b98a-4c7d7b2d9711.png">

**Comment by Bin-Huang** [comment]
很棒的建议，已经采纳了
