### ISSUE TITLE
[Feature]能增加一个对话导出功能吗？

### ISSUE THREAD

**Issue by taylormao** [Bin-Huang/chatbox#329]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by hotji** [comment]
可以讲中文吗

**Comment by jackdiy** [comment]
确实需要一个批量选择对话然后导出成HTML或其他格式的功能

**Comment by Bin-Huang** [comment]
新版本已经支持了
<img width="223" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/3b4cdb63-cd2c-49de-993d-690c3cffecfa">

<img width="694" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/96cf23c5-4229-4af1-9eff-7802954217ec">
<img width="1156" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/319a13c3-9d08-44b0-94f5-73a5b6060eac">
