### ISSUE TITLE
[BUG]新版本0.33响应速度大不如以前

### ISSUE THREAD

**Issue by tavengers** [Bin-Huang/chatbox#330]
**Bug 描述**
刚下载的新版本0.3.3，感觉响应速度大不如之前，以前基本上都是秒回，现在有点官方的感觉了，速度不是很好了

**Comment by Bin-Huang** [comment]
能不能提供一些和以前版本速度的数据对比，这样我可以更好的排查问题？

**Comment by Bin-Huang** [comment]
有没有可能是网络的问题？或者是因为字体变小了所以直观感觉更慢了。所以如果有更加客观的数据对比就更好了

**Comment by myworksfun** [comment]
I feel that there is no difference between the response speed of this version (ver.0.33) and the previous , maybe it is a problem with your network.

**Comment by me2hk** [comment]
是的，我同样没感觉到响应速度有变化，可能是你网络的问题

**Comment by aioscn** [comment]
今天测试的，可能是今天chatgpt比较卡，0.29版本生成50个标题，用时2分53秒，0.33用时3分7秒

**Comment by ErwinSchroding** [comment]
我也遇到此问题。
我同时测试了0.2.9版本，响应速度很慢。另外我测试了网页版，响应速度很快。
周末愉快

**Comment by a5185330** [comment]
我也是,今天才出现这种问题的.之前速度很快

**Comment by wuyuezhui** [comment]
我的也是，今天无论切换哪个节点，速度都特别慢。

**Comment by Bin-Huang** [comment]
我已经做了非常详细的测试，对比了不同版本之间的生成速度，最新版本的速度和以前**完全是一模一样的**（长文本生成的场景下，在我的网络中 v0.3.4 和 v0.2.x 都是每秒 16 个字符的生成速度），不存在变慢的问题。

如果你觉得变慢了，我认为可能有两个原因：
1. v0.3.4 采用了更加紧凑的布局，每一行包含的字符变多了，所以很容易产生每行生成速度变慢的错觉
2. 根据其他 Issues，OpenAI 近期可能对免费账户进行了限速，这个我不太了解，需要进一步考证。
