### ISSUE TITLE
希望增加查看图像的功能

### ISSUE THREAD

**Issue by wss-wss** [Bin-Huang/chatbox#333]
**问题描述**
gpt发过来的图像无法在聊天框显示
![图像无法显示](https://user-images.githubusercontent.com/67221565/230415227-9fabd867-54bd-44f8-b8ae-6fc9f0ed90a2.png)

**解决思路**
希望增加一个能用客户端的软件查看图像的功能。

**附加上下文**
我新人用户，不知道在哪可以打赏支持一下作者，有的话请告诉我，非常感谢你的作品，作品很好对我帮助很大谢谢！

**Comment by Bin-Huang** [comment]
你好，这种情况是因为AI发的图片不存在。你可以点击消息的更多菜单，点击编辑查看图片链接。Chatbox是支持图片显示的。
