### ISSUE TITLE
[Feature]最近经常遇到回复过长的问题，这里能增加一个自动截断分两次或多次回复的方法吗？

### ISSUE THREAD

**Issue by jackdiy** [Bin-Huang/chatbox#335]
**问题描述**
{"error":{"message":"This model's maximum context length is 4097 tokens. However, you requested 4179 tokens (2179 in the messages, 2000 in the completion). Please reduce the length of the messages or completion.","type":"invalid_request_error","param":"messages","code":"context_length_exceeded"}}

**解决思路**
最近经常遇到回复过长的问题，这里能增加一个自动截断分两次或多次回复的方法吗？

**Comment by Bin-Huang** [comment]
请重置设置中的model&tokens的设置。这是因为你设置配错了，重置就不会遇到这种问题。
