### ISSUE TITLE
[BUG]API 请求失败: An SSL error has occurred and a secure connection to the server cannot be made.

### ISSUE THREAD

**Issue by tracywenjin** [Bin-Huang/chatbox#337]
**Bug 描述**

0.3.3版本，正常配置，聊天报错如下：
API 请求失败：

An SSL error has occurred and a secure connection to the server cannot be made.

**桌面端（请填写以下信息）：**
- 操作系统：macOS  CPU:m1  
- 应用程序版本：0.3.3

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by weizhe940605** [comment]
![image](https://user-images.githubusercontent.com/123148906/230830250-99cc3b33-fd52-40ab-a68c-1550d90f23de.png)
用不了啊

**Comment by ferbylv** [comment]
我也遇到了同样问题

**Comment by Bin-Huang** [comment]
SSL 看上去像是网络问题

**Comment by Bin-Huang** [comment]
> ![image](https:user-images.githubusercontent.com/123148906/230830250-99cc3b33-fd52-40ab-a68c-1550d90f23de.png) 用不了啊

你的问题不一样。 这是因为你的 API 账户没有余额，或者余额已经过期了。和软件没有任何关系的。如果你不想折腾 API KEY 的话，可以考虑 v0.5.0 中内置的 AI 服务，是直接开箱即用的 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0
