### ISSUE TITLE
[Feature]新增对于代码块的显示方式

### ISSUE THREAD

**Issue by Marley-zhang** [Bin-Huang/chatbox#339]
希望可以像chatGPT那样对于返回的代码块可以用markdown的方式显示出来

<img width="729" alt="image" src="https://user-images.githubusercontent.com/12506693/230523480-ed72b4f1-4467-449b-b7f4-c7586429b93d.png">

就像这样 这样对于程序猿来说就比较清晰了

**Comment by Bin-Huang** [comment]
其实一直都支持 markdown 哦，只是 AI 没有按照 markdown 格式返回。你可以让 AI 用 markdown 格式返回。
