### ISSUE TITLE
以markdown 文件格式输出

### ISSUE THREAD

**Issue by wxmpro** [Bin-Huang/chatbox#342]
有时候想和朋友分享对话的技巧和过程，能不能以markdown文件或者可以复制全部对话？

**Comment by ttyy33** [comment]
你告诉它“给我markdown源代码格式”

**Comment by wxmpro** [comment]
实际是想把整个对话过程导出来🤓，不光是代码。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月7日(周五) 中午12:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Bin-Huang/chatbox] 以markdown 文件格式输出 (Issue #342)




 
你告诉它“给我markdown源代码格式”

**Comment by ttyy33** [comment]
> 

你试过了嘛？我是试过了，可以。你都懒得试，下次我不会回答你的提问了。

**Comment by lvmj99** [comment]
我也想要这个功能。增加一键导出聊天记录功能，格式可选markdown或者pdf，感谢

**Comment by lvmj99** [comment]
> 你告诉它“给我markdown源代码格式”

楼主说的是软件功能，你说的是GPT本身

**Comment by wxmpro** [comment]
伤心，我肯定试过了，用的 gpt3.5，不能输出从头开始的所有对话，不单单是他回复的代码。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月7日(周五) 中午1:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Bin-Huang/chatbox] 以markdown 文件格式输出 (Issue #342)




   
你试过了嘛？我是试过了，可以。你都懒得试，下次我不会回答你的提问了。

**Comment by Bin-Huang** [comment]
如果要导入所有的消息到 Markdown，可以点击导出按钮；
如果要查看一条消息的markdown源码，点击消息的编辑按钮；
如果你看不到这些按钮，升级软件
