### ISSUE TITLE
[BUG]WIN7无法安装

### ISSUE THREAD

**Issue by hcymysql** [Bin-Huang/chatbox#344]
![图片](https://user-images.githubusercontent.com/19261879/230537275-452d1be6-2566-47cf-9f01-62b6facaee1e.png)

**Comment by simpleisall** [comment]
win 10 遇到了同样的问题。
There is a problem with this Windows Installer package.
A program required for this install to complete could not be run. Contact your support personnel or package
vendor.

**Comment by LingerD02** [comment]
个人解决办法，仅供参考
1、安装@lencx的ChatGPT。（里面有附带edge浏览器的webview2）
     查看程序webview2是否出现在安装列表（没得就重启一下电脑）
2、然后安装chatbox。
PS  安装失败实际是webview2安装失败，我试了几次安装成功了

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases

新版本已经兼容 Window7 了。
The new version is now compatible with Windows 7.
