### ISSUE TITLE
[Feature]一些改善用户体验的建议

### ISSUE THREAD

**Issue by me2hk** [Bin-Huang/chatbox#345]
我很喜欢chatbox的使用体验，希望作者能持续迭代 以下是一些改善使用体验的建议希望它能更加便捷的使用：

**1、快速定位**，通过一个箭头按钮快速到达对话框底部或顶部（因为每次打开对话框的时候都默认是在顶部，找到最后的位置得拖动一阵，有些不便），或者记录当前位置信息，每次可以自动定位上次的位置。

**2、置托盘图标**，很多软件在关闭时都会置托盘图标方便再次调用（可以放在设置里开启或关闭），习惯性的操作经常导致我经常不小心关闭，又得重新打开，可能是个人习惯。

**3、拖动对话**，可拖动排列对话，使用拖动来调整对话顺序。

感谢作者和各位贡献者的付出

**Comment by Bin-Huang** [comment]
除了第二点外，其他功能基本已经实现了，升级看看

**Comment by Bin-Huang** [comment]
I feel like this issue is a bit outdated, so I went ahead and closed it. But if you think it's necessary, feel free to create a new issue at any time.
