### ISSUE TITLE
[BUG]模型版本设置后未起效

### ISSUE THREAD

**Issue by nlj626** [Bin-Huang/chatbox#346]
*Bug 描述**
设置选择其他模型后，依然显示的是gpt3.5-turbo

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 ".设置"
2. 选择 "gpt4的模型"
3. 点击"保存"
4. 进入对话模式进行对话，显示模型版本为gpt3.5-turbo。

**期望结果**
对话模式显示的模型版本为gpt4。

**实际结果**
显示的模型版本为gpt3.5-turbo。

**截图**
无

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 0.3.3]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by ttyy33** [comment]
先设置gpt4模型，再新建窗口就可以使用gpt4的模型了。
