### ISSUE TITLE
[Feature]增加余额的显示

### ISSUE THREAD

**Issue by yellowgg** [Bin-Huang/chatbox#347]
**问题描述**
想要增加余额的显示

**解决思路**
有余额api接口的,在设置页面增加查询显示

**附加上下文**
谢谢老大,我看了下其他issue提余额是因为调用api失败了,跟我这个应该没冲突

**Comment by 1414894911** [comment]
访问一下usage

**Comment by Bin-Huang** [comment]
Due to the need to support many model providers, and not all providers have similar interfaces, there is currently no development plan for this feature.
