### ISSUE TITLE
[Feature] 关于主题文字与代码的背景显示是否可以分开，目前统一显示不方便阅读

### ISSUE THREAD

**Issue by hedywqy** [Bin-Huang/chatbox#349]
**例如飞书的wiki，白色背景模式下这么显示**

![image](https://user-images.githubusercontent.com/7055224/230560894-b0188376-4205-4927-b0ee-7fa2a9b6f677.png)

**Comment by Bin-Huang** [comment]
新版本已经改成黑色代码背景了
