### ISSUE TITLE
API Request Failed:  Failed to fetch

### ISSUE THREAD

**Issue by Bojeck** [Bin-Huang/chatbox#35]
API Request Failed:

Failed to fetch

**Comment by Bin-Huang** [comment]
大陆地区需要特殊网络环境

**Comment by sundazhen** [comment]
我已经使用了梯子，并且在“https://chat.openai.com/”可以使用，但是使用chatbox依然显示
API Request Failed: 
```
Failed to fetch
```

**Comment by dashuai233** [comment]
Me too!! wait for a solution

**Comment by Bin-Huang** [comment]
如果你懒得处理那个网络问题，可以把 API HOST 改成 https://proxy2.chatbox.run 就可以了
