### ISSUE TITLE
[Feature]一次性返回结果，移除打字机动画

### ISSUE THREAD

**Issue by Corgile** [Bin-Huang/chatbox#350]
如题。

**Comment by myworksfun** [comment]
I think the typewriter works great, no need to remove it!

**Comment by GotoFox** [comment]
会浪费等待时间，不建议移除

**Comment by DevinFu** [comment]
目前的方式很好，一个字一个字展示，展示完了我也就读完了。不浪费时间，如果一次性展示，那么在展示前，等待时间比较久，尤其是答案比较长的时候。

所以，希望现在这种方式，不建议移除

**Comment by Bin-Huang** [comment]
不会移除打字机动画。可能只是因为你的接口太慢了，让你觉得返回很慢。其他人都是很快回复的
