### ISSUE TITLE
[Feature]增加界面文字大小调节的功能

### ISSUE THREAD

**Issue by LifeNT** [Bin-Huang/chatbox#351]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。
目前0.3.3界面与聊天文字变小了，在分辨率较高的显示器上有点吃力，能否增加显示文字大小调节，最好能分开调节UI文字与聊天内容文本大小。
**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by magicdmer** [comment]
的确，新版本文字突然变小，在高分屏就没之前老板本体验好了，希望能改进

**Comment by Bin-Huang** [comment]
已经可以设置字体大小了
