### ISSUE TITLE
[BUG]部分对话界面横向过长

### ISSUE THREAD

**Issue by mikoli524** [Bin-Huang/chatbox#356]
刚刚更新了0.3.4，我有一段用了很久的记录，这个记录的文字显示超出了边框，连带输入框和发送按钮都只能拖动横向进度条才能看到
![image](https://user-images.githubusercontent.com/48148226/230586898-6239d112-32d0-48fb-be5d-22fc455bbb39.png)
![image](https://user-images.githubusercontent.com/48148226/230586967-1b633791-88a3-443b-a260-2632f72f393c.png)

**Comment by Bin-Huang** [comment]
这个问题应该以前修复过了。试试新版本
