### ISSUE TITLE
[BUG]更新0.3.4后用不了，报错API请求失败

### ISSUE THREAD

**Issue by RayCssjmt** [Bin-Huang/chatbox#357]
**Bug 描述**
更新0.3.4后用不了，报错API请求失败

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1、直接发送即可

**期望结果**
正常返回结果

**实际结果**
API请求失败：Load failed

**桌面端（请填写以下信息）：**
- 操作系统：mac arm
- 应用程序版本：0.3.4

**Comment by Bin-Huang** [comment]
先排查下网络问题？这个应该和版本没有关系

**Comment by RayCssjmt** [comment]
> 先排查下网络问题？这个应该和版本没有关系

可以了 ，新建个对话就发送一次 再切回去就好了

**Comment by haoxinqing888** [comment]
Load failed
我的还是不好用

**Comment by haoxinqing888** [comment]
0.4.4版本还是不好报这个错Load failed

**Comment by Bin-Huang** [comment]
Load failed
大概率是那个“网络问题”，请确定可以正常访问海外的服务
