### ISSUE TITLE
[BUG]左侧对话栏不能调整大小了

### ISSUE THREAD

**Issue by kickTiger** [Bin-Huang/chatbox#358]
以前的版本，左侧对话栏的宽度是可以调整的，刚升级了 0.3.4 之后不能调整了。

左侧对话的标题稍微长点就无法看全了。
- 希望左侧对话栏恢复可以调整宽度
- 或者改成鼠标放在标题可滚动查看 标题 全文 

不然就没法看对话的标题全文了。太紧凑了

**Comment by otakutyrant** [comment]
现在是不是可以调整了？我这里不能。

**Comment by kickTiger** [comment]
> 

不能，那次之后就再也不能调整了

**Comment by otakutyrant** [comment]
PLEASE OPEN THIS ISSUE AGAIN!

**Comment by kickTiger** [comment]
没用的，几百条ISSUE 了，根本没人管的
