### ISSUE TITLE
[Feature] Bulk delete and chat export / 大量刪除訊息以及聊天匯出功能

### ISSUE THREAD

**Issue by jmleetw** [Bin-Huang/chatbox#359]
**Problem Description**
Although chat tabbing is already quite useful, there may be cases where you need to remove specific requests and responses in a chat. It would be great to have a "bulk delete" feature for this purpose. Also, it would be very helpful to have the ability to export the chat as a JSON or TXT file if possible.

**Proposed Solution**
After clicking the "Bulk Delete" button (which may be located next to the "Clear" button), a checkbox will appear next to each message. Just select the checkbox next to the messages you want to delete, and then click the "Bulk Delete" button again to delete the unwanted messages. As for the "Export Chat" button, it can be set in the three-dot menu on the chat tab.

**Additional Context**
N/A

-----------------------

**问题描述**
雖然分頁已經相當實用，但在某些情況下，可能會需要某則聊天中的特定對話和回應。希望可以新增大量刪除訊息 (要求及回應) 的功能。另外，將聊天匯出為 JSON 或 TXT 檔案也會相當實用。

**解决思路**
點選「大量刪除」按鈕 (可位於「清除」按鈕旁) 後，訊息旁隨即會顯示核取方塊，只要找出要刪除的訊息並勾選旁邊的方塊，然後再次點選「大量刪除」按鈕，即可將不需要的訊息刪除。至於「匯出聊天」按鈕，則可設置於聊天分頁的三點選單中。

**附加上下文**
無

**Comment by Bin-Huang** [comment]
v0.6.2 has been implemented, give it a try.
https://github.com/Bin-Huang/chatbox/releases

**Comment by mika76** [comment]
@Bin-Huang I see there is bulk cleaning, but could you add the bulk export feature as well - or at least an option on the bulk cleaning to also export whatever it cleans?
