### ISSUE TITLE
API Request Failed: Error parsing item

### ISSUE THREAD

**Issue by gitaidea** [Bin-Huang/chatbox#36]
提交两次均出错，均是API Request Failed
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/126068841/225037096-bfa7a380-817c-4ae9-aea8-b5aa047dbbb8.png">

**Comment by valleyk** [comment]
标注一下是代理还是自定义域名，试试这个 #34

**Comment by olin2011** [comment]
> 标注一下是代理还是自定义域名，试试这个 #34

我遇到同样的问题，我使用的是自定义域名，我是0.1.1版

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/v0.1.2

最新版本v0.1.2已经修复了，感谢 @valleyk

**Comment by olin2011** [comment]
> https://github.com/Bin-Huang/chatbox/releases/tag/v0.1.2
> 
> 最新版本v0.1.2已经修复了，感谢 @valleyk

表示还是会遇到这个问题，我已经是v0.1.2

**Comment by Bin-Huang** [comment]
> > https://github.com/Bin-Huang/chatbox/releases/tag/v0.1.2
> > 最新版本v0.1.2已经修复了，感谢 @valleyk
> 
> 表示还是会遇到这个问题，我已经是v0.1.2

方便提供一下你的自定义域名的配置吗？比如 nginx 或 caddy 的配置文件的示例？

**Comment by olin2011** [comment]
> > > https://github.com/Bin-Huang/chatbox/releases/tag/v0.1.2
> > > 最新版本v0.1.2已经修复了，感谢 @valleyk
> > 
> > 
> > 表示还是会遇到这个问题，我已经是v0.1.2

详细已经发送你主页的邮箱了
