### ISSUE TITLE
[Other]新版本的回复变慢了，每次回复都要等十几秒。应该不是我的网络原因吧？

### ISSUE THREAD

**Issue by FixedGear-2020** [Bin-Huang/chatbox#360]
新版本的回复变慢了，每次回复都要等十几秒。应该不是我的网络原因吧？

**Comment by Sheldontao** [comment]
ChatGPT 免费 API 用户当前得到回答的速度变慢了许多，V2EX 的网友怀疑是 OpenAI 进行了限速。

另外一种可能是 OpenAI 将更多的计算资源优先供给付费用户，相对而言免费用户受到挤兑的影响更大了。

**Comment by wuyuezhui** [comment]
不是网络问题，我的也慢了好多多，可能真的是后台限速了

**Comment by wuyuezhui** [comment]
不是网络问题，我的也慢了好多多，可能真的是后台限速了

**Comment by aa342138039** [comment]
就今天开始变慢的

**Comment by ErwinSchroding** [comment]
可是网页版本的回复仍然快速，难道只对api进行了限速吗

**Comment by Sheldontao** [comment]
有没有plus用户现身说法一下？？？

**Comment by myworksfun** [comment]
Yes, the response has become much slower, after all, you are using the free api.

**Comment by zzwzl1** [comment]
我今天用api速度感觉好慢，之前都挺快的啊，但是网页速度正常

**Comment by PPiXXX** [comment]
确实被限速了！感觉慢了好多。

**Comment by VanYe666** [comment]
plus用户说也有变慢

**Comment by Bin-Huang** [comment]
我已经做了非常详细的测试，对比了不同版本之间的生成速度，最新版本的速度和以前**完全是一模一样的**（长文本生成的场景下，在我的网络中 v0.3.4 和 v0.2.x 都是每秒 16 个字符的生成速度），不存在变慢的问题。

如果你觉得变慢了，我认为可能有两个原因：
1. v0.3.4 采用了更加紧凑的布局，每一行包含的字符变多了，所以很容易产生每行生成速度变慢的错觉
2. 根据其他 Issues，OpenAI 近期可能对免费账户进行了限速，这个我不太了解，需要进一步考证。
