### ISSUE TITLE
[BUG]当api调用失败后，多次返回失败

### ISSUE THREAD

**Issue by Sheldontao** [Bin-Huang/chatbox#367]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/36765652/230639533-d70a0b2c-0f88-4b82-9e4d-641128ec2385.png">

只要你按更新键，会给你多生成一条失败消息

**Comment by iambonboncat** [comment]
设置系统代理

**Comment by Sheldontao** [comment]
我的问题是：合并多次返回报错。不是说为什么会报错

**Comment by Bin-Huang** [comment]
试试最新版本
https://github.com/Bin-Huang/chatbox/releases
