### ISSUE TITLE
能否设置代理服务器？

### ISSUE THREAD

**Issue by iambonboncat** [Bin-Huang/chatbox#368]
能否设置代理服务器？这样比较方便

**Comment by myworksfun** [comment]
![2](https://user-images.githubusercontent.com/45185967/230696925-4231dca0-ed44-4d41-87ff-307753482bdc.png)
The proxy function is always available!

**Comment by iambonboncat** [comment]
not the API proxy ，I mean the Proxy server

**Comment by ZhuYichuan** [comment]
可以用使用 Proxifier 来进行app 流量的代理
参考youtube  [视频地址](https://www.youtube.com/watch?v=ZPi56hSm__E)

**Comment by Bin-Huang** [comment]
看文档
https://github.com/Bin-Huang/chatbox/blob/main/team-sharing/README.md
