### ISSUE TITLE
[建议]左侧点击删除对话的时候，右边聊天框能否也同时清空

### ISSUE THREAD

**Issue by iKun4real** [Bin-Huang/chatbox#369]
现在点击左侧的对话标签删除后，右边聊天框的内容是还在的，能否修改成点击删除后，右侧聊天框清空。假如右侧还有其他对话标签，能么就选索引最高的一个置焦点，然后右侧聊天框显示对应对话的内容。

**Comment by zhengzhou** [comment]
这个是个bug， 菜单删除会切换到第一个会话，但是多触发了一次menu的点击按钮，又给切回来了

**Comment by lovewac723-png** [comment]
سلام عليكم
