### ISSUE TITLE
[Feature]新加的停止按钮我根本追不上它

### ISSUE THREAD

**Issue by taohe009** [Bin-Huang/chatbox#370]
新加的停止按钮我根本追不上它，因为输出的字的滚动速度实在是太快了，右侧的按钮就跟着上去了，这就成了一个鸡肋功能，其他复制、引用、编辑、删除功能都是在生成完结果后使用的，所以滚上去也不用追，而只有停止按钮最尴尬了，追不上去，按不了，除非输出内容非常少，才能来得及按这个按钮，我希望改成和ChatGPT一样位置的停止按钮吧

**Comment by zzwzl1** [comment]
为什么我的滚动速度这么慢的捏我是0.34版本

**Comment by hsing0527** [comment]
> 为什么我的滚动速度这么慢的捏我是0.34版本

如果一些答案是竖向生成的，比如列出某些bullet list数据，就会一直往上跑

**Comment by Bin-Huang** [comment]
已经改成消息下方的位置了

**Comment by magicdmer** [comment]
> 已经改成消息下方的位置了

其实我看了，放到下方也跟不上，最佳方案还是和网页版chatgpt一样，弄个悬浮的停止按钮，或者直接下面加个停止按钮

**Comment by taohe009** [comment]
加一个可以查询余额token的功能



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: magicdmer ***@***.***&gt;
发送时间: 2023年4月24日 20:18
收件人: Bin-Huang/chatbox ***@***.***&gt;
抄送: taohe009 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Bin-Huang/chatbox] [Feature]新加的停止按钮我根本追不上它 (Issue #370)





  
已经改成消息下方的位置了
  
其实我看了，放到下方也跟不上，最佳方案还是和网页版chatgpt一样，弄个悬浮的停止按钮，或者直接下面加个停止按钮
