### ISSUE TITLE
[建议]代码块纵列生成过长会导致看横向越过右侧窗口的代码不方便

### ISSUE THREAD

**Issue by longshensanjie** [Bin-Huang/chatbox#373]
当生成代码块过长的时候，想看横向越过右侧窗口的代码的时候必须将纵向滑动条先拖到最下面去，然后拖动横向滑动条，接着又要将纵向滑动条滑回刚刚的代码部分才能看到想看的代码，这整个操作流程太麻烦了，希望优化一下

**Comment by everyx** [comment]
按 shift 并滚动鼠标就可以直接横向滚动了

**Comment by longshensanjie** [comment]
@everyx 感谢提醒
