### ISSUE TITLE
[BUG]0.34版本windows系统生成速度变慢了，还有就是不能在生成的时候切换其他会话

### ISSUE THREAD

**Issue by zzwzl1** [Bin-Huang/chatbox#374]
windows0.34版本生成速度没有以前快了，不过能接受，就是回答出来的速度太慢了，一个字一个字出来还好，但是速度不够快，还有就是在这个会话生成回答的时候不能切换到其他会话，希望大佬优化一下谢谢

**Comment by PPiXXX** [comment]
应该是被限速了吧。好多人反应都说慢。秋大佬解惑！

**Comment by lonespeak** [comment]
我还以为是版本的问题，我还给换回老版本，发现还是一样。

**Comment by Bin-Huang** [comment]
我已经做了非常详细的测试，对比了不同版本之间的生成速度，最新版本的速度和以前**完全是一模一样的**（长文本生成的场景下，在我的网络中 v0.3.4 和 v0.2.x 都是每秒 16 个字符的生成速度），不存在变慢的问题。

如果你觉得变慢了，我认为可能有两个原因：
1. v0.3.4 采用了更加紧凑的布局，每一行包含的字符变多了，所以很容易产生每行生成速度变慢的错觉
2. 根据其他 Issues，OpenAI 近期可能对免费账户进行了限速，这个我不太了解，需要进一步考证。
