### ISSUE TITLE
macOS每次启动chatbox都得重新设置，不能保存上一次的设置[BUG]

### ISSUE THREAD

**Issue by iambonboncat** [Bin-Huang/chatbox#375]
[BUG]macOS每次启动chatbox都得重新设置，不能保存上一次的设置

**Comment by qhenry** [comment]
我也遇到此问题

**Comment by Bin-Huang** [comment]
请问是不是 MacOS 10 版本？这个版本在设置存储上有一些兼容问题

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复，试试最新版本
https://github.com/Bin-Huang/chatbox/releases
