### ISSUE TITLE
为什么只有GPT-3能用，选择4的都出错？

### ISSUE THREAD

**Issue by saharaqq** [Bin-Huang/chatbox#376]
{"error":{"message":"The model: `gpt-4-32k-0314` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}

**Comment by chunfengchuilaoseng** [comment]
有可能是设置选项的模型设置里面有关于模型联系上下文和回答字数限制的选项数值超出了GPT-4的数值范围，适当把数值改小一点就好

**Comment by iambonboncat** [comment]
应该是没给钱脉plus

**Comment by heicai2023** [comment]
我也是   我的账号升级了plus   还是在chatbox里面用不了4的模型  有大佬解释一下怎么用吗

**Comment by LipYoung** [comment]
动手之前多看看官方的文档啊.你的账号有没有申请到4的使用权啊.plus和开放平台是2个东西.

**Comment by ChenChen61882** [comment]
> 

申请到Plus也是不能在ChatBOX中使用吗？谢谢

**Comment by LipYoung** [comment]
@ChenChen61882 是的.你要到官方申请到4的使用权.多看看官方的文档,.很多问题就不存在了

**Comment by Macy2028** [comment]
我也是同样的情况 明显给了KEY 还是不行 买了PLUS了 再逼我 我就自己写本地的了。

**Comment by remington258** [comment]
求大佬教程，有偿



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月16日(周日) 晚上7:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Bin-Huang/chatbox] 为什么只有GPT-3能用，选择4的都出错？ (Issue #376)




 
我也是同样的情况 明显给了KEY 还是不行 买了PLUS了 再逼我 我就自己写本地的了。

**Comment by Bin-Huang** [comment]
根本不需要买 Plus。
不管你有没有买 Plus，使用 GPT4.0 的 API 账户都要排队申请，没有申请都无法使用 GPT4.0。
排队链接：https://openai.com/waitlist/gpt-4-api
