### ISSUE TITLE
GPT 4.0?

### ISSUE THREAD

**Issue by Smellbourne** [Bin-Huang/chatbox#38]
Hello, I like your app.

Will you be adding support for the GPT 4 API? Apparently it is rolling out today.

Thanks!

**Comment by LifeNT** [comment]
好像GPT-4 API调用方式与GPT-3.5没有变化?但我又看到说目前新API只对测试者开放。

**Comment by Bin-Huang** [comment]
Of course, I will promptly add the support when GPT-4 becomes widely available.

**Comment by Smellbourne** [comment]
> Of course, I will promptly add the support when GPT-4 becomes widely available.

Do you think that will be soon? I have access to the API already and I'm not anyone special. As far as I can tell it should just be a matter of specifying the model to use in the API request. Maybe you could add a text field to the settings similar to the API URL field where we can specify the model to use? I'd also be curious to use their older models like GPT 3.

https://platform.openai.com/docs/models/gpt-4

Thank you again, don't mean to nag you.

**Comment by Bin-Huang** [comment]
> > Of course, I will promptly add the support when GPT-4 becomes widely available.
> 
> Do you think that will be soon? I have access to the API already and I'm not anyone special. As far as I can tell it should just be a matter of specifying the model to use in the API request. Maybe you could add a text field to the settings similar to the API URL field where we can specify the model to use? I'd also be curious to use their older models like GPT 3.
> 
> https://platform.openai.com/docs/models/gpt-4
> 
> Thank you again, don't mean to nag you.

I am still on the waiting list😭😭😭

**Comment by joegoldin** [comment]
@Bin-Huang I got API access this am but had to wait to get home from work to implement this: https://github.com/Bin-Huang/chatbox/pull/66

**Comment by joegoldin** [comment]
> > Of course, I will promptly add the support when GPT-4 becomes widely available.
> 
> Do you think that will be soon? I have access to the API already and I'm not anyone special. As far as I can tell it should just be a matter of specifying the model to use in the API request. Maybe you could add a text field to the settings similar to the API URL field where we can specify the model to use? I'd also be curious to use their older models like GPT 3.
> 
> [platform.openai.com/docs/models/gpt-4](https://platform.openai.com/docs/models/gpt-4)
> 
> Thank you again, don't mean to nag you.

The Chat API actually only allows `gpt-3.5-turbo`, `gpt-3.5-turbo-0301`, `gpt-4`, and `gpt-4-0314`. You can only use the other models with the Completion API.

**Comment by joegoldin** [comment]
It also definitely costs more 😭 I've spent a whole ten cents testing!! 😂

**Comment by Smellbourne** [comment]
> > I'd also be curious to use their older models like GPT 3.
> 
> The Chat API actually [only allows](https://platform.openai.com/docs/models/model-endpoint-compatibility) `gpt-3.5-turbo`, `gpt-3.5-turbo-0301`, `gpt-4`, and `gpt-4-0314`. You can only use the other models with the Completion API.
> 
> Edit: `gpt-4-32k` and `gpt-4-32k-0314` work too, I don't have access to those yet though 😭

Interesting, did not know that. Thank you guys for your great work.

**Comment by joegoldin** [comment]
@Smellbourne Check out [version 0.1.5](https://github.com/Bin-Huang/chatbox/releases/tag/Chatbox-v0.1.15) 😉

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/Chatbox-v0.2.0
