### ISSUE TITLE
关于chatbox的响应速度

### ISSUE THREAD

**Issue by VanYe666** [Bin-Huang/chatbox#380]
从今天开始，发起提问之后，响应速度很慢，回复也是一个字一个字的出，很难受

**Comment by a5185330** [comment]
免费的API被限速了,没办法的

**Comment by iambonboncat** [comment]
其实也不算免费，还是得扣费用……

**Comment by Zhangsxphd** [comment]
我觉得不是免费限速问题，我是会员也有同样的问题。版本一更新，明显感觉变慢

> 免费的API被限速了,没办法的

**Comment by Bin-Huang** [comment]
我已经做了非常详细的测试，对比了不同版本之间的生成速度，最新版本的速度和以前**完全是一模一样的**（长文本生成的场景下，在我的网络中 v0.3.4 和 v0.2.x 都是每秒 16 个字符的生成速度），不存在变慢的问题。

如果你觉得变慢了，我认为可能有两个原因：
1. v0.3.4 采用了更加紧凑的布局，每一行包含的字符变多了，所以很容易产生每行生成速度变慢的错觉
2. 根据其他 Issues，OpenAI 近期可能对免费账户进行了限速，这个我不太了解，需要进一步考证。
