### ISSUE TITLE
接入0.3.4版本之后，chat的回复出现慢速

### ISSUE THREAD

**Issue by sugerlime** [Bin-Huang/chatbox#381]
安装完成0.3.4版本之后，chat的回复速度变的很慢。这是因为软件升级的问题，还是chat的API的问题

**Comment by cvbnt** [comment]
API问题，OPENAI对免费用户做了限速

**Comment by sugerlime** [comment]
哦！不过之前好像反应的速度好像还可以，就最近一段时间就有点慢了。

**Comment by Zhangsxphd** [comment]
是的，能明显感受到变慢了，我是会员也有同样的问题，不是因为对免费用户限速的问题。

> API问题，OPENAI对免费用户做了限速

**Comment by ITwolffy** [comment]
原来如此

**Comment by lxy-Jason** [comment]
有解决方案了吗?大佬们

**Comment by bravehearat** [comment]
我也是，之前用的0.2.9，响应一直很快，今天升级到0.3.4，明显速度慢了很多，经常会出现响应：几个字出来后要卡一会儿才继续往下写。求解决

**Comment by Dean-Dai** [comment]
两台电脑，同样的api，一个用0.3.4就很慢。 一个是0.2.9很快。另外还有0.3.4模型是GPT-2。  0.2.9的模型是GPT-3。也可能是这个问题引起的

**Comment by sugerlime** [comment]
我尝试了一下重新安装0.2.9版本，然后打开程序后，会被强制要求升级到0.3.4，再重新安装0.3.4之后，chatGPT的反馈速度就会快很多我。各位可以尝试以下。

**Comment by Bin-Huang** [comment]
感谢大家的反馈。可能是我最近一次升级导致的，因为我为了修复一些用户在极弱网环境下老是报错的问题做了很多冗余检查。我看下怎么优化…

**Comment by 626lj** [comment]
> 感谢大家的反馈。可能是我最近一次升级导致的，因为我为了修复一些用户在极弱网环境下老是报错的问题做了很多冗余检查。我看下怎么优化…

感谢大佬

**Comment by Bin-Huang** [comment]
我已经做了非常详细的测试，对比了不同版本之间的生成速度，最新版本的速度和以前**完全是一模一样的**（长文本生成的场景下，在我的网络中 v0.3.4 和 v0.2.x 都是每秒 16 个字符的生成速度），不存在变慢的问题。

如果你觉得变慢了，我认为可能有两个原因：
1. v0.3.4 采用了更加紧凑的布局，每一行包含的字符变多了，所以很容易产生每行生成速度变慢的错觉
2. 根据其他 Issues，OpenAI 近期可能对免费账户进行了限速，这个我不太了解，需要进一步考证。

**Comment by wuyuezhui** [comment]
今天更新到0.0.5后，速度恢复了，很给力
