### ISSUE TITLE
[Other] About OpenAI API Key code and API request failed. 

### ISSUE THREAD

**Issue by EleTing** [Bin-Huang/chatbox#382]
Hi, these are my question below: 
1: May I ask what I should type in the box of 'OpenAI API Key' from the setting? 
2: When I type some questions, it just shows 
'API Request Failed:
Copy
{"error":{"message":"You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":null}}' 

Thank you for your help.

**Comment by myworksfun** [comment]
reference  error tips：“You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth”。
