### ISSUE TITLE
[BUG]Win10安装后，打开时白屏，无法正常打开使用

### ISSUE THREAD

**Issue by Jone-Chan** [Bin-Huang/chatbox#387]
**Bug 描述**
Win10安装后，打开时白屏，无法正常打开使用，而且点击关闭窗口按钮无法关闭，只能通过任务管理器结束进程才能关闭。
![image](https://user-images.githubusercontent.com/57897644/230752217-dbb2a064-a0ca-4c22-a5ae-5afcccce2723.png)

**重现步骤**
下载最新的chatbox_0.3.4_x64_en-US.msi安装，安装后运行，运行后就如上图所示，白屏无法正常运行。
系统版本：Windows 10 专业版 22H2

**桌面端（请填写以下信息）：**
- 操作系统：Windows 10 专业版 22H2
- 应用程序版本：0.3.4_x64

**Comment by liangjiacun** [comment]
我也是

**Comment by yuzhaofeng** [comment]
我也是 如何解决啊

**Comment by andyxman** [comment]
Chatbox-v0.3.5 在 Windows 11 专业版 22H2 上也出现相同情况，无法正常运行

**Comment by 543670663** [comment]
解决方法：属性 兼容性 换成win7解决

**Comment by dzucwf** [comment]
same problem.

**Comment by Jone-Chan** [comment]
> 解决方法：属性 兼容性 换成win7解决

请问在哪里设置属性？软件白屏，没有地方设置

**Comment by Jone-Chan** [comment]
> 解决方法：属性 兼容性 换成win7解决
