### ISSUE TITLE
[Other]win11，之前使用正常，现在不能打开软件了，闪了一下就退出了

### ISSUE THREAD

**Issue by zxy67** [Bin-Huang/chatbox#388]

**Comment by AlieinApril** [comment]
我是win10 ，也是打开就直接闪退

**Comment by zxy67** [comment]
我的AMD的处理器，是不是和处理器有关？

**Comment by WuDi-ZhanShen** [comment]
加一，一闪而过，没有任何提示之类的

**Comment by Konseru** [comment]
不知道你解决了没有，如果没有的话可以尝试一下以下方法:
在安装的应用中找到Microsoft Edge WebView2 Runtime 点击右侧的 `...`，然后点击修改选择修复。
![image](https://user-images.githubusercontent.com/90184282/231532452-a7649666-894f-4cc9-a2c8-1f9ecf8aaf68.png)
![image](https://user-images.githubusercontent.com/90184282/231533890-e2a992b5-9c31-4b3f-aa92-00890e663f6c.png)

**Comment by WuDi-ZhanShen** [comment]
> 不知道你解决了没有，如果没有的话可以尝试一下以下方法: 在安装的应用中找到Microsoft Edge WebView2 Runtime 点击右侧的 `...`，然后点击修改选择修复。 ![image](https://user-images.githubusercontent.com/90184282/231532452-a7649666-894f-4cc9-a2c8-1f9ecf8aaf68.png) ![image](https://user-images.githubusercontent.com/90184282/231533890-e2a992b5-9c31-4b3f-aa92-00890e663f6c.png)

非常感谢您！我的电脑没有管理员权限，因此无法做到System-Level安装Microsoft Edge WebView2 Runtime。我也尝试了将Microsoft Edge WebView2 Runtime仅为当前用户安装，提示安装成功，但是ChatBox最新版依旧闪退。现在我找到了ChatBox 0.17版本（最后一个安装包体积很大的版本，约100MB），可以在我电脑上正常使用。如果用更高的版本就会闪退了。

我不太了解Windows上的这些软件的开发框架，但是我猜测ChatBox的软件核心部分应该并不大且很容易移植，请问您是否有好办法可以将最新版的ChatBox的核心部分移植进0.17版本中？非常感谢您！

**Comment by Bin-Huang** [comment]
你好，新版本做了修复，下载最新版本再试一下？https://github.com/Bin-Huang/chatbox/releases

**Comment by WuDi-ZhanShen** [comment]
非常感谢您！因为公司电脑没有管理员权限，因此msi格式的安装包无法在我公司电脑上安装。不过我现在正在使用网页版ChatBox，效果非常不错，大大提升了我的工作效率。感谢您的付出！
