### ISSUE TITLE
[Feature]在推特看到MemoryGPT，不知道有没有可借鉴性

### ISSUE THREAD

**Issue by jackdiy** [Bin-Huang/chatbox#389]
Problem Description
When chatting with ChatGPT, it is common to encounter the problem of forgetting. Although this is due to limitations in the OpenAI API, it seems that some people have been trying to solve it.

Solution Idea
Today, I saw a guru demonstrating this on Twitter: https://twitter.com/rikvk01/status/1644787327057776645
He said the test will be open next Tuesday.

-----------------------

**问题描述**
与ChatGPT聊天时经常遇到它失忆的问题，虽然这是OpenAI对API的限制导致，但似乎一直有一些人在想办法解决它

**解决思路**
今天在推特看到一位大神演示了这个：https://twitter.com/rikvk01/status/1644787327057776645
他说下周二开放测试

**Comment by LipYoung** [comment]
这个大神,思路也不讲.代码也不贴出来.藏着掖着的.靠

**Comment by Bin-Huang** [comment]
其实我大概知道背后的实现思路，就是不断地让GPT总结以往的聊天记录，然后存储在本地的向量数据库中。这么做的话非常消耗tokens……
