### ISSUE TITLE
建议添加整理导出聊天记录的功能，输出报告

### ISSUE THREAD

**Issue by LifeNT** [Bin-Huang/chatbox#39]
很多时候，我们需要把chatgpt的反馈转发给其它人、或者自己的其它设备，或用来存储备份。
目前我能想到的数据保存、传递方式无非就是
1、复制文本或截图后发送。
2、导出本地聊天数据。
3、利用一些第三方的浏览器插件比如印象笔记的插件。
这些方式都可以解决一部分需求，但都不能充分发挥第三方软件的优势：那就是对内容的强大编辑整理能力，加上GPT自己还能参与编辑，若能有这么一个功能：
1、由用户选择需要输出的聊天记录，然后让GPT整理出一份摘要，摘要也允许用户编辑。
2、提供可定制的输出模板，由软件输出为完整的报告，报告结构采用“摘要+正文（带目录）”的方式。
3、模板应有一定的基本规则，能够让查看的人一眼认出是ChatGPT生成。
4、模板应该能识别针对选定的内容由chatgpt多次生成几个备选答案，在正文中只显示一份用户选定的答案，但模板能存储所有chatgpt输出答案，提供某种方式让用户查看，这会使报告的意义更大。

这个功能会使得与ChatGPT的交互变成了更正式的“创作”，最终能以完整的报告文章的方式得到一个相对严谨的结果，可以方便的与其它用户、朋友同事进行交流。

这种报告存储格式会是个问题，也许PDF会比较容易实现，或者用mhtml的帮助格式？

**Comment by orangelckc** [comment]
这个不就是微软发布会上演示的365 Copilot！！！
目前chatgpt的对话直接保存截图（全文截图），或者输出成markdown格式以供下载是最方便的（chatgpt原生返回markdown）

**Comment by wuyudi** [comment]
![image](https://user-images.githubusercontent.com/30024051/233791159-caa7c6c7-2cd7-4ffc-bb9f-30b589ecb558.png)

**Comment by Bin-Huang** [comment]
新版本已经支持了
<img width="223" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/3b4cdb63-cd2c-49de-993d-690c3cffecfa">

<img width="694" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/96cf23c5-4229-4af1-9eff-7802954217ec">
<img width="1419" alt="截屏2024-05-14 20 53 39" src="https://github.com/Bin-Huang/chatbox/assets/20723142/1de9c589-4791-48b2-86ca-5d05145a96cf">

**Comment by SoDebug** [comment]
> 新版本已经支持了 <img alt="image" width="223" src="https://private-user-images.githubusercontent.com/20723142/330435264-3b4cdb63-cd2c-49de-993d-690c3cffecfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDM3ODQsIm5iZiI6MTczMzgwMzQ4NCwicGF0aCI6Ii8yMDcyMzE0Mi8zMzA0MzUyNjQtM2I0Y2RiNjMtY2QyYy00OWRlLTk5M2QtNjkwYzNjZmZlY2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA0MDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYjhjNzBhODg3NTNlMTgwZGU4ZTFmOWQyY2JhNTdkNTZjYjIzN2Q3M2M0NjA5NGZiMTFkNjk0MjAxMjBhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pJbfIwROR4AZejSszwwsGA_hHb4kfjXK9QOrWojdlvI">
> 
> <img alt="image" width="694" src="https://private-user-images.githubusercontent.com/20723142/330435124-96cf23c5-4229-4af1-9eff-7802954217ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDM3ODQsIm5iZiI6MTczMzgwMzQ4NCwicGF0aCI6Ii8yMDcyMzE0Mi8zMzA0MzUxMjQtOTZjZjIzYzUtNDIyOS00YWYxLTllZmYtNzgwMjk1NDIxN2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA0MDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNzI5ZDRhNjYzMmViOGMwY2Y3ODdkMzhlZjk5NjkzOThiNGE5M2I2M2YyODA0ZWY2N2Q1MGZlMzUzMDc4OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.d_IjiAG-hq7KOjoQjwENr4qZEE3gYzQ3mWIv1RNFlUo"> <img alt="截屏2024-05-14 20 53 39" width="1419" src="https://private-user-images.githubusercontent.com/20723142/330436330-1de9c589-4791-48b2-86ca-5d05145a96cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MDM3ODQsIm5iZiI6MTczMzgwMzQ4NCwicGF0aCI6Ii8yMDcyMzE0Mi8zMzA0MzYzMzAtMWRlOWM1ODktNDc5MS00OGIyLTg2Y2EtNWQwNTE0NWE5NmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDA0MDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YmUyMjk1MDM3NDBiMTA5OTBjMDZhYTk3OGJjNmNhNGViY2I3M2M1YzU0NTRkNWE3ZWVmNzUyYjFmNTMwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pYeBeGWLRVmKbt53monAVWUZg9pILNH_1hK5MmqKJ-M">

这个导出的路径是哪儿啊，没看到

**Comment by Bin-Huang** [comment]
@SoDebug 请问使用的是社区版吗？建议改成官方版～

**Comment by SoDebug** [comment]
> @SoDebug 请问使用的是社区版吗？建议改成官方版～

我从play上面下载的
