### ISSUE TITLE
[Other]左侧对话栏菜单按钮没必要隐藏

### ISSUE THREAD

**Issue by graycz** [Bin-Huang/chatbox#391]
[Chatbox v0.3.1]以及之后的版本，左侧对话栏菜单按钮平时处于隐藏状态，鼠标放上去才会显示菜单按钮（三个点），但是显示的同时就会挤到右侧的对话框，导致右侧对话框向右移动，然后又恢复正常，肉眼看上去就是不停闪烁的感觉。
建议加入左侧对话栏菜单按钮是否显示功能，或者加入自主调节左侧对话栏宽度的功能。

**Comment by Bin-Huang** [comment]
v0.3.5 版本已经没有右侧菜单了
