### ISSUE TITLE
为了方便手机使用，暂时把chatbox转成网页模式

### ISSUE THREAD

**Issue by nufeng1999** [Bin-Huang/chatbox#393]
https://mychat.epizy.com/

所有参数均保存在浏览器中。
移动版edge chrome 均可。![Screenshot_2023-04-10-14-38-33-69.jpg](https://user-images.githubusercontent.com/28748029/230842578-fd34bc8c-6e02-40aa-9148-6c12db7f342e.jpg)

**Comment by leonlincc** [comment]
可以，提过意见要作者搞一个移动版的，估计是没时间，没顾得上这头，这个临时方法挺不错！

**Comment by leonlincc** [comment]
我直接用我的小屏幕设备打开这个页面，发现左边话题列表默认只显示一个图标，右边的字体偏小了一点点，正好不影响阅读的情况下同屏幕能容下更多内容！！这个调整不错！

**Comment by nufeng1999** [comment]
> 我直接用我的小屏幕设备打开这个页面，发现左边话题列表默认只显示一个图标，右边的字体偏小了一点点，正好不影响阅读的情况下同屏幕能容下更多内容！！这个调整不错！

目前只是简单的适配了 微软和google 的浏览器，其它的浏览器可能不正常

**Comment by nufeng1999** [comment]
> 可以，提过意见要作者搞一个移动版的，估计是没时间，没顾得上这头，这个临时方法挺不错！

花了点时间，把语音输入加上了。

**Comment by LipYoung** [comment]
挺好的啊,创建PR,按照符合现在的代码规范,把代码提交上来啊.让大家去访问你的网站就不太好了.别人不会给你KEY,提供源码,让用户自己部署

**Comment by Bin-Huang** [comment]
移动端是要做的，可能就是几周内的事情了

**Comment by nufeng1999** [comment]
> 挺好的啊,创建PR,按照符合现在的代码规范,把代码提交上来啊.让大家去访问你的网站就不太好了.别人不会给你KEY,提供源码,让用户自己部署

这个web分支仅仅是为了手机使用方便，Key也仅保存在浏览器中，服务器仅仅只有代码。

**Comment by wuyuezhui** [comment]
为啥现在进不去了
“

**Comment by nufeng1999** [comment]
> 为啥现在进不去了
> “

https://nufeng1999.github.io 换地方了
