### ISSUE TITLE
[BUG]chatbox使用gpt3.5提示4.0模型不可用

### ISSUE THREAD

**Issue by VanYe666** [Bin-Huang/chatbox#394]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
chatbox使用gpt3.5提示4.0模型不可用

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
设置好之后与chatgpt聊天

**期望结果**
正常回应
**实际结果**
提示我4.0模型不可用
**截图**

**桌面端（请填写以下信息）：**
- 操作系统：windows
- 应用程序版本0.3.4

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
下载最新版本，已经修复
