### ISSUE TITLE
[BUG] 我问他是什么版本,他说他不是GPT,是我的设置有问题吗?

### ISSUE THREAD

**Issue by HaohuaLin** [Bin-Huang/chatbox#395]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/59164470/230847054-b2847fab-c292-49fb-ae2c-76711efea650.png">

<img width="549" alt="image" src="https://user-images.githubusercontent.com/59164470/230847130-28505373-c09c-4f27-a878-76668742cb7f.png">

**Comment by wuyudi** [comment]
不是这软件的问题，然后 gpt 只是 LLM，不保证生成内容的正确性。

**Comment by myworksfun** [comment]
![Snipaste_2023-04-11_09-09-58](https://user-images.githubusercontent.com/45185967/231029383-bd164536-e3cb-45d0-9099-6dc992dd37b0.png)

**Comment by Bin-Huang** [comment]
众所周知GPT最不了解的是自己
