### ISSUE TITLE
[BUG] Can not use HTTP Proxy

### ISSUE THREAD

**Issue by JiajunDou** [Bin-Huang/chatbox#396]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Setting Proxy
2. Input http://127.0.0.1:10809

**Expected Results**

My proxy return bellow error
```
failed to read http request > malformed HTTP request "\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03Qt\x12\xf6|\a\xd5\xf4\x1c\x04\x03}[\x02\xb6;\xf9\x87\xb2.\x99K*\xa9\xdc!zq)\x9c\xb8\x82 \x13ZP\xe7\x1a\x14j\x8d~\xa6Z\x13R0:\x01\xa9ߘ\xf9t\xbe\xe6\xf9\xa2d\x99-\xcbj7\xed\x00\"\xfa\xfa\x13\x01\x13\x02\x13\x02\x13\x03\xc0+\xc0/\xc0,\xc00̨̩\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x01\x91"
```

**Actual Results**
Can not use Local Http Proxy!!! 

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: Windows 11
- Application Version: V2Ray

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Comment by Bin-Huang** [comment]
This issue has been resolved in the latest version. Give the newest version a try:
https://github.com/Bin-Huang/chatbox/releases

**Comment by terryzwt** [comment]
@Bin-Huang 可不可以在软件上提供proxy的配置？最近发现api2d不用代理不稳定。
