### ISSUE TITLE
[Feature]加入类似 WebChatGPT的功能，让他能获得最新的百度、bing、google讯息的功能。

### ISSUE THREAD

**Issue by leonlincc** [Bin-Huang/chatbox#397]
rt,如果有了这个功能，可以提高我们沟通的效率以及准确性。

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1238, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1238。这条 issue 先关闭了～～
