### ISSUE TITLE
[Feature]为输入框绑定一个快捷键。

### ISSUE THREAD

**Issue by buddhiko1** [Bin-Huang/chatbox#399]
**问题描述**
没有快捷键激活输入框。
每次打开软件或者执行过复制之后都要手动在输入框点击鼠标重新获得focus，感觉非常不方便。

**解决思路**
添加一个快捷键(例如 Ctril+i)获取输入框的focus即可。这样就不用在鼠标和键盘之间来回切换。

**附加上下文**

**Comment by Bin-Huang** [comment]
可以提一个PR～
