### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by kangyiwen** [Bin-Huang/chatbox#4]
下载你这个后，直接把我同事写的EXE给删了。

提点建议：
1.  模仿微信的回车逻辑： 回车直接发送，Shift+回车 聊天换行。  当然这个可以做成可配置那就最好了。
2.  每段话，增加 复制 按钮，或者默认GPT回复的最后一段话，默认放剪贴板。
3.  希望菜单做个中文版。

**Comment by aloasut** [comment]
附议，默认是回车发送就很好。因为使用中很多连续输入的场景，需要不断按组合键发送很讨厌。
更多建议：
1.允许自己配置频道，新建的时候自动发送prompt。
2.允许一键清空当前频道的历史信息。而不是通过删除频道实现。

**Comment by Bin-Huang** [comment]
@kangyiwen @aloasut 回车发送已经实现了，下载最新的 v0.0.6 版本试试

**Comment by Bin-Huang** [comment]
中文菜单很快也会有了，按排做了
