### ISSUE TITLE
API请求失败[BUG]

### ISSUE THREAD

**Issue by Andywang089** [Bin-Huang/chatbox#401]
-------------------------------------

**Bug 描述**
之前可以正常使用，最近无法正常使用，显示API请求失败，已create new API，还是出现同样错误。个人ChatGPT3.5官网可以正常使用，但是chatbox出现API请求失败情况。

**截图**
<img width="564" alt="1" src="https://user-images.githubusercontent.com/15190823/231030286-ccc03bce-5e22-4820-9ede-c6076fc2b11e.png">

**桌面端（请填写以下信息）：**
- 操作系统：win11
- 应用程序版本：chatbox 最新版0.3.4

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by yhl10000** [comment]
我遇到这个问题很久了, 我只有一个API key.

**Comment by laksg2009** [comment]
我今天用，被封了。。。。

**Comment by GGB121** [comment]
这是节点问题吧

**Comment by laksg2009** [comment]
我换个试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月11日(周二) 下午3:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Bin-Huang/chatbox] API请求失败[BUG] (Issue #401)




 
这是节点问题吧

**Comment by myworksfun** [comment]
@Andywang089  Translate the error message below and you'll understand that it has nothing to do with the chatbox bug.
**"You exceeded your current quota, please check your plan and billing details."**

**Comment by laksg2009** [comment]
> 这是节点问题吧

搞定

**Comment by wangensi** [comment]
> > 这是节点问题吧
> 
> 搞定

怎么搞定的？重新注册了账号还是换了节点？

**Comment by Bin-Huang** [comment]
其实原因已经在错误里了。API 账户和 ChatGPT 账户是 OpenAI 两套独立的账户体系。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。
这个问题和软件没有任何关系。
如果你不想折腾 API 账户的各种问题的话，强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0

**Comment by Andywang089** [comment]
> 其实原因已经在错误里了。API 账户和 ChatGPT 账户是 OpenAI 两套独立的账户体系。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。
> 这个问题和软件没有任何关系。
> 如果你不想折腾 API 账户的各种问题的话，强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种技术和账户问题。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0

感谢感谢，我试一试
