### ISSUE TITLE
[Feature]怎样使用chatbox发送图片？

### ISSUE THREAD

**Issue by hygood** [Bin-Huang/chatbox#403]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
chatgpt对话速度很快，但我常需要让chatgpt分析图片，但发现chatgpt没有发送图片的功能。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by nufeng1999** [comment]
!()[http://asdlfj.com/test.png]
试试这种方法

**Comment by Bin-Huang** [comment]
需要用markdown格式
