### ISSUE TITLE
[Other]一些功能优化建议

### ISSUE THREAD

**Issue by Zhujiankai123** [Bin-Huang/chatbox#404]
1. 希望能够增加一个“停止”功能，网络环境不好的时候，重复发送会导致两个地方同时在输出结果，页面上下跳来跳去的很难受。而且有时候回答的不是自己需要的内容时，很需要停下来补充提问细节来让他重新回答
2. 左下角版本那里一直显示一个提示更新的小蓝点，即使目前已经是最新版本了
<img width="172" alt="image" src="https://user-images.githubusercontent.com/36138496/231107899-1573a02d-48c6-4069-82d2-a3e5647882aa.png">
3. 建议提供图标修改/选择功能，或着你们重新换一个图标，这个版本的图标真的是很丑啊。。。
<img width="54" alt="image" src="https://user-images.githubusercontent.com/36138496/231108149-6c574cb5-f708-4eec-b5e8-4d8dc88a8dbc.png">

**Comment by Bin-Huang** [comment]
I feel like this issue is a bit outdated, so I went ahead and closed it. But if you think it's necessary, feel free to create a new issue at any time.
