### ISSUE TITLE
[Other] 回答差异、system prompt

### ISSUE THREAD

**Issue by AlvinCZ** [Bin-Huang/chatbox#406]
感觉Chatbox中ChatGPT回答总是比OpenAI官方的（以及其他类似api平台的）短很多，内容不够丰富详细，甚至出现其他平台没有的错误（例如我测试的问题：蓝牙耳机坏了应该去看牙科医生还是去看耳科医生，Chatbox有概率回答看耳科医生，而openai的会指出问题）。另外，Chatbox不能设置system prompt，希望添加类似的功能。（不知道是不是没有system prompt导致的回答问题不详细？）

v0.3.4 gpt-3.5-turbo

**Comment by AlvinCZ** [comment]
我利用可以修改system prompt的平台试了一下。当system prompt为空时，针对“蓝牙耳机坏了应该去看牙科医生还是去看耳科医生”这个问题，同样会有概率出现错误回答（不知道其他问题的正确性是否也会受到影响），当system prompt为“You are a helpful assistant, your answers should be informative and constructive”时，回答就正常了很多

**Comment by LipYoung** [comment]
@Bin-Huang 建议增加一个在System里面写注释的功能.
例如:
```
// 你是一个热情的助理
You are a passionate assistant.
```
实际提交到API的内容是没有注释那一行的.

这样做的目的是方便使用英文进行一些设置.因为英文的token更少,效果更好.希望你能考虑下
