### ISSUE TITLE
[BUG] 代码块在文字输出时不能左右滑动

### ISSUE THREAD

**Issue by hahaha28** [Bin-Huang/chatbox#408]
首先感谢大佬辛苦付出，提一个小bug
回答中包含可以左右滑动的代码块时，如果正在输出文字，代码块无法左右滑动，只能固定在最左边，有点影响阅读，希望大佬能改进一下，感谢

**Comment by Bin-Huang** [comment]
试试新版本，这个问题我可能很早前修复过了
