### ISSUE TITLE
关于chatbox聊天框中的系统内容设置问题。

### ISSUE THREAD

**Issue by chunfengchuilaoseng** [Bin-Huang/chatbox#409]
昨天我在聊天框中给当前会话设置了系统内容，
![1](https://user-images.githubusercontent.com/115630423/231184745-4e68ab33-41cb-43f4-a201-3c7a6125f211.png)
类似于这种系统设置我设置了几个，当时用的时候没有问题它能记住，今天我再打开聊天界面问它设置的内容时它就不记得了，是我设置的有问题？还是每天会话前都得给它重新发一遍？
有谁用过这个功能的科普一下。

**Comment by LipYoung** [comment]
自己多看看官方文档
