### ISSUE TITLE
建议增加聊天记录导出保存为文件的功能，例如导出截图、pdf、txt等。

### ISSUE THREAD

**Issue by niuble6** [Bin-Huang/chatbox#411]
### 建议增加聊天记录导出保存为文件的功能，例如快捷导出截图、pdf、txt等。

网页版有一个油猴脚本实现了这样的功能，参考链接：[chatgpt-exporter](https://github.com/pionxzh/chatgpt-exporter)

希望这个基于api的本地chatGPT软件也能增加此功能，便于对聊天记录进行分享和备份。

**Comment by jerrylususu** [comment]
可以直接把聊天记录文件复制出来，就是一个大 JSON。
Windows 下在 `%APPDATA%\Roaming\xyz.chatboxapp.app\config.json`
https://github.com/Bin-Huang/chatbox/blob/c0f21f81f5399b526009c4708a61ab89133eaa54/src/api.ts#L27

**Comment by tshemeng** [comment]
%APPDATA%\xyz.chatboxapp.app\config.json

> 可以直接把聊天记录文件复制出来，就是一个大 JSON。 Windows 下在 `%APPDATA%\Roaming\xyz.chatboxapp.app\config.json`
> 
> https://github.com/Bin-Huang/chatbox/blob/c0f21f81f5399b526009c4708a61ab89133eaa54/src/api.ts#L32

%APPDATA%包含Roaming路径，实际文件是 %APPDATA%\xyz.chatboxapp.app\config.json

**Comment by Bin-Huang** [comment]
目前版本可以导出 txt/markdown/html 格式，可以试试看
