### ISSUE TITLE
[Feature]增加直接到底的快捷键，或者点开话题的时候，直接到达底部

### ISSUE THREAD

**Issue by my7yilink** [Bin-Huang/chatbox#412]
现在对话内容越来越多，第二天打开时，会默认到顶部，但主要需求是想继续昨天的话题，所以最好

1   默认到话题最后

2  随着话题的深入，对有价值的对话内容就有了收藏的需求。可以考虑加入一下

3 话题展开的讨论越来越多，就会造成加载内容影响内存的问题，分步加载需要考虑一下

**Comment by Bin-Huang** [comment]
新版本有了
