### ISSUE TITLE
能否取消对话自动跳转

### ISSUE THREAD

**Issue by Atomadeus** [Bin-Huang/chatbox#417]
例如当我在对话A中提交问题后，等待GPT回答的这段时间我转到对话B中查看内容，但是对话A一旦接收到数据后就将当前页面跳转回对话A了，能否将这个跳转功能设置为可选的呢？

**Comment by Bin-Huang** [comment]
很早之前的版本已经实现了，可以更新一下，先关闭了这条 issues 了。
