### ISSUE TITLE
关于API-KEY失效的问题

### ISSUE THREAD

**Issue by PengTao259** [Bin-Huang/chatbox#418]
用了产品大概几天，现在整个API的调用都被ban了，只有chatGPT官方的聊天还可以用，请问软件这边有没有上传用户API-KEY的行为？

**Comment by Bin-Huang** [comment]
软件是完全开源的，没有上传你的key。你帐号被封禁应该是其他原因。

**Comment by PengTao259** [comment]
好的，谢谢您解答疑惑
