### ISSUE TITLE
功能建议：代码一键复制

### ISSUE THREAD

**Issue by Lenvia** [Bin-Huang/chatbox#42]
Web端AI输出的代码段，右上角有复制按钮。当前chatbox只能鼠标拖动。希望添加一下这个小功能，感谢

**Comment by winner106** [comment]
附议，同时建议可以选择直接返回 markdown 纯文本，这样就能直接把回复的内容放入笔记中，那就真是太方便了！

**Comment by nantongxue** [comment]
常规的生成内容，支持鼠标右键点击ai回复的消息卡片即直接成功复制（或者像pc的微信消息一样，鼠标右键消息卡片即默认全选中消息内容同时右键菜单中有复制选项）
现在的复制内容操作入口太不方便了……

**Comment by KingJadeLight** [comment]
> 附议，同时建议可以选择直接返回 markdown 纯文本，这样就能直接把回复的内容放入笔记中，那就真是太方便了！

对，像typingmind那样提供raw格式按钮。

**Comment by Bin-Huang** [comment]
@KingJadeLight @winner106 复制消息全部 raw 内容的话，直接点击现在的复制按钮就行。代码块的复制在计划中，但在这几天的规划里优先级不高。如果有人感兴趣实现，非常欢迎贡献 PR。
