### ISSUE TITLE
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}[BUG]

### ISSUE THREAD

**Issue by hcymysql** [Bin-Huang/chatbox#422]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
这得花钱购买VIP账号吗？

**Comment by ruirui1128** [comment]
我也是同样的问题

**Comment by philau** [comment]
same

**Comment by lingtianfeng** [comment]
刚下载的，也是一样的问题。不管是用GPT4还是GPT3

**Comment by LesterLJS** [comment]
我差点去买会员。

**Comment by Bin-Huang** [comment]
大家看清楚错误信息，或者翻译一下都行啊。这是账户问题，没有绑定信用卡。和软件没有关系。

**Comment by qixuema** [comment]
> 大家看清楚错误信息，或者翻译一下都行啊。这是账户问题，没有绑定信用卡。和软件没有关系。

麻烦问一下，没有信用卡怎么办呢？

**Comment by changliu21** [comment]
所以没信用卡用不了呗，算了算了

**Comment by qixuema** [comment]
实测，换节点可以用，我这边是所有的美国节点都被禁了，换成德国或者法国的节点，还是可以接着用（PS：亚洲的节点虽然也可以，但还是不放心）

**Comment by Programmingmakesmebald** [comment]
怎么解决的啊？

**Comment by Bin-Huang** [comment]
其实原因已经在错误里了。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。

这个问题和软件没有任何关系。

如果你不想折腾 API 账户的各种问题的话，**强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题**。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0

**Comment by Bin-Huang** [comment]
> > 其实原因已经在错误里了。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。
> > 这个问题和软件没有任何关系。
> > 如果你不想折腾 API 账户的各种问题的话，**强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题**。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0
> 
> 不是的，同一个账号的GPT-3.5-turbo，我用网页版会提示Quota exceeds, 用0.4.5 windows PC版就没问题。应该存在API调用Bug。

感觉不是同一个KEY？

**Comment by bumprat** [comment]
> 

不好意思，是我弄错了，确实不是同一个Key。
