### ISSUE TITLE
[BUG]一直提示Failed to fetch是什么问题

### ISSUE THREAD

**Issue by helloo2020** [Bin-Huang/chatbox#427]
![Uploading image.png…]()
使用的API，有余额，账户用网页登陆也没问题。帮忙看看，谢谢！

**Comment by zhyf08** [comment]
没设代理之前我的也一直提示Failed to fetch，一次都没成功过；后来在我外网的VPS上用nginx反向代理到openai，然后再在chatbox里修改“代理->API域名”设置后才算能正常使用了。

**Comment by zhyf08** [comment]
搜索一下【nginx 反向代理 openai】

**Comment by Bin-Huang** [comment]
如果你懒得处理那些特殊的网络问题，API HOST 改成 https://proxy2.chatbox.run/ 就可以了
