### ISSUE TITLE
[Other]使用VPN时有时无法使用

### ISSUE THREAD

**Issue by sqjshr** [Bin-Huang/chatbox#428]
发现用VPN时，网页智能模式时，无法正常联网。（这种模式最方便，最常用）
使用网卡智能模式时，可以正常联网，但有些网页却没办法正常访问了（不常用不好用的模式）。
能不能优化一下，普通网页智能模式时，APP也能上网呢？

**Comment by leviyanx** [comment]
这应该是你的vpn软件设置的问题，不是这个软件的问题

**Comment by Bin-Huang** [comment]
试试最新版本
https://github.com/Bin-Huang/chatbox/releases
