### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by aimo6** [Bin-Huang/chatbox#43]
这是什么类型的项目，需要怎么启动，求解答

**Comment by wuyudi** [comment]
> 这是什么类型的项目

这是桌面客户端项目。

> 需要怎么启动

去 release 下载你的系统的包，运行，输入 api

**Comment by Bin-Huang** [comment]
上面回答的很好，如果你是想进行开发的话，需要安装 Node.js 环境，然后运行 `npm install` 安装依赖，然后 `npm start` 启动开发环境

**Comment by Bin-Huang** [comment]
还有其他问题吗？没有的话我 Close 评论了？

**Comment by aimo6** [comment]
> > 这是什么类型的项目
> 
> 这是桌面客户端项目。
> 
> > 需要怎么启动
> 
> 去 release 下载你的系统的包，运行，输入 api



> 还有其他问题吗？没有的话我 Close issue了？

没有了，谢谢
