### ISSUE TITLE
[Feature]希望能添加一个锁定某条聊天消息的功能

### ISSUE THREAD

**Issue by manjarooh** [Bin-Huang/chatbox#430]
**问题描述**
因为gpt3.5模型的token是有限的，软件会一直上传聊天记录来让chatgpt产生上下文联系。但是聊天记录一旦过多，token就会超出并报错，如果每次都要手动删除，会比较麻烦。虽然软件带了一键清除聊天记录功能，但某些信息我是想保留的，所以我希望能添加锁定聊天记录的功能。

**解决思路**
如下图的位置上添加一个锁定按钮，主要目的就是在使用一键清除按钮时可以保留该聊天记录。
**附加上下文**
[https://i.328888.xyz/2023/04/13/ig3FSV.png](url)

**Comment by Bin-Huang** [comment]
首先，chatbox 会处理好上下文，理论上是不会报错的。可能是你修改了默认的一些设置，建议把设置窗口的模型和Token 部分的设置重置。
其实从 v0.0.1 版本就支持“锁定”，点击消息的编辑，把消息的角色改成系统就行了。当然操作入口有点深，已经准备好优化了。

**Comment by lovitus** [comment]
> 首先，chatbox 会处理好上下文，理论上是不会报错的。可能是你修改了默认的一些设置，建议把设置窗口的模型和Token 部分的设置重置。 其实从 v0.0.1 版本就支持“锁定”，点击消息的编辑，把消息的角色改成系统就行了。当然操作入口有点深，已经准备好优化了。

这个隐藏得有点深, 一直不知道怎么设置 . 如果设置成了system prompt可以置顶就好了. 这样自己也知道怎么限制的会话

**Comment by Bin-Huang** [comment]
> > 首先，chatbox 会处理好上下文，理论上是不会报错的。可能是你修改了默认的一些设置，建议把设置窗口的模型和Token 部分的设置重置。 其实从 v0.0.1 版本就支持“锁定”，点击消息的编辑，把消息的角色改成系统就行了。当然操作入口有点深，已经准备好优化了。
> 
> 我的意思是不断的聊天会导致token超出gpt3.5的模型大小，用久了会报token超出4096，只能删掉一些信息来减少上传的token。

我的意思是 Chatbox 会自动帮你解决上下文问题，不会报错token超出4096。现在报错了是因为你设置错误了
