### ISSUE TITLE
[BUG]在IT Expert对话框中，托条异常，其他对话框正常

### ISSUE THREAD

**Issue by wss-wss** [Bin-Huang/chatbox#437]
**Bug 描述**
在IT Expert对话框中，托条异常，其他对话框正常

**重现步骤**

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
![image](https://user-images.githubusercontent.com/67221565/231810227-f4423fe4-077c-4c11-aa0d-f83a2dbe7371.png)

**桌面端（请填写以下信息）：**
- 操作系统：Windows10
- 应用程序版本：0.3.5

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
很早之前的版本已经解决了，可以更新一下，先关闭了这条 issues 了。
