### ISSUE TITLE
[BUG]Mac版本的无法保存聊天记录和OpenAI密钥，只要关闭应用，全部数据都会丢失

### ISSUE THREAD

**Issue by asen888** [Bin-Huang/chatbox#440]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
请问是什么版本呢？系统是？

**Comment by AlexiaAnn** [comment]
我的电脑也是同样的问题，一旦退出，所有记录都会消失

**Comment by Bin-Huang** [comment]
版本是什么呢？系统是什么？

**Comment by asen888** [comment]
Version 0.4.0 (20230417.115813)， Mac 10.15.3 @Bin-Huang

**Comment by Braidy-Wu** [comment]
我的也是，测试了0.3.4和0.4.0，都有这个问题，系统是10.14.5
每次打开都需要重新输入API key才能用，而且没有聊天记录

**Comment by Bin-Huang** [comment]
属于很早期的问题，之前的更新中已经修复过了
