### ISSUE TITLE
使用api和网页版的回答不一样

### ISSUE THREAD

**Issue by yangyang0223** [Bin-Huang/chatbox#441]
如题，api似乎不如网页版的智能

**Comment by sunnyykk** [comment]
api更智能的吧~api是turbo版，是消耗openai账户余额的，而网页版好像是默认免费的

**Comment by huaqiang97** [comment]
> 

网页版更智能。可以尝试一下

**Comment by Bin-Huang** [comment]
这个和你的 prompt 有关

**Comment by nmww** [comment]
网页的经常出错误提示， 公众号更稳定些，但是总需要 ‘继续’

网页版本如何增加，多用户登录使用

**Comment by nmww** [comment]
网页版如何嵌入其他网站使用呢？

**Comment by nmww** [comment]
这个项目可以通过宝塔统一安装管理吗？

单独启动python项目  公众号的80端口；
和其他服务器网站项目， 80 冲突；   导致  打开的都是   这个项目的默认页面，这个如何调整呢

安装了traefic，docter  也没有很好的 调和两个项目

**Comment by nmww** [comment]
启动系统服务提示错；
`[INFO][2023-04-22 03:21:23][log.py:34] - [MultiChannel] Start up chatgpt on http
[ERROR][2023-04-22 03:21:23][log.py:47] - [MultiChannel] Start up failed on http: No module named 'flask_socketio'
[INFO][2023-04-22 03:21:23][wechat_mp_channel.py:39] - [WX_Public] Wechat Public account service start!
Bottle v0.12.25 server starting up (using AutoServer())...`

但实际的模块名称应该是   ‘flask-socketio’   而 不是  ‘flask_socketio’   杠在中间；

宝塔安装 python管理 模块 也是 ‘flask-socketio’     才可以成功；

但是 本程序启动报错是   `No module named 'flask_socketio'`

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/6917516/233759948-72dcd4e5-3204-4cbe-80dc-4645f59b2b89.png">
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/6917516/233759949-d0118a0b-7695-4a85-bcef-ef712f9c0c47.png">

**Comment by nmww** [comment]
<img width="916" alt="image" src="https://user-images.githubusercontent.com/6917516/233759981-f9704848-f568-48a4-be3d-10e4d284e1de.png">

**Comment by nmww** [comment]
`- [MultiChannel] Start up failed on http: cannot import name 'Namespace' from 'socketio' (/www/wwwroot/gpt.jingchengbang.com/bot-on-anything-master/62239e6c0f995ae1fdc00d18b7905eac_venv/lib/python3.9/site-packages/socketio/__init__.py)`

这属于什么情况呢，
模块安装了，
是python版本问题吗
