### ISSUE TITLE
能做到压缩上下文，减少token使用么？

### ISSUE THREAD

**Issue by nlj626** [Bin-Huang/chatbox#442]
看到一个ChatGPT Next Web的项目，其中有个功能是压缩上下文，减少token使用的，这点很赞。不知道chatbox是不是也可以借鉴下？

谢谢！

**Comment by Bin-Huang** [comment]
I feel like this issue is a bit outdated, so I went ahead and closed it. But if you think it's necessary, feel free to create a new issue at any time.
