### ISSUE TITLE
[Feature] have a field on the top to set the System parameter for a Chat 

### ISSUE THREAD

**Issue by agmuntianu** [Bin-Huang/chatbox#445]
**Problem Description**
Currently there is no easy way of setting the System instruction field for a Chat .

**Proposed Solution**
Between the Chat title and the first message sent to the API , add a text field to set the system prompt 

PS: Great tool !! 👍😁

**Comment by Bin-Huang** [comment]
This feature has been around for a while now, try updating it.

**Comment by cobbenterprises** [comment]
I'm running 1.0.2 and I don't see a way to add the custom system instruction.  Where is that located?
Thanks!

**Comment by Bin-Huang** [comment]
There are three ways:
1. Edit the first message of the conversation (which is usually a system message); this sets the prompt for the current conversation.
2. Click on 'My Copilots' > 'Create New Copilot'; this allows you to save a system prompt that can be used repeatedly.
3. Click on 'Settings' > 'Chat' > 'Default prompt for new conversation' to set the default prompt for each new conversation.

I hope I've understood your question correctly and that my answer is helpful. By the way, do you have any good ideas on how to prevent other new users from inadvertently encountering similar issues? ☺️☺️
