### ISSUE TITLE
希望回答问题支持友好的表格模式

### ISSUE THREAD

**Issue by pdgxiaofei** [Bin-Huang/chatbox#446]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.
当我要求gpt以列表的形式回答我的问题时，结果是这样的
![image](https://user-images.githubusercontent.com/37896719/232090603-81a78d6f-638e-404c-b93c-3083541c3b99.png)

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.
希望能像markdown一样展示友好的表格

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by pdgxiaofei** [comment]
这个有哪个大佬帮忙支持下，期待更友好的支持markdown格式

**Comment by Bin-Huang** [comment]
已经支持，查看最新版本
