### ISSUE TITLE
同样长度的文本，chatgpt网页可以发送，但是api显示超过4096token

### ISSUE THREAD

**Issue by Sheldontao** [Bin-Huang/chatbox#450]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/36765652/232225113-da3b57b1-867f-400d-8721-8131edf4cddb.png">

**Comment by Bin-Huang** [comment]
是不是修改了设置中的“模型与tokens”部分？点击重置按钮吧……

**Comment by Sheldontao** [comment]
它抱错的理由就是它这个模型token最大值就是4096，有没有可能chatgpt的最大值跟大了？有没有人知道
