### ISSUE TITLE
[BUG] UI is slow/laggy

### ISSUE THREAD

**Issue by claysauruswrecks** [Bin-Huang/chatbox#451]
**Bug Description**
UI is really slow/laggy for what the app does. Clicking on chat items, the animations are slow. Typing prompt is slow. Everything is slow.

**Steps to Reproduce**
1. Build/download AppImage
2. Run AppImage
```
git checkout v0.3.6
VERSION=0.3.6 make change-version
yarn
yarn tauri build
```

**Expected Results**
Expected fast UI.

**Desktop (please complete the following information):**
Ubuntu 20.04

**Comment by Bin-Huang** [comment]
Thanks a lot for your feedback. I'm working on resolving this issue as we speak.

**Comment by Bin-Huang** [comment]
This issue has been resolved in the latest version. Give the newest version a try:
https://github.com/Bin-Huang/chatbox/releases
