### ISSUE TITLE
[Feature]请增加对自定义API的支持

### ISSUE THREAD

**Issue by LifeNT** [Bin-Huang/chatbox#452]
越来越多的本地运行的模型被释放出来，请增加对自定义模型的支持：
允许输入受支持的API地址，允许自定义模型名称。

**Comment by hnbc2023** [comment]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by Magic-ming-ss** [comment]
顶！！！孩子觉得这确实需要！

**Comment by Bin-Huang** [comment]
@hnbc2023 你的问题是因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。
这个问题和软件没有任何关系。
如果你不想折腾 API 账户的各种问题的话，强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0
