### ISSUE TITLE
[BUG]  打开就闪退，有什么解决办法吗

### ISSUE THREAD

**Issue by lysasheng** [Bin-Huang/chatbox#453]

**Comment by enJoyFreedoms** [comment]
修复下"Microsoft Edge WebView2 Runtime"这个应用，下载传送门：https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

**Comment by Bin-Huang** [comment]
你好，新版本做了修复，下载最新版本再试一下？https://github.com/Bin-Huang/chatbox/releases
