### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by fzlee** [Bin-Huang/chatbox#457]
**问题描述**
能否基于会话来设置token传输的上限， 而不是所有会话使用一个全局的token限制

使用场景是有的会话，并不需要太多的上下文关联， 而有的场景又必须要上下文强制相关，基于会话限制token传递数可以更灵活

**Comment by Bin-Huang** [comment]
Looks like this issue might be from an older version. If you're still seeing the problem in the latest release, go ahead and reopen this!

随着版本的更新，这个 issue 可能过时了。如果最新版本依然存在这个问题，请随时重新开启这个 issue
