### ISSUE TITLE
[BUG] GPT4用户在使用GPT4 模型下，问问题得到 API 请求失败 同时用3.5没有问题 所以不是网络账号问题

### ISSUE THREAD

**Issue by Macy2028** [Bin-Huang/chatbox#458]
**Bug Description**
我是PLUS用户，在一个对话中用3.5 另一个用4

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**

在设置完毕GPT4模型后 输入你好 得到：

API 请求失败：

复制
{"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}
model: gpt-4, word count: 20, token estimate: 63

同时回到3.5的对话框，输入你好 得到正常回复
<img width="699" alt="2" src="https://user-images.githubusercontent.com/129026772/232306992-ab1b629e-e637-4c3b-aab5-fd8b27508577.png">
<img width="728" alt="1" src="https://user-images.githubusercontent.com/129026772/232306994-41e28b30-4ab2-4ff7-b39c-2a7261c2e819.png">

**Screenshots**

**Desktop (please complete the following information):**
WINDOWS 10

版本 0.3.6

**Comment by Macy2028** [comment]
这个问题不是第一次了，求解决方法，谢谢。

**Comment by zhaijinbao** [comment]
GPT-4 API需要授权 需要先加入waitAPI等待列表，等待openai给你开放，chatplus和openai的API账号不是通用的 我也在等待不过按照现在情况很难等到，我也是chatgpt的plus会员 不过现在被禁止访问 api还用不了GPT-4 烦躁啊

**Comment by yout0703** [comment]
Is the GPT-4 model actually being used?
![image](https://user-images.githubusercontent.com/63359656/232400868-c380cc51-5a26-4c82-a6f5-fb7a1b186e96.png)
