### ISSUE TITLE
希望用颜色区分 USER 和 ASSISTANT 

### ISSUE THREAD

**Issue by devyujie** [Bin-Huang/chatbox#46]
可以加个颜色区分 `USER` 和 `ASSISTANT` 吗

![image](https://user-images.githubusercontent.com/48620527/225238361-78a7f665-490c-4f35-b713-d686f03511a2.png)

**Comment by Bin-Huang** [comment]
早有此意，暂时还没有比较合适的配色方案。不知道你有没有什么好的建议？

**Comment by Tesla-1i** [comment]
imassage配色？

**Comment by Bin-Huang** [comment]
已经实现了，试试最新版本
