### ISSUE TITLE
建议加入安卓端或网页端

### ISSUE THREAD

**Issue by FidStyle** [Bin-Huang/chatbox#462]

**Comment by EzSync** [comment]
Good suggestion!!

**Comment by nufeng1999** [comment]
> 

这个分支可以试试
https://github.com/nufeng1999/chatai

**Comment by syheliel** [comment]
> > 
> 
> 这个分支可以试试 https://github.com/nufeng1999/chatai

已失效

**Comment by nufeng1999** [comment]
> > > 
> > 
> > 
> > 这个分支可以试试 https://github.com/nufeng1999/chatai
> 
> 已失效

https://nufeng1999.github.io/index.html

**Comment by FidStyle** [comment]
thanks for you

Benn Huang ***@***.***> 于2023年5月10日周三 15:52写道：
