### ISSUE TITLE
需求:国内ip及账号防封

### ISSUE THREAD

**Issue by juneren26** [Bin-Huang/chatbox#466]
希望大脑能增加固定代理功能模块,国内访问api或者挂载vpn访问,都有极高的被封ip及账号风险,有没有好的解决方案来处理防封呢

**Comment by myworksfun** [comment]
reference blew:
![ref](https://user-images.githubusercontent.com/45185967/232413401-47958270-2d68-490e-9c49-53a5dab5c26e.png)
