### ISSUE TITLE
[Feature] support RTL(right-to-left) text

### ISSUE THREAD

**Issue by fontgah** [Bin-Huang/chatbox#469]
Hello, thank you for providing us with such an extraordinary program for free. Please kindly add the right-to-left (RTL) feature for Persian and Arabic languages to properly display the text.

translates to "like these explanations.
https://github.com/josStorer/chatGPTBox/issues/6

**Comment by lmalma** [comment]
Since it's been a while since the application was opened, I'd love if you could add the right-to-left feature, thanks.

**Comment by Bin-Huang** [comment]
Arabic (RTL) has already been implemented, and there are plans to develop Persian, but not so soon.
