### ISSUE TITLE
[Feature]是否可以考虑增加调整字号大小

### ISSUE THREAD

**Issue by pictureye** [Bin-Huang/chatbox#470]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
使用外界屏幕时候，由于分辨率限制，字号较小，希望可以调整字号大小来便于适配不同的屏幕

**解决思路**
调整字号。

**附加上下文**
这是一个请求哈，非常感谢开发者的app，解决了国内使用gpt的问题。

**Comment by ShakesBill** [comment]
有这个需求，用笔记本的时候字太小看的累

**Comment by Bin-Huang** [comment]
已经可以在设置中调节字体大小了，升级到最新版本
