### ISSUE TITLE
[Feature]建议新增团队版功能

### ISSUE THREAD

**Issue by EndDream** [Bin-Huang/chatbox#472]
**Problem Description**
As an individual user, chatbox is excellent on Windows, but it is still very troublesome for the team to configure chatbox for multiple computers.

**Proposed Solution**
I hope that there will be a team version of the function, which will be unified by a computer or server to manage api and send users, and conduct anti-generation access through the server (similar to opencat). The rest of the users will join the team through links or code and automatically issue the configuration.

**Additional Context**
https://opencat.app/docs/zh-CN/opencat-for-team （Similar functions）

-----------------------

**问题描述**
作为个人用户，chatbox在windows端十分优秀，但是对于团队而言给多台电脑配置chatbox还是十分的麻烦

**解决思路**
我希望能有一个团队版本，该功能将由单一电脑或服务器统一管理api和下发用户，并通过服务器进行反代访问（类似于opencat）。其余用户将通过链接或代码加入团队，并自动发布配置

**附加上下文**
[请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。]
https://opencat.app/docs/zh-CN/opencat-for-team （功能类似）

**Comment by ZhuYichuan** [comment]
可以用使用 Proxifier 来进行app 流量的代理
参考youtube  [视频地址](https://www.youtube.com/watch?v=ZPi56hSm__E)

**Comment by Bin-Huang** [comment]
抱歉这块我可能文档没有写好，其实 Chatbox 从 v0.0.1 版本就支持类似的团队功能了，因为我开发 Chatbox 的初心就是为了方便团队办公。使用起来非常简单，你只需要在公司内部搭建一个内置 APIKEY 的方向代理服务器，然后所有用户只需要在 Proxy 中填入代理服务器地址就能正常工作了，不需要每个用户都输入 APIKEY。很感谢你的反馈，这块文档我看看怎么完善一下。

**Comment by EndDream** [comment]
> 

原来如此，我去看看

**Comment by edichangz** [comment]
是否可以配置 Azure OpenAI？我现在只有Azure 的key，是否可以设置Azure 的团队代理。

**Comment by lmingzhi** [comment]
同样想咨询如何配置 azure openai service 的 chatbox 团队代理功能
