### ISSUE TITLE
[BUG]传了一个大文本，第二次无法正常打开程序

### ISSUE THREAD

**Issue by dousha0w0** [Bin-Huang/chatbox#477]
如题

**Comment by Bin-Huang** [comment]
新版本（0.7～）遇到这类问题：

MacOS 用户，打开终端，输入命令 rm "~/Library/Application Support/xyz.chatboxapp.app/config.json" 然后重启应用。

Windows 用户，文件浏览器中地址栏输入 %APPDATA%/xyz.chatboxapp.app 进入数据文件夹，删除 config.json，然后重启应用。

这样会清理错误的应用数据，然后就能正常使用了
