### ISSUE TITLE
[BUG]回复不能正常显示图片

### ISSUE THREAD

**Issue by Sweetlsq** [Bin-Huang/chatbox#481]
Bug 描述
回答的图片不能正常显示

重现步骤
直接向GPT提问“请使用 Matplotlib 的 pyplot 模块画一个简易的折线图，并显示图片”

滚动到 "显示图片部分"
可以发现这个 bug。

期望结果
图片正常显示

实际结果
显示图片小标志和image.png

操作系统：[win10]

**Comment by HuaiHan** [comment]
+1 变成了这样
![image](https://user-images.githubusercontent.com/45888728/232649403-5c550036-4727-4421-8dde-a58a8e1e5e2b.png)

**Comment by Sweetlsq** [comment]
刚刚更新了，0.4.0版本更新后已解决

**Comment by Bin-Huang** [comment]
和版本无关，主要是 AI 返回的图片链接是错的
