### ISSUE TITLE
[Feature] Set the default prompt?

### ISSUE THREAD

**Issue by Abumbalum** [Bin-Huang/chatbox#484]
I like the idea of the default prompt for new chats. It would be helpful if we could configure what this default prompt is ourselves though, unless I'm missing something it seems to always just say: "You are a helpful assistant. You can help me by answering my questions. You can also ask me questions."

**Comment by Bin-Huang** [comment]
v0.6.2 has been implemented, give it a try.
https://github.com/Bin-Huang/chatbox/releases
