### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by VIP0536** [Bin-Huang/chatbox#486]
-------------------------------------

**Bug 描述**
版本：0.40，模型设置为GTP-4时，无法应用。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "设置"
2. 点击 "模型ToKen"
3. 选择模型 "gpt-4"，保存
4. 在prompt中提问，出现图示BUG。

**截图**
![image](https://user-images.githubusercontent.com/119274559/232647122-c46bce9e-cb1b-4d1e-a1c3-6a38bc68a1c7.png)

**桌面端（请填写以下信息）：**
- 操作系统：[win11]
- 应用程序版本：[0.40]

**Comment by BruceYangGZ** [comment]
我也出现相同问题

**Comment by Bin-Huang** [comment]
这是因为你们的账户不支持 GPT4。
不管是不是 ChatGPT Plus 用户，你都需要申请 waiting list 才能在 API 中使用 GPT4.

**Comment by BruceYangGZ** [comment]
谢谢。因为我前几天还可以用gpt 4，这两天突然用不了了&nbsp;


Bruce&nbsp;Yang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Benn ***@***.***&gt;; 
发送时间: 2023年4月18日(星期二) 下午2:12
收件人: ***@***.***&gt;; 
抄送: "Bruce ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Bin-Huang/chatbox] [BUG] (Issue #486)





 
这是因为你们的账户不支持 GPT4。
 不管是不是 ChatGPT Plus 用户，你都需要申请 waiting list 才能在 API 中使用 GPT4.
