### ISSUE TITLE
打开程序显示空白，然后点击关闭直接卡死应该如何解决？

### ISSUE THREAD

**Issue by LUXUS1** [Bin-Huang/chatbox#487]
![image](https://user-images.githubusercontent.com/57226206/232649297-0831a2e2-6a0b-4bb2-8fa8-53f5921a6980.png)

**Comment by Bin-Huang** [comment]
什么版本呢？

**Comment by LUXUS1** [comment]
chatbox是：[chatbox_0.4.0_x64_en-US.msi]
系统版本是：Windows 10

**Comment by fightlord** [comment]
chatbox不同版本，同样win10系统，同样问题

**Comment by devgame66** [comment]
同样的问题！ 如何解决？

**Comment by Bin-Huang** [comment]
重新安装试试？
