### ISSUE TITLE
[Feature] 希望支持免安装版的下载和使用

### ISSUE THREAD

**Issue by jerryblues** [Bin-Huang/chatbox#488]
希望支持免安装版的下载和使用

**Comment by wuyudi** [comment]
ref https://github.com/zzzgydi/clash-verge/blob/main/scripts/portable.mjs

**Comment by Bin-Huang** [comment]
I feel like this issue is a bit outdated, so I went ahead and closed it. But if you think it's necessary, feel free to create a new issue at any time.
