### ISSUE TITLE
chatgpt联网

### ISSUE THREAD

**Issue by 49946479** [Bin-Huang/chatbox#490]
可以接入webchatgpt(插件)吗,就是一个联网的功能, 有一些资料需要联网查询 网页班的chatgpt很容易断开链接

**Comment by nlj626** [comment]
我也想要这个功能。

**Comment by king6731253** [comment]
+1 这个；-）

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1238, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1238。这条 issue 先关闭了～～
