### ISSUE TITLE
[BUG] Sidebar issue

### ISSUE THREAD

**Issue by leong918** [Bin-Huang/chatbox#492]
**Bug Description**
Sidebar rendering problem when application i not use it.

**Steps to Reproduce**
I think is minimize windows cause it.

**Screenshots**
![image](https://user-images.githubusercontent.com/45736660/232720769-d8d0d68f-63cc-41d8-9d7b-ba0ad2bfb8f0.png)

**Desktop (please complete the following information):**
- Operating System: Windows 11
- Application Version: 0.4.0

**Comment by Bin-Huang** [comment]
之前的更新中已经修复过了
