### ISSUE TITLE
[Feature]建议可以更新上传PDF阅读的功能

### ISSUE THREAD

**Issue by superangryduck** [Bin-Huang/chatbox#493]
建议可以在对话框内上传PDF，让chatbox快速阅读后，用户可以提问题。

**Comment by Hisoka-J** [comment]
这个得在本地自建向量数据库才可以

**Comment by nufeng1999** [comment]
有什么好思路吗

**Comment by Bin-Huang** [comment]
新版本 v1.3.4 已经支持这个功能。为了达到最佳的智能表现，目前仅支持 Chatbox AI 4 模型

**Comment by superangryduck** [comment]
太好了！您成功将一位claude pro用户再次拉了回来。

Benn Huang ***@***.***> 于2024年4月15日周一 14:32写道：
