### ISSUE TITLE
[Feature]希望增加一个 清除上下文 功能，可以参照OpenCat，Poe等其他客户端

### ISSUE THREAD

**Issue by heeyfan** [Bin-Huang/chatbox#494]
现在最新的版本0.4.0可以设置 system了，但是只有清除所有聊天记录的功能才会把上下文清除掉，

基于某些情况，不需要上下文关联，但是需要system，现在只能清除所有聊天记录才能实现。
但是既想保留聊天记录，又不想上下文进行关联，现在好像无法实现。

可以参照其他客户端，比如OpenCat，Poe等客户端提供清除上下文功能，并且做成一个按钮，点一下清除上下文，再次点击则恢复上下文。

希望大佬可以考虑下

**Comment by Bin-Huang** [comment]
好的，我考虑下怎么设计更合适

**Comment by Bin-Huang** [comment]
这个功能在很久之前就实现了，更新试试看～～～
