### ISSUE TITLE
增加类似WebChatGPT插件的功能

### ISSUE THREAD

**Issue by leonlincc** [Bin-Huang/chatbox#496]
RT
很多时候，即便是他有2021年之前的数据，但是也不全，如果能通过网络补全这个短板，这个工具会更好用！

**Comment by nufeng1999** [comment]
> RT
> 很多时候，即便是他有2021年之前的数据，但是也不全，如果能通过网络补全这个短板，这个工具会更好用！

如何补全?

**Comment by Bin-Huang** [comment]
和其他 issue 重复了，为了更好的整理，所以先关闭了哈～
