### ISSUE TITLE
【Bug】给了图片链接后不能正常显示

### ISSUE THREAD

**Issue by lfy0** [Bin-Huang/chatbox#499]
当回答里有图片链接时那个位置好像会被处理，不能正常显示图片，也无法点击或复制连接，只能显示一个加载失败的图片
![图片](https://user-images.githubusercontent.com/26156595/232983396-d3578b20-ebb4-47b5-8cb7-e9a4f2c9a9af.png)

**Comment by Bin-Huang** [comment]
点击下方的编辑按钮，可以看到链接。一般这种情况是 AI 返回的图片链接有误。
