### ISSUE TITLE
darkmode and copy button

### ISSUE THREAD

**Issue by githubxnoob** [Bin-Huang/chatbox#5]
hi please add darkmode and a copy button to quickly copy chat gpt replies.

**Comment by Bin-Huang** [comment]
It has already been added to the roadmap and planned to be done.

**Comment by Bin-Huang** [comment]
The copy button has been implemented, try the latest version

https://github.com/Bin-Huang/chatbox/releases

**Comment by Bin-Huang** [comment]
Yes, this is a bug and I have fixed it. I will release a new version later.😂
