### ISSUE TITLE
希望显示toke剩余数量

### ISSUE THREAD

**Issue by noangel2014** [Bin-Huang/chatbox#50]
希望有个地方显示toke剩余数量，不知道api还剩多少，好控制使用

**Comment by Bin-Huang** [comment]
每条消息的 tokens 预估已经在实现中了，至于剩余 token 数量我不太懂你的意思，可以详细解释下吗？

**Comment by noangel2014** [comment]
谢谢， 是我表达错误了。因为在另一个工具里看到 0 tokens used ≈ 0.0000 usd，我觉得很酷。我看到你最新版里面已经统计了toke计算，这样很好，让我们在使用的时候有点b数 ^-^

顺便报告一个小bug，清扫聊天记录的时候，有时候会把第一条prompt也给删掉了，这样很不好。prompt是很重要的。

我发现现在市面上的客户端功能千篇一律，但大多数对prompt管理都不太重视呀，以后可以考虑这方面增强一下 ^-^

**Comment by Bin-Huang** [comment]
其实你只需要在 Chatbox 编辑那条 prompt 消息，把它改成 system（系统设定）就行了。这样不但不会被清理，还可以强化 GPT 3.5 的 prompting 效果（参考官方文档）。

其实 Chatbox 在 prompting 上是非常重视的，从第一版本 0.0.1 就具有了很强的 prompting 开发调试能力。我实在太忙了，没有在文档里把这块说清楚。

**Comment by Bin-Huang** [comment]
是的，我也是这么想的。我还没有来得及开发，现在才刚刚上 0.1 的版本

**Comment by Bin-Huang** [comment]
这个软件叫啥名字？

**Comment by noangel2014** [comment]
copy.ai   看你如何定位，不打算商业化的话 不要搞这么复杂，它虽然专门写文案用的，不过prompt管理这款做的很好，可以参考
