### ISSUE TITLE
[BUG]Cannot run the tool without admin right

### ISSUE THREAD

**Issue by bachvnnvn** [Bin-Huang/chatbox#500]
Hi,

This tool is quite awesome, but I only can run it with full administrator right.
Because I cannot install the MSI file, so I copy the file chatbox.exe to my non-admin machine but it doesn't open up.
On the same machine, if I right-click and run as admin --> Provide an admin account --> it works fine.

Could you please help to make it works without admin right?

Thanks!

**Comment by Bin-Huang** [comment]
This issue has been resolved in the latest version. Give the newest version a try:
https://github.com/Bin-Huang/chatbox/releases
