### ISSUE TITLE
[Feature]  why do not   add  socket 5  proxy   ,  http proxy is  useless 

### ISSUE THREAD

**Issue by dingjian2** [Bin-Huang/chatbox#503]
why do not   add  socket 5  proxy   ,  http proxy is  useless

**Comment by chenshaoju** [comment]
Please add ` --proxy-server="socks5://127.0.0.1:1080"` after the chatbox bin, on the Windows system, for example:
```
"C:\Program Files\ChatBox\Chatbox.exe" --proxy-server="socks5://127.0.0.1:1080"
```

![image](https://github.com/Bin-Huang/chatbox/assets/515763/a13bfd29-775c-4368-ba8d-24c56ad50a3f)

**Comment by Bin-Huang** [comment]
Looks like this issue might be from an older version. This feature has been implemented, try the latest version.
