### ISSUE TITLE
 黑苹果下无法打开

### ISSUE THREAD

**Issue by ccljmcc** [Bin-Huang/chatbox#504]
**Bug 描述**
黑苹果下无法打开应用

**截图**
![image](https://user-images.githubusercontent.com/30434838/233048325-9e588c42-b728-4d3c-9fff-6d1da046414b.png)
![image](https://user-images.githubusercontent.com/30434838/233048105-21012612-26e4-48da-84c0-12d90b2342f4.png)

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 0.4.0]

**Comment by Bin-Huang** [comment]
请下载对应芯片的版本
