### ISSUE TITLE
想问下安装后一打开就闪退是什么原因

### ISSUE THREAD

**Issue by Caben123** [Bin-Huang/chatbox#505]

**Comment by ufgtb24** [comment]
同问

**Comment by jerrybeing** [comment]
一样的，找开就闪退了。

**Comment by beijito** [comment]
解决了么。

**Comment by wuyudi** [comment]
什么系统，然后命令行运行时的输出是什么。

**Comment by Caben123** [comment]
> 什么系统，然后命令行运行时的输出是什么。

win11，低版本的0.1.7exe的安装包安装后能正常使用，msi的安装后点开就闪退。

**Comment by Bin-Huang** [comment]
现在最新的版本也会吗？

**Comment by Bin-Huang** [comment]
试一下最新版本，现在已经更新好几个版本了

**Comment by Caben123** [comment]
> 现在最新的版本也会吗？

还是会

**Comment by Caben123** [comment]
> 现在最新的版本也会吗？

刚刚试了新版本，还是一打开就会闪退

**Comment by Bin-Huang** [comment]
你好，新版本做了修复，下载最新版本再试一下？https://github.com/Bin-Huang/chatbox/releases
