### ISSUE TITLE
希望增加一个web服务，实现局域网共享功能

### ISSUE THREAD

**Issue by ziteng-wang** [Bin-Huang/chatbox#508]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by nufeng1999** [comment]
> 

这个分支可以试试
https://nufeng1999.github.io

**Comment by Bin-Huang** [comment]
出于安全考虑，暂时不要使用第三方不开源的网站客户端

**Comment by Bin-Huang** [comment]
Chatbox 会出官方的版本

**Comment by tech1502** [comment]
https://chatgpt.030987.xyz/   web服务安全稳定

**Comment by ziteng-wang** [comment]
> Chatbox 会出官方的版本

目前出的共享版本和预想的不太一样耶，目前是把api转换成chatbox语言，其他主机还是要安装客户端并填写吗？😂我的预想是让一台主机安装chatbox作为服务端填写api，启用web服务，然后其他主机可以直接浏览器访问

**Comment by Bin-Huang** [comment]
这里是 Chatbox 的官方网页版本：https://web.chatboxapp.xyz/

请不要使用其他第三方版本，可能会出现盗取 API KEY 的安全问题
