### ISSUE TITLE
[Other]这个也需要科学上网吗

### ISSUE THREAD

**Issue by cyrilyoung** [Bin-Huang/chatbox#513]
如题

**Comment by 78412709** [comment]
需要

**Comment by liqupanpan** [comment]
需要，但是api设置的这里，如果使用代理转发的api，应该是不需要的

**Comment by ZhuYichuan** [comment]
可以用使用 Proxifier 来进行app 流量的代理
参考youtube  [视频地址](https://www.youtube.com/watch?v=ZPi56hSm__E)

**Comment by Bin-Huang** [comment]
#582 
很简单就能解决，看这里
