### ISSUE TITLE
[Other]我的app代码部分没有颜色, 这个咋弄

### ISSUE THREAD

**Issue by LucasIsGood** [Bin-Huang/chatbox#515]
<img width="1440" alt="截屏2023-04-21 15 54 36" src="https://user-images.githubusercontent.com/56297860/233577579-9b078ef5-2715-476c-9b74-5e0b273cbaf1.png">

**Comment by wuyudi** [comment]
代码高亮似乎有点问题了。可能可以用 https://github.com/highlightjs/highlight.js#in-the-browser 。不太清楚 gpt 返回时是否附带了代码识别。

**Comment by Bin-Huang** [comment]
![image](https://user-images.githubusercontent.com/20723142/233826780-d5092f24-11b9-4b30-ada6-5304a3d4350e.png)
很明显 AI 返回了 TXT 格式
