### ISSUE TITLE
gpt4账号无法使用 gpt4的模型[BUG]

### ISSUE THREAD

**Issue by a6480078** [Bin-Huang/chatbox#516]
本人使用 gpt4 的账号无法使用 gpt4 的模型

**Comment by basuui123** [comment]
我也同样的情况

**Comment by Icatme** [comment]
GPT4 API只有极少数帐号有, ChatGPT Plus 并不包含GPT-4的API使用

**Comment by fattycat2020** [comment]
> GPT4 API只有极少数帐号有, ChatGPT Plus 并不包含GPT-4的API使用

请问有官方的说明页面吗
