### ISSUE TITLE
对话框上下抖动

### ISSUE THREAD

**Issue by wuyudi** [Bin-Huang/chatbox#52]
复现方法：

1. 让 gpt 处于打一大段话中
2. 发送下一句话
3. 2 个框就会同时回答，焦点会不停来回切换，对话框就像抽搐了一样。

**Comment by Bin-Huang** [comment]
感谢反馈，这个问题已经在计划修复了

**Comment by tisfeng** [comment]
这抖动看着太难受了 😢

**Comment by Bin-Huang** [comment]
新版本修复了
