### ISSUE TITLE
[Other]什么时候有手机版哦

### ISSUE THREAD

**Issue by mxtao123** [Bin-Huang/chatbox#523]

**Comment by Bin-Huang** [comment]
先试试手机上的网页版本吧，APP快了：

https://web.chatboxapp.xyz/

**Comment by mxtao123** [comment]
好的，期待APP版本，一定要安卓苹果都有啊~

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/issues/686
在内测了
