### ISSUE TITLE
[BUG] cant select GPT-4

### ISSUE THREAD

**Issue by kimjyb** [Bin-Huang/chatbox#524]
**Bug 描述**
模型选择ＧＰＴ－４的话，出现以下Error。
选择GPT-３.５是没问题。

{"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}

**Comment by gaoxiang7552** [comment]
没有权限,gpt-4需要申请

**Comment by zwz466459262** [comment]
我也是一样的，而且我的账号有gpt4的权限，不知道要怎么弄

**Comment by eternaldlw** [comment]
我的账号已经申请了GPT4，选择了GPT-4若干模型后还是失败

**Comment by Bin-Huang** [comment]
GPT4 的 API 权限，需要在 OpenAI 排队才能申请得到。
