### ISSUE TITLE
[BUG] IT Expert 角色的预置prompt没有锁定，会被clean掉

### ISSUE THREAD

**Issue by ponycoding** [Bin-Huang/chatbox#527]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Bug 描述**
 IT Expert 角色的预置prompt没有锁定，会被clean掉。

**重现步骤**
 在 IT Expert 角色页面，点击右上角clean后，角色预置prompt一并被清除，失去了角色锁定功能

**截图**

**桌面端（请填写以下信息）：**
- 操作系统：Windows 11 x64
- 应用程序版本：0.4.0

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by EnzoNeves** [comment]
可以自己去改一下config.json，看一下就知道怎么改了

**Comment by Bin-Huang** [comment]
I feel like this issue is a bit outdated, so I went ahead and closed it. But if you think it's necessary, feel free to create a new issue at any time.
