### ISSUE TITLE
[BUG] macOS 10.13 运行出错，配置丢失，界面异常，无法显示版本号，卸载（删除）后重装无效。

### ISSUE THREAD

**Issue by javenhmh** [Bin-Huang/chatbox#532]
macOS 10.13 运行出错，配置丢失，界面异常，无法显示版本号，卸载（删除）后重装无效。

![image](https://user-images.githubusercontent.com/12635249/234010639-3110fdeb-862e-466e-9153-251c171155e3.png)

添加 API 配置可临时使用，重启应用后会丢失信息，无法保存配置。

**Comment by javenhmh** [comment]
![image](https://user-images.githubusercontent.com/12635249/234010806-a873144b-286e-4e5a-8ea4-835e38ac52e6.png)

**Comment by MaiitZhao** [comment]
我的也是，intel芯片，版本10.14，没法保存历史聊天，重启就需要重新配置，也不显示版本号

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复，试试最新版本
https://github.com/Bin-Huang/chatbox/releases
