### ISSUE TITLE
[BUG] win11 图片无法显示

### ISSUE THREAD

**Issue by Joiner12** [Bin-Huang/chatbox#533]
**Bug 描述**
使用过程中，有时候会自动输出图片，但是图片都无法显示。

![image](https://user-images.githubusercontent.com/30167196/234225319-2809fd1a-83fc-4a1d-8ae7-2433235748ea.png)

**Comment by Bin-Huang** [comment]
是 GPT 返回的图片链接不对，和chatbox无关。你试着用markdown插入一个正常的图片链接就知道了
