### ISSUE TITLE
API请求失败[BUG]

### ISSUE THREAD

**Issue by chengleec** [Bin-Huang/chatbox#534]
![CleanShot 2023-04-25 at 14 56 12](https://user-images.githubusercontent.com/49826259/234317580-4a53680b-d00b-499d-a2b2-1aab1139ef25.png)
系统：
macos ventura 13.3.1
版本：
0.4.0

**Comment by chengleec** [comment]
> ![CleanShot 2023-04-25 at 14 56 12](https://user-images.githubusercontent.com/49826259/234317580-4a53680b-d00b-499d-a2b2-1aab1139ef25.png) 系统： macos ventura 13.3.1 版本： 0.4.0
中文就请求失败，英文就秒出。。。。。
![CleanShot 2023-04-25 at 15 03 04](https://user-images.githubusercontent.com/49826259/234320007-96f1e4e9-dc21-4daf-9419-3ffc9d0e6345.png)

**Comment by chengleec** [comment]
中文就请求失败，英文就秒出。。。。
![CleanShot 2023-04-25 at 15 03 04](https://user-images.githubusercontent.com/49826259/234320179-cbc792e0-a870-4caf-a6b5-45d536f2ce36.png)

**Comment by downerxl** [comment]
我这是使用代理时如果用普通的api，一次性输出是没问题的，但是用sse逐字输出就报跟你同样的错误。调试时正常，打包后macos客户端就不行，windows客户端没有这个问题。

**Comment by yangzhenran** [comment]
我也是这种情况，卸载重装也不行

**Comment by famacer** [comment]
这个可能和节点有关，我这里更换节点就可以解决

**Comment by downerxl** [comment]
> 我这是使用代理时如果用普通的api，一次性输出是没问题的，但是用sse逐字输出就报跟你同样的错误。调试时正常，打包后macos客户端就不行，windows客户端没有这个问题。

我是用的chatgpt-proxy做的openai代理转发，部署在我一台服务器上。经查是sse的代理网址出现跨域，通过在中转服务器给Header添加允许跨域的参数，目前问题已经解决。
