### ISSUE TITLE
建议加一个修改头像功能，虽然没什么屌用

### ISSUE THREAD

**Issue by hezhenyuqwq** [Bin-Huang/chatbox#535]
建议增加一个修改个人和机器人头像得功能，虽然我不能要求太多，但是默认的头像我是真的欣赏不来，谢谢。
![94830536_p0](https://user-images.githubusercontent.com/91007437/234477010-8fbf0dcc-6102-4499-a2c2-b3d0a281347e.jpg)

**Comment by PandaTwo** [comment]
+1

就喜欢这些没屌用的 龟毛需求。

**Comment by LetitiaChan** [comment]
跪求大佬，头像太有用了，每个对话都是一个角色，角色咋能没有头像呢，太影响我们培养感情了

**Comment by WhaleLetter** [comment]
你们都在干什么！！！

**Comment by tech1502** [comment]
https://chatgpt.030987.xyz/

**Comment by Bin-Huang** [comment]
很早之前的版本已经实现了，可以更新一下，先关闭了这条 issues 了。

**Comment by Likes123** [comment]
> 很早之前的版本已经实现了，可以更新一下，先关闭了这条 issues 了。

机器人的头像可以更改，但是个人的没法更改样
