### ISSUE TITLE
WINDOWS下，切换所有的gpt4模型都提示不存在

### ISSUE THREAD

**Issue by fattycat2020** [Bin-Huang/chatbox#537]
API 请求失败：

{"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}

**Comment by Bin-Huang** [comment]
你的账户不支持GPT4。所有账户都需要在OpenAI申请排队，才可以在API中使用GPT4.

**Comment by fattycat2020** [comment]
感谢😊

Benn Huang ***@***.***> 于 2023年4月26日周三 下午3:40写道：
