### ISSUE TITLE
[BUG]API请求失败，提示信息

### ISSUE THREAD

**Issue by kk-mouse** [Bin-Huang/chatbox#538]
{"error":{"message":"This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?","type":"invalid_request_error","param":"model","code":null}}

**Comment by ShinChven** [comment]
改改模型试试。是不是选错模型了？

**Comment by ChenHuaQin** [comment]
> 改模型试试。是不是选错模型了？

试了还是没有用

**Comment by himbeeer** [comment]
一樣
gpt3.5 turbo 可以
gpt4 就error

**Comment by QQ3516969** [comment]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
api请求失败

**Comment by QQ3516969** [comment]
gpt3.5-turbo

**Comment by devycx** [comment]
> 

亲，每个账号的使用量是有限额的，就好比手机流量，你api密钥对应的流量超过免费的额度了，就不让你用了，可以考虑付费或者注册一个新的账号哟~

**Comment by devycx** [comment]
> > 改模型试试。是不是选错模型了？
> 
> 试了还是没有用

亲，最好试着录个视频哟~以便我们尽快复现bug以锁定并修复问题哦

**Comment by aoqiangit** [comment]
我用的系统是centos 9，包用的是chatbox_0.4.1_amd64.AppImage，一直提示API请求失败，但是在WIN11上就不会提示正常使用，是不是对于LINUX不太友好呢？希望有大佬能解决以下

**Comment by Bin-Huang** [comment]
@kk-mouse 你的问题是因为模型选错了，进入设置，重置模型的配置就行。

@QQ3516969 你的问题是因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。
这个问题和软件没有任何关系。
如果你不想折腾 API 账户的各种问题的话，强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0
