### ISSUE TITLE
我想自定义一个prompt，但不能做到像预置的那样，清空时仍然保留。

### ISSUE THREAD

**Issue by hb-0** [Bin-Huang/chatbox#54]
如题，怎么做到清空时不保留呢，就像预置的那样？

**Comment by Bin-Huang** [comment]
编辑消息，把角色改成 system 就可以了。根据官方文档，这么做的 prompt 效果也最好，相当于 ai 的系统设定。

**Comment by 14790897** [comment]
> 编辑消息，把角色改成 system 就可以了。根据官方文档，这么做的 prompt 效果也最好，相当于 ai 的系统设定。

你好，修改role为system后，还需要重新发送那条消息才能让chatgpt知道吗？

**Comment by Bin-Huang** [comment]
不用

**Comment by Bin-Huang** [comment]
每次生成，都是根据上面的消息，包括编辑过的（这也是 chatbox 为什么可以很方便的 prompting，因为你可以直接改造 AI 的输出风格）

**Comment by leeperfect** [comment]
> 编辑消息，把角色改成 system 就可以了。根据官方文档，这么做的 prompt 效果也最好，相当于 ai 的系统设定。

我想请问如何设置SYSTEM？我们找到对应的选项。
