### ISSUE TITLE
[Feature] Add Wrong Word Correction Popup

### ISSUE THREAD

**Issue by abdullahbaa5** [Bin-Huang/chatbox#541]
**Problem Description**
Not being able to right click a wrong word in order to correct it even though it checks if a word is wrong already.

**Proposed Solution**
Add OS native popup that has a list of correct word to replace with.

**Additional Context**
![image](https://user-images.githubusercontent.com/38984510/234641588-b9110757-3c4c-4fae-8f2d-de8dd0a79409.png)

**Comment by Bin-Huang** [comment]
I still remember this bug, and it has been fixed in subsequent versions.
