### ISSUE TITLE
[Feature] Add ability to edit the default system message

### ISSUE THREAD

**Issue by thaKnza** [Bin-Huang/chatbox#542]
A default system message was added,
"You are a helpful assistant. You can help me by answering my questions. You can also ask me questions."
It would be nice if we could change this ourselves through the user interface so that each new conversation used a user-defined system message instead of this one. Even better would be if we could create our own library of system messages and pick one from a drop-down menu including an option for "no system message".

I appreciate the consideration.

**Comment by Bin-Huang** [comment]
v0.6.2 has been implemented, give it a try.
https://github.com/Bin-Huang/chatbox/releases
