### ISSUE TITLE
GPT Plus使用GPT4 API 请求失败[BUG]

### ISSUE THREAD

**Issue by qq429564748** [Bin-Huang/chatbox#543]
描述：
版本0.4.1
(使用GPT Plus的API key, 在官网能使用GPT4.0的模型)
在chatbox中使用GPT4.0，gpt-4-32k，gpt-4-0314，gpt-4-32k，gpt-4-32k-0314都不会返回API请求失败,只能使用gpt 3.5版本的模型

软件中提示如下：
API 请求失败：

TXT
复制
{"error":{"message":"The model: `gpt-4-32k` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}
model: gpt-4-32k

**Comment by itestit** [comment]
GPT4 API需要单独向openAI申请，并非开通Plus会员即可享受

**Comment by Ludwig-Liu173** [comment]
> 
我也遇到这个问题，在chatbox中只能使用gpt3而无法使用gpt4，请问gpt4的API要如何申请？

**Comment by MoGuGuai-hzr** [comment]
目前 API 优先向开发者提供, 需要[申请](https://openai.com/waitlist/gpt-4-api)

**Comment by xingyinzhu** [comment]
希望作者可以用accessToken实现这个功能，具体我看 github上已经有人实现了
