### ISSUE TITLE
[chatbox提问得到的答案和直接opnai页面得到的答案相比精确度总体要差，这是为什么？]

### ISSUE THREAD

**Issue by tencentemr** [Bin-Huang/chatbox#544]
比对了很多问题。总体都是感觉chabox回答比官网页面的质量不高，理解度略差。

不知道是用了本地缓存？还是其他原因。

按说如果走的API应该没啥太大的区别才对。

**Comment by isooya** [comment]
模型的区别？这个默认是3.5

**Comment by isooya** [comment]
模型的区别？这个默认用的是3.5

**Comment by isooya** [comment]
模型的区别？默认是3.5

**Comment by Zard-void** [comment]
建议直接问ChatBox

Q：你和ChatGPT是什么关系

A：我和ChatGPT都是自然语言生成技术的代表之一，但两者之间不存在直接的关系。ChatGPT是由OpenAI开发的一系列基于Transformer模型的自然语言生成算法，可以用于生成对话、文本、摘要、翻译等任务，其性能和效果在自然语言生成领域处于领先地位。而我是一个基于预定义规则和模板的语言模型，也可以用于自然语言生成任务，但比起ChatGPT等神经网络模型，我的规模更小、更简单，适用于一些相对简单的任务和场景。总之，我们都是自然语言生成技术的代表，但技术实现和应用场景存在差异。

Q：详细说下 你是一个基于预定义规则和模板的语言模型 是什么意思

A：我是一个基于预定义规则和模板的语言模型，意味着我的回答是由预定义的规则和模板来产生。我的系统并不是像神经网络一样从大量的数据中进行学习和训练得出模型，而是通过人工编写，利用语言知识及指定的规则来组成回答。在我的系统中，收到的问题会被与预定义的问题模板库进行匹配，然后在规则库中查找与问题相关的规则，这些规则是编写用于回答特定类型问题的逻辑代码。根据匹配到的模板和规则，我的系统会生成回答并返回给用户。这种方法类似于基于规则和模板的语音识别和机器翻译系统，在一些特定的场景下有很好的效果。然而，它有一个缺点，就是需要人为编写规则和模板，难以适应复杂和多变的场景。

Q：那为什么你还需要GPT的key

A：作为一个基于预定义规则和模板的语言模型，我的能力受限于我所拥有的规则和模板。虽然我可以回答很多基本问题，但有些问题可能需要对某些具体的实体或概念进行更深入的理解和推理，而这是我的规则和模板无法覆盖的。这时，我可以通过与Chat GPT等模型的集成，从这些神经网络模型中获取更深入的知识来解决一些更高级的问题。

Chat GPT是一个语言模型，它学习了大量的文本数据，并可以生成高质量、光滑流畅的文本输出。作为一个可以生成自然语言文本的模型，它可以帮助我丰富我的回答，并使我的回答更加自然、准确和多样化。通过使用GPT的API，我可以利用它的功能来为用户提供更好的服务。例如，当我的规则库无法回答某些问题时，我可以使用GPT来生成更为自然的回答。因此，与GPT集成可以拓展我的能力，提高我的回答的质量和多样性。

**Comment by tencentemr** [comment]
> 建议直接问ChatBox
> 
> Q：你和ChatGPT是什么关系
> 
> A：我和ChatGPT都是自然语言生成技术的代表之一，但两者之间不存在直接的关系。ChatGPT是由OpenAI开发的一系列基于Transformer模型的自然语言生成算法，可以用于生成对话、文本、摘要、翻译等任务，其性能和效果在自然语言生成领域处于领先地位。而我是一个基于预定义规则和模板的语言模型，也可以用于自然语言生成任务，但比起ChatGPT等神经网络模型，我的规模更小、更简单，适用于一些相对简单的任务和场景。总之，我们都是自然语言生成技术的代表，但技术实现和应用场景存在差异。
> 
> Q：详细说下 你是一个基于预定义规则和模板的语言模型 是什么意思
> 
> A：我是一个基于预定义规则和模板的语言模型，意味着我的回答是由预定义的规则和模板来产生。我的系统并不是像神经网络一样从大量的数据中进行学习和训练得出模型，而是通过人工编写，利用语言知识及指定的规则来组成回答。在我的系统中，收到的问题会被与预定义的问题模板库进行匹配，然后在规则库中查找与问题相关的规则，这些规则是编写用于回答特定类型问题的逻辑代码。根据匹配到的模板和规则，我的系统会生成回答并返回给用户。这种方法类似于基于规则和模板的语音识别和机器翻译系统，在一些特定的场景下有很好的效果。然而，它有一个缺点，就是需要人为编写规则和模板，难以适应复杂和多变的场景。
> 
> Q：那为什么你还需要GPT的key
> 
> A：作为一个基于预定义规则和模板的语言模型，我的能力受限于我所拥有的规则和模板。虽然我可以回答很多基本问题，但有些问题可能需要对某些具体的实体或概念进行更深入的理解和推理，而这是我的规则和模板无法覆盖的。这时，我可以通过与Chat GPT等模型的集成，从这些神经网络模型中获取更深入的知识来解决一些更高级的问题。
> 
> Chat GPT是一个语言模型，它学习了大量的文本数据，并可以生成高质量、光滑流畅的文本输出。作为一个可以生成自然语言文本的模型，它可以帮助我丰富我的回答，并使我的回答更加自然、准确和多样化。通过使用GPT的API，我可以利用它的功能来为用户提供更好的服务。例如，当我的规则库无法回答某些问题时，我可以使用GPT来生成更为自然的回答。因此，与GPT集成可以拓展我的能力，提高我的回答的质量和多样性。

猿来如此！

**Comment by Bin-Huang** [comment]
我再次解释一下，调用官方接口使用的模型，和 ChatGPT 用的底层模型是一摸一样的。**即使是同样的底层模型，直接对话的效果也会有差异，但这主要和 prompt 与温度设置有关**。ChatGPT 在前置 prompt 有自己的设计，并且给予了足够多的上下文，让它知道自己叫ChatGPT、内置了什么版本的模型…… 

**建议不要把和模型的直接询问结果作为参考依据**，有以下原因：
1. 新版本模型在训练时，使用的数据集也是当时的，所以这会导致**模型无法知道自己的真实版本，总以为自己是上一代版本**。比如在没有任何 prompt 的情况下询问 GPT4 模型，模型会说“GPT4还没发布”，这是因为它训练数据是以前的，它训练时自己当然还没有发布。
2. 在技术上，底层模型本身对自己信息存在大量误解，比如你多次单独询问，或者用不同方式询问，得到的结果可能是不相同的。如果希望模型表现得更像一个知道自己是谁的“人”，应该在 prompt 进行灌输和提示，这也是 ChatGPT 的做法。
3. 即使在 prompt 层面灌输正常，模型本身也会出现错误输出，这在技术和论文中叫做“出现幻觉”。

以上所有信息都可以通过 ChatGPT、OpenAI 官网/官方文档获知。

我觉得既然使用模型官方接口，我的建议是：
1. 不要去纠结表现出来的自我认知和幻觉，而应该直接去利用底层的生成和推理能力
2. 必要的时候，利用更自由的 prompt 能力来定制自己的高级 AI，Chatbox 的 prompt 自由度和 AI 定制能力是很大优势（因为前置 prompt 可以随意设置和修改）

**Comment by tencentemr** [comment]
> 我再次解释一下，调用官方接口使用的模型，和 ChatGPT 用的底层模型是一摸一样的。**即使是同样的底层模型，直接对话的效果也会有差异，但这主要和 prompt 与温度设置有关**。ChatGPT 在前置 prompt 有自己的设计，并且给予了足够多的上下文，让它知道自己叫ChatGPT、内置了什么版本的模型……
> 
> **建议不要把和模型的直接询问结果作为参考依据**，有以下原因：
> 
> 1. 新版本模型在训练时，使用的数据集也是当时的，所以这会导致**模型无法知道自己的真实版本，总以为自己是上一代版本**。比如在没有任何 prompt 的情况下询问 GPT4 模型，模型会说“GPT4还没发布”，这是因为它训练数据是以前的，它训练时自己当然还没有发布。
> 2. 在技术上，底层模型本身对自己信息存在大量误解，比如你多次单独询问，或者用不同方式询问，得到的结果可能是不相同的。如果希望模型表现得更像一个知道自己是谁的“人”，应该在 prompt 进行灌输和提示，这也是 ChatGPT 的做法。
> 3. 即使在 prompt 层面灌输正常，模型本身也会出现错误输出，这在技术和论文中叫做“出现幻觉”。
> 
> 以上所有信息都可以通过 ChatGPT、OpenAI 官网/官方文档获知。
> 
> 我觉得既然使用模型官方接口，我的建议是：
> 
> 1. 不要去纠结表现出来的自我认知和幻觉，而应该直接去利用底层的生成和推理能力
> 2. 必要的时候，利用更自由的 prompt 能力来定制自己的高级 AI，Chatbox 的 prompt 自由度和 AI 定制能力是很大优势（因为前置 prompt 可以随意设置和修改）

感谢大佬答疑释惑！
