### ISSUE TITLE
滚动会导致整个页面滚动偏移[BUG]

### ISSUE THREAD

**Issue by alook123** [Bin-Huang/chatbox#548]
**截图**
![图片](https://media.cleanshot.cloud/media/60682/MqZS6sihGqvpzk8dRhHlg6O3Hz22fQNHGouMWM68.jpeg?Expires=1682665888&Signature=f1iLazfN3BpbEFerN5MsxNdYQK33RprfUd8w~BjdZGaCNHkBvFpbFJIl3fXcWkKGfdvjYJANy0VwBMheG9t6VM8LarX5eUIqyGsEkXAPumClhK7iw53ZCXQytbWPyDZlCMo9uuLs4jvybn2Jm6QpRa7HmkGIro4fv1TREr56kEjgq3utIy61zMFMHqC~BS6xEa4MJmRkAU877xD8VglbcGOOqU5WnykrKbXlh5wIwLAmR4aWsPlf5Au~wWv~AYDchU7~9NxEEJ6x8C5xWOnAGRNVWdzO3BH4LMpCqAOOuEDxfnRu3o7pp61-SYmr-~QbyXimYZBQY05~rftXtH6VLA__&Key-Pair-Id=K269JMAT9ZF4GZ)

**桌面端：**
- macos 13.3.1

**Comment by Bin-Huang** [comment]
早期版本的问题，已经修复过了，记得更新～～
