### ISSUE TITLE
[Feature]建议在设置中添加“关闭主面板”选项

### ISSUE THREAD

**Issue by Blanchot-satou** [Bin-Huang/chatbox#551]
**问题描述**
经常性地使用完毕后点下了“关闭”而非“最小化”（仅仅是个人习惯），在下一次需要使用时发现系统托盘内没找到，需要重新打开

**解决思路**
希望能够在设置中添加“关闭主面板”的选项，能够选择“最小化到系统托盘”或“退出ChatBox”

**Comment by Mingxiangyu** [comment]
[问题描述
经常性地使用完毕后点下了“关闭”而非“最小化”（仅仅是个人习惯），在下一次需要使用时发现系统托盘内没找到，需要重新打开

解决思路
希望能够在设置中添加“关闭主面板”的选项，能够选择“最小化到系统托盘”或“退出ChatBox”](https://github.com/Bin-Huang/chatbox/issues/551#issue-1688045479)
具备同样的问题

**Comment by Mingxiangyu** [comment]
> **问题描述** 经常性地使用完毕后点下了“关闭”而非“最小化”（仅仅是个人习惯），在下一次需要使用时发现系统托盘内没找到，需要重新打开
> 
> **解决思路** 希望能够在设置中添加“关闭主面板”的选项，能够选择“最小化到系统托盘”或“退出ChatBox”

具备同样的问题

**Comment by leidichen** [comment]
同样的需求，希望关闭 chatbox 之后，它可以在系统托盘待命，使用快捷键唤醒窗口。

**Comment by Bin-Huang** [comment]
最近的几个版本里已经支持了，试试看～
