### ISSUE TITLE
[Feature]建议增加一个快速切换模型的功能

### ISSUE THREAD

**Issue by yuexiaoliang** [Bin-Huang/chatbox#552]
**问题描述**
很多问题实际上gpt-3就够用了，但是有些问题又不得不用gpt-4，这时候切换模型还是有点麻烦的，而一直用gpt-4总有种金钱在燃烧的感觉，有点扛不住~

**Comment by houyvcai** [comment]
能告诉我怎么在chatbox中使用gpt-4的吗，谢谢

**Comment by Vstory** [comment]
> 能告诉我怎么在chatbox中使用gpt-4的吗，谢谢

设置里

**Comment by yuexiaoliang** [comment]
> 能告诉我怎么在chatbox中使用gpt-4的吗，谢谢

如果你的账号有使用 gpt-4 权限的话，直接在设置里切换就行了，如果没权限就会报错

**Comment by houyvcai** [comment]
好的谢谢

岳晓亮 ***@***.***> 于2023年5月5日周五 10:42写道：

**Comment by Flow-sandyu** [comment]
希望能实现下图这种功能（https://app.nextchat.dev/#/），每次都点开设置窗口，然后才能切换模型太麻烦了。如果能直接在编辑窗口切换模型就好了
![image](https://github.com/Bin-Huang/chatbox/assets/72751523/7af651cb-9e76-48bc-a9ca-54833f4c07ba)

**Comment by Bin-Huang** [comment]
这个功能在最近半年的新版本中已经有了，先关闭了
