### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by liuyiheng001** [Bin-Huang/chatbox#553]
**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "[chatbox_0.4.1_amd64.AppImage)"
2. 点击 对话窗口，点击复制，无法复制内容，并且代码中点击复制，也无法复制

**桌面端（请填写以下信息）：
- 操作系统：Linux ubuntu20.04
- 应用程序版本：0.4.1

**Comment by youyublue** [comment]
操作系统：Manjaro，应用程序版本：0.4.2
依然有以上问题，按复制按钮没有相应

**Comment by Bin-Huang** [comment]
This feature has been implemented, try the latest version.

随着版本的更新，这个功能已经实现了，试试最新的版本。
