### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aoqiangit** [Bin-Huang/chatbox#555]
我用的系统是centos 9，包用的是chatbox_0.4.1_amd64.AppImage，一直提示API请求失败，但是在WIN11上就不会提示正常使用，是不是对于LINUX不太友好呢？希望有大佬能解决以下。
一直提示如下：
API 请求失败：
TXT
Load failed

I use the system is centos 9, the package used is chatbox_0.4.1_amd64.AppImage, always prompt API request failure, but in WIN11 will not prompt normal use, is not for LINUX is not very friendly? I hope some big brother can solve the following. It keeps prompting as follows: API request failed: TXT Load failed

**Comment by aoqiangit** [comment]
![2023-04-29 23-29-17屏幕截图](https://user-images.githubusercontent.com/53580644/235310717-0b775a8e-b289-4a78-8068-c0a34710b775.png)
有没有大佬遇到过这个问题的，帮忙解决以下

**Comment by aoqiangit** [comment]
![2023-04-29 23-31-34屏幕截图](https://user-images.githubusercontent.com/53580644/235310785-ae51aae4-9a08-41fc-ab0d-70dffd602c29.png)

**Comment by aoqiangit** [comment]
![2023-04-29 23-31-34屏幕截图](https://user-images.githubusercontent.com/53580644/235310806-cc55132f-c9da-4199-8dd1-6bef05c965f8.png)
设置上我是默认的

**Comment by Bin-Huang** [comment]
和软件无关，这个是网络问题，需要解决那个特殊的网络问题才能
