### ISSUE TITLE
[BUG] extremely slow interface in ubuntu

### ISSUE THREAD

**Issue by CaneRandagio1983** [Bin-Huang/chatbox#557]
The **user interface is extremely slow** to respond to inputs.

I expect usage to be fast and not slowed down.

I first installed via .deb package and tried the software, then uninstalled and tried the AppImage version.
The experience was the same, the graphical interface is extremely slow in clicking on the buttons and opening the settings windows for example, or when I entered the API key, it took 7/8 seconds to show it after pasting it .
When I type the prompt, it is not written instantly but many seconds pass before it is visible in the textbox.
I checked the processor usage and it was really low.

- Operating System: Ubuntu 22.04.2 LTS
- Application Version: 0.4.1

**Comment by Bin-Huang** [comment]
Thanks a lot for your feedback. I'm working on resolving this issue as we speak.

**Comment by Bin-Huang** [comment]
This issue has been resolved in the latest version. Give the newest version a try:
https://github.com/Bin-Huang/chatbox/releases
