### ISSUE TITLE
4api使用失败

### ISSUE THREAD

**Issue by houyvcai** [Bin-Huang/chatbox#559]
我是plus会员，也申请了api通过了，然后生成了新的API（在原来处，没找到其他的地方生成4api），用新的API和使用GPT-4仍然失败,提示:{"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}

**Comment by Whatsk** [comment]
我也是同样的问题。

**Comment by tigerdoo** [comment]
我也是同样的问题，求解

**Comment by Bin-Huang** [comment]
API 和 ChatGPT 是两个账户体系。不管是不是 ChatGPT  Plus，API 账户使用 GPT4 都需要额外排队申请。官方申请链接是：https://openai.com/waitlist/gpt-4-api

**Comment by dullduck** [comment]
现在是没有https://openai.com/waitlist/gpt-4-api 这个waitlist了吗，访问后，页面不是登记页面了
