### ISSUE TITLE
[Feature]希望可以自己设置上下文消息个数的功能

### ISSUE THREAD

**Issue by yyy22335** [Bin-Huang/chatbox#563]
因为有些对话可能不需要太多的上下文信息，因此有自定义选项将非常有用。

**Comment by Vstory** [comment]
上下文字数到了一定数量，支持自动做个总结，然后使用总结内容作为上下文。

**Comment by yyy22335** [comment]
> 上下文字数到了一定数量，支持自动做个总结，然后使用总结内容作为上下文。

其实我的意思并不是需要一个自动总结的上下文，因为有些时候，AI对同一个提示词的多轮对话，并没有单独对话的效果来的好，所以有些特定的提示词，仅仅需要将当前对话发送给AI，并不需要联系上下文。

**Comment by Bin-Huang** [comment]
已经有这个功能了，试试更新到最新版本
