### ISSUE TITLE
[Feature] prompt提供自定义分组保存

### ISSUE THREAD

**Issue by lxy-Jason** [Bin-Huang/chatbox#566]
就是我想创建新对话的时候,能够使用我之前自定义添加的prompt,

**Comment by lxy-Jason** [comment]
可以再加上清除记录的时候,我设置的prompt可以保留,比如我让gpt充当翻译,当tokens满了,不管我是清空记录还是新开一个会话,之前的prompt都没有了,我希望能做到保留prompt,这样可以不必重复输入prompt

**Comment by Hisoka-J** [comment]
是的新建对话的时候能自定义prompt就很好了，现在新建对话就是新的，空的，之前预设的对话一旦删掉就找不回来了

**Comment by Bin-Huang** [comment]
也可以试试新的 My Copilots 的功能
