### ISSUE TITLE
chatbox软件会永久免费吗？

### ISSUE THREAD

**Issue by wuyuezhui** [Bin-Huang/chatbox#567]
大家都知道天下没有免费的午餐，我想知道咱们这个软件什么时候会收费？

**Comment by Bin-Huang** [comment]
你现在用的功能全部是免费的，后续可能会有付费的高级功能。

**Comment by Bin-Huang** [comment]
很感谢你的理解和支持，“用爱发电”真的很难长久

**Comment by Aoyia** [comment]
写个软件，收点咖啡费用太正常了，和吃饭一样这费用不能省。感谢大佬提供的如此便捷的windows工具

**Comment by tech1502** [comment]
https://chatgpt.030987.xyz/

**Comment by LucasIsGood** [comment]
后续可能的付费是订阅制还是买断制哇, 价格多少我好考虑🫢

**Comment by Bin-Huang** [comment]
你目前所有用到的功能都是免费的，如果收费的话只会做新的高级功能。
目前我兴趣成分更多，很多其他软件里的高级功能我会完全免费。
