### ISSUE TITLE
[BUG]安装后卡在这个界面一直不懂

### ISSUE THREAD

**Issue by chocolatedes** [Bin-Huang/chatbox#569]
![image](https://user-images.githubusercontent.com/77556859/236110948-9006ce39-ba02-49c0-9fe3-7da48af26ce8.png)

**Comment by chocolatedes** [comment]
光标也是不动的，点按钮都没用

**Comment by Bin-Huang** [comment]
你好，请问是什么系统和版本？

**Comment by chocolatedes** [comment]
win10和4.0版本

**Comment by chocolatedes** [comment]
打开了将近一分钟，他才跳到了界面。之前我都是十几秒没反应我就关掉了。

**Comment by Bin-Huang** [comment]
之前的更新中应该已经修复了
