### ISSUE TITLE
请问如何在保留聊天记录的情况下更新版本呢？

### ISSUE THREAD

**Issue by Garmax** [Bin-Huang/chatbox#57]
RT，更新非常勤快点赞^_^

**Comment by Bin-Huang** [comment]
直接更新。会话是保存到本地的，每次更新都会确保兼容。

**Comment by Garmax** [comment]
> 直接更新。会话是保存到本地的，每次更新都会确保兼容。

是直接把新版本的所有文件copy过来就行吗
