### ISSUE TITLE
[望添加语音输入和自动播放功能]

### ISSUE THREAD

**Issue by pixels9** [Bin-Huang/chatbox#572]

**Comment by ra1nzzz** [comment]
复议，语音回答和提问。

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1239, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1239。这条 issue 先关闭了～～
