### ISSUE TITLE
[BUG]安装成功后一直显示白屏页面无法进入

### ISSUE THREAD

**Issue by tangjiamin1220** [Bin-Huang/chatbox#576]
**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1.  "安装了0.4.0和0.4.1两个版本，安装成功后双击运行（已挂梯子），均停留在白屏页面，点击关闭按钮无法关闭，只能在任务管理器中关闭"
2. 我的系统版本是win10 LTSC 1809，操作系统内部版本为17763.4131

![image](https://user-images.githubusercontent.com/49683020/236362515-d4cc53b6-7a97-44c6-ac30-1d0fb40f598e.png)

![image](https://user-images.githubusercontent.com/49683020/236362559-5d4b14ed-5e5b-4ef3-a99b-b7e341531819.png)

**Comment by Http-200** [comment]
尝试下载最新的webview2试试看，https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/

**Comment by Bin-Huang** [comment]
你好，新版本做了修复，下载最新版本再试一下？https://github.com/Bin-Huang/chatbox/releases

**Comment by tangjiamin1220** [comment]
收到 万分感谢已经正常了
