### ISSUE TITLE
[BUG] 请问数据存储在本地，不会丢失，那么数据到底在哪呢？我可能需要偶尔换电脑使用

### ISSUE THREAD

**Issue by ontheroad023** [Bin-Huang/chatbox#579]
**Bug 描述**
黄工，你好，我刚又确认了一下咱们的这个软件的介绍，其中有一条写的是咱们的这个软件数据存储在本地，不会丢失。
我用everything搜索了一下关键字，然后又在系统自带的Documents文件夹找了一下，都没有找到数据。

请问，如果我需要备份数据(是不是只能选择导出功能啊)，那如果我换了电脑，这个数据是不是就不太好找了呢？只能旧电脑导出新电脑导入吗？

**桌面端（请填写以下信息）：**
- 操作系统：Windows10
- 应用程序版本：Chatbox v0.4.1
![1](https://user-images.githubusercontent.com/132318350/236372630-b30902f1-4bcf-4e67-a0ff-93c073e2b8b1.png)

**Comment by Http-200** [comment]
Win在这个文件路径下：`C:\Users\你的用户名\AppData\Roaming\xyz.chatboxapp.app\config.json`

**Comment by yyy22335** [comment]
> Win在这个文件路径下：`C:\Users\你的用户名\AppData\Roaming\xyz.chatboxapp.app\config.json`

谢谢，借助同步软件，现在可以多台电脑同步聊天记录了。

**Comment by Http-200** [comment]
> > Win在这个文件路径下：`C:\Users\你的用户名\AppData\Roaming\xyz.chatboxapp.app\config.json`
> 
> 谢谢，借助同步软件，现在可以多台电脑同步聊天记录了。

哈，对你有帮助就行！！！

**Comment by ontheroad023** [comment]
感谢http-200的回答，已解决我的疑问，非常感谢，同时也感谢wuyudi的思路，Thks

**Comment by ivanberry** [comment]
> 感谢http-200的回答，已解决我的疑问，非常感谢，同时也感谢wuyudi的思路，Thks

macOS 是什么文件路径，有人知道吗？

**Comment by huxk96** [comment]
> > 感谢http-200的回答，已解决我的疑问，非常感谢，同时也感谢wuyudi的思路，Thks
> 
> macOS 是什么文件路径，有人知道吗？

同问

**Comment by xiaotao1340** [comment]
> > 感谢http-200的回答，已解决我的疑问，非常感谢，同时也感谢wuyudi的思路，Thks
> 
> macOS 是什么文件路径，有人知道吗？

找了一下，应该是在 Library/Application\ Support/xyz.chatboxapp.app/config.json

**Comment by xiaotao1340** [comment]
> > > 感谢http-200的回答，已解决我的疑问，非常感谢，同时也感谢wuyudi的思路，Thks
> > 
> > 
> > macOS 是什么文件路径，有人知道吗？
> 
> 同问

试试 Library/Application\ Support/xyz.chatboxapp.app/config.json

**Comment by Pochinki98** [comment]
求一下各位大佬apk版的储存路径？

**Comment by ZY111spec** [comment]
> > > > 感谢http-200的回答，已解决我的疑问，非常感谢，同时也感谢wuyudi的思路，Thks
> > > 
> > > 
> > > macOS 是什么文件路径，有人知道吗？
> > 
> > 
> > 同问
> 
> 试试 Library/Application\ Support/xyz.chatboxapp.app/config.json

那么安卓手机（鸿蒙OS）的文件路径存储在哪里呢，我找不到，求解答！！
