### ISSUE TITLE
关于可能被封禁的情况提醒

### ISSUE THREAD

**Issue by weavers1f** [Bin-Huang/chatbox#58]
我是在异次元软件世界那里的文章《比 ChatGPT 网页版好用百倍！8 款整合 API 的智能客户端工具与 Ai 插件推荐》中看到这个工具的，试用下很好，不过评论中有人说到使用后账号被OPENAI封禁的情况。
今早在网罗灯下黑的公众号推文《我玩GPT4号被封了》中看到，如果使用国内IP调用的话，就可能会被封禁，在另外一篇文章中看到使用新加坡ip调用API也会有可能。
就想是不是收集下相关信息，在软件界面对此类情况进行提示一下？
![VeryCapture_20230317084840](https://user-images.githubusercontent.com/19663899/225784063-3f77e3b2-aa75-4c4b-a8b6-e5d5f4fb24f0.jpg)
![VeryCapture_20230317085233](https://user-images.githubusercontent.com/19663899/225784083-840e6a9d-84ae-4c83-8e84-c33ea1c7d32d.jpg)

**Comment by Bin-Huang** [comment]
好的，我考虑在中文readme中加下

**Comment by HenMie** [comment]
这类情况应该是IP的问题，最近风控似乎比较严，尽量避免共用IP（比如机场）
