### ISSUE TITLE
[建议]希望 用户框和机器人框区分开来，或者 增加头像

### ISSUE THREAD

**Issue by Thomas-cat** [Bin-Huang/chatbox#580]
两个机器人未定义头像在那里。有时候一样望过去你都不知道哪个是自己发的，哪个是机器人

而且机器人头 和用户头 都是在左侧 。按理说 不应该一左一右吗。

或者两个字体颜色设置不同的区分开来比较好。 
或者两个隔离框框用 不同的明显的颜色区分比较好

**Comment by Bin-Huang** [comment]
很早之前的版本已经实现了，可以更新一下，先关闭了这条 issues 了。

**Comment by Hydway** [comment]
请问如何修改呢，在windows软件里没有找到
