### ISSUE TITLE
这显然要翻墙才可以用的 [Feature]

### ISSUE THREAD

**Issue by jjiikkkk** [Bin-Huang/chatbox#582]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by Bin-Huang** [comment]
一直都需要的

**Comment by Bin-Huang** [comment]
但是可以做到普通用户直接使用，无需解决网络问题。具体做法可见 Proxy 配置和搜索。

**Comment by tech1502** [comment]
@jjiikkkk   https://chatgpt.030987.xyz/

**Comment by Bin-Huang** [comment]
没想到这个功能有这么多讨论。其实真的很简单，出了某种原因我这里简单讲一下解决方案。

方法一：（推荐）

打开 Chatbox 设置窗口，展开 “Proxy/代理” 栏，在输入框中填入 https://proxy2.chatbox.run，即可正常使用

方法二：

将 openai.com 添加到你的代理工具名单，一般热门的工具会积极维护 PAC，你拉取最新的 PAC 文件后可能发现工具已经支持了。这样你的工具会代理 openai.com 的流量。

希望可以帮助到大家

**Comment by jjiikkkk** [comment]
嗯 其实想说的就是这个意思 不想因为代理的事情，给自己招惹麻烦
