### ISSUE TITLE
[BUG]macos10.13.6 配置无法保存

### ISSUE THREAD

**Issue by kingxiaofire** [Bin-Huang/chatbox#584]
感谢提供如此优秀的项目
**Bug 描述**
macos10.13.6 配置无法保存，关闭程序后，重新打开，需要重新设置，而且需要重新填写API KEY
这就比较麻烦了，望修复

**Comment by Bin-Huang** [comment]
你好，我猜测可能是和 MacOS 10 的兼容性有关。方便升级一下你的 MacOS 系统版本吗？也许可以直接解决问题。如果有什么进展请务必告诉我，这样我可以更方便排查。

**Comment by kingxiaofire** [comment]
非常感谢您的回复，暂时有部分工作仍需要mac，涉及环境和依赖，不太方便升级版本。我不会mac开发，不然或许能帮上忙。但也没关系，我可以继续在linux使用您的项目，再次表示感谢，祝好。

**Comment by Bin-Huang** [comment]
好的，还可以试试网页版本：https://web.chatboxapp.xyz/
