### ISSUE TITLE
样式问题

### ISSUE THREAD

**Issue by ynotoony** [Bin-Huang/chatbox#586]
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/20440468/236594220-ebebd4fc-949c-4816-9a8a-a1ec972ae99b.png">

**Comment by ynotoony** [comment]
还有一个问题是，我设置了白天模式，退出再进入，又会变成黑夜模式，而且设置项还是停留在白天模式，需要重新点一下才能白回来。

**Comment by Bin-Huang** [comment]
新版本还有这个问题吗？
