### ISSUE TITLE
[Feature]内置SOCKS代理支持

### ISSUE THREAD

**Issue by yiding-he** [Bin-Huang/chatbox#587]
希望能支持App内配置SOCKS代理，或者在运行参数中指定代理也行

**Comment by ayakasuki** [comment]
#13 其实作者已经做好，在犹豫该不该上线。

**Comment by Bin-Huang** [comment]
没想到这个功能有这么多讨论。其实真的很简单，出了某种原因我这里只能简单讲下。

**方法一：（推荐）**

打开 Chatbox 设置窗口，展开 “Proxy/代理” 栏，在输入框中填入 `https://proxy2.chatbox.run`，即可正常使用

**方法二：**

将 openai.com 添加到你的代理工具名单，一般热门的工具会积极维护 PAC，你拉取最新的 PAC 文件后可能发现工具已经支持了。这样你的工具会代理 openai.com 的流量。

**关于内置代理功能**

出于各种原因暂时不会发布，而且我认为这个功能其实有太多更好的替代方法了

希望可以帮助到大家

**Comment by pubyun** [comment]
Chatbox 设置窗口，没有找到 “Proxy/代理” 栏

**Comment by Bin-Huang** [comment]
选择 OpenAI API，直接输入到 API HOST 就可以了

**Comment by Bin-Huang** [comment]
Implemented

**Comment by 1572683490** [comment]
> 选择 OpenAI API，直接输入到 API HOST 就可以了

现在的代理是不是不支持socks5的身份认证呀
