### ISSUE TITLE
[BUG] Prompt 输入时，界面文字偶尔会消失

### ISSUE THREAD

**Issue by everyx** [Bin-Huang/chatbox#589]
**Bug 描述**
Prompt 输入时，界面文字偶尔会消失，目前找不到触发的规律

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 打开主界面
2. 输入 Prompt
4. 发现了这个 bug。

**期望结果**
文字正常显示

**实际结果**
文字消失

**截图**
[录屏 2023-05-06 23-03-51.webm](https://user-images.githubusercontent.com/1665522/236632266-7b4b1fc9-c7c7-4f0c-9f04-f4df456a7844.webm)

**桌面端（请填写以下信息）：**
- 操作系统：Arch Linux
- 应用程序版本：0.4.1

**其他上下文**
无

**Comment by Bin-Huang** [comment]
很早之前的版本已经解决了，可以更新一下，先关闭了这条 issues 了。
