### ISSUE TITLE
希望支持代码视图，支持常见语言的格式化

### ISSUE THREAD

**Issue by qingyiquan** [Bin-Huang/chatbox#59]
RT，现在代码输出的注释和代码经常混为一行，没有语法高亮和排版。可以在对话框视图内嵌代码块格式化的组件么？

**Comment by Bin-Huang** [comment]
你好，这个功能从第一个版本就支持的哦。你至所以会遇到这个问题，是因为 AI 返回了纯文本。你可以让他用 markdown 的方式回复你，就可以看到代码高亮了。

**Comment by qingyiquan** [comment]
多谢指教
