### ISSUE TITLE
[虫子]api代理地址不能用

### ISSUE THREAD

**Issue by es3344520** [Bin-Huang/chatbox#594]
如题，这个代理地址在其它app可以正常使用，在你这个软件里面就用不了。 显示api请求失败。

**Comment by sugerlime** [comment]
我也遇到这个问题，chatGPT网页版没有问题，都可以正常用，但是box就显示使用量已经用完等等。今天升级了0.4.2 还是出现同样的问题

**Comment by lincoln2023** [comment]
同样的问题，如何解决？
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by zlzshh** [comment]
> 同样的问题，如何解决？ {"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

蹲一下，同样的问题

**Comment by tech1502** [comment]
https://chatgpt.030987.xyz/

**Comment by Bin-Huang** [comment]
这个问题是因为 API 账户和ChatGPT账户是两套独立的账户体系，你只需要在 platform.openai.com 绑定信用卡，就能解决上面的问题。
