### ISSUE TITLE
[feature] 版本升级希望可以在当前应用里安装更新，而无需跳转网页下载后覆盖

### ISSUE THREAD

**Issue by haikerapples** [Bin-Huang/chatbox#596]
版本升级希望可以在当前应用里安装更新，而无需跳转网页下载后覆盖

**Comment by Bin-Huang** [comment]
什么系统呢？一直都有自动更新弹窗的

**Comment by haikerapples** [comment]
我这边是MacOS 13.3.1； 自动更新弹框的弹出逻辑是怎样的？APP启动时候检测弹出吗？ 

我这边的情况是APP一直挂在后台运行着，在这期间可能有更新的版本，但是APP内部没看到弹框；当主动点击检查更新，就跳转到了github中的下载页了

**Comment by Bin-Huang** [comment]
每次重启时就会看到弹窗
