### ISSUE TITLE
[特点] 在 Apple XDR Display 屏幕上 能不能支持高刷？

### ISSUE THREAD

**Issue by Cooper-Han** [Bin-Huang/chatbox#597]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by LucasIsGood** [comment]
有这块屏幕, 还来github干啥, 直接联系国际开发者做一个个性化软件不在话下

**Comment by HKZ773999** [comment]
> 有这块屏幕, 还来github干啥, 直接联系国际开发者做一个个性化软件不在话下

所有的 带刘海的 MacBook Pro 都搭载的这款屏幕啊。

**Comment by LucasIsGood** [comment]
不是呀, 是苹果官网40000块的那个

**Comment by HKZ773999** [comment]
> 不是呀, 是苹果官网40000块的那个

我的意思是所有的带刘海的 MacBook Pro 都支持高刷，跟4W 那个显示器样都是 mini Led。也叫 Apple XDR Display。

**Comment by Bin-Huang** [comment]
你好，请问最新版本还有这个问题吗？

**Comment by Bin-Huang** [comment]
我自己也是使用新款的 Macbook Pro，目前从来没有遇到显示问题，所以先关闭了～
