### ISSUE TITLE
求助，为什么更换了api代码，一直还是提示API 请求失败，重装也没用，请求帮忙回复。

### ISSUE THREAD

**Issue by xxf19900504** [Bin-Huang/chatbox#599]
输入prompt，无法展开对话。选择的模型就是免费3.5模型呀。
![001](https://user-images.githubusercontent.com/90176983/236760347-bc59dd5a-9488-419f-8bc4-36fc993c96f6.png)

**Comment by zlzshh** [comment]
同问，蹲一下解决方法

**Comment by tech1502** [comment]
来试试啊   https://chatgpt.030987.xyz/  web更方便

**Comment by TFTree** [comment]
这是因为免费额度过期了

**Comment by Bin-Huang** [comment]
其实原因已经在错误里了。API 账户和 ChatGPT 账户是 OpenAI 两套独立的账户体系。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。
这个问题和软件没有任何关系。
如果你不想折腾 API 账户的各种问题的话，强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0
