### ISSUE TITLE
正在输出文字的时候，不能用鼠标暂停滚动或向上滚动

### ISSUE THREAD

**Issue by KingJadeLight** [Bin-Huang/chatbox#60]
因为文字是连续输出的，为了效率，有时候我想边输出边读。在官网或typingmind里可以用正常用鼠标滚轮暂停滚动或向上滚动。但是这里这么做的时候输出文字会强制继续向下滚动并发生颤抖。希望可以改进，使得输出文字和上下滚动互相独立。

**Comment by KingJadeLight** [comment]
和这个issue应该是有联系： https://github.com/Bin-Huang/chatbox/issues/52#issue-1626054111

**Comment by Bin-Huang** [comment]
是的，这个问题已经在修复中了。因为和其他 issues 重复，我先关闭了。讨论可以到相关 issues 进行
