### ISSUE TITLE
[BUG]提交prompt后，始终回复：“Failed to fetch”，在windows运行0.4.2版本

### ISSUE THREAD

**Issue by pengcheng1978** [Bin-Huang/chatbox#600]
**Bug Description**
1、已经正确设置了，api key，代理的地址。
2、ping 我代理的地址是可以的。
3、通过浏览器直接访问代理的地址也是可以的。
但是，通过本软件就是会提示：
“
API 请求失败：

TXT
复制
Failed to fetch
”

同样的配置，我用macbook版本是可以正常运行的。
<img width="837" alt="image" src="https://user-images.githubusercontent.com/129757867/236792266-0eedd6a6-1a3b-472b-941f-31787772a226.png">

**Comment by goodrabbit** [comment]
感觉是个BUG，0.4.1版本还是好的，我也遇到了这个恼人的问题。

**Comment by pengcheng1978** [comment]
0.4.1也不行。
在反向代理的日志里，看不到请求。
但ping可以通，浏览器访问可以通。

**Comment by zjfqcdb** [comment]
我也遇到了同样的问题，0.4.1没遇到过过，更新后经常Failed to fetch

**Comment by evanchan1989** [comment]
同样遇到，很奇怪呢

**Comment by zhengzhou** [comment]
这个基本可以肯定就是网络问题

**Comment by pengcheng1978** [comment]
> 这个基本可以肯定就是网络问题

你仔细看，windows下，直接浏览器打开，是通的，ping也是通的。
另外，这个windows是macbook的虚拟机，macbook下的可以用。

**Comment by pengcheng1978** [comment]
<img width="1479" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/129757867/70d5503b-a4cc-4a8d-9659-d9cd01d8cd15">

**Comment by zhengzhou** [comment]
```Fetch API cannotoad http://43.157.81.249/v1```

这个是你的代理吗，有没有端口什么的。 TypeError 错误就是网络请求fetch函数的异常

**Comment by pengcheng1978** [comment]
> `Fetch API cannotoad http://43.157.81.249/v1`
> 
> 这个是你的代理吗，有没有端口什么的。 TypeError: Load failed 错误就是网络请求fetch函数的异常

MacBook版本的chatbox可以使用，只是windows版本的不行，同样的配置。。。

**Comment by pengcheng1978** [comment]
> 

是代理，无端口，macbook版本的chatbox在同样配置下没有任何问题。
<img width="988" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/129757867/8740392e-3284-4c22-badf-973fb70e353b">

**Comment by pengcheng1978** [comment]
<img width="922" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/129757867/e44b31ff-773c-46e8-a520-224b3867c126">
这个文件404，是个问题原因吗？

**Comment by pengcheng1978** [comment]
<img width="771" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/129757867/29a48ed3-db42-40cd-9e10-339ec5c93d3d">

**Comment by zhengzhou** [comment]
后面这个截图看到原因了，404和tauri_metadata那个警告都没关系，注意是红色❗️那个fetch api问题，看着是跨域问题导致请求失败。可能tauri在要配置一下

**Comment by pengcheng1978** [comment]
> 后面这个截图看到原因了，404和tauri_metadata那个警告都没关系，注意是红色❗️那个fetch api问题，看着是跨域问题导致请求失败。可能tauri在要配置一下

应该是，跨域，因为没看代码，所以就拿web版本调试看了下。
因为不确定windows窗口版本是不是和web同样机制。
mac版本是另一套机制吗？mac版本一直可以正常使用。

**Comment by pengcheng1978** [comment]
这个问题，在0.4.4还存在。
@goodrabbit @zhengzhou

**Comment by Bin-Huang** [comment]
大家好，一般这个是网络问题

**Comment by Bin-Huang** [comment]
可以仔细描述下你们的网络情况以及使用了哪些代理吗？

**Comment by Bin-Huang** [comment]
和软件和版本都没有关系的，是网络或者代理设置的问题
