### ISSUE TITLE
[Feature] Local data persistence options

### ISSUE THREAD

**Issue by FreedomBen** [Bin-Huang/chatbox#604]
Apologies if this is not the correct place for this.  I searched around but could not find anywhere.

Where is local data _currently_ stored when running the app image version?  I looked through the code and also through my filesystem but could not find it.   Is it just in the tauri version of local storage? 

Expanded persistence options would be a killer feature, at least for me.  The ideal for me is the run a self-hosted server and have the history stored in postgres, but just about anything that allows me to backup (and preferably merge) would be fantastic.  Most of the history isn't all that useful, but so far I've already had a couple times come up where being able to see exactly what was asked and answered would have been really useful.

**Comment by Http-200** [comment]
#579 You can go to this path to view: `C:\Users\Your Username\AppData\Roaming\xyz.chatboxapp.app\config.json`

**Comment by FreedomBen** [comment]
Thank you!  I'm on Linux and found it here (for anyone in the future looking for this info):

```
/home/ben/.local/share/xyz.chatboxapp.app/config.json
```
