### ISSUE TITLE
网页版咋部署

### ISSUE THREAD

**Issue by yuanjie-ai** [Bin-Huang/chatbox#605]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by tech1502** [comment]
https://chatgpt.030987.xyz   网页版

**Comment by yanyuxiyangzk** [comment]
> https://chatgpt.030987.xyz 网页版

这个在哪里的，是开源的吗

**Comment by Bin-Huang** [comment]
## 官方的网页版本是 https://web.chatboxapp.xyz/

现在有很多三方的网页UI会诱导不知真相的用户输入 API KEY，从而达到盗取 KEY 的目的。我实在不希望出现一些不怀好心的人顶着 Chatbox 的 logo 做盗KEY网站，所以 Chatbox 不会提供直接的网页版部署方法。因此：

1. 如果你是一个普通用户，只想有个好用的网页版本客户端，请直接使用 Chatbox 官方网页版 https://web.chatboxapp.xyz/
2. 如果你是开发者希望有个自部署网页UI，可以考虑使用其他开源自部署方案 https://github.com/Yidadaa/ChatGPT-Next-Web
