### ISSUE TITLE
关于系统人设的使用体会和建议

### ISSUE THREAD

**Issue by xieziyu** [Bin-Huang/chatbox#61]
翻阅了一下源码，注意到当前调用api时总是会保留当前 chat session 的第一条 prompt，结合 clean 功能仅清除 system role 之外的消息，我猜想这里的设计初衷是希望引导用户把第一条 prompt 优先作为 system role 来使用的，这样能达到最佳的指导效果。

这几天在实际使用时，我会对不同的问答场景开不同的 chat session，这里会首先预设它的身份。目前的交互是：
先发一条 prompt 预设其身份，一些指导性的 context 以及输入输出的用例指导。等回复后，我会把第一条消息 edit 一下，把 role 改成 system，然后 clean 掉 bot 无意义的答复，再开始提出实际的问题。接下来再把交互中新产生的一些有用的背景知识 edit 到第一条 system 消息里。这个 session 就成了未来相同场景下的专家了。

这里想说的是，是否可以将 system role 的 prompt 单独地做成一个 chat session 的配置项，而不是默认总拼接第一条？而且在设置 system 的时候，不需要发出 api 请求？主要是这几点：
1. system role 本是可选的，尤其是一些简单提问场景下，不太能预设第一条一定是人设型的问题。
2. 当需要设定 system role 时，能更直观和方便，且不会产生多余的 api 调用
3. 这个 system role 的 prompt 可以通过置顶或者其他固定的展示方式，用于提示这个chat session的基本设定，而不用一直往上翻来确认和编辑

**Comment by Bin-Huang** [comment]
太巧了不是？我正在思考这个问题，刚好有一个完整的方案，你的issues就来了。

这是我最新鲜的想法：
1. 会话中的消息可以右键设置为prompt。每次生成都会带上所有prompt消息和最近上下文。
2. 一个精心设计prompt的会话，可以保存为prompt会话模版，存入自己的prompt book（咒语书）
3. 可以分享自己的prompt book到社区的prompt library（咒语图书馆）

大家有没有其他想法？

**Comment by orangelckc** [comment]
prompt 预设建议存在本地，允许用户自己添加新的预设角色，可以做成多session+多角色的模式

另外有现成的开源[prompt社区]可以参考:
- [中文](https://github.com/PlexPt/awesome-chatgpt-prompts-zh)
- [英文](https://prompts.chat/)

> 太巧了不是？我正在思考这个问题，刚好有一个完整的方案，你的issues就来了。
> 
> 这是我最新鲜的想法：
> 
> 1. 会话中的消息可以右键设置为prompt。每次生成都会带上所有prompt消息和最近上下文。
> 2. 一个精心设计prompt的会话，可以保存为prompt会话模版，存入自己的prompt book（咒语书）
> 3. 可以分享自己的prompt book到社区的prompt library（咒语图书馆）
> 
> 大家有没有其他想法？

**Comment by Bin-Huang** [comment]
这个 issue 有些过时了，同时一些功能也已经实现已久，所以先关闭 issue 了

**Comment by zhaoweiguo** [comment]
> 这个 issue 有些过时了，同时一些功能也已经实现已久，所以先关闭 issue 了

可是这个问题没被解决

**Comment by Bin-Huang** [comment]
> > 这个 issue 有些过时了，同时一些功能也已经实现已久，所以先关闭 issue 了
> 
> 可是这个问题没被解决

@zhaoweiguo 具体是指哪些功能缺失，我看下怎么加一下～

**Comment by zhaoweiguo** [comment]
> > > 这个 issue 有些过时了，同时一些功能也已经实现已久，所以先关闭 issue 了
> > 
> > 
> > 可是这个问题没被解决
> 
> @zhaoweiguo 具体是指哪些功能缺失，我看下怎么加一下～

暂时找到一个方法。
是这样的，我把系统人社设置为空
![image](https://github.com/user-attachments/assets/4e8a61a4-72d3-4993-96d2-e6edcea9822e)
我刷新上下文后，他又给我设置回来了
![image](https://github.com/user-attachments/assets/edc27053-59ba-43c7-bbcb-f736cd52bac7)

我找到的方法是把系统人设设置为空后，再清空
![image](https://github.com/user-attachments/assets/9458534e-d419-4e6d-aa09-587c6ce70507)
