### ISSUE TITLE
[BUG]之前0.4.1能正常使用，更新到0.4.2后，重装多次，依然进入如图页面，无法正常使用了

### ISSUE THREAD

**Issue by tantubufan** [Bin-Huang/chatbox#612]
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2022/‎7/‎6
操作系统内部版本	19045.2486
体验	Windows Feature Experience Pack 120.2212.4190.0

![企业微信截图_16836974004100](https://github.com/Bin-Huang/chatbox/assets/105898330/a117a6bf-4b1a-4f83-9e56-030b2874a431)

**Comment by tantubufan** [comment]
![企业微信截图_16836976312327](https://github.com/Bin-Huang/chatbox/assets/105898330/fa190c15-301a-45d5-b9e1-dec4a1c70bf5)

**Comment by Bin-Huang** [comment]
新版本做了修复，重新下载试试
