### ISSUE TITLE
[BUG]0.4.2无法在Windows10 LTSC 21H2下安装

### ISSUE THREAD

**Issue by meiyouyan** [Bin-Huang/chatbox#613]
**Bug 描述**

无法在Windows10 LTSC 21H2下安装

**重现步骤**
安装时出错

**期望结果**
能够安装成功

**实际结果**
安装失败

**截图**
![image](https://github.com/Bin-Huang/chatbox/assets/49462962/51752655-2bc2-48bd-a9be-0bba25608716)

**桌面端（请填写以下信息）：**
- 操作系统：Windows 10 LTSC
- 应用程序版本：21H2
- 操作系统内部版本：19044.2788

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Exile008** [comment]
我的LTSC安装正常，使用正常
![image](https://github.com/Bin-Huang/chatbox/assets/58934372/0edfa9ff-2396-47f2-899e-66b50a94d1d0)
