### ISSUE TITLE
打开后无法有任何操作，卡死状态只能关掉，再次打开也是不行[BUG]

### ISSUE THREAD

**Issue by wjf68888** [Bin-Huang/chatbox#617]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
打开软件卡死。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
应该是我提交了过多的信息导致，具体原因不详，但是现在重新安装到其他目录也不能使用，我的系统是win10

**期望结果**
让我使用上或者折中的办法感谢

**实际结果**
无

**截图**
![image](https://github.com/Bin-Huang/chatbox/assets/129050236/3b9a1e6e-cb53-4d20-a06e-89e7162debc6)

**桌面端（请填写以下信息）：**
- 操作系统：[win10]
- 应用程序版本：所有版本

**其他上下文**
无

**Comment by wakaka123wakaka** [comment]
我也是最近频繁发现这种卡死现象

**Comment by wjf68888** [comment]
我知道原因了就是单次提交的内容过多过长，切里面还包含了一些代码而导致的，解决办法就是找一台好一点的电脑等待他彻底打开读取完信息，然后删除掉这个有问题的提问就恢复正常了。
