### ISSUE TITLE
添加微软tts语音朗读

### ISSUE THREAD

**Issue by xyh2132** [Bin-Huang/chatbox#618]
如题,加上语音朗读,是学英语的好帮手

**Comment by JackyWay** [comment]
确实，这个功能很实用，建议增加Azure /AWS /Google等 TTS（Text to speech）的API接口，使其能够朗读。

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1239, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1239。这条 issue 先关闭了～～
