### ISSUE TITLE
[BUG]chatbox: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by orsenthil** [Bin-Huang/chatbox#619]
**Bug Description**
chatbox: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

$ sudo dpkg -i chatbox_0.4.3_amd64.deb 
Selecting previously unselected package chatbox.
(Reading database ... 605131 files and directories currently installed.)
Preparing to unpack chatbox_0.4.3_amd64.deb ...
Unpacking chatbox (0.4.3) ...
Setting up chatbox (0.4.3) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...

$ chatbox 
chatbox: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```


```
$ openssl version
OpenSSL 1.1.1t  7 Feb 2023
```

**Comment by Bin-Huang** [comment]
Could you please try downloading the latest version, v0.4.4, and let me know if you encounter any issues during the installation process?

**Comment by Bin-Huang** [comment]
This issue has been resolved in the latest version. Give the newest version a try:
https://github.com/Bin-Huang/chatbox/releases
