### ISSUE TITLE
最近网络不好导致回答出现了“network error”，能否保留已生成的文本不被替换

### ISSUE THREAD

**Issue by hb-0** [Bin-Huang/chatbox#62]
但是有时候已经生成了大半，甚至90%了，直接被替换成了如下：

API Request Failed:
network error

已经生成的都看不见了，能否保留已经输出过的内容呢？

**Comment by hb-0** [comment]
自顶一下，基本就剩这一个问题影响体验了。

**Comment by Bin-Huang** [comment]
我大概有个思路了～

**Comment by Bin-Huang** [comment]
I feel like this issue is a bit outdated, so I went ahead and closed it. But if you think it's necessary, feel free to create a new issue at any time.
