### ISSUE TITLE
[Feature] Organization of chats in folders and subfolders project

### ISSUE THREAD

**Issue by CaneRandagio1983** [Bin-Huang/chatbox#626]
**Problem Description**
When using software for a long time, chats become many, and it is difficult to find them, as in all application for chatgpt

**Proposed Solution**
I would like to be able to organize chats in folders and subfolders, for a quick search according to logic criteria.

**Additional Context**
It is the same principle that regulates the organization of the files in operating systems, programs, etc ... the files are organized for folders and subfolders, as well as the chats should be.

Thanks

**Comment by Bin-Huang** [comment]
It is already supported in the new version.
https://github.com/Bin-Huang/chatbox/releases
