### ISSUE TITLE
[Feature]回复的文字具有语音播报的功能。

### ISSUE THREAD

**Issue by nickycrc** [Bin-Huang/chatbox#627]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
这个电脑端的系统非常好用，但是我可能平时更多的是用语音来进行输入。所以我特别想得到的回复，也能够是一个文字+语音的回复。

**解决思路**
可否做一个语音的开关，有文字的同时播放语音，也可以只显示回复文字。
**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1239, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1239。这条 issue 先关闭了～～
