### ISSUE TITLE
关于windows上 的更新疑问

### ISSUE THREAD

**Issue by langZhuYao** [Bin-Huang/chatbox#63]
感谢开发者开发的好应用，最近一直在用，体验很不错。
但是今天提示更新，而我用的是便携版，解压以后直接用的那一版，我不知道这一版怎么更新才不会遗失我旧版的数据，是把新版解压了直接全部复制过去？还是只复制exe主程序就行？
希望开发者能帮帮我

**Comment by Bin-Huang** [comment]
直接安装即可，数据不会丢失的

**Comment by pre-sight** [comment]
从0.1.3更新到0.3.4有办法不丢失对话记录吗
