### ISSUE TITLE
希望添加对GPT答案的语音阅读功能

### ISSUE THREAD

**Issue by lfy0** [Bin-Huang/chatbox#630]
希望添加对GPT答案的语音阅读功能，这样可以节省阅读时间，感觉体验会更完善

**Comment by jinwyp** [comment]
可以使用微软的TTS 或 windows 的 edge 内置的TTS 接口

**Comment by JackyWay** [comment]
确实，这个功能很实用，建议桌面客户端增加Azure /AWS /Google等 TTS（Text to speech）的API接口，使其能够朗读。

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1239, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1239。这条 issue 先关闭了～～
