### ISSUE TITLE
希望添加代理功能

### ISSUE THREAD

**Issue by leader-sudu** [Bin-Huang/chatbox#631]
希望添加一个代理功能，这样下次使用的时候就不用开全局代理了，指着在客户端中设置代理就可以了

**Comment by MaddoxUp** [comment]
+1

**Comment by jackywu** [comment]
+1

**Comment by fu7100** [comment]
+1

**Comment by wanghuiyt** [comment]
> 希望添加一个代理功能，这样下次使用的时候就不用开全局代理了，指着在客户端中设置代理就可以了

目前暂时可以通过 Proxifier 解决. 不会动着全局代理

**Comment by kingxiaofire** [comment]
+1希望可以增加代理功能

**Comment by DreamsCat** [comment]
> > 希望添加一个代理功能，这样下次使用的时候就不用开全局代理了，指着在客户端中设置代理就可以了
> 
> 目前暂时可以通过 Proxifier 解决. 不会动着全局代理

不行，Proxifier 无法识别 ChatBox ，已添加到规则里

**Comment by Bin-Huang** [comment]
This has been implemented.
