### ISSUE TITLE
[Other] 0.4.4 版本 Windows release 打包了一份 Webview?

### ISSUE THREAD

**Issue by ZhangTianrong** [Bin-Huang/chatbox#636]
因为 Tauri app 比较节约资源所以选择的 chatbox, 但是新的版本打包了 webview 导致体积增大了近 40 倍，这是怎么回事啊？我将系统中的 `113.0.1774.42` 版本 webview 链接代替了安装包内的 `Microsoft.WebView2.FixedVersionRuntime.109.0.1518.78.x64` 似乎并没有遇到什么错误。该问题仅限于 Windows 版本，Linux 和 Mac 版本均未受到影响。

**Comment by coolguy001tv** [comment]
win版本大小的确，太恐怖了，吓得我停在了0.4.3

**Comment by nulshell** [comment]
今天打开提示 0.4.4升级但没有自动升。来release这边看了下200多MB的安装包也下了我一跳，原先的不到10MB，没有选择手动升级。

Azure openai api 看起来价格大概跟Openai的差不多，大家会去买吗？节俭如我，目前试用期的免费值还没用完，用的不多。

**Comment by Bin-Huang** [comment]
原因是 windows 操作系统本身在 webview2 的兼容和维护上做的没有很好，导致有时候 windows 更新就让 webview2 损坏了，之前影响了不少用户。而且并不是所有用户的电脑上 webview2 配置都是正常可以工作的。所以这次固定了 webview2 版本。

节约资源本身可能只是一个强迫症习惯，因为本质上不管如何都是要启动 webview2 进程消耗资源，无非就是哪个版本而已。我觉得唯一解决的就是磁盘大小，但200MB对于论则几T的现代磁盘，感觉只是小水滴而已。
