### ISSUE TITLE
[Other]现在的两个新版本无法在原有版本上自动更新了，必须得重新安装新版本

### ISSUE THREAD

**Issue by MrGongqi** [Bin-Huang/chatbox#638]
你好，，，我发现现在的两个新版本无法自动更新了，以前都是可以在原有安装版本的基础上更新的，现在无法做到了，只能重新下载新版的安装程序来安装，这是一个bug，还是我电脑的问题啊？我也不清楚。

还有一个问题：Microsoft Azure OpenAI API有什么用呀？

**Comment by Bin-Huang** [comment]
应该不是一个bug，新版本下载会久一些，等一下就会弹出重启框。

Microsoft Azure OpenAI API 是另外一种 GPT 的官方可用的方式。
