### ISSUE TITLE
bug：不能正确显示换行

### ISSUE THREAD

**Issue by HenMie** [Bin-Huang/chatbox#64]
例子：
![image.png](https://s2.loli.net/2023/03/18/D51n6GOWtPw8XfK.png)
而点开“编辑”时，图片才会正确显示。
![image.png](https://s2.loli.net/2023/03/18/HYsEhkMogq7UOw5.png)

我猜测是因为渲染时使用了markdown默认的严格换行，而ChatGPT的输出默认是不遵循严格换行的，所以发生了如上的显示错误。

**Comment by Bin-Huang** [comment]
修复了，下载新版本试试
