### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JaronZou** [Bin-Huang/chatbox#640]
**Environment**
chatbox version: 0.4.4
microsoft edge version:  113.0.1774.42

**Bug Description**
双击打开就出现下面的画面了
 
Screenshot:
<img width="641" alt="1684122139829" src="https://github.com/Bin-Huang/chatbox/assets/76270861/38a8f022-dc11-422b-af63-81000e120552">

**Comment by JaronZou** [comment]
似乎是我的问题，而不是ChatBox的问题，因此我将这个Issue关闭了

**Comment by cccccccczy** [comment]
请问怎么解决的？熬夜到现在还没打开，网上方法试遍了还没解决Orz
