### ISSUE TITLE
API域名设置为http协议，IP为内网IP时，请求异常

### ISSUE THREAD

**Issue by longyuxiao** [Bin-Huang/chatbox#641]
API域名设置为内网： http://172.19.13.242:8080， 请求一直报错 Failed to fetch。  使用wireshark抓包，未发现任何包发出(包括tcp连接报文)

**Comment by longyuxiao** [comment]
使用https可以正常发包

**Comment by Bin-Huang** [comment]
我大概知道是什么原因了，我看看怎么处理比较好

**Comment by pengcheng1978** [comment]
#600
一样的问题。windows版本有这个问题，mac版本没有这个问题。

**Comment by zippozeng** [comment]
这个问题我也遇到了

**Comment by denggeng** [comment]
我也遇到这个问题，在远程，好像用https也不行，抓包看到没发出任何请求体，只有头部信息，而且还发了两次：
`req: Request {
  bodyUsed: false,
  headers: Headers {
  accept: "*/*",
  "accept-encoding": "gzip, deflate, br",
  "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
  "access-control-request-headers": "authorization,content-type",
  "access-control-request-method": "POST",
  connection: "keep-alive",
  host: "supabase_deno_relay_code:8081",
  origin: "https://tauri.localhost",
  "sec-fetch-dest": "empty",
  "sec-fetch-mode": "cors",
  "sec-fetch-site": "cross-site",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Sa...",
  "x-forwarded-for": "172.19.0.1",
  "x-forwarded-host": "127.0.0.1",
  "x-forwarded-path": "/functions/v1/hello/v1/chat/completions",
  "x-forwarded-port": "8000",
  "x-forwarded-prefix": "/functions/v1/",
  "x-forwarded-proto": "http",
  "x-real-ip": "172.19.0.1"
},
  method: "OPTIONS",
  redirect: "follow",
  url: "http://supabase_deno_relay_code:8081/hello/v1/chat/completions"
}
req.text:
query body is empety`

**Comment by denggeng** [comment]
> #600 一样的问题。windows版本有这个问题，mac版本没有这个问题。

我这都有问题

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复
https://github.com/Bin-Huang/chatbox/releases

**Comment by longyuxiao** [comment]
好像还有点问题， http协议的时候，不可以用域名， 只可以写死IP
