### ISSUE TITLE
[Feature] 使用等宽字体显示代码块

### ISSUE THREAD

**Issue by everyx** [Bin-Huang/chatbox#642]
**问题描述**
目前代码块的显示不是使用的等快字体（Linux 环境安装），如下图，代码等宽字体显示效果要好很多。

**解决思路**
针对代码块设置采用等宽字体。

**附加上下文**
![图片](https://github.com/Bin-Huang/chatbox/assets/1665522/ef68c965-6bbb-4823-9181-06f9e710ed7f)

**Comment by everyx** [comment]
简单看了一下，看起来只需要在这里加入？

```css
font-family: ui-monospace, monospace;
```

https://github.com/Bin-Huang/chatbox/blob/6c4b3c6519b2803f6e24dd2f7d31d82f337c53ff/src/styles/Block.scss#LL81C1-L87C2

**Comment by Bin-Huang** [comment]
Looks like this issue might be from an older version. If you're still seeing the problem in the latest release, go ahead and reopen this!
