### ISSUE TITLE
新版本安装包过大 [BUG]

### ISSUE THREAD

**Issue by lovitus** [Bin-Huang/chatbox#643]
win版本的安装包超过200M了。 
能否打包到以前的10M以内

**Comment by alfoil** [comment]
同样觉得，发现是作者打包了一个WebView2进去，无语~

**Comment by Bin-Huang** [comment]
原因是 windows 操作系统本身在 webview2 的兼容和维护上做的没有很好，导致有时候 windows 更新就让 webview2 损坏了，之前影响了不少用户。而且并不是所有用户的电脑上 webview2 配置都是正常可以工作的。所以这次固定了 webview2 版本。

节约资源本身可能只是一个强迫症习惯，因为本质上不管如何都是要启动 webview2 进程消耗资源，无非就是哪个版本而已。我觉得唯一解决的就是磁盘大小，但200MB对于论则几T的现代磁盘，感觉只是小水滴而已。

**Comment by RebornQ** [comment]
> 原因是 windows 操作系统本身在 webview2 的兼容和维护上做的没有很好，导致有时候 windows 更新就让 webview2 损坏了，之前影响了不少用户。而且并不是所有用户的电脑上 webview2 配置都是正常可以工作的。所以这次固定了 webview2 版本。
> 
> 节约资源本身可能只是一个强迫症习惯，因为本质上不管如何都是要启动 webview2 进程消耗资源，无非就是哪个版本而已。我觉得唯一解决的就是磁盘大小，但200MB对于论则几T的现代磁盘，感觉只是小水滴而已。

🤔那是否可以把 webview2 作为可选下载的选项呢？

**Comment by Bin-Huang** [comment]
之前版本就是这样作为自动下载项的，会在需要的时候自动下载，但效果差强人意……如果用户的系统不兼容，还是会出现各种问题。

这个兼容问题我跟踪了很久，发现影响最小的方法就是让包大一些、牺牲一点磁盘空间。

**Comment by Bin-Huang** [comment]
如果微软未来在 webview2 上花的心思多一些、把这些问题解决了，chatbox 会改回来的。但愿早日看到。

**Comment by sslisen** [comment]
> 原因是 windows 操作系统本身在 webview2 的兼容和维护上做的没有很好，导致有时候 windows 更新就让 webview2 损坏了，之前影响了不少用户。而且并不是所有用户的电脑上 webview2 配置都是正常可以工作的。所以这次固定了 webview2 版本。
> 
> 节约资源本身可能只是一个强迫症习惯，因为本质上不管如何都是要启动 webview2 进程消耗资源，无非就是哪个版本而已。我觉得唯一解决的就是磁盘大小，但200MB对于论则几T的现代磁盘，感觉只是小水滴而已。

不是做开发工作的，但是作者的回复我感觉非常有道理，因为每个人的window版本都是不一样的，所以会出现各种兼容性问题，200M的体积对于现在的电脑来说，还没有一天的微信群聊占用空间大，为了稳定性，这样的打包体积非常值得。
