### ISSUE TITLE
[Other]How can I view the code for supporting Azure OpenAI?

### ISSUE THREAD

**Issue by aiyogg** [Bin-Huang/chatbox#646]
I updated to version 0.4.4 in order to use the Azure OpenAI feature, but encountered an error: `{"error":{"code":"DeploymentNotFound","message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}`.
I want to see the code for implementing an Azure API call, but I can't find it.

**Comment by JipingWei** [comment]
Azure Deployment Name is the model name, not the resource name

**Comment by aiyogg** [comment]
> Azure Deployment Name is the model name, not the resource name

Thank you for your reply, It has resolved my issue.
However, I am still curious about the implementation of Azure API support. I couldn't find them in the source code.

**Comment by Bin-Huang** [comment]
I will add more helpful tips in the future to avoid similar issues. Thank you for your feedback😄😄
