### ISSUE TITLE
[BUG]0.4.4输入框的placeholder不会消失

### ISSUE THREAD

**Issue by kingname** [Bin-Huang/chatbox#647]
**Bug Description**
Please provide a clear and concise description of what the bug is.
![image](https://github.com/Bin-Huang/chatbox/assets/5440523/10a36889-31e1-4772-9f59-348ae235f732)

刚刚升级0.4.4版本，发现输入框中的`prompt`这个placeholder，在我输入了文本以后也不会消失，导致两个文字重叠在一起根本看不清。

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. 安装0.4.3
2. 根据提示升级到0.4.4并自动重启
4. Observe the bug.

**Expected Results**
输入文字时，placeholder消失

**Actual Results**
文字重叠在一起

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: macOS
- Application Version: 0.4.4

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

**Comment by Bin-Huang** [comment]
你好，请问是一直复现的吗？mac 什么版本呢？

**Comment by Bin-Huang** [comment]
虽然不知道什么原因，不过新版本 0.6.1 应该不会这样了

**Comment by kingname** [comment]
来信已收到，我会尽快回复。

**Comment by kingname** [comment]
好的，感谢
