### ISSUE TITLE
[Feature]团队共享的反代服务器能否自定义？

### ISSUE THREAD

**Issue by do21** [Bin-Huang/chatbox#648]
看了一下Docker的文档，其中团队共享部分功能看懂了是用caddy做了反代，但是目前申请到Azure OpenAI的话，建议能否用参数的方式传递反代的目标服务器呢？

谢谢作者！

**Comment by seanshb** [comment]
+1

**Comment by Bin-Huang** [comment]
和其他 issues 重复了，先关闭了
