### ISSUE TITLE
[BUG] Linux下不能启用搜狗输入法

### ISSUE THREAD

**Issue by greatzh** [Bin-Huang/chatbox#649]
**Bug 描述**
不能输入中文，可能是应用输入法配置的问题吗，我在输入框里面只能输入英文，而用来输入中文的搜狗输入法，Chatbox貌似是启用不了

**期望结果**
能够用其他输入法输入中文

**实际结果**
只能字母输入

**桌面端（请填写以下信息）：**
- 操作系统：Ubuntu20.04
- 应用程序版本：0.4.4

**Comment by sakura745** [comment]
我的也是一样的问题
系统：
Ubuntu 20.04.6 LTS
chatbox 0.4.4

**Comment by Bin-Huang** [comment]
This issue has been resolved in the new version v0.6.3. If the problem still persists, you can reopen the issue at any time😊.
https://github.com/Bin-Huang/chatbox/releases
