### ISSUE TITLE
[Other]为什么Windows版本突然增大到了203MB？？？以往一直都不到10MB

### ISSUE THREAD

**Issue by shentong0722** [Bin-Huang/chatbox#650]
为什么Windows版本突然增大到了203MB？？？以往一直都不到10MB，而且同样的4.4版本，其他平台的包都要远远小于Windows平台。

**Comment by AStarStory** [comment]
我也非常好奇，为啥就更了一个版本突然这么大了

**Comment by tw0cat** [comment]
+1，而且打开提示有新版本，点确认更新后无反应，不能更新

**Comment by lusbus** [comment]
黑色模式也不能保持了，每次都要手动打开

**Comment by Bin-Huang** [comment]
这里是原因： #643
