### ISSUE TITLE
[Other] 0.4.4 版本的 Windows 安装包怎么一下子大了好多倍

### ISSUE THREAD

**Issue by chllei** [Bin-Huang/chatbox#653]
之前的 Windows 安装包只有8mb，现在怎么变成200+mb了

**Comment by JJ-GeniusBoyius** [comment]
为什么0.4.4版本 安装了打开是白屏

**Comment by Xu-Jam** [comment]
0.4.4怎么没有输入框了。。。。win

**Comment by meoow** [comment]
因为捆绑了一个微软的webview2，可以看成是内置了一个浏览器。我个人是觉得没必要这么搞

**Comment by singularitti** [comment]
> 之前的 Windows 安装包只有8mb，现在怎么变成200+mb了

See https://github.com/Bin-Huang/chatbox/issues/643#issuecomment-1547537918

**Comment by Bin-Huang** [comment]
原因： https://github.com/Bin-Huang/chatbox/issues/643#issuecomment-1547537918
