### ISSUE TITLE
[Feature]希望可以为每个对话单独选择模型

### ISSUE THREAD

**Issue by magicyuuu** [Bin-Huang/chatbox#654]
**问题描述**
当前每个对话都会使用默认的模型，希望可以为每个对话单独设置模型。

**解决思路**
普通的对话使用GPT3.5，有对准确率较高的要求的对话希望使用GPT4.0，这样就可以平衡速率与费用。

**附加上下文**
不涉及。

**Comment by Bin-Huang** [comment]
之前的更新中已经实现了，点击会话标题，打开专属设置，你就能找到了
