### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LuoCong-cc** [Bin-Huang/chatbox#655]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
Chatbox 团队共享功能，使用docker 启动时报错

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行
![1684379615156](https://github.com/Bin-Huang/chatbox/assets/19941594/e09b0bc3-a4d8-4de2-bd76-f6f0e82293d4)
，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统： Debian GNU/Linux 11 (bullseye)

- 应用程序版本：

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
提供下 docker compose yml 或者你的 docker 执行命令

**Comment by Bin-Huang** [comment]
Looks like this issue might be from an older version. If you're still seeing the problem in the latest release, go ahead and reopen this!
