### ISSUE TITLE
[Feature] 多语言prompt和预制prompt列表

### ISSUE THREAD

**Issue by IzualYang** [Bin-Huang/chatbox#656]
**Problem Description**
1. When switching UI language, the initial prompts stay unchanged
2. There is no prompt management options. An editable/importable/exportable preset prompt list will provide great convenience.
3. Another approach is parsing a prompt list/marketplace website, filtering and loading prompts from it.

**Proposed Solution**
Already described above

**Additional Context**
My original problem was asking chatbox to translating prompts (from EN to zh-CN) by itself. But it thought I was asking it to change the character he's been acting as.
-----------------------

**问题描述**
能否为会话切换多语言的初始prompt，以及提供一个可编辑/导入的预制prompt列表，或者绑定一个prompt市场/列表网站从其中加载prompt

**解决思路**
如上

**附加上下文**
问题背景：其实我最初碰到的问题是想让chatbox自己翻译prompt来着，结果它看到角色扮演的字样，把翻译的角色给夺舍了……

**Comment by Bin-Huang** [comment]
在开发了，很巧的是快完成了
