### ISSUE TITLE
[Feature]一键清除下面的所有对话

### ISSUE THREAD

**Issue by 7yilink** [Bin-Huang/chatbox#661]
在对话过程中会出现一些发现无效的对话，所以想从前面的对话再重新开始，使用引用会发现可能不能继续上面的对话，或由于回复长度很长，无法进行引用。
当前我是手动一个一个去删除掉下面的对话，这样可以让话题回到正确的轨迹。否则很容易跑题

**Comment by Bin-Huang** [comment]
v0.6.2 has been implemented, give it a try.
https://github.com/Bin-Huang/chatbox/releases
