### ISSUE TITLE
[Other]Latex 公式编译

### ISSUE THREAD

**Issue by guanyihang** [Bin-Huang/chatbox#662]
latex公式在聊天框中会自动编译，直接复制会生成乱码。

例如：
在输入框中输入 $H_\infty$
![image](https://github.com/Bin-Huang/chatbox/assets/48246303/f19955cd-64f8-4203-b6f7-9e636aca9f1d)
发出去会变成：
![image](https://github.com/Bin-Huang/chatbox/assets/48246303/73e3b893-bfa4-4d1d-90ac-bc95dc99f5ed)
用鼠标复制下来再粘贴会变成：
H 
∞
​
但点击复制按钮再粘贴会变成：
$H_\infty$

我用的版本是0.4.0，我记得几个月前latex公式在聊天框中还不会自动编译，可以直接复制。自动编译确实是个很棒的功能，可以让对话更优美。但能否将这个功能作为可选项呢？

**Comment by guanyihang** [comment]
我有时会用chatGPT纠正我论文的语法错误，直接在聊天中用鼠标拖动选中并复制，再粘贴到vscode中就变成乱码。而点击复制按钮不会有这个问题，但会整段复制，有些不需要的文字还得手动删除。
总的来说不是什么大问题，如果您有时间，希望您考虑将“在聊天中自动渲染 Latex”做成开关选项。

**Comment by Bin-Huang** [comment]
其实你可以点击编辑，这时候可以看到原始文本
