### ISSUE TITLE
【Request】免费账户登录

### ISSUE THREAD

**Issue by AjianYo** [Bin-Huang/chatbox#665]
**Problem Description**
作为轻中度GPT用户，api需求不大，仅免费账户够用。有可能支持账户登录吗？虽然我不知道实现难度

**Additional Context**
同类型中佼佼者，很喜欢这个App，感谢你们的付出。

**Comment by cc852852** [comment]
你的意思就是提供支持access token的版本，我觉得这个可以，感觉作者也会加上该功能

**Comment by Bin-Huang** [comment]
我认为这个属于“破解”ChatGPT的范畴了，不会考虑做这个事情。API 是 ChatGPT 官方开放的，但 access token 不是。
