### ISSUE TITLE
[Feature]快捷Quote按钮

### ISSUE THREAD

**Issue by wchniou** [Bin-Huang/chatbox#668]
ChatGPT有上下文文本reference的限制，每次要提一个新问题，要引用之前发给GPT的对回答的具体要求，但是又不想开一个新的chat页面，所以能不能加个默认的prompt quote，然后再加个快捷方式，放在在prompt输入框上方，每次要提一个新问题直接按一下，就不用滚动到最上方，然后再点quote了。

**Comment by Bin-Huang** [comment]
升级一下，引用按钮很早就改变位置了
