### ISSUE TITLE
[Feature] Delete Chats

### ISSUE THREAD

**Issue by g4borg** [Bin-Huang/chatbox#669]
**Problem Description**
There is cleaning (which sometimes does not seem to work correctly, but this is not about cleaning chats), but there is no way to simply delete a chat entry.

**Proposed Solution**
Add Deletion in the Menu for sidemenu items

**Additional Context**
This should be rudimentary.

Starting the app and having example discussions is one thing, not being able to remove them and start fresh, immediately stands out as a blocker for future use.

**Comment by Bin-Huang** [comment]
😊😊This feature has been implemented in the new version v0.6.3.
https://github.com/Bin-Huang/chatbox/releases

😊😊这个功能在新版本 v0.6.3 已经实现
https://github.com/Bin-Huang/chatbox/releases
