### ISSUE TITLE
求带：   API HOST 这功能怎么用？ 我没理解，谢谢

### ISSUE THREAD

**Issue by kangyiwen** [Bin-Huang/chatbox#67]
求带：   API HOST 这功能怎么用？ 我没理解，谢谢

![image](https://user-images.githubusercontent.com/76672577/226109633-bb2e046b-7def-4e82-89ad-8fb24b0eca2e.png)

**Comment by HenMie** [comment]
这个是请求api的地址，默认是官方的，使用api host可以解决无法直连或者直连速度较慢的情况。你可以使用别人的中转站，或者自己搭建中转代理站（最简单的就是直接反向代理）

**Comment by kangyiwen** [comment]
谢谢，这个理解，但实际怎么找到别人的中转站？ 或自己搭建反代的标准是什么，做一个和OPENAI一模一样参数的接口，只是IP不一样吗？

**Comment by kangyiwen** [comment]
谢谢，这个理解，但实际怎么找到别人的中转站？ 或自己搭建反代的标准是什么，做一个和OPENAI一模一样参数的接口，只是IP不一样吗？

**Comment by kangyiwen** [comment]
谢谢，这个理解，但实际怎么找到别人的中转站？ 或自己搭建反代的标准是什么，做一个和OPENAI一模一样参数的接口，只是IP不一样吗？

**Comment by hb-0** [comment]
自己搭反代最简单应该就是部署一个nginx, 接收请求后一律proxy pass https://api.openai.com，不用管什么参数啦。

**Comment by kangyiwen** [comment]
谢谢
