### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Brooks-2010** [Bin-Huang/chatbox#671]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
不能上传文件。

**解决思路**
支持上传文件，并通过API解析文件文本。

**附加上下文**
当我需要对大数据量文本进行内容解析时，需要反复多段上传。且GPT根据每段内容自动回复时会理解歧义，不如整段内容一起作为GPT的上下文。

**Comment by Bin-Huang** [comment]
这个 issue 有些过时了，先关闭了～
