### ISSUE TITLE
[BUG] Mac 0.44 API Request Failed

### ISSUE THREAD

**Issue by Young0201** [Bin-Huang/chatbox#672]
<img width="986" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/134294871/7c6d976e-da42-4808-9f19-6a6d3a833aa5">

MAC 0.44版本报错 API Request Failed - TXT Load Failed

相同的API key，相同的代理在Windows版本上的chatbox可以正常运行，请问各位前辈，这是怎么回事呢？可以如何修复吗？

**Comment by Alonewolf0408** [comment]
你可以去openai的官网上看看你的API KEY是不是已经锁定或者是满了

**Comment by Young0201** [comment]
> 你可以去openai的官网上看看你的API KEY是不是已经锁定或者是满了

你好，我在官网看了下API KEY还没满，而且我在windows上的chatbox是可以正常使用的，只是在mac上不行。还有什么其他方法可以解决这个问题吗？

**Comment by Bin-Huang** [comment]
I feel like this issue is a bit outdated, so I went ahead and closed it. But if you think it's necessary, feel free to create a new issue at any time.
