### ISSUE TITLE
[Feature] Shortcut keys of switching between chats 

### ISSUE THREAD

**Issue by Flow-sandyu** [Bin-Huang/chatbox#674]
**Function Description**
I hope to be able to switch between chats using Ctrl + Tab and Ctrl + Shift + Tab, which can reduce the switching cost of the mouse and keyboard
 
-----------------------

**功能描述**
我希望可以同过 ctrl + tab 和 ctrl + shift + tab 来上下切换对话，这样可以减少鼠标和键盘的切换开销

**Comment by homoky** [comment]
It would be also great to make cmd + n to make new chat and autofocus on textarea...

**Comment by Bin-Huang** [comment]
Coming soon, stay tuned😁😁😁
