### ISSUE TITLE
Recycle Bin

### ISSUE THREAD

**Issue by MontDawgg** [Bin-Huang/chatbox#678]
**Problem Description**
A way to restore deleted chats. I accidentally deleted a chat and found no way to restore it. Additionally, the program should default to asking confirmation when deleting individual chats. 

**Proposed Solution**
A recycle bin where deleted chats go and can be restored or permanently deleted. 

**Additional Context**
Implementing a recycle bin feature is crucial to restore mistakenly deleted chats, enhancing user experience and data security. Kindly consider this upgrade.

**Comment by Bin-Huang** [comment]
Thank you for your suggestion. I will carefully consider how to design andimplement it.

**Comment by Bin-Huang** [comment]
It is already supported in the new version.
https://github.com/Bin-Huang/chatbox/releases
