### ISSUE TITLE
[BUG] [Web版] 如果使用azure openai作为provider，每次打开页面会提示设置窗口

### ISSUE THREAD

**Issue by MonwF** [Bin-Huang/chatbox#679]
**Bug 描述**
在web版本下，如果使用azure openai作为provider，每次打开页面都会提示设置窗口

**重现步骤**
配置azure key和endpoint，查询，刷新页面

**期望结果**
如果配置了azure key和endpoint，不需要每次进入时弹出窗口

**其他上下文**
目前仅检测openaiKey是否为空，导致该bug
![image](https://github.com/Bin-Huang/chatbox/assets/1267050/ed4e64e6-0e30-49af-b8f2-2dd2b032027c)

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复
https://github.com/Bin-Huang/chatbox/releases

**Comment by MonwF** [comment]
感谢
