### ISSUE TITLE
网络代理问题

### ISSUE THREAD

**Issue by simuty** [Bin-Huang/chatbox#68]
如果开全局代理，可以正常使用；
**如果走规则判断，则提示下边的**

```
API Request Failed:
Failed to fetch
```

规则判断中加了

```
- 'DOMAIN-KEYWORD,chatgpt,Proxy'
```

后来问chatgpt, 他说

```
要访问 ChatGPT，您需要将以下域名设置为走代理：

[chatgpt.com](http://chatgpt.com/)
[s3.amazonaws.com](http://s3.amazonaws.com/)
这两个域名都是 ChatGPT 使用的服务所在的域名。若要正常使用 ChatGPT，需要保证您的网络连接可以访问这些域名。
```

```
    - 'DOMAIN-KEYWORD,s3.amazonaws,Proxy'
    - 'DOMAIN-KEYWORD,chatgpt,Proxy'
```
`用的是同一个节点，开了全局就可以，加上这两个配置依旧不能用`

**请问，是不是需要配置别的域名？**

**Comment by ttyy33** [comment]
你用的clash嘛

**Comment by simuty** [comment]
是的

**Comment by simuty** [comment]
> 你用的clash嘛

是的

**Comment by ttyy33** [comment]
> > 你用的clash嘛
> 
> 是的

你用clash的tun模式 和proxifier组合起来试试

**Comment by ttyy33** [comment]
> > > 你用的clash嘛
> > 
> > 
> > 是的
> 
> 你用clash的tun模式 和proxifier组合起来试试

我刚才试了下，可以使用

**Comment by nwangwei** [comment]
index.ts

添加一段硬编码，临时解决了代理的问题：

// Create the browser window.
const mainWindow = new BrowserWindow({
    height: 1000,
    width: 1400,
    webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        nodeIntegration: true,
    },
});

// 设置代理
mainWindow.webContents.session.setProxy({
    proxyRules: 'socks5://localhost:8888',
    proxyBypassRules: 'localhost',
});

// and load the index.html of the app.
mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

可以针对“socks5://localhost:8888修改代码后

我用的也是clash，我都是指定应用代理的，不想其他没有预期的应用也代理。

**Comment by simuty** [comment]
> > > 你用的clash嘛
> > 
> > 
> > 是的
> 
> 用clash的tun模式可以


> mac版本的增强模式，开着也不好使

**Comment by simuty** [comment]
> index.ts
> 
> 添加一段硬编码，临时解决了代理的问题：
> 
> // Create the browser window. const mainWindow = new BrowserWindow({ height: 1000, width: 1400, webPreferences: { preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY, nodeIntegration: true, }, });
> 
> // 设置代理 mainWindow.webContents.session.setProxy({ proxyRules: 'socks5://localhost:8888', proxyBypassRules: 'localhost', });
> 
> // and load the index.html of the app. mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
> 
> 可以针对“socks5://localhost:8888”修改代码，然后 npm run package重新打包
> 
> 我用的也是clash，我都是指定应用代理的，不想其他没有预期的应用也代理。

谢谢，我试试哈

**Comment by simuty** [comment]
**配置这个就可以了. 问题关闭了。**

```
- 'DOMAIN,api.openai.com,Proxy'
```

**Comment by ttyy33** [comment]
> - 'DOMAIN,api.openai.com,Proxy'

在clash的哪里加，你用的rule模式吗？

**Comment by zhummming** [comment]
> > * 'DOMAIN,api.openai.com,Proxy'
> 
> 在clash的哪里加，你用的rule模式吗？

我试了下，rule模式下在yaml配置文件里添加就好了, 我是把Proxy改成了Direct
```
- 'DOMAIN,api.openai.com,Direct'
```
