### ISSUE TITLE
[BUG]主题设置成黑色之后再次启动程序主题依旧是白色的

### ISSUE THREAD

**Issue by EXBC-TSJH** [Bin-Huang/chatbox#681]
我看了json里面的设置,thems是0(也就是黑色主题的标识),
但是启动后并没有应用这个主题,就像是启动之后主题应用失败了,刷新一下他就可以变成黑色主题了
我个人感觉应该是渲染引擎的问题,但是我也不知道到底是因为什么
希望修复一下这个bug,不知道是不是就我有这个问题

**Comment by sslisen** [comment]
借楼问个问题：0.4.4版本为啥突然200多M大小了。

**Comment by EXBC-TSJH** [comment]
本次更新包含以下内容：

1.新增对 Microsoft Azure OpenAI API 的支持
2.修复一些已知的小问题
---------------------------------------------------------
新增对 Microsoft Azure OpenAI API 的支持,我不知道这个东西是什么,但是希望开发团队完善一下,坐等0.4.5

**Comment by baoxiehao** [comment]
+1

**Comment by Bin-Huang** [comment]
主题问题已经修复过了，更新看看
