### ISSUE TITLE
chatbox can not use，please help me

### ISSUE THREAD

**Issue by Alonewolf0408** [Bin-Huang/chatbox#684]
chatbox show error question：API 请求失败： 
```
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
```
how can I do？

**Comment by undesicimo** [comment]
if you generated your api with a free openAI account youll have a quota on how much you can interact with the language model. Thus you have to pay for more prompts as mentioned on the error message

ref
https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details

**Comment by Bin-Huang** [comment]
Your API account has no balance or the balance has expired, so you need to bind a credit card to the account to continue using it. This issue has nothing to do with the software.
If you don't want to bother with various issues related to the API account, it is strongly recommended to use the built-in AI service added in Chatbox v0.5.0, which is ready to use and doesn't require any network or account issues. https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0
