### ISSUE TITLE
[Feature] Talk to Chatbox via voice

### ISSUE THREAD

**Issue by vaidab** [Bin-Huang/chatbox#685]
Easier integration with various workflows can be enabled by adding dictation to the app.
Basically it would have a unique feature that would differentiate it from other API integrations, the ability to talk to the AI.

**Comment by Bin-Huang** [comment]
This feature has been on my roadmap and is currently in the development queue

**Comment by opediy** [comment]
> 

首先多谢大大的app，的确是目前很好用的一款，非常感谢！
其次是，如果大大考虑加入语音支持，大大可以考虑一下：每个对话，独立的语音设置！
比如：一个对话是：英翻中，另一个对话是中翻英。 市面上的同类app，都无法实现。

另外，很希望大大能完善一下Prompting , 具体请见： https://github.com/Yidadaa/ChatGPT-Next-Web/issues/138

这个功能对于针对性的话题，就是神器 。

再次感谢大大！

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1239, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1239。这条 issue 先关闭了～～
