### ISSUE TITLE
[Feature] iOS / Android app??

### ISSUE THREAD

**Issue by vaidab** [Bin-Huang/chatbox#686]
I'd love to have an iOS version of the app.

**Comment by myworksfun** [comment]
https://apps.apple.com/us/app/openai-chatgpt/id6448311069?l=zh

reference 😄

**Comment by NecronomiconCoding** [comment]
> 

by far nothing like chatbox though.

**Comment by Bin-Huang** [comment]
I'm sorry, but currently, there are no iOS or Android versions available. However, I **have plans to** develop them in the future. In the meantime, I highly recommend using the **web version on your phone**. Personally, I find it fully functional and sufficient for my needs.

**Mobile web version: http://web.chatboxai.app/**

**Comment by Bin-Huang** [comment]
Hello everyone 👋, Chatbox for iOS and Android is now available for beta testing. Click the link below to get early access to the mobile version of Chatbox 😉😉:

📱 iOS (Testflight): [https://testflight.apple.com/join/40nHblIb](https://t.co/xPGxtDcuZa)
📱 Android (Google Play): https://play.google.com/apps/testing/xyz.chatboxapp.chatbox

For Android users, please fill out this application form and I'll grant you early access permissions: https://forms.office.com/r/gZunw2Tswj

**Comment by max-wittig** [comment]
@Bin-Huang Thanks for creating this cool iOS app. It seems like the credentials for OpenAI compatible endpoints are not send. I just get a 401 on iOS, while everything works well on Desktop. Are you aware of that?

**Comment by Bin-Huang** [comment]
> @Bin-Huang Thanks for creating this cool iOS app. It seems like the credentials for OpenAI compatible endpoints are not send. I just get a 401 on iOS, while everything works well on Desktop. Are you aware of that?

If you encounter a 401 error, it may be due to an account issue with OpenAI rather than a Chatbox error.

**Comment by max-wittig** [comment]
@Bin-Huang Thanks for the response! 

We got our own hosted models and we can see that the desktop version works, however the mobile version seems to send empty authentication.

**Comment by elewen** [comment]
大佬，能否将iphone、ipad版app最低能够允许运行的ios系统版本降低到ios14或者ios15？app现在要求最低的系统版本是16.4，这会导致部分无法升级系统的老机型和不愿意升级到较新版本的iphone用户无缘ios版本的app。我大致看了一下，App Store上面现存的绝大多数app将最低可兼容的系统版本设置在ios15.0以下，很少有app会要求系统版本在ios15以上的

**Comment by elewen** [comment]
大佬，能否将iphone、ipad版app最低能够允许运行的ios系统版本降低到ios14或者ios15？app现在要求最低的系统版本是16.4，这会导致部分无法升级系统的老机型和不愿意升级到较新版本的iphone用户无缘ios版本的app。我大致看了一下，App Store上面现存的绝大多数app将最低可兼容的系统版本设置在ios15.0以下，很少有app会要求系统版本在ios15以上的
