### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jwh12333** [Bin-Huang/chatbox#691]
是只有我有这个bug吗，用这个chatbox调api正常询问和回复一次它会调用两次api，第一次显示回复的token很少，第二次才正常，这搞得收我两次费用。我用python调用没有这方面的问题，正常询问和回复一次就是调用一次api
![7CV~I6MNYZTFXZ HP$2UC0L](https://github.com/Bin-Huang/chatbox/assets/109291929/16811f08-898c-4a0d-b72c-fe419887de3d)
上面是不正确的调用api，调用两次但是我只进行了一次问答
![V7HYBML%CF9MK65QZL7DO%V](https://github.com/Bin-Huang/chatbox/assets/109291929/89f9d57d-d1ac-4227-9920-b6ef8c64a1e7)
上面是我用python调用api，这才是正常的调用，问答一次调用一次api
不知道是什么问题，搞得我现在都不用这个了，因为会加倍我调用api的费用

**Comment by Bin-Huang** [comment]
我已经回复过你了，是因为新会话会发送一个请求来自动生成标题，每个会话只会自动生成一次。并不是什么 BUG。
