### ISSUE TITLE
团队共享功能 是否可以支持 AzureOpenAI

### ISSUE THREAD

**Issue by edichangz** [Bin-Huang/chatbox#693]
![图片](https://github.com/Bin-Huang/chatbox/assets/28720557/11722054-6d11-47d8-b31b-f55b218695b9)
团队共享功能 是否可以支持 AzureOpenAI?
现在只能用 Open AI 吗？

**Comment by Bin-Huang** [comment]
目前这个功能已经有非常优秀的开源项目，因此不会考虑在 chatbox 内置这个功能了
