### ISSUE TITLE
[BUG] 代码部分的排版与官网不一致

### ISSUE THREAD

**Issue by maqingbo** [Bin-Huang/chatbox#695]
**Bug Description**

GPT 3.5 是不支持返回图片的，所以我想能不能让他返回字符画，比如简单的逻辑图，结果排版是错乱的。

我拿小奶牛做例子做了测试，如下图：

**Screenshots**

![image](https://github.com/Bin-Huang/chatbox/assets/20136852/175d9f33-312b-4ab6-9eab-938eb0cf7f91)

<img width="686" alt="Snipaste_2023-05-29_18-02-09" src="https://github.com/Bin-Huang/chatbox/assets/20136852/6fa54505-5af5-4623-b2d7-74e6fa643685">

当然有可能他俩返回的不是同一个字符画，但很明显客户端返回的就不是个图案。

**expect result**

返回和官网一样的排版顺序，在使用字符画一些逻辑图时真的非常有用！

**Desktop (please complete the following information):**

- Operating System: [e.g. Windows 10]
- Application Version: [e.g. 0.4.4]

**Comment by trader-tsang** [comment]
明显不是一个图了，调下temperature试试
