### ISSUE TITLE
请问升级会导致聊天记录丢失吗？[Other]

### ISSUE THREAD

**Issue by sslisen** [Bin-Huang/chatbox#701]
看到刚刚更新了0.4.5版本，加入了很多新功能。
非常兴奋看到有了新的版本。
我是从0.4.4开始使用的，还没有经历过版本更新。我看更新的方式是重新下载安装。
所以我想请问：更新后是否会导致原来版本的聊天记录丢失？ AI会不会丢失已经创建好的上下文场景？

感谢。

**Comment by Bin-Huang** [comment]
不会

**Comment by sslisen** [comment]
好的 谢谢
