### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by MWD-IOT** [Bin-Huang/chatbox#704]
希望大佬增加一个能让GPT联网的功能，已有Edge插件实现了这个功能，链接：https://microsoftedge.microsoft.com/addons/detail/webchatgpt%EF%BC%9A%E5%8F%AF%E8%BF%9E%E4%B8%8A%E7%BD%91%E8%AE%BF%E9%97%AE%E4%BA%92%E8%81%94%E7%BD%91%E7%9A%84chat/flahobhjikkpnpohomeckhdjjkkkkmoc
不知大佬能否参考实现一下，感激不尽

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in https://github.com/Bin-Huang/chatbox/issues/1238, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 https://github.com/Bin-Huang/chatbox/issues/1238。这条 issue 先关闭了～～
