### ISSUE TITLE
API 请求失败  Failed to fetch

### ISSUE THREAD

**Issue by JinBerlin** [Bin-Huang/chatbox#705]
API 请求失败  一直报错：Failed to fetch   
换了API key 还是一样报错。(网页版可正常使用)
如图：
![F72ND8N2)T)GE7{MBPAW`JC](https://github.com/Bin-Huang/chatbox/assets/135118598/e2c78994-6ef9-4a65-a608-40e9a66130fa)

**Comment by weixiying** [comment]
因为网不通，梯子架上才可以，之前不用梯子，现在必须用梯子才可以，

**Comment by jokefox** [comment]
梯子不行也会这样吗？

**Comment by JinBerlin** [comment]
> 梯子不行也会这样吗？可是，楼上可以使用网页版呢

网页有油猴的梯子，但是好像覆盖不了全局

**Comment by Snow-S0** [comment]
我使用了几个梯子都不行，我的外网程序都可以正常登录，就它报请求失败

**Comment by ZoeImport** [comment]
我也是我就换了个订阅,官网是能进的但是这里显示这个

**Comment by Alotcer2023** [comment]
有没有解决办法？

**Comment by Alotcer2023** [comment]
用梯子也不行啊，没人解决吗

**Comment by moshouhot** [comment]
路由器安装个梯子就行了，全局代理。

**Comment by Bin-Huang** [comment]
和软件无关，需要解决网络问题😂。也可以试试新版本中内置的AI服务，可以不用折腾网络和账户
