### ISSUE TITLE
之前不用梯子就可以用，现在必须用梯子

### ISSUE THREAD

**Issue by weixiying** [Bin-Huang/chatbox#706]

**Comment by Lala-0x3f** [comment]
这是openai api的问题吧？

**Comment by weixiying** [comment]
> 



> 这是openai api的问题吧？

前几天还可以直接用，昨天发现就不行了，必需架梯子

**Comment by JSCSZZSS** [comment]
我一直需要架梯子才能用。。。

**Comment by Bin-Huang** [comment]
一直都是需要解决网络问题的

**Comment by yemao221** [comment]
2024年最稳定梯子VPN，科学上网2年亲测稳定，56元畅享一年！   
地址：https://www.xxxlsop.com/#/register?code=sf9UTRC0    


🔥全年2300GB高速流量  
针对亚洲优化的IEPL中转方案  
palm world 团队的热门产品  

🌍 奈飞、迪士尼等流媒体解锁 畅享国际热门流媒体  
💡 ChatGPT解锁 - 无障碍访问ChatGPT  
🌐 全球10个国家接入 - 全球多点接入  
🛡️ 99.99% SLA 保证 - 高可靠性服务等级协议  
⚡ 1000Mbps 带宽保证 - 超高速带宽。  
💻 20台客户端同时登录 - 轻量用户的选择。    
[![QQ20240824-134644](https://github.com/user-attachments/assets/6edfdb33-c6bc-492a-8f17-c8d4348a27a2)](https://www.xxxlsop.com/#/register?code=sf9UTRC0)
