### ISSUE TITLE
API 请求失败 超出配额限制

### ISSUE THREAD

**Issue by chaoluo4822** [Bin-Huang/chatbox#707]
**Bug Description**
Please provide a clear and concise description of what the bug is.

输入任何请求，发出下面的报错信息，提示超过了配额限制，但是在我的账户在openAI官网还能正常使用
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by chaoluo4822** [comment]
换了网页版报错方式一样

**Comment by liu-6666** [comment]
我的也是同样情况，在官网看额度还有很多

**Comment by nis3638** [comment]
同样的问题，但是在chatgpt上正常

**Comment by zh-rocco** [comment]
说是 API 过期了

**Comment by qweasdzxc54188** [comment]
同样问题

**Comment by csyunzheng** [comment]
怎么设置呢，是不是api域名的问题

**Comment by DOGE2theMOON** [comment]
同样的问题，更新之后出现的

**Comment by lssgit** [comment]
是的我遇到了同样的问题，实际上还有剩余余额可用

**Comment by tangyunlong** [comment]
俺也一样

**Comment by loveplay1983** [comment]
我认为是试用的API到期了,我查了,有三个月限制,我的提示6月1号到,正好今天.网页可以用,我问它,它自己说网页版和API调用是分开的,同时plus和API调用的费用也是分开的.

**Comment by loveplay1983** [comment]
我之前正好是三月份左右的时候开始使用的好像,那时候建的账号.

**Comment by JoneHm** [comment]
那又要用购买一个接受码来注册了？我去

**Comment by JoneHm** [comment]
我今天也是发现用不了

**Comment by JoneHm** [comment]
我刚刚也重新搞了个新号，也可以用了！应该是试用期过了

**Comment by qweasdzxc54188** [comment]
@loveplay1983 我是搞个新号

**Comment by loveplay1983** [comment]
> 
搞个新号指的是什么意思,重新注册,还是直接买?

**Comment by loveplay1983** [comment]
> @loveplay1983 我是搞个新号

成功了,我知道杂做了哈哈,顺便推荐POE chatgpt,另一个方法可以直接使用,是Quora旗下的

**Comment by chaoluo4822** [comment]
总结就是：
方案①重新注册一个openAI账号，用新的API key才能继续使用chatbox，代价是定期就需要换新的账号，约等于开了一个季度会员；
方案②可以在openAI官网继续使用ChatGPT。我旧电脑ip被openAI封了，但新电脑还能用，暂时可以用这个办法。

但是chatbox响应速度和使用体验都比在官网好太多了，感谢大佬做的软件！

**Comment by xiexuan-1** [comment]
一个Google账户只能注册一个Open AI账号

**Comment by datalazy** [comment]
只要一付費，80%都跑光光

**Comment by qq11109071** [comment]
请问现在有什么解决方案吗？还有是不是都是6月1日过期的？

**Comment by qq11109071** [comment]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by Guiquan-27** [comment]
俺也一样

**Comment by Bin-Huang** [comment]
其实原因已经在错误里了。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。

这个问题和软件没有任何关系。

如果你不想折腾 API 账户的各种问题的话，**强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题**。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0

**Comment by artillerymans** [comment]
> 其实原因已经在错误里了。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。
> 
> 这个问题和软件没有任何关系。
> 
> 如果你不想折腾 API 账户的各种问题的话，**强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题**。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0

@Bin-Huang 我觉得很尴尬一点就是你这个虽然很方便 但是我网页版本是正常的 你这个模型我看了下是3.5的 跟网页端没啥区别

**Comment by Bin-Huang** [comment]
@artillerymans 模型已经更新了，多了很多更好的模型了
