### ISSUE TITLE
win11软件打开白屏

### ISSUE THREAD

**Issue by JJ-GeniusBoyius** [Bin-Huang/chatbox#715]
win11自从 4.4开始以来更新完打开就是白屏状态，而且关闭不了。

**Comment by kyong5** [comment]
兄弟，问题解决了嘛~我也遇到同样的问题，苦恼

**Comment by JJ-GeniusBoyius** [comment]
kyong5 ***@***.***>于2023年6月12日 周一11:30写道：

**Comment by JJ-GeniusBoyius** [comment]
没有解决兄弟

**Comment by Bin-Huang** [comment]
试试下载微软的 webview2，然后启动修复模式看看？

https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by JJ-GeniusBoyius** [comment]
好的

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复
https://github.com/Bin-Huang/chatbox/releases
