### ISSUE TITLE
功能请求：能否加入微软Azure，实现多角色语音聊天

### ISSUE THREAD

**Issue by w004545** [Bin-Huang/chatbox#716]
大佬，您好！能否加入微软Azure，实现多角色语音聊天，这能让我们更好地与AI交流，也能帮助孩子学好外语。最后，感谢您无私分享，祝福您！

**Comment by Magic-ming-ss** [comment]
蹲一个。我觉得能和bot实时对话要是能集成在这个软件中将暴杀市场上一切AI工具。

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1239, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1239。这条 issue 先关闭了～～
