### ISSUE TITLE
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

### ISSUE THREAD

**Issue by itgamer** [Bin-Huang/chatbox#717]
这段报错是什么意思？一直用3.5，更换了API还是不行，请大神帮忙解答{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by myworksfun** [comment]
**I'm having the same problem, it's when the free use of the API key expires and requires a subscription to use it, so I've given up using chatGPT. 😄**

**Comment by zmpx** [comment]
今天出现同样的报错，我去chatgpt官网网页版可以正常使用，怎么回事？

**Comment by Model-Zachary** [comment]
我也是这个问题 去网页版 也是 
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by Snow-S0** [comment]
同样也是这个问题

**Comment by lead2000** [comment]
me too

**Comment by Field95** [comment]
me too. the same info jumped in other apps using api

**Comment by Qinsmoon** [comment]
> 今天出现同样的报错，我去chatgpt官网网页版可以正常使用，怎么回事？

网页暂时还能顶一阵

**Comment by zhoujkop** [comment]
一样的问题

**Comment by zmpx** [comment]
> ![image](https://user-images.githubusercontent.com/104411911/243706877-e24b1fe1-19e4-4a0b-95d9-bf1157f2fcf3.png) 到期了

这个是从哪里看到的？

**Comment by ATacoo** [comment]
![image](https://github.com/Bin-Huang/chatbox/assets/26988762/822dd293-123b-4a8d-9844-f48f9e42ed7b)
同样的问题 @Bin-Huang 大佬 这里好多人需要急救

**Comment by ATacoo** [comment]
![image](https://github.com/Bin-Huang/chatbox/assets/26988762/6229d657-bc3c-48a6-b8b8-1dd317b54963)
为什么我没有免费的5美元的额度？

**Comment by Bin-Huang** [comment]
其实如果你们搜索一下，就会发现这个问题我已经回答不只几十遍了😂😂。这个问题是 OpenAI 的账户问题，也就是你们 API 账户的余额到期了，需要绑定信用卡才能使用。和软件没有任何关系。

**Comment by Bin-Huang** [comment]
我考虑内置一个 AI 服务（只是考虑犹豫的阶段），这样大家就不用这么折腾地处理这些 OpenAI 账户和网络问题……

**Comment by huojianmao** [comment]
同样的情况😂😂

**Comment by zhoujkop** [comment]
就是你的key额度用完了 或者日期到了

**Comment by Bin-Huang** [comment]
其实原因已经在错误里了。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。

这个问题和软件没有任何关系。

如果你不想折腾 API 账户的各种问题的话，**强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题**。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0

**Comment by Bin-Huang** [comment]
The reason is actually within the error itself. It seems that your API account has insufficient balance or the balance has expired. To continue using the service, you will need to link an overseas credit card to your account.

This issue is unrelated to the software itself.

If you don't want to deal with various problems related to your API account, I highly recommend using the built-in Chatbox AI service. It is ready to use out of the box and eliminates the need to troubleshoot technical and account-related issues.

**Comment by fengxb** [comment]
为什么网页版可以用呢

**Comment by rliang-gpfw** [comment]
<img width="625" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/165869367/7387632f-09be-4c0f-b545-bb043346e2f7">

**Comment by Freiling87** [comment]
Same problem: I've used 0% of my OpenAI quota, but I still get this error message.

**Comment by jayahariv** [comment]
<img width="573" alt="Image" src="https://github.com/user-attachments/assets/f0cf193a-65ba-444c-b75f-1f70dec77c5a" />

I have updated the max message count in context to 20, issue seems gone away. Earlier it was 'No Limit'
