### ISSUE TITLE
[Feature] 允许App后台运行并添加一个快捷键唤出

### ISSUE THREAD

**Issue by thtTNT** [Bin-Huang/chatbox#718]
**问题描述**
在应用程序开的较多的情况下，需要切换出ChatBox需要Option+Tab的方式或是使用鼠标，十分的不方便。ChatBox作为常用的软件，希望可以采用更加方便的唤出方式。

**解决思路**
添加快捷键以及后台运行功能，可以通过一个快捷键快速地唤出ChatBox。

**Comment by aishuaikang** [comment]
+1

**Comment by Bin-Huang** [comment]
😊😊This feature has been implemented in the new version v0.6.5.
https://github.com/Bin-Huang/chatbox/releases
