### ISSUE TITLE
GPT 3.5的APIkey突然用不了，会显示API请求失败，重新更换apikey依然不能使用，但是openai官网上的gpt是可以正常使用的！[BUG]

### ISSUE THREAD

**Issue by simpleisall** [Bin-Huang/chatbox#719]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by iBiNCoder** [comment]
gpt4 apikey用不了

**Comment by iBiNCoder** [comment]
{"error":{"message":"The model: `gpt-4` does not exist","type":"invalid_request_error","param":null,"code":"model_not_found"}}

**Comment by w2816771** [comment]
你用 官方样例可以访问么？ 访问不了，很可能你的IP 被ban了，参考cloudflare 中转吧。

**Comment by ATacoo** [comment]
![image](https://github.com/Bin-Huang/chatbox/assets/26988762/e4b98de2-72ea-4fc4-9764-f1fe17ccd5ab)
我在官网 网页版是可以的 但是 chatbox不可以  有大佬看看吗

**Comment by ATacoo** [comment]
@Bin-Huang 大佬可以看看吗

**Comment by chwncy** [comment]
openai key免费试用已经过期了
https://platform.openai.com/account/usage

**Comment by ATacoo** [comment]
> openai key免费试用已经过期了 https://platform.openai.com/account/usage

openai key 还有免费试用期？ 哪里有注明有试用期限

**Comment by Bin-Huang** [comment]
这个问题是 OpenAI 的账户问题，也就是你们 API 账户的余额到期了，需要绑定信用卡才能使用。和软件没有任何关系。😂😂😂
