### ISSUE TITLE
左边的各种chat栏能不能设置自动隐藏,

### ISSUE THREAD

**Issue by ddwinhzy** [Bin-Huang/chatbox#72]
让需要的话可以鼠标划过去他就出现,不用的时候可以自动隐藏起来,这样可以让整个Untitled更简洁大方.

**Comment by Bin-Huang** [comment]
提醒一下该升级版本了，很早之前就可以自动给会话命名，不会再出现 Untitled。建议考虑下，不一定有时间做。
