### ISSUE TITLE
[Feature] 是否考虑增加Google Palm API 支持

### ISSUE THREAD

**Issue by w2816771** [Bin-Huang/chatbox#721]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
增加Google Palm API 支持

**解决思路**

Google Palm 现在可以在Makersuit 中使用了，是否可以提供一下支持。我申请到了 API key了。

**附加上下文**

相关文档：https://developers.generativeai.google/tutorials/text_quickstart

**Comment by w2816771** [comment]
我可以提供API key 但是只能用美国IP登录

**Comment by Bin-Huang** [comment]
新版本已经支持更好用的 google gemini pro 模型了
