### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Xokoukio** [Bin-Huang/chatbox#724]
**Bug 描述**
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
重換了API也沒用，但網頁版能用
**实际结果**
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
**截图**
![image](https://github.com/Bin-Huang/chatbox/assets/130911603/3aa2c2c9-abaf-49c3-949b-ea030e5b15e0)

**桌面端（请填写以下信息）：**
- 操作系统：win11
- 应用程序版本：0.4.5

**Comment by Bin-Huang** [comment]
其实原因已经在错误里了。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。

这个问题和软件没有任何关系。

如果你不想折腾 API 账户的各种问题的话，**强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题**。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0
