### ISSUE TITLE
帮忙看看为什么无法使用？

### ISSUE THREAD

**Issue by joefox1234** [Bin-Huang/chatbox#730]
输入任何信息都会反馈如下内容：
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
请问如何解决？
我的账号在openAI官网上是没有问题的。

**Comment by QzCrane** [comment]
the same

**Comment by zhoujkop** [comment]
额度用完或者免费体用到期 就这样

**Comment by Vicmata** [comment]
一样的问题

**Comment by BanKnight** [comment]
就是额度用完了，网页使用不消耗api的额度的，api额度是单独的

**Comment by Bin-Huang** [comment]
其实原因已经在错误里了。因为你的 API 账户没有余额，或者余额过期了，你需要给账户绑定海外信用卡才能继续使用。

这个问题和软件没有任何关系。

如果你不想折腾 API 账户的各种问题的话，**强烈推荐 Chatbox v0.5.0 新增的内置 AI 服务，开箱即用，不需要再折腾各种网络和账户问题**。 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.0
