### ISSUE TITLE
内存占用过高

### ISSUE THREAD

**Issue by 879611427** [Bin-Huang/chatbox#732]
当我提问一个问题的时候，内存占用就会升高，这个是正常的现象吗。我的理解计算是在服务器，怎么会升高呢
![image](https://github.com/Bin-Huang/chatbox/assets/37837452/cb9089f7-cb3c-4c30-9298-dd85a50f1828)

**Comment by Bin-Huang** [comment]
新版本还有这个问题

**Comment by 879611427** [comment]
> 新版本还有这个问题

0.5.1还是有这个问题
![image](https://github.com/Bin-Huang/chatbox/assets/37837452/982f7209-e25f-4543-bbe8-04c0b598ef08)

**Comment by Bin-Huang** [comment]
等下，其实内存没有升高呀？你看其中 chatbox 才占了 85MB 的内存……

**Comment by 879611427** [comment]
说错了，cpu cpu，调用的时候edge也会一起

**Comment by myworksfun** [comment]
Memory usage in normal 😄
![memory](https://github.com/Bin-Huang/chatbox/assets/45185967/5278fb2f-ec2c-4334-9032-e5c94933d0df)
