### ISSUE TITLE
[BUG] 严重！！ 输入1个字符，也显示内容超出，计算逻辑严重bug，APP无法使用

### ISSUE THREAD

**Issue by haikerapples** [Bin-Huang/chatbox#734]
![image](https://github.com/Bin-Huang/chatbox/assets/27751726/e2df6966-56f4-435a-8d49-cbc53dcc63db)

**Comment by haikerapples** [comment]
救救孩子，APP无法使用，卸载重装了2次了，然后一会又G了，这里面的计算逻辑有严重bug

**Comment by Bin-Huang** [comment]
求求你看清楚错误信息。进入设置页面，点击重置按钮、重置 Model&Tokens的设置，就可以了，然后记得及时更新。

这个问题是因为你改错了模型配置，我在软件里写了很长的提示告诉你说这个设置不能随便改
