### ISSUE TITLE
希望能够支持 Azure Key 的团队共享

### ISSUE THREAD

**Issue by seanshb** [Bin-Huang/chatbox#735]
**Problem Description**
因为支付问题,公司内可以申请Azure的Key 但是Azure Key的团队分享不能直接启用

**Proposed Solution**
1、 允许自定义API 地址,  自己通过其他服务转化, 然后指向自定义服务器
2、 直接支持 Azure OpenAI API类型格式,

**Comment by Bin-Huang** [comment]
目前这个功能已经有非常成熟的开源项目，因此没有内置到 chatbox 的开发计划
