### ISSUE TITLE
[BUG]生成答案的时候卡住

### ISSUE THREAD

**Issue by lusbus** [Bin-Huang/chatbox#738]
**Bug 描述**
在AI生成答案的时候，页面卡顿。例如最小化点击无效，延迟到生成完答案才生效。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 选择一个问题，在答案生成中（时）操作
2. 点击 "页面的最小化，最大化，设置等按钮"
3. 无反应，等候生成完答案有反应。
4. 发现了这个 bug。

**Comment by lusbus** [comment]
应该不是我的电脑卡住，我切换其他应用界面没有明显卡顿。

**Comment by Bin-Huang** [comment]
请问是软件什么版本呢？

**Comment by lusbus** [comment]
0.5的版本

**Comment by Bin-Huang** [comment]
什么系统和版本呢？
