### ISSUE TITLE
[BUG]azure api不工作

### ISSUE THREAD

**Issue by helloo2020** [Bin-Huang/chatbox#739]
提示部署不存在，实际上已经部署1个多小时了
提示：API 请求失败：  
```
{"error":{"code":"DeploymentNotFound","message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}
```

**Comment by Bin-Huang** [comment]
这个问题是你输入的模型部署名称，和你的 Azure 部署名不相同导致的。

**Comment by Bin-Huang** [comment]
<img width="790" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/3f093017-49ec-4387-8565-5b069633b095">

**Comment by helloo2020** [comment]
> <img alt="image" width="790" src="https://user-images.githubusercontent.com/20723142/245130852-3f093017-49ec-4387-8565-5b069633b095.png">

非常感谢，问题解决！
