### ISSUE TITLE
1.14版本解释

### ISSUE THREAD

**Issue by Yun-Tianming** [Bin-Huang/chatbox#74]
该版本设置选项里有gpt4和无限token，但用的时候实际是不行的，请问有啥解释不。。。

**Comment by Bin-Huang** [comment]
请问你的 API KEY 确定可以访问 GPT4 吗？

**Comment by Yun-Tianming** [comment]
> 请问你的 API KEY 确定可以访问 GPT4 吗？

不清楚欸，访问gpt4必须要开通plus是吗？

**Comment by Bin-Huang** [comment]
这是因为你的账号不支持导致的。

**Comment by Yun-Tianming** [comment]
哦哦应该是这样，不知道是不是我错觉，感觉新版本不如老版本稳定，api请求失败概率非常高。。。
