### ISSUE TITLE
[Other]购买了CHATBOX AI服务后并没有实现高速响应，回复慢

### ISSUE THREAD

**Issue by Magic-ming-ss** [Bin-Huang/chatbox#742]
已是最新版本
时间6月12日晚9点左右。
![image](https://github.com/Bin-Huang/chatbox/assets/80674900/aa25ebe2-d34b-4da1-b984-1895c3b946a3)
转圈显示时间长（我的问题很简短）

**Comment by Bin-Huang** [comment]
可能和网络也有关系的。还有就是回答是以句子为单位显示的，不是一个字一个字，但整体回答的速度是一样很快的。

辛苦联系下 support@benn.app

**Comment by Magic-ming-ss** [comment]
额，我只能说刚才确实生成很慢，要不然我也不会反馈。
可能是我的网络问题或者流量高峰期？（我的网络问题的可能性是比较低的）
现在的响应速度是正常的。
不，还是很慢，是非常慢，至少30s以上
![image](https://github.com/Bin-Huang/chatbox/assets/80674900/e8cd52fe-3eba-4b29-91d1-a45d47a2b172)
![image](https://github.com/Bin-Huang/chatbox/assets/80674900/52971d59-6e5b-4f68-92f9-672469db13fc)

**Comment by Bin-Huang** [comment]
30秒回答的内容大概多少字？
