### ISSUE TITLE
[Feature] New gpt-3.5-turbo-16k model

### ISSUE THREAD

**Issue by bitnom** [Bin-Huang/chatbox#750]
OpenAI has released a new model `gpt-3.5-turbo-16k` which has an increased context window.

**Comment by wunengbiao** [comment]
链接: https://pan.baidu.com/s/1MJRLyEYqCos5T-TJMQyk2w?pwd=widf 提取码: widf

**Comment by Xu-Jam** [comment]
> 链接: https://pan.baidu.com/s/1MJRLyEYqCos5T-TJMQyk2w?pwd=widf 提取码: widf

win的有木有啊，大佬

**Comment by wunengbiao** [comment]
> > 链接: https://pan.baidu.com/s/1MJRLyEYqCos5T-TJMQyk2w?pwd=widf 提取码: widf
> 
> win的有木有啊，大佬

没有 Windows 系统

**Comment by Bin-Huang** [comment]
上面的不是官方版本，小心木马病毒。
16k网页版本当天就支持了 https://web.chatboxai.app/
桌面客户端周末发版本
