### ISSUE TITLE
[BUG] macOS下点击左侧标签切换会话的时候会产生拖拽效果，鼠标已经松开了但是会话黏在鼠标上面

### ISSUE THREAD

**Issue by LNoving** [Bin-Huang/chatbox#753]
**Bug 描述**
清晰简洁地描述这个 bug 是什么。
不清楚具体的触发机制，但是触发的概率很大。就是在点击标签进行切换的时候，点完了不是进行切换，而是黏在鼠标上，好像我是在拖拽一样。
其他应用中均不存在此问题

**截图**
![image](https://github.com/Bin-Huang/chatbox/assets/32219194/4955b974-dce7-43ef-9a06-07fcc92a7531)

**桌面端（请填写以下信息）：**
- 操作系统：macOS M1 版本
- 应用程序版本：最近的几个版本均有此问题

补充：
1.不是100%触发，大概30%概率触发。
2. 黏住之后需要再点击一次才能取消黏住
因为我是轻触代替触击，所以我切换tab的流程是，轻轻点一下目标tab进行切换，然后把鼠标挪走，就是在挪走的过程中会黏住

另外，我系统设置中使用三指拖移和单指轻点代替点按的设置，不知道是否有影响。

**Comment by LNoving** [comment]
有木有人

**Comment by lszero** [comment]
+1

**Comment by Bin-Huang** [comment]
在之前的版本中已经修复了

**Comment by LNoving** [comment]
> 在之前的版本中已经修复了

谢谢开发者，辛苦了。
