### ISSUE TITLE
[Feature]Openai今天推出了新的api升级 希望同步

### ISSUE THREAD

**Issue by Mit0chrondr1a** [Bin-Huang/chatbox#754]
![image](https://github.com/Bin-Huang/chatbox/assets/12169214/b7335b5c-e2a8-4461-b19e-c1a5d2849d1c)
![image](https://github.com/Bin-Huang/chatbox/assets/12169214/8b01737e-32e4-4d79-bf10-6e6061dea53b)

**Comment by hadesgeek** [comment]
+1

**Comment by wunengbiao** [comment]
链接: https://pan.baidu.com/s/1MJRLyEYqCos5T-TJMQyk2w?pwd=widf 提取码: widf

**Comment by MinatoAquin33** [comment]
+1

**Comment by Bin-Huang** [comment]
大家不要点击上面被折叠的有百度云链接的评论，那个不是官方更新，小心其中包含木马病毒。

[Chatbox 网页版本](https://chatboxai.app/)已经支持最新的模型了，设置页中“AI提供方”选择 OpenAI，在模型列表中就能看到。
桌面客户端版本等待下一次版本更新。
