### ISSUE TITLE
[Feature] 优化长文本对话框的UI性能 | Optimizing the UI performance of long text dialog boxes

### ISSUE THREAD

**Issue by JamesFlare1212** [Bin-Huang/chatbox#756]
随着我测试更多Large Token Window的模型，比如Claude v1.3 100k。当文本长度达到30k Token以上后可以感到明显的卡顿，90k Token的时候基本上难以使用。我认为这是一个效率和优化的问题，以前可能不明显，但是现在越来越明显了。

----

As I test more models with Large Token Window, such as Claude v1.3 100k, I can feel obvious lag when the text length exceeds 30k tokens. It's basically unusable at 90k tokens. I think this is an efficiency and optimization issue that may not have been noticeable before but is becoming increasingly apparent now.

**Comment by Bin-Huang** [comment]
请问是什么版本呢？

**Comment by bitnom** [comment]
> 随着我测试更多Large Token Window的模型，比如Claude v1.3 100k。当文本长度达到30k Token以上后可以感到明显的卡顿，90k Token的时候基本上难以使用。我认为这是一个效率和优化的问题，以前可能不明显，但是现在越来越明显了。
> 
> As I test more models with Large Token Window, such as Claude v1.3 100k, I can feel obvious lag when the text length exceeds 30k tokens. It's basically unusable at 90k tokens. I think this is an efficiency and optimization issue that may not have been noticeable before but is becoming increasingly apparent now.

I experience it too for long conversations. It would be better to lazy-load/unload a shifting window of messages. Since the data is local it should be a pretty seamless transition/load.

**Comment by Bin-Huang** [comment]
This issue has been resolved in the new version v0.6.3. If the problem still persists, you can reopen the issue at any time😊.
https://github.com/Bin-Huang/chatbox/releases


这个问题在新版本 v0.6.3 已经解决，如果问题还存在你可以随时重新开启这个 issues 😊。
https://github.com/Bin-Huang/chatbox/releases
