### ISSUE TITLE
[Feature]  新建聊天 & 删除聊天的快捷键 ，高频顺滑使用此工具的关键

### ISSUE THREAD

**Issue by IntelHeartPrime** [Bin-Huang/chatbox#757]
我认为真的真的很重要
这是我可以高频使用此工具的关键

**Comment by chenhaoaixuexi** [comment]
还有搜索对话的能力,  在对话多的时候可以查找

**Comment by yeahJwczjzlTest** [comment]
一键删除 强烈需求

**Comment by yeahJwczjzlTest** [comment]
一键删除 强烈需求

**Comment by Bin-Huang** [comment]
😊😊This feature has been implemented in the new version v0.6.5.
https://github.com/Bin-Huang/chatbox/releases

😊😊这个功能在新版本 v0.6.5 已经实现
https://github.com/Bin-Huang/chatbox/releases
