### ISSUE TITLE
输出到一半的内容会被打断

### ISSUE THREAD

**Issue by wuyudi** [Bin-Huang/chatbox#76]
如下

```
API Request Failed:

Error parsing item: {"id":"chatcmpl-xxxxxxxxxxxxxxx","object":"chat.completion.chunk","created":xxxxxxxx,"model":"gpt-3.5-.
Error Details: SyntaxError: JSON Parse error: Unterminated string
```

然后我就看着一大段 ai 的话消失了，能即使 Error 也 keep 现场吗。

**Comment by happylemon233** [comment]
没有拖动窗口或动滚轮，也有类似的问题：
API Request Failed:

Error parsing item: {"id":"c.
Error Details: SyntaxError: Unterminated string in JSON at position 8

**Comment by happylemon233** [comment]
API Request Failed:

Error parsing item: {"id":"chatcmpl-xxxxxxxxxxxxxxxxxxxxxxxxxx","object":"chat.completion.chunk","created":xxxxxxxxxxxxxxxx,"model":"gpt-3.5-turbo-0301","choices":[{"delta":{"content":"我们"},"index":.
Error Details: SyntaxError: Unexpected end of JSON input

**Comment by wuyudi** [comment]
翻了下，是这里

https://github.com/Bin-Huang/chatbox/blob/738da1dceb604edd54919c263e510605d5b7e4b3/src/client.ts#L75-L90

**Comment by Bin-Huang** [comment]
什么版本，最新版本 v0.2.7 还会这样吗？我已经修复过了

**Comment by wuyudi** [comment]
> 什么版本，最新版本 v0.2.7 还会这样吗？

是 0.2.7

**Comment by Bin-Huang** [comment]
可以介绍下你的网络环境吗？比如代理服务器的情况

**Comment by xzy111222333** [comment]
我也遇到了相同的情况啊
