### ISSUE TITLE
[BUG] Can not display image correctly

### ISSUE THREAD

**Issue by cxlight** [Bin-Huang/chatbox#764]
<img width="808" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/3929361/78264350-5fb1-4607-8f86-bd5174a2f75c">

**Comment by Bin-Huang** [comment]
一般这种情况是AI返回的图片链接不对，这与软件没有关系

**Comment by cxlight** [comment]
但是我在Poe.com问ChatGPT类似的问题，图是有的。二用chatbox 没有一次正常显示过。poe难道不也是调用OpenAI的API的吗？

**Comment by Bin-Huang** [comment]
所有模型都有概率产生错误的内容，你可以点击编辑按钮，可以看到AI返回的图片链接

**Comment by cxlight** [comment]
有点不太明白，如果在chatbox中出现的图片出错概率是100%，而在Poe.com中图片出错的概率是0%，这个仍然和chatbox无关么？

**Comment by cxlight** [comment]
图片链接：
https://user-images.githubusercontent.com/78270710/127492036-9b8bb3c5-1d0d-4be1-a6f8-6c4f3102d9bc.png

浏览器查看时是报个错：

AccessDeniedAccess DeniedM4WQNSN1YKPWN23K77cWi80ejEkSe0MelV32CcOAoyRPaNuiyEO1J8M4I1v1DoBdt23jGXpZyWgZgOMQ76PotYN3GvM=
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>M4WQNSN1YKPWN23K</RequestId>
<HostId>77cWi80ejEkSe0MelV32CcOAoyRPaNuiyEO1J8M4I1v1DoBdt23jGXpZyWgZgOMQ76PotYN3GvM=</HostId>
...
</Error>

**Comment by Bin-Huang** [comment]
我感觉你没有搞清楚问题…… 上面两个答案一个是代码块，一个是 Markdown 图片，不是同一种回答方式。你遇到的问题是 GPT 回答了一个链接不存在的图片，导致客户端找不到图片加载。说到底，真正提供回答的是 GPT 模型，不是客户端软件。模型本身有时候会生成错误的回答，这个和 prompt 和参数有关。

**Comment by Bin-Huang** [comment]
<img width="695" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/4164d690-e066-4027-a8e8-6672c54a0e58">
<img width="702" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/3538680f-cdf2-4456-b10d-5d4f9c590c5b">

**Comment by Bin-Huang** [comment]
问法很重要
