### ISSUE TITLE
[BUG] Missing release 0.5.2_amd64.deb 未发布

### ISSUE THREAD

**Issue by Technetium1** [Bin-Huang/chatbox#765]
**Bug Description**
https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.1 has a `.deb` release. https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.2 does not.

**Steps to Reproduce**
View https://github.com/Bin-Huang/chatbox/releases

**Expected Results**
`chatbox_0.5.2_amd64.deb` should exist at https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.2

**Actual Results**
There is not a `.deb` available

**Screenshots**
![image](https://github.com/Bin-Huang/chatbox/assets/9877150/aeb24203-75d4-4f8d-818f-98742d3a90b5)

**Desktop (please complete the following information):**
- Operating System: Linux
- Application Version: `0.5.2`

**Additional Context**
This is blocking [chatbox-bin on the AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chatbox-bin) from being able to be updated, which then blocks me from adding it to [Chaotic-AUR](https://aur.chaotic.cx/), where it was recently requested: https://github.com/chaotic-aur/packages/issues/2575

-------------------------------------

**Bug 描述**
https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.1 有释放 `.deb`. https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.2 没有，但需要 `.deb`

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
👀 https://github.com/Bin-Huang/chatbox/releases

**期望结果**
我们必须有适用于 Linux 的文件

**实际结果**
文件不存在

**截图**
请参阅上面的英文

**桌面端（请填写以下信息）：**
- 操作系统：Linux
- 应用程序版本：`0.5.2`

**其他上下文**
- 我尽力用谷歌翻译。 以上是更好的英文描述。 谢谢你的努力。 我希望将来错误会记录在 GitHub Actions 中。
- 这会阻止 AUR 上的 [chatbox-bin](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=chatbox-bin) 更新
- 因为它没有发布，所以它阻止我将它添加到 [Chaotic-AUR](https://aur.chaotic.cx/) 最近在哪里被要求添加: https://github.com/chaotic-aur/packages/issues/2575

**Comment by Bin-Huang** [comment]
A huge thanks for the heads-up! I only just noticed the issue myself. When I released v0.5.2, it was already pretty late, and I was super tired (thanks to v0.5.0). On top of that, Github Action kept throwing errors, so I had to manually publish the release, and that's probably where I slipped up. I've added the deb files now, and I really appreciate your work on AUR.

Oh, by the way, you don't actually need to use Chinese in the issues on purpose. I've always preferred communicating in English, as it helps to reach more people around the world and collaborate with a wider audience. I once suggested that everyone should use English in issues as much as possible, but there were just too many Chinese issues later on, so I ended up replying in Chinese directly. I hope this hasn't caused you too much confusion.😅😅😅😅

**Comment by Technetium1** [comment]
Thanks for the fast fix! I also tried to make sense of the Actions logs, but ultimately was a bit thrown off on how there were errors but still releases, suddenly it makes sense!

I honestly wasn't sure which language would be preferred, so I did my best to make both legible. Maybe there could be `English preferred` in the start of the Chinese section of the template?

**Comment by wuyudi** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/v0.6.2 also doesn't have deb released.

Is the deb version no longer provided? (Then I may update the AUR script.

**Comment by Technetium1** [comment]
@Bin-Huang it is definitely missing again, is the cause the same?

**Comment by Bin-Huang** [comment]
This issue has been resolved in the new version v0.6.3. If the problem still persists, you can reopen the issue at any time😊.
https://github.com/Bin-Huang/chatbox/releases
