### ISSUE TITLE
[Other] 上下文长度问题

### ISSUE THREAD

**Issue by zhang-jiayuan** [Bin-Huang/chatbox#766]
现在的上下文长度是所有聊天室的长度吗？ 为啥我把当前聊天室清空后，输入几百个字符，仍然会提示上下文长度超过了阈值呢？有没有清空上下文长度的接口

**Comment by Bin-Huang** [comment]
上下文长度只会计算当前会话。

![image](https://github.com/Bin-Huang/chatbox/assets/20723142/0164f7b0-a1e4-403a-b866-902be55b5ddd)

平均每个汉字会消耗 4 个tokens，所以如果“几百个字符”是九百多，那么加上你设定的系统 prompt，确实很容易超过限制。
