### ISSUE TITLE
[Other]想了解一下开源情况，部分开源还是全开源

### ISSUE THREAD

**Issue by hadesgeek** [Bin-Huang/chatbox#767]
首先感谢作者的工具，最近正在学习 tauri 开发，正好看到了这个项目，做的非常好。
我也尝试再本地 搭建了一下。
但是发现 开源的版本是 0.0.1 不是最新版
![1686900367986](https://github.com/Bin-Huang/chatbox/assets/129089956/34f433f4-95ef-4cd5-9446-66214a51afb0)

我不确定是我本地搭建的问题，还是开源仅是部分开源。
我希望通过 chatbox 项目学习一下 rust vue 和tauri。
不知道 是不是能够复现一个完全一样的东西。

**Comment by Bin-Huang** [comment]
一言难尽……有很多培训机构直接销售我的源码，有很多黑产到处发布带有漏洞的版本，所以我暂时隐藏后续的更新内容了

**Comment by hadesgeek** [comment]
非常感谢作者的回复。我已了解。我先看看现有开源代码学习，当我遇到问题 希望能够得到您的回复。如果有什么群可以交流学习就更好了。chatbox 确实是我目前见到过 桌面版最好用的工具，作者继续加油吧。做自己认为喜欢的事。

**Comment by Bin-Huang** [comment]
感谢理解，这真的也是我很纠结才做出的决定。那段时间我差点就不想维护了。
