### ISSUE TITLE
[Feature]openai于6月15日发布的新模型，计划什么时候支持呢？

### ISSUE THREAD

**Issue by ablackey** [Bin-Huang/chatbox#768]
openai于6月15日发布的新模型，计划什么时候支持呢？

**Comment by Bin-Huang** [comment]
当天就支持了……网页版本当天已经更新了 https://web.chatboxai.app/
桌面客户端版本应该刚刚发布过版本更新，所以挪到周末发布了

**Comment by wangbiye** [comment]
Yeah, 熬夜等发布[doge]

**Comment by wangbiye** [comment]
@Bin-Huang Yeah, 熬夜等发布[doge]
