### ISSUE TITLE
1.14及之后的安装都需要管理员权限

### ISSUE THREAD

**Issue by NOirBRight** [Bin-Huang/chatbox#77]
我在公司电脑上使用这款软件，1.13及之前的所有安装包都有一个好处，就是不需要管理员权限就能安装（EXE格式），从1.14之后安装包变成了MSI格式，这个格式在安装时，必须要求管理员权限。
公司的电脑对软件安装的限制比较多，每次我都需要找AI才能完成更新，导致非常麻烦，是否可以回复到之前的安装包形式？

**Comment by Bin-Huang** [comment]
This issue has been resolved in the new version v0.6.3. If the problem still persists, you can reopen the issue at any time😊.
https://github.com/Bin-Huang/chatbox/releases


这个问题在新版本 v0.6.3 已经解决，如果问题还存在你可以随时重新开启这个 issues 😊。
https://github.com/Bin-Huang/chatbox/releases
