### ISSUE TITLE
[BUG] 网页版接口重复调用

### ISSUE THREAD

**Issue by SailFlorve** [Bin-Huang/chatbox#773]
自定义Key和BaseURL，网页版新建对话并发送后，可以观察到有1-2个聊天本身的接口调用，4个给对话起标题的接口调用！这导致了接口的重复调用和token的重复消耗。

**Comment by SailFlorve** [comment]
另外，生成标题建议固定为3.5turbo。

**Comment by Bin-Huang** [comment]
应该有一半是 OPTIONS 请求吧，这个不消耗 tokens 的

**Comment by Bin-Huang** [comment]
每个会话只会自动生成一次标题，我认为不需要过于纠结这个问题？
