### ISSUE TITLE
[Feature] 希望能更新一下支持的模型

### ISSUE THREAD

**Issue by chllei** [Bin-Huang/chatbox#774]
大佬，希望能够支持一下0613的新模型，非常感谢！

**Comment by wangbiye** [comment]
先请个咖啡再说话[手动狗头]

**Comment by CCCoralie** [comment]
link #763

**Comment by Bin-Huang** [comment]
新版本支持了，试试看 https://github.com/Bin-Huang/chatbox/releases 😄

**Comment by chllei** [comment]
> 新版本支持了，试试看 https://github.com/Bin-Huang/chatbox/releases 😄

太感谢了！！

**Comment by terobox** [comment]
源码有更新0613吗
