### ISSUE TITLE
[Other] 可否添加一个网页登录接口，而不用key（免费的key已经过期了）

### ISSUE THREAD

**Issue by duofengzhiling** [Bin-Huang/chatbox#777]
如题，昨天用chatbox时，发现遇到了这个问题，{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}
这才发现key过期了，恰好之前看到有人抓取网页而非使用key，也能实现对答。（gpt4之前就没有key）。
这个是项目地址：https://github.com/zixiiu/Digital_Life_Server
这个是演示视频:   https://www.bilibili.com/video/BV1bm4y117ba/

**Comment by Bin-Huang** [comment]
没有这个计划，这种方式已经徘徊在服务破解的边缘了，不会考虑这么做。
