### ISSUE TITLE
[Other]MacOS 切换应用唤出 chatbox 无法自动聚焦到输入框

### ISSUE THREAD

**Issue by QingYunA** [Bin-Huang/chatbox#779]
OS: macOS 12.6.6

使用 alfred 5 切换到 chatbox 界面无法自动聚焦到输入框,需要使用鼠标移动到输入框才可以输入.
由于本人偏好全键盘操作,因此不希望浪费时间在挪动鼠标上,希望作者可以加上自动聚焦!感谢!!

**Comment by Bin-Huang** [comment]
了解，有计划要做各种快捷键。现阶段你可以 CMD+I 的方式聚焦输入框。

**Comment by Bin-Huang** [comment]
😊😊这个功能在新版本 v0.6.5 已经实现
https://github.com/Bin-Huang/chatbox/releases
