### ISSUE TITLE
Load models from json file

### ISSUE THREAD

**Issue by bitnom** [Bin-Huang/chatbox#780]
I was looking at the PR https://github.com/Bin-Huang/chatbox/pull/763

hoping for an update to support 16k context length which lead me to realize it is hard-coded. It would be better to load from JSON of a github repo that could be updated independent of the chatbox repo.

**Comment by Bin-Huang** [comment]
The update you've been waiting for is finally here! Give it a try at https://github.com/Bin-Huang/chatbox/releases 😄
