### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yxmnjxzx** [Bin-Huang/chatbox#782]
-------------------------------------

**Bug 描述**
设置OPENAI api无法选择

**重现步骤**
设置中点击选择OPENAI API无法选择，其他如Azure都可以选择

**期望结果**
修复。

**实际结果**
修复。

**截图**
![image](https://github.com/Bin-Huang/chatbox/assets/95153568/d82ff6be-a871-43a8-9e41-7cb0f2ef3cd8)

**桌面端（请填写以下信息）：**
- 操作系统：win 10
- 应用程序版本：0.5.5，最新版

**Comment by Bin-Huang** [comment]
可以简单录一个像吗？其他用户有遇到吗？

**Comment by yxmnjxzx** [comment]
https://github.com/Bin-Huang/chatbox/assets/95153568/4c663c28-bbac-42ab-a442-5a79ccc92a3c

**Comment by Bin-Huang** [comment]
@yxmnjxzx  我做了紧急修复，大家试试最新的 0.5.6 版本，看看问题有没有解决。地址： 
 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.6

**Comment by Bin-Huang** [comment]
如果问题解决了，请务必告诉我

**Comment by yxmnjxzx** [comment]
已解决
