### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Miing3016** [Bin-Huang/chatbox#783]
**Bug 描述**
点击设置后一片空白，啥也出不来。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端：**
- 操作系统：win10
- 应用程序版本：0.5.5

**Comment by shiyun09** [comment]
Bug 描述
点击设置后一片空白，啥也出不来。

截图
![image](https://github.com/Bin-Huang/chatbox/assets/18658687/447a67c2-6b80-49cf-bdf4-cbca3b40bdbe)


桌面端：

操作系统：win10
应用程序版本：0.5.5

**Comment by LSMihiing** [comment]
同样出现这个问题
<img width="795" alt="1" src="https://github.com/Bin-Huang/chatbox/assets/105102166/da451366-d8d2-4286-b96f-b4d7a7db9f0f">

**Comment by Bin-Huang** [comment]
@Miing3016 @shiyun09 @LSMihiing 我做了紧急修复，大家试试最新的 0.5.6 版本，看看问题有没有解决。地址： 
 https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.6

**Comment by Bin-Huang** [comment]
如果问题解决了，请务必告诉我

**Comment by exAClior** [comment]
> 如果问题解决了，请务必告诉我

macos 上已经可以使用了，不会出现白屏。

**Comment by Miing3016** [comment]
> @Miing3016 @shiyun09 @LSMihiing 我做了紧急修复，大家试试最新的 0.5.6 版本，看看问题有没有解决。地址： https://github.com/Bin-Huang/chatbox/releases/tag/v0.5.6

已解决！
