### ISSUE TITLE
[Feature] 每个聊天窗口单独设置api和key的功能

### ISSUE THREAD

**Issue by vindia9** [Bin-Huang/chatbox#787]
**问题描述**

作者你好，非常感谢你，chatbox真是很厉害的开源项目！
请问作者有考虑过增加每个对话窗口能单独配置api key的需求吗？
我同时有gpt4-32k、gpt4-8k、gpt3.5、glm……
想用其他的api时，需要来回切换…

**解决思路**

在每个对话窗口的更多设置中，增加一个 单独配置api 的选项卡，可以自定义当前对话的api

**Comment by Bin-Huang** [comment]
我也遇到和你类似的问题，有类似的想法，但暂时还不知道如何设计。

**Comment by AIgsc** [comment]
> 我也遇到和你类似的问题，有类似的想法，但暂时还不知道如何设计。

可以加到提问框下面，随时可以单独修改设置当前的对话模型，对话使用的KEY。默认不填写，需要用的人，可以自己填写，优先级大于设置页面的KEY。执行发送的时候一起发送给后端，然后后端根据新的配置信息，发送给openai。

**Comment by AIgsc** [comment]
就这种感觉
![image](https://github.com/Bin-Huang/chatbox/assets/133596862/f76a4712-1a95-4494-baea-5bc7bf02bf8f)

**Comment by AIgsc** [comment]
确实需要这样的功能，如果简单的问题 也用GPT4问，就太贵了

**Comment by vindia9** [comment]
可以在此处加入对话设置

<img width="211" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/9072630/8f4f8866-3c19-4014-8955-d605abf53921">

在这个设置页面中，仍然可以添加同样的设置，但优先级高于global config

<img width="553" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/9072630/7d66d6af-8986-4d79-8cea-3be7630b13e3">

**Comment by iDvel** [comment]
应该大部分人都是 gpt-3.5-turbo 和 gpt-4 混用的，很希望有这个功能，可以单独设置一个窗口的模型类型与 Temperature。

**Comment by GuLu-ch** [comment]
非常希望出一个这个功能，GPT4和3.5混用，每次都需要到设置中切换模型确实有些麻烦

**Comment by Bin-Huang** [comment]
这个功能在新版本 v0.6.3 已经实现
https://github.com/Bin-Huang/chatbox/releases

**Comment by vindia9** [comment]
> 这个功能在新版本 v0.6.3 已经实现 https://github.com/Bin-Huang/chatbox/releases

非常感谢！！
