### ISSUE TITLE
大佬能否加一个功能：记住上次调整的窗口大小,记住上次关闭窗口时的位置

### ISSUE THREAD

**Issue by wuvbyy29** [Bin-Huang/chatbox#789]
能否加一个记住上次调整的窗口大小,记住上次关闭窗口时的位置的功能，请次打开程序都要调整窗口大小和位置。有点不人性化

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/v1.0.4
