### ISSUE TITLE
[Feature] 固定使用gpt-3.5-turbo生成对话的标题

### ISSUE THREAD

**Issue by SailFlorve** [Bin-Huang/chatbox#794]
GPT4模型下，生成标题同样用的是GPT4，但是GPT4的token太贵了，如果第一条消息或者回复很长将会造成双倍的token浪费，希望可以固定使用gpt-3.5-turbo生成对话的标题，用GPT4完全没必要。

**Comment by MurphyLo** [comment]
尤其是使用 32k 时自动生成标题，查额度真的会血压飙升😭。或者增加一个“自动生成标题”开关也挺好。建议供参考。辛苦开发者了。

**Comment by ychxp** [comment]
非常同意，正因为这个原因，我只能默默地换别的客户端了。看看你这个issue的时间，半年了。估计短时间也加不了这个功能

**Comment by Bin-Huang** [comment]
这个问题大可放心。新版本只会用消息的前100个字符来生成标题

**Comment by MurphyLo** [comment]
o1 发布后是否会重新考虑一下 允许用户通过设置项关闭自动生成标题？这个模型的补全太多了，而且不确定性很强，输出数个字的标题的情况下也可能产生数k tokens的补全。
