### ISSUE TITLE
[BUG] macOs Sonoma 14.0 对话框不断滚动

### ISSUE THREAD

**Issue by memoryFade** [Bin-Huang/chatbox#795]
**Bug Description**
在输入需要的内容并点击发送后，整个对话框，会不断的从头到尾的不断滚动，

**Steps to Reproduce**
1. 使用macOs 14 系统
2. 新建一个对话
3. 输入所需的内容
4. 点击发送

**Expected Results**
流式对话一点点新增内容

**Actual Results**
流式对话每次新增内容，整个对话都会从头到尾滚动

**Screenshots**

**Desktop (please complete the following information):**
- Operating System: macOs Sonoma 14.0
- Application Version: 0.5.6
**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

**Comment by Bin-Huang** [comment]
v0.6.1 还会有这个问题吗？

**Comment by htmambo** [comment]
> v0.6.1 还会有这个问题吗？

0.6.1 已经没有这个问题了。我当时的解决办法是在等回答时先把滚动条向上移动一点，这样它就不会一直在底部刷新了。

**Comment by memoryFade** [comment]
> 

我也是这么解决这个问题的
