### ISSUE TITLE
[BUG]使用最新0.5.6版本调用ChatGLM2-6B的API出错

### ISSUE THREAD

**Issue by xazaj** [Bin-Huang/chatbox#797]
**Bug 描述**
使用最新0.5.6版本调用ChatGLM2-6B的API出错，
本地启动的是chatGLM2-6b，客户端配置这里只有chatGLM-6B，这两个官方API不兼容吗？

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1.本机跑ChatGLM**2**-6B模型，使用API模式启动服务
2.在ChatBox的配置自己的api,目前0.5.6版本只能选择ChatGLM-6B
3.在聊天窗口进行交互会出错。

**截图**
1.ChatGLM服务器错误提示
···
INFO:     127.0.0.1:40142 - "POST / HTTP/1.1" 200 OK
Input length of input_ids is 2141, but `max_length` is set to 2048. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
···
2.客户端报错
![image](https://github.com/Bin-Huang/chatbox/assets/835274/c91f6db0-716e-4869-900d-61e1569b1854)

**桌面端（请填写以下信息）：**
- 操作系统：Win10
- 应用程序版本：[0.56]

**其他上下文**

本地启动的是chatGLM2-6b，客户端配置这里只有chatGLM-6B

**Comment by xazaj** [comment]
另外补充一下，使用OpenAI 格式的流式 API 部署ChatGLM2-6B，在最新的0.5.6客户端以OpenAI的API访问也会出错。

参考：
https://github.com/THUDM/ChatGLM2-6B/tree/main
![image](https://github.com/Bin-Huang/chatbox/assets/835274/943a7d58-32aa-4413-ad76-06465211cd55)

**Comment by Bin-Huang** [comment]
即然部署的是 OpenAI API 格式，那么直接试试 OpenAI API？

**Comment by Bin-Huang** [comment]
设置页面 AI Provider 选择 OpenAI API
