### ISSUE TITLE
是否会有移动端 App

### ISSUE THREAD

**Issue by undefine4080** [Bin-Huang/chatbox#798]
请问作者大大有没有计划推出移动端 chatbox ？付费的都可以，Chatbox太好用了👍

**Comment by Miing3016** [comment]
同求移动端，另外可以账号登录就好了，就不用在不同端重复部署prompt了

**Comment by myworksfun** [comment]
**`This is a very important requirement.`**

**Comment by IntelHeartPrime** [comment]
Think so ,  若支持可买断| 订阅制，必然付费支持。 当然ipad端希望可以适配的好一点

**Comment by Hisoka-J** [comment]
同需要，愿意付费

**Comment by Miing3016** [comment]
> https://github.com/Tlntin/chatbox-android/releases/tag/v0.5.6
> 可以试试这个，基于tauri 2.0打包的，核心功能没做变动，只是升级了一下框架。已经生成了一个安卓apk。

求更新啊
