### ISSUE TITLE
[Other]希望界面更加紧凑、字体可以提供更小的选择

### ISSUE THREAD

**Issue by CooperZhuang** [Bin-Huang/chatbox#799]
v0.5.6，已经将字体设置为12px 了，但是整体的界面还是显得太“松”，想要更紧凑的界面，可以同屏显示更多的内容。

**Comment by myworksfun** [comment]
**I also have the same requirement. The UI layout seems too loosely organized visually .**😂

**Comment by Bin-Huang** [comment]
Work in progress~

**Comment by Bin-Huang** [comment]
v0.6.2 has been implemented, give it a try.
https://github.com/Bin-Huang/chatbox/releases
