### ISSUE TITLE
apiHost无默认值，正则验证出错，导致第一次打开白屏

### ISSUE THREAD

**Issue by gqfjob** [Bin-Huang/chatbox#8]
!settingsEdit.apiHost.match(/^(https?:\/\/)?api.openai.com(:\d+)?$/) ，第一次apiHost为空 , .match保错

**Comment by Bin-Huang** [comment]
哪个版本

**Comment by gqfjob** [comment]
刚刚更新的代码，测试删除Setting页面那段验证就可以了，填入Host后，再加上那段验证，就不会报错了
