### ISSUE TITLE
请问可以开发一下浏览器插件吗？

### ISSUE THREAD

**Issue by wuyuezhui** [Bin-Huang/chatbox#800]
今天我偶然间试用了一款浏览器插件，叫作Monica， 真的非常智能。但是非常非常贵，而且无法调用自己的API。
如果咱们chatbox可以内嵌到浏览器，并支持语音输入，那就我本人非常愿意付费使用。
希望您可以考虑考虑我这个请求

**Comment by wuyuezhui** [comment]
hello？

**Comment by xcwen6** [comment]
chathub

**Comment by wuyuezhui** [comment]
> chathub

谢谢分享，刚试了一下，不是我理想中的样子

**Comment by Marchccc** [comment]
ChatGPTBox
