### ISSUE TITLE
[BUG]windows的客户端就不能访问

### ISSUE THREAD

**Issue by suzhi123** [Bin-Huang/chatbox#805]
我部署了server端的服务，Mac的客户端就没问题，可以正常访问，可是![Snipaste_2023-06-30_00-32-18](https://github.com/Bin-Huang/chatbox/assets/131503844/cecef916-70e4-444e-a918-de2dfc87d7c4)，试了多个客户端版本，也让多名朋友用不同版本的windows和不同的电脑试了，都不行。

**Comment by whptv** [comment]
是的，我也是这样的，有什么办法解决吗

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复
https://github.com/Bin-Huang/chatbox/releases
