### ISSUE TITLE
现在的版本生成字的时候很卡。是否能解决？

### ISSUE THREAD

**Issue by q877604530** [Bin-Huang/chatbox#808]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by Qinsmoon** [comment]
我也遇到了这个问题，我是买的api服务。

**Comment by benben312** [comment]
我也是，右上角会显示未响应，每次大概得卡个四五秒。

**Comment by Bin-Huang** [comment]
看下最新版本是否解决问题：https://github.com/Bin-Huang/chatbox/releases

**Comment by benben312** [comment]
更新到最新版本之后，问题解决了。
