### ISSUE TITLE
[Feature]希望程序允许设置default聊天类别。希望聊天记录加载速度变快。希望加入拼写输入检查功能 request for setting of default chat category, spell checking feature, please improve chat record loading speed.

### ISSUE THREAD

**Issue by hq5566** [Bin-Huang/chatbox#809]
现在程序的左手边Chat下面有数个聊天类别，像我的就是“Just Chat”在最上面（我已将它加了Star），下面的是Midjourney，Translator, Software development等聊天类别。 问题是每次程序刚开始运行时，都只能让我在第二项Midjourney类别中输入，无法将Default聊天类别设置为我已经Star了的Just Chat。当然我可以每次运行程序后点Just Chat，但发现文字（以前的聊天记录）载入有点慢。希望程序允许设置default聊天类别。希望聊天记录加载速度变快。

还有，在输入框中输入时有时会英文拼错字，这时候浏览器输入框中，自动拼写校正，或将错词下面加红波浪线，允许我右键进行选词修改的功能。希望加入拼写输入检查功能

Translation: Currently, on the left-hand side of the interface, below the Chat tab, there are several chat categories. For example, mine is "Just Chat" at the top (I have starred it), and below it are categories like "Midjourney," "Translator," "Software Development," and others. The issue is that every time the program starts, it only allows me to input in the second category, "Midjourney," and I cannot set the default chat category to "Just Chat," which I have already starred. Of course, I can click on "Just Chat" every time after running the program, but I have noticed that loading the previous chat history takes a bit longer. I hope the program allows setting the default chat category. I also would appreciate if the chat history could load faster.

Furthermore, sometimes I make spelling mistakes in the input box. It would be helpful if the program could have a spell-checking feature, similar to the browser's automatic spelling correction or underlining misspelled words with a red squiggly line, allowing me to right-click and make word corrections. I hope to see the addition of a spell-checking feature for input.

我下了很多openai api windows客户端来试，这款APP是我觉得写得最好的，我希望它能变得更完善。谢谢来自深圳的开发者。

Translation: I have downloaded several OpenAI API Windows clients (GUIs) to try, and I have found this app to be the best one. I hope it continues to improve and become even better. I want to express my gratitude to the developer for sharing this app with us.

**Comment by Bin-Huang** [comment]
v0.6.2 has been implemented, give it a try.
https://github.com/Bin-Huang/chatbox/releases
