### ISSUE TITLE
[Feature]能否提供一键清空所有会话的功能？ 能否提供按关键词来查询所有会话的功能？

### ISSUE THREAD

**Issue by dwczhixingheyi** [Bin-Huang/chatbox#810]
**Problem Description**
Question 1: I generally create a new session when I have a new topic conversation, and after a long time, there are many sessions in the left list, and the software does not have the function of clearing all sessions with one click, and when I want to clean up the conversation, I need to delete it one by one, which is more time-consuming and laborious.

Question 2: When I have a lot of conversations, sometimes I have to check the previous chat history according to the conversation, the current software does not have the function of finding records by keywords, and I need to use scroll bars to find them one by one, which is more time-consuming and laborious.

**Proposed Solution**
For question 1: Add a menu to clear all sessions, click it, prompt whether to clear it, select Clear, and clear all sessions.

For question 2: Add the input box to find keywords, after filling in the keywords, the chat history containing the keywords will be displayed, and you can right-click to view the before and after chats and locate the record.

**Additional Context**
Regarding question 1: 100 sessions have been created, and by using the "clear all sessions" menu, all 100 sessions can be cleared at once.
Regarding question 2: 100 sessions have been created, and by entering the keyword "requirement analysis," all chat records containing the keyword "requirement analysis" can be searched. By clicking on "view previous and next chats," the record can be located, and the scroll bar can be used to view the chat records before and after that specific record.

-----------------------

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。
问题1：我一般在新主题对话时，会创建新的会话，使用时间长了，左边列表中就有很多会话，而软件没有一键清空所有会话的功能，想要清理会话时，需要一个一个删除，比较费时费力。
问题2：当我有很多会话时，有时要根据会话查一下之前的聊天记录，目前软件没有按关键词查找记录的功能，需要逐个对话用滚动条查看来查找，比较费时费力。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。
对问题1：追加一个清除所有会话的菜单，点击后，提示是否清空，选择清空，就清空所有会话。
对问题2：追加查找关键词的输入框，填写关键词后，就显示含关键词的聊天记录，并可以右键查看前后聊天，定位到该条记录处。

**附加上下文**
对问题1：创建了100个会话，用清除所有会话菜单，实现100个会话全部清空的效果。
对问题2：创建了100个会话，输入关键词“需求分析”，能查到所有含有“需求分析”的聊天记录，点击“查看前后聊天”，定位到该条记录处，可滚动条查看前后的聊天记录。

**Comment by Bin-Huang** [comment]
v0.6.2 已经实现了，试试看
https://github.com/Bin-Huang/chatbox/releases
