### ISSUE TITLE
[BUG]经常出现这个提示:OpenAI API期望有一个JSON的有效载荷，但发送的不是有效的JSON

### ISSUE THREAD

**Issue by hen1332** [Bin-Huang/chatbox#812]
{"error":{"message":"We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)","type":"invalid_request_error","param":null,"code":null}}
![image](https://github.com/Bin-Huang/chatbox/assets/62668502/9099df21-a9f6-4cd5-a86b-2acccd56ae28)
![image](https://github.com/Bin-Huang/chatbox/assets/62668502/de564017-f351-43ed-9a62-ae2d1e49442f)

WIN10  chatbox-0.5.6版本 
即使是简短的问答,也有可能出现这个错误提示,而同样的问答在网页版是不会出现的.

**Comment by Bin-Huang** [comment]
建议观察一段时间，可能是 OpenAI 本身服务器的问题。现在还会吗？

**Comment by Bin-Huang** [comment]
感觉你可能使用了某些代理服务器？

**Comment by hen1332** [comment]
> 感觉你可能使用了某些代理服务器？

感谢回答.目前使用0.6版本的还是会出现这个问题.有使用WS反代API.OPENAI.COM,因为直连OPENAIAPI连不上.话说为什么不在软件内置一个代理功能?让用户可以手动填入自己的代理.

**Comment by hen1332** [comment]
location /openai/ {
            proxy_pass https://api.openai.com/;
            proxy_ssl_server_name on;
            proxy_set_header Host api.openai.com;
            proxy_set_header Connection '';
            proxy_http_version 1.1;
            chunked_transfer_encoding off;
            proxy_buffering off;
            proxy_cache off;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header
            X-Forwarded-Proto $scheme;
            proxy_set_body $request_body;
        }
