### ISSUE TITLE
[BUG]安装时报2503、2502错误

### ISSUE THREAD

**Issue by Amarantosss** [Bin-Huang/chatbox#813]
![屏幕截图 2023-07-04 193734](https://github.com/Bin-Huang/chatbox/assets/102932644/3472b678-de5c-47ae-89c4-e804e0688a74)

**Comment by Amarantosss** [comment]
这是解决方案https://blog.csdn.net/yuanbotao219/article/details/105484473

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复
https://github.com/Bin-Huang/chatbox/releases
