### ISSUE TITLE
[BUG]自定义http API无法使用 

### ISSUE THREAD

**Issue by APPX-Studio** [Bin-Huang/chatbox#814]
**Bug Description**
Please provide a clear and concise description of what the bug is.
服务端使用One API 采用http 没有用https
 

**Bug 描述**
[BUG]自定义http API无法使用 

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
<img width="984" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/49307767/8c300248-a482-4814-b48f-0305a68672d0">

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by APPX-Studio** [comment]
其他工具没有问题

**Comment by Bin-Huang** [comment]
这个问题在最新版本已经修复
https://github.com/Bin-Huang/chatbox/releases
