### ISSUE TITLE
[Other] 请问后续付费的 chatbox AI 是否支持选择模型

### ISSUE THREAD

**Issue by shengbeiniao** [Bin-Huang/chatbox#816]
目前回答的语言风格和官方差异较大，每次回答结束都会加一句 如果您有任何其他问题，请随时提问！，显得啰里啰嗦

这个是否调用的 gpt3.5-turbo?
是如何微调的？

查阅了源码，没发现有 Chatbox AI 相关代码，好奇作者是怎么解决实现成本价接入的，毕竟官方订阅每个月都要5$

**Comment by Bin-Huang** [comment]
前置使用 prompt 进行微调。你可以修改 system 消息进行微调。
