### ISSUE TITLE
[Other]7月6日开始无法使用，有如下返回信息，使用的openai api，是开始收费了吗？

### ISSUE THREAD

**Issue by Mikeyancn** [Bin-Huang/chatbox#818]
{"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":null}}

**Comment by luckmc** [comment]
确实是这个情况，我更换api key，只要chatbox调用了，openai后台就把这个key给禁止了

**Comment by Roxannej** [comment]
我也是遇到了这个问题

**Comment by Roxannej** [comment]
> 

但是自己打开chatGPT却可以正常的使用

**Comment by luckmc** [comment]
你们的现在可以用了吗？

**Comment by kmkeeper** [comment]
我也一样的报错,不能用了

**Comment by njhayy** [comment]
一样的问题，重新换了api key还是不可以

**Comment by Bin-Huang** [comment]
你们其实可以搜索一下，就知道这个是账户问题了。
这里是详细的帮助文档：https://github.com/Bin-Huang/chatbox/blob/main/FAQ-CN.md#1002

**Comment by LeBroSs** [comment]
现在能用了吗？  我也有同样的情况

**Comment by Bin-Huang** [comment]
@LeBroSs 这个是账户问题，具体原因查看帮助文档：https://github.com/Bin-Huang/chatbox/blob/main/FAQ-CN.md#1002
