### ISSUE TITLE
[BUG]使用openai的api选择了gpt-4模型，询问gpt是什么版本的模型，gpt回答是gpt-3，甚至都不是3.5

### ISSUE THREAD

**Issue by godblessbb** [Bin-Huang/chatbox#819]
![WechatIMG905](https://github.com/Bin-Huang/chatbox/assets/4539598/8bb77dbf-eb25-46ad-9531-09d39952e093)

**Comment by godblessbb** [comment]
> 

哈哈哈，何苦骗自己呢

**Comment by Hisoka-J** [comment]
> 

![image](https://github.com/Bin-Huang/chatbox/assets/8022389/91981e06-7056-4b4d-abd2-b9548988cd98)

看下方这里

**Comment by Bin-Huang** [comment]
这是因为 GPT4 在训练的时候世界上还没有 GPT4，所以它的训练数据根本就没有自己的信息
