### ISSUE TITLE
[Feature] 为不同对话设置不同模型 / 并能更显眼地显示当前的模型

### ISSUE THREAD

**Issue by xtremforce** [Bin-Huang/chatbox#820]
**问题描述**
GPT-4 基本全开放了，但日常使用太贵无需用到 4，但偶尔又需要更准确的回答。
而目前的切换模型都是整个 APP 全局更换的，来回更换很麻烦。

**解决思路**
新建会话时，可以设置/修改该会话的模型

**Comment by CoREse** [comment]
附议！是真的很需要！

**Comment by Bin-Huang** [comment]
This feature has been implemented, try the latest version.

随着版本的更新，这个功能已经实现了，试试最新的版本。
