### ISSUE TITLE
[BUG] *** Very slow & lagging application when you make too many chats ***

### ISSUE THREAD

**Issue by elendil7** [Bin-Huang/chatbox#822]
**Bug Description**
The application slows down & freezes when sending a message in any conversation. The words do not appear smoothly on the screen, and the application freezes until the generation is fully complete. This did not happen before, but randomly started happening one day.

I believe this may be due to the fact that I have 100s of conversations, which I do not delete.

**Video showcase**
https://github.com/Bin-Huang/chatbox/assets/80429382/fcb58104-c24f-4197-8549-3cdcdac6c4cf

**Steps to Reproduce**
1. Enter program
2. Open a chat
3. Send a message in the chat

**Expected Results**
Smooth animation of text appearing on the screen as it is fetched from OpenAI ChatGPT API.

**Actual Results**
Lagging, freezing, and stuttering.

**Desktop (please complete the following information):**
- Operating System: Windows 10 Pro
- Application Version: Chatbox v0.5.6

**Comment by Bin-Huang** [comment]
I'm trying to fix it right now.

**Comment by Bin-Huang** [comment]
Now, in v0.6.2, a bulk cleaning feature for conversation lists has been added. Give it a try.
https://github.com/Bin-Huang/chatbox/releases

**Comment by elendil7** [comment]
Works well! Ty
