### ISSUE TITLE
[BUG] 0.6.1版本，使用内网http代理，使用域名时，无法访问

### ISSUE THREAD

**Issue by longyuxiao** [Bin-Huang/chatbox#824]
在windows客户端上， 0.6.1版本， api域名设置为 http://xxx.xxxxx.com:8080, 无法正常访问，抓包未发现任何tcp建连报文， 设置为： http://172.19.14.12:8080， 可以正常访问。

**Comment by hen1332** [comment]
考虑域名证书是否设置正确 我自己使用域名是正常的

**Comment by Bin-Huang** [comment]
v0.6.2 试试看？https://github.com/Bin-Huang/chatbox/releases

**Comment by longyuxiao** [comment]
> 

我用的http, 不是https不需要证书

**Comment by longyuxiao** [comment]
> v0.6.2 试试看？https://github.com/Bin-Huang/chatbox/releases

试了， 还是不行。 这个域名是走公网解析的

**Comment by Bin-Huang** [comment]
诶，插个话题，我突然意识到，如果你不使用 HTTPS 的话是会有安全问题的，黑客可能利用中间人攻击窃取你的 API Token，尤其是这种公网解析的场景。只是提醒你一下

**Comment by longyuxiao** [comment]
哦， 这个不用担心，这个搭出来是给公司内网用的， 外网通道是用https访问的

**Comment by badboy-tian** [comment]
@Bin-Huang 请问有可能给app添加http代理吗？谢谢 不想全局

**Comment by Bin-Huang** [comment]
Implemented

**Comment by badboy-tian** [comment]
thank you very much
