### ISSUE TITLE
[BUG] 安装0.6.1后重启软件显示版本依旧显示0.5.6

### ISSUE THREAD

**Issue by BingZi-233** [Bin-Huang/chatbox#825]
**Bug 描述**
安装后重启软件版本依旧为0.5.6

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 安装0.5.6版本
2. 使用0.6.1升级安装包
3. 重启软件
4. 发现了这个 bug。

**期望结果**
重启后应该显示为0.6.1

**实际结果**
实际为0.5.6

**桌面端：**
- 操作系统：Windows
- 应用程序版本：0.5.6

**Comment by Boreal** [comment]
加1

**Comment by Bin-Huang** [comment]
Windows 是什么版本？

**Comment by wildywerewolf** [comment]
你看看有没有C:\Users\*****\AppData\Local\Programs\xyz.chatboxapp.app 这个文件夹，我安装完的0.6.1直接自动默认这里了。

**Comment by Bin-Huang** [comment]
需要手动卸载掉旧的版本
