### ISSUE TITLE
v0.61版本安装时，为何没有安装路径可选择，自动安装在C盘 [BUG]

### ISSUE THREAD

**Issue by treefive3000** [Bin-Huang/chatbox#828]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：
1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**
- 操作系统：[例如 macOS]
- 应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by myworksfun** [comment]
**The author avoids the "Program Files" folder permissions problem and installs it directly into the user directory, which is very clever!** 😄

**Comment by feodorren** [comment]
这不是bug吧？直接安装在C盘是否不妥？更新里还写了要手动卸载旧版本？

**Comment by treefive3000** [comment]
之前安装软件大多数会提供给使用者自主选择安装路径，由于C盘空间有限，还请楼主能否在下一版本考虑此类需求，谢谢！

**Comment by Atomadeus** [comment]
其实可以解压出来的，先解压“Chatbox-0.6.1-Setup.exe”文件，然后在“$PLUGINSDIR”文件夹里面有个名为“app-64.7z”的压缩文件，解压它就能看到Chatbox.exe可执行文件了。

**Comment by Bin-Huang** [comment]
以后考虑提供免安装版本……
