### ISSUE TITLE
[BUG] *2 VERSIONS OF THE SAME SOFTWARE INSTALLED*

### ISSUE THREAD

**Issue by elendil7** [Bin-Huang/chatbox#829]
**Bug Description**
2 versions of chatbox are available after installing 0.6.1. Version 0.5.6 does not get deleted. I initially thought that the software was being downgraded back to 0.5.6 after restarting the application , when in fact the version 0.5.6 was pinned to my taskbar!

**Screenshots**
![image](https://github.com/Bin-Huang/chatbox/assets/80429382/ab4a42b8-e8b0-4aa5-87e4-435c6afdeac0)
![image](https://github.com/Bin-Huang/chatbox/assets/80429382/ac3b509a-4117-461e-bc23-f6bbc5e81452)

**Desktop (please complete the following information):**
- Operating System: Windows 10 Pro
- Application Version: 0.5.6 => 0.6.1

**Comment by myworksfun** [comment]
Just uninstall the version 0.56, as version 0.61 changed the installation directory and will not overwrite the previous version. so you will see 2 versions。😄

**Comment by elendil7** [comment]
Done

**Comment by Bin-Huang** [comment]
The installation of the new version has been changed to a different location, to avoid requiring administrator privileges. I didn't make it clear in the update notes, but you actually need to manually uninstall the old version
