### ISSUE TITLE
[Feature]ChatBox Ai按量付费的实现

### ISSUE THREAD

**Issue by rhejuilna27** [Bin-Huang/chatbox#837]
我之前是注册的openai,账户送了$5的使用额度，3个月有效期，使用下来发现，$5够我用3个月不止。我看0.61版本的chatbox里面增加了chatbox ai付费的实现，但是按月要$4, 3个月$11,个人觉得很多人可能没有那么多需求的，$4每月的价格太贵了，有没有可能搞成按实际使用量付费的？比如$5 给固定的tokens的，使用完就失效

**Comment by Bin-Huang** [comment]
其实在 0.5 版本就有了……这里主要讨论 Chatbox 软件，Chatbox AI 服务的建议可以发邮件到 hi@benn.app。
