### ISSUE TITLE
是否可以增加prompt的导入

### ISSUE THREAD

**Issue by geekbb** [Bin-Huang/chatbox#84]
提供两个prompt搜集项目网址
https://github.com/PlexPt/awesome-chatgpt-prompts-zh
https://github.com/Nothing1024/chatgpt-prompt-collection

类：
<img width="575" alt="CleanShot 2023-03-20 at 18 43 13@2x" src="https://user-images.githubusercontent.com/46196358/226317001-9034f922-0d95-498e-ba23-471ba55b77df.png">
<img width="989" alt="CleanShot 2023-03-20 at 18 41 59@2x" src="https://user-images.githubusercontent.com/46196358/226317063-e8777856-cecc-419a-bb3c-798de4fad551.png">

**Comment by ttyy33** [comment]
我觉得你对提问题的描述有问题，prompt翻译成中文是提示，你想说的应该是：先设置特定的角色，再进行提问

**Comment by geekbb** [comment]
> 我觉得你对提问题的描述有问题，prompt翻译成中文是提示，你想说的应该是：先设置特定的角色，再进行提问

prompt是什么不重要，作者加进去就好

**Comment by hr159** [comment]
+1，希望能设置角色描述

**Comment by crystoneme** [comment]
> > 我觉得你对提问题的描述有问题，prompt翻译成中文是提示，你想说的应该是：先设置特定的角色，再进行提问
> 
> prompt是什么不重要，作者加进去就好

我需要加入自己定制的提示，找不到添加的地方

**Comment by Bin-Huang** [comment]
很早之前的版本已经实现了，可以更新一下，先关闭了这条 issues 了。
