### ISSUE TITLE
[Feature]可以支持claude的API么？

### ISSUE THREAD

**Issue by Hisoka-J** [Bin-Huang/chatbox#841]
目前claude是免费的，感觉也挺不错的，还支持上传文件进行分析，希望chatbox能支持claude

**Comment by chinyah0616** [comment]
同意QQ我也求支持claude

**Comment by caoyangyang1215** [comment]
> 目前claude是免费的，感觉也挺不错的，还支持上传文件进行分析，希望chatbox能支持claude

calude 有提供个人用户的 api 吗

**Comment by VeeDou** [comment]
> > 目前claude是免费的，感觉也挺不错的，还支持上传文件进行分析，希望chatbox能支持claude
> 
> calude 有提供个人用户的 api 吗

我申请了两次了，还没有通过

**Comment by Bin-Huang** [comment]
In the latest version, I have added support for the Claude API. Please upgrade and take a look. https://github.com/Bin-Huang/chatbox/releases

在最新版本中我已经添加了对 Claude API 的支持，请升级看看。https://github.com/Bin-Huang/chatbox/releases
