### ISSUE TITLE
Need a one-click Vercel deployment?[Other]

### ISSUE THREAD

**Issue by Formyselfonly** [Bin-Huang/chatbox#843]
I can write a one-click Vercel deployment for u!If u don't need,i will write a other project.
The one-click Vercel is such like this:
This is one-click Vercel for ChatGPT-Next-Web
![image](https://github.com/Bin-Huang/chatbox/assets/56914169/a05a1adb-12ee-4700-aba7-ae9d461608f3)

**Comment by Bin-Huang** [comment]
精神可敬，暂时没有计划。因为这会帮助到那些盗取 API KEY 黑产。我之前被他们搞怕了。
