### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by AurevoirXavier** [Bin-Huang/chatbox#844]
虽然 release 描述写的是重写提升性能以及稳定性。

但切换到新版后，感到性能明显下降。

- 关闭再打开，加载时间久，一段时间内无法输入内容
- 拖拽更改窗口大小非常卡

---

```
Chip M1 Max
macOS 13.4.1

Chatbox 0.6.2-arm-mac
```

**Comment by Bin-Huang** [comment]
重新安装到历史版本(v0.5.x)后性能有提升吗？我需要先排除下是不是升级导致的问题

**Comment by Bin-Huang** [comment]
0.6.3 进行了大规模性能升级，看看有没有解决问题 https://github.com/Bin-Huang/chatbox/releases

**Comment by AurevoirXavier** [comment]
> 0.6.3 进行了大规模性能升级，看看有没有解决问题 [Bin-Huang/chatbox/releases](https://github.com/Bin-Huang/chatbox/releases)

Resolved.
