### ISSUE TITLE
网页的chatgpt能够正常使用，密钥也进行了更新，但chatbox用不了了

### ISSUE THREAD

**Issue by LeBroSs** [Bin-Huang/chatbox#845]
API Error: {"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":"insufficient_quota"}}

遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

<img width="518" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/102779574/a88411d2-6d57-4449-b233-dbbe438a26b1">

**Comment by Bin-Huang** [comment]
查看文档，这个问题写得很清楚的
