### ISSUE TITLE
[Feature] Use Exact Token Usage In The Response Subscript

### ISSUE THREAD

**Issue by JakuWorksOfficial** [Bin-Huang/chatbox#846]
**Problem Description**
I do not know the exact number of tokens used. Instead, I have an estimated number - https://i.imgur.com/UzE1Sz2.png.
The "~" characters indicate that this is an estimate, even though there IS a way to get the exact number, not an estimation.

**Proposed Solution**
I know the OpenAI returns the exact number of API tokens used to generate an answer - https://i.imgur.com/wXAnRA9.png

You may edit the subscript in Chatbox like so:

Before
"word count: 30, token count: ~43, tokens used: ~2111, model: gpt-3.5-turbo-16k" 

After
"word count: 30, token count: [the exact number from the response], tokens used: [the exact number from the response], model: gpt-3.5-turbo-16k" 

The [] indicates a placeholder.
Notice the removed '~' characters, indicating it's no longer an estimate.

The used ~ characters are misleading, and You should remove them if the number of the tokens is exact and not an approximation.

**Additional Context**
I do not know if this was this already implemented. The ~ characters may have misled me as well.

The "~" (tilde) character often indicates an approximation. Maybe it has been misused.

Using an exact number instead of an estimate will make ChatBox look more professional and reliable.

-----------------------

**Comment by Bin-Huang** [comment]
This reminder just popped up, seems like we can drop the "~".

**Comment by Bin-Huang** [comment]
This issue has been resolved in the new version v0.6.3. If the problem still persists, you can reopen the issue at any time😊.
https://github.com/Bin-Huang/chatbox/releases
