### ISSUE TITLE
[Other]团队共享部署的时候可否添加变量直接置入 API HOST？

### ISSUE THREAD

**Issue by chengxiao** [Bin-Huang/chatbox#849]
用了国内的第三方代理，因为没有合适的支付方式，但是又想分享给内网的人直接使用

我看团队部署是支持变量输入的
-e HOST=<YOUR_DOMAIN> 
-e KEY=<YOUR_OPENAI_KEY> 

那是否有 API PROXY的变量设置呢？

**Comment by Bin-Huang** [comment]
建议看文档，我感觉现在应该已经满足你的需要了
