### ISSUE TITLE
[Feature]Azure OpenAI API提供模型的选择

### ISSUE THREAD

**Issue by fredericky123** [Bin-Huang/chatbox#854]
能否给Azure OpenAI API提供模型的选择
虽然在azure openai 官网上部署的事gpt3.5 可是使用bob translator意外发现选择gpt4模型时也能用，确实比gpt3.5翻译的好
<img width="730" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/13982749/9f4679f0-d931-4cbf-a3b9-ddce7886e898">

**Comment by Bin-Huang** [comment]
我觉得可能是哪里弄错了。据我所知 Azure 每一个部署都是固定的模型版本，只能通过更改部署的方式来更改模型版本。我怀疑你截图中的这个模型切换应该是没有生效的。

**Comment by fredericky123** [comment]
> 我觉得可能是哪里弄错了。据我所知 Azure 每一个部署都是固定的模型版本，只能通过更改部署的方式来更改模型版本。我怀疑你截图中的这个模型切换应该是没有生效的。

奇怪的是我测试了，选择不同的模型，翻译的结果并不一样，且选择gpt4明显流畅好多

**Comment by fredericky123** [comment]
如果也用bob translator的话，欢迎测试一下
