### ISSUE TITLE
[BUG] 504 报错

### ISSUE THREAD

**Issue by iRubbish** [Bin-Huang/chatbox#855]
**Bug 描述**
![image](https://github.com/Bin-Huang/chatbox/assets/32736415/755a1f1a-1dac-4702-bd81-2ff1b031d7a8)

**Comment by Bin-Huang** [comment]
这个错误和软件无关，如果使用了反向代理应该检查代理问题。最后可能是OpenAI本身服务抖动了，这个情况比较少见，但却是也曾经发生过几次了
