### ISSUE TITLE
[Other]Windows版本配置文件在哪里？

### ISSUE THREAD

**Issue by liuxing87327** [Bin-Huang/chatbox#857]
Windows版本的本地配置文件在哪里？我想直接修改配置文件，批量初始化一些自定义的搭档和Prompt

**Comment by liuxing87327** [comment]
已经找到
windows
C:\Users\Administrator\AppData\Roaming\xyz.chatboxapp.app\config.json
macos
~/Library/Application Support/xyz.chatboxapp.app/config.json

**Comment by Idealisten** [comment]
> 已经找到 windows C:\Users\Administrator\AppData\Roaming\xyz.chatboxapp.app\config.json macos ~/Library/Application Support/xyz.chatboxapp.app/config.json

Users下面没有Administrator这个文件夹，在我的个人用户下也没找到AppData这个文件夹，到底会在哪呢。。
