### ISSUE TITLE
[Feature] Accounting of token usage.

### ISSUE THREAD

**Issue by cocoonkid** [Bin-Huang/chatbox#859]
**Problem Description**

For some reason my openapi api rate limit get's hit faster with chatbox.
Unusually quick.

It would be great to have a simnple stats page to see how much tokens used on avg per day/month 
so we can compare it with usage data displayed by openapi , which is really not helpful at all :-)

**Proposed Solution**
Statistics tab providing historical usage data.

Question:

Does this look unusual?

This day cost 10 usd alone.

![image](https://github.com/Bin-Huang/chatbox/assets/43231640/db76736d-3d7c-42a1-b053-78d461e7f568)

I am mostly currently working with ansible playbooks and I really don't think my usage is higher.

On my other account using some other UI in the past I averaged 2-3 usd a month.
And I do not think my usage patterns changed much.

**Comment by cocoonkid** [comment]
Today I get this:
I have chatted no more than a dozen token. No one else is using the key. I revoked all  and only used a fresh one.
![Uploading image.png…]()

**Comment by cocoonkid** [comment]
Today I get this:
I have chatted no more than a dozen token. No one else is using the key. I revoked all  and only used a fresh one.


![image](https://github.com/Bin-Huang/chatbox/assets/43231640/9120ec77-ea16-4a95-918b-fa3d380492bc)

**Comment by Bin-Huang** [comment]
Perhaps I should first address the issue of tokens being consumed too quickly. I think I've got a pretty good idea of what's causing it: by default (unless the user changes the settings), the Chatbox tries to carry as much context as possible for better performance, which leads to more and more token consumption as the conversation progresses. Maybe I should add a default context limit specifically for GPT-4.

**Comment by cocoonkid** [comment]
Great. Thank you for taking the time to comment.

As a poweruser with wide contexts I appreciate the thought put into optimization.

I do not know enough about the inner workings in this case  but it would be really great if a user could set it with a slider or value selection.

like kind of a gauge on how "contex-tintensive" the current chat is considered from the user persepctive.

when work on ansible playbooks I need context intensivity high.

When know i will only work with those 50 lines script now  I am happy it forgets context quicly so I get more "varioation" .

I hope I am able to convey what my intention is here :-)

**Comment by Bin-Huang** [comment]
I totally get and agree with your idea. In fact, that's exactly how I designed it: users can customize it according to their own needs. It's currently under development, and I'm hoping to roll it out with the next release.

**Comment by Bin-Huang** [comment]
😊😊This feature has been implemented in the new version v0.6.5.
https://github.com/Bin-Huang/chatbox/releases
