### ISSUE TITLE
azure openai api add failed

### ISSUE THREAD

**Issue by Readme23** [Bin-Huang/chatbox#861]
{"error":{"code":"DeploymentNotFound","message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

**Comment by Readme23** [comment]
{"error":{"code":"DeploymentNotFound","message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

**Comment by superpoussin22** [comment]
Works fine on Azure on my side, can you provide more details ? (with and Without apim )

**Comment by Bin-Huang** [comment]
The usual reason is that you have configured it incorrectly ☺️☺️☺️
