### ISSUE TITLE
[Other] 大佬可以适配安卓吗，跪求！

### ISSUE THREAD

**Issue by SMFDrummer** [Bin-Huang/chatbox#867]

**Comment by wuyudi** [comment]
~~需要等上游 tauri 支持 android~~

https://github.com/tauri-apps/tauri-mobile 哦，已经 alpha 了

**Comment by SMFDrummer** [comment]
所以有希望，是这样吗，期待大佬，跪谢！

**Comment by wuyudi** [comment]
> 所以有希望，是这样吗，期待大佬，跪谢！

哦，不用想了，才发现已经换成 electron 了。

人话：electron 没有移动端。

**Comment by Bin-Huang** [comment]
可以先用移动端的网页版本： http://web.chatboxai.app/

**Comment by Bin-Huang** [comment]
安卓版本已经在内测了，可以在这里了解进度：
https://github.com/Bin-Huang/chatbox/issues/686
