### ISSUE TITLE
[Feature] 关于会话导出功能

### ISSUE THREAD

**Issue by IzualYang** [Bin-Huang/chatbox#868]
**Problem Description**
Chatbox now provides the function to: 1. Save the current (single) chat session as a markdown file; 2. backup or syncronize config.json file outside the software (desktop version only). However, it lacks the ability to:
1. Import saved session (single file/session, or just let user export/import ALL sessions at once)
2. Save current session and name saved .md file by "Session Name + Time Stamp", instead of using just default filename.

**Proposed Solution**
See above

**Additional Context**
\-

-----------------------

**问题描述**
目前似乎只有同步json（客户端）和保存为markdown的功能，并且：
1.  .md文件只有保存没有导入
2.  .md文件只会按照默认文件名保存

**解决思路**
1. 能否添加会话导入功能（例如我不想替换整个config.json，只是想导入某一个会话）
2. 能否根据会话标题和时间戳自动命名保存的.md文件（我主要使用[网页端](https://web.chatboxapp.xyz)，不确定客户端webview2和浏览器的行为会不会有所不同）

**附加上下文**
\-

**Comment by Ismael-Hery** [comment]
Being able to import saved conversations (whether in markdown or json) would allow use to share conversations with other team member.

**Comment by Bin-Huang** [comment]
This feature has already been implemented. Give it a try after updating.
https://github.com/Bin-Huang/chatbox/releases
