### ISSUE TITLE
[BUG] Paste to system prompt or message edit field fails

### ISSUE THREAD

**Issue by sam1am** [Bin-Huang/chatbox#869]
**Bug Description**
Pasting into the system prompt, or into the editing field of a previously sent message, pasting fails. 

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
Click to edit the system prompt or a previous message. 
Attempt to paste ~100 lines of text or code. 

**Expected Results**
Text should paste into the field.

**Actual Results**
Editing ends and changes are lost. 

**Screenshots**

About to paste some code: 
<img width="797" alt="Screenshot 2023-07-28 at 1 41 30 PM" src="https://github.com/Bin-Huang/chatbox/assets/127555/0cf2d892-4afb-490b-8b6e-e675e38ed790">
After hitting paste: 
<img width="788" alt="Screenshot 2023-07-28 at 1 41 36 PM" src="https://github.com/Bin-Huang/chatbox/assets/127555/46e668f6-d08c-4c95-a493-f1587994c5c4">

**Desktop (please complete the following information):**
- Operating System: This showed up in the latest version on Windows and mac OS. 
- Application Version: 0.6.3

**Comment by sam1am** [comment]
Reverting to 0.6.2 and pasting text works normally, but the app will only run once before auto-updating.

**Comment by Bin-Huang** [comment]
Thanks for the feedback! The issue has been fixed and will be included in the next release.

**Comment by Bin-Huang** [comment]
Fixed
