### ISSUE TITLE
支持手机版自适应的ui界面

### ISSUE THREAD

**Issue by renjieQ** [Bin-Huang/chatbox#87]
您好，我build了代码，depoly之后，在手机端访问网页。得到的试图有些。。 🎃。。详见图：

<img src="https://user-images.githubusercontent.com/53574350/226430726-13e34df7-987c-4969-b129-b691822aef52.png" width="50%">
<img src="https://user-images.githubusercontent.com/53574350/226430762-566c5e59-1f3b-4722-8d36-db86a6b1a243.png" width="50%">

**Comment by Bin-Huang** [comment]
安卓版本确定要做了，请给我一周

**Comment by nufeng1999** [comment]
试试这个 https://nufeng1999.github.io/index.html

**Comment by Bin-Huang** [comment]
Chatbox 官方的网页版本 https://web.chatboxapp.xyz/ 已经兼容手机浏览器了。可以先用用看看。

建议不要使用第三方网页版本，可能会出现 API KEY 盗取的安全问题。
