### ISSUE TITLE
[BUG] After updating I've lost all my conversations

### ISSUE THREAD

**Issue by abuisman** [Bin-Huang/chatbox#871]
**Bug Description**
I've updated to 0.6.3 and suddenly all my conversations are gone!

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Have an older version installed. 
2. Create some chats
3. Install the update through the dialog in the app
4. Observe that all conversations are gone

**Expected Results**
I would've expected the app to update and all my old chats to still be there. 

**Actual Results**
The app was updated, but the conversations were gone.

**Screenshots**
<img width="1116" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/27729/fb97e5df-bfc1-466a-8199-d0954094b298">

**Desktop (please complete the following information):**
- Operating System: macOS 13.1 (22C65)
- Application Version: Chatbox(v0.6.3)

**Additional Context**
The copilot I created is still there as is the custom "Default prompt for new conversations"

**Comment by Bin-Huang** [comment]
This is the first time I've heard of someone encountering this issue. I'm sorry for the trouble you're experiencing. Do you recall which version you upgraded from to get to v0.6.3?

**Comment by Bin-Huang** [comment]
The data might still be salvageable. Try running this command and see if your historical chat data is still there.

```shell
cat ~/Library/Application\ Support/xyz.chatboxapp.app/config.json
```

If the data is present and you trust me, you can send this file to me at [hi@benn.app](mailto:hi@benn.app). I'll try to troubleshoot the problem and help you recover the data. The file will contain your apikeys and chat history, but rest assured, I will delete all data once the process is complete.

**Comment by Bin-Huang** [comment]
I'm glad to hear that you've recovered your data. Maybe I should plan to add a data synchronization service in the future, which should help avoid similar issues and synchronize with the mobile web version...
