### ISSUE TITLE
上下文是什么意思?

### ISSUE THREAD

**Issue by hanke-cnc** [Bin-Huang/chatbox#875]
意思是我每次对话都会发送之前的对话信息吗?那岂不是连续对话越长,每次对话消耗的钱更多😳

**Comment by xiaochen0517** [comment]
这就是token limit的作用。

**Comment by Bin-Huang** [comment]
目前所有的模型都需要把上下文（也就是消息记录）附带发送，才能让模型知道你们的聊天话题，这也是目前主流且唯一的做法。不过为了帮你节约 tokens，Chatbox 会自动无视掉当前会话的早期记录、仅发送最近的记录。同时，你可以通过 Chatbox 提供的两个设置：上下文 token 限制、上下文数量限制进行自定义调节。
