### ISSUE TITLE
[Feature]windows系统安装时提供安装选项，以供用户选择为所有用户安装，还是仅为我安装

### ISSUE THREAD

**Issue by cococolanosugar** [Bin-Huang/chatbox#876]
**问题描述**
目前chatbox在Windows系统安装时未提供**仅为当前用户安装**的选项，这会导致chatbox在一些没有管理员权限的电脑设备上无法安装使用。

**解决思路**
参考FileZilla安装器，提供多种安装选项

[FileZilla安装器图片](https://www.tutorials24x7.com/uploads/2020-06-19/files/4-tutorials24x7-install-filezilla-ftp-client-windows-10-installation-options.png)

**Comment by Bin-Huang** [comment]
新版本 v1.3.4 中已经支持
