### ISSUE TITLE
[Feature]希望载入窗口时默认展示最新对话内容（展示最底部对话）

### ISSUE THREAD

**Issue by hyue418** [Bin-Huang/chatbox#877]
**问题描述**
Mac关闭窗口再重新打开时窗口会自动加载，加载完成后会展示最早的对话内容，而最新的对话在页面下方，所以每次都需要点击按钮回到最底部才能看到最新的对话内容，不是很方便

**解决思路**
加载窗口时从底部开始展示

**Comment by Bin-Huang** [comment]
已修复，将会发布到 v1.3.2 版本中（预计两周后）
