### ISSUE TITLE
点击设置后，弹窗有问题，[BUG]

### ISSUE THREAD

**Issue by Lucifer2u** [Bin-Huang/chatbox#880]
**Bug 描述**
前端点击设置后的花屏

**期望结果**
无这个问题

**截图**
<img width="1024" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/57136396/9fd745a0-e91f-4dfd-b0ab-906dfec198be">

**桌面端（请填写以下信息）：**
- 操作系统：macOS 13.5 (22G74)
- 应用程序版本：Chatbox(v0.6.6)

**Comment by Bin-Huang** [comment]
在你的操作系统使用其他软件遇到过这种问题吗？或者还有人遇到类似的问题吗？感觉和软件关系不大……

**Comment by Lucifer2u** [comment]
没有哎，只有这个软件有这个问题，有可以上传日志的地方吗



梁枭伟


------------------ 原始邮件 ------------------
发件人: Benn Huang ***@***.***&gt;
发送时间: 2023年8月4日 11:01
收件人: Bin-Huang/chatbox ***@***.***&gt;
抄送: LuciferPro ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Bin-Huang/chatbox] 点击设置后，弹窗有问题，[BUG] (Issue #880)





 
在你的操作系统使用其他软件遇到过这种问题吗？或者还有人遇到类似的问题吗？感觉和软件关系不大……

**Comment by Bin-Huang** [comment]
请问这个问题在新版本中还存在吗？可能随着更新已经解决了？

**Comment by Bin-Huang** [comment]
这个问题可能有些过时了（已经被顺带解决），先关闭了
