### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alvist0101** [Bin-Huang/chatbox#883]
为什么每次更新，需要重启很多次，而且都要重新输入license!!!!!!!!!!!!!!!!!!!

**Comment by IzualYang** [comment]
网页端 https://web.chatboxapp.xyz 是不是有问题了，记不住配置了

**Comment by IzualYang** [comment]
> 网页端 https://web.chatboxapp.xyz 是不是有问题了，记不住配置了

目前好像正常了
