### ISSUE TITLE
[Other]

### ISSUE THREAD

**Issue by uiguosun** [Bin-Huang/chatbox#884]
<img width="780" alt="截屏2023-08-04 10 46 06" src="https://github.com/Bin-Huang/chatbox/assets/40018545/65f97fce-4b7c-40a7-a493-b07f68f24efe">
<img width="596" alt="截屏2023-08-04 10 46 26" src="https://github.com/Bin-Huang/chatbox/assets/40018545/6b0de824-e891-465e-9338-321aa9301d10">
我在使用自己账户生成的API密钥后 出现了这种问题 请问这是什么原因

**Comment by Bin-Huang** [comment]
说过了，和软件没有关系，你自己的服务正常吗
