### ISSUE TITLE
我在使用自己的API密钥时出现“API Error: 401 Unauthorized”

### ISSUE THREAD

**Issue by uiguosun** [Bin-Huang/chatbox#885]
[这是不能用吗
<img width="734" alt="截屏2023-08-04 10 50 05" src="https://github.com/Bin-Huang/chatbox/assets/40018545/b9795797-6718-406f-b075-69f1441a6c94">
<img width="568" alt="截屏2023-08-04 10 50 22" src="https://github.com/Bin-Huang/chatbox/assets/40018545/14c03574-0363-4321-83f2-05c3a2233a2f">

**Comment by Bin-Huang** [comment]
和软件没有关系哦。好像是你的服务认为你的key不正确，拒绝访问了。
