### ISSUE TITLE
[Feature] 使用快捷键切换模型！/ Use shortcut keys to switch models!

### ISSUE THREAD

**Issue by Unstoppablesss** [Bin-Huang/chatbox#888]
有时候大量使用chatbox的时候是想要用GPT3.5的，因为便宜。
但是有时候问一些问题的时候，比如定义啊，少量文本的翻译啊，是想要用 GPT 4的因为输出结果更好一些。
应该有很多人预算比较不充足的人跟我一样，希望这样快速切换可以省点钱，还有一个就是GPT 3.5也有4k的版本和16k的版本
模型切换起来也更方便

功能实现：

比如说在软件中
control + 3 是 使用 GPT 3.5
control + 4 是 使用 GPT 4

Sometimes heavy use of chatbox is wanting to use GPT 3.5 because it's cheaper.

But sometimes when you ask some questions, such as definitions, translations of small amounts of text, you want to use GPT 4 because the output is better.

There should be a lot of people with less budget like me, hope that this fast switch can save some money, there is also a GPT 3.5 also has a 4k version and 16k version!

It's also easier to switch between models.

The modeling is also more convenient to switch between the 4k and 16k versions.

Functional realization:

For example, in the software

control + 3 is implemented using GPT 3.5.

control + 4 is to use GPT 4

**Comment by Bin-Huang** [comment]
One current usage involves combining conversation settings and keyboard shortcuts. For example, I can set up a translation conversation to only use GPT-3.5 and then star it at the top, allowing me to quickly switch to this conversation using the keyboard shortcut Ctrl+1.

现在有种用法是结合会话设置和快捷键，比如我尝尝把翻译会话设置成只使用GPT-3.5，然后将其置于顶部，这样我就可以使用快捷键 ctrl+1 快速切换到这个会话。
