### ISSUE TITLE
我是一名产品设计师，希望可以贡献一份力量

### ISSUE THREAD

**Issue by yinrenzhangsir** [Bin-Huang/chatbox#89]
从0.08左右的时候开始就用了，看了别人的评论，也可能有一些交互的优化，产品的UI可以升级，不知道你这边的团伙或个人是如何运作的，希望我可以帮到你来改善产品

**Comment by Bin-Huang** [comment]
我们目前还是以开源社区的方式驱动迭代。你可以在 issues 这里详细表达你的想法，和所有感兴趣的人一起讨论。我或者其他感兴趣的人会把可行的想法开发出来。不过提醒一下标题和正文的可读性、还有最好同时使用中英文～～

We are currently driving iterations through an open-source community approach. You can express your ideas in detail here in the issues section and discuss them with all interested parties. I or other interested individuals will develop feasible ideas. However, please keep in mind the readability of the title and content, and it is best to use both Chinese and English at the same time.

😁😁😁
