### ISSUE TITLE
[BUG] UI goes black when the user switches screen while receiving streaming

### ISSUE THREAD

**Issue by hycxnas** [Bin-Huang/chatbox#892]
**Bug Description**
The UI goes black when the user switches screen while receiving streaming API (SSE) responses.

**Steps to Reproduce**
1. Start receiving streaming responses from an API in Chatbox 
2. While the responses are streaming, switch to another screen or desktop
3. The Chatbox UI goes completely black and becomes unresponsive

**Expected Results**
The Chatbox UI should remain visible and responsive when switching screens during streaming API responses.

**Actual Results** 
The UI goes black and becomes unresponsive as soon as the screen is switched.

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Operating System: Windows 10 Home
- Application Version: Chatbox 0.6.6

**Additional Context**
This seems to happen every time the user switches screens during a streaming response. It makes the app unusable if you need to monitor the streaming output. Needs an urgent fix.

**Comment by Bin-Huang** [comment]
Is the issue still present in the latest version (v0.6.8)?
