### ISSUE TITLE
[BUG] Webview crash once a long title is returned by API

### ISSUE THREAD

**Issue by hycxnas** [Bin-Huang/chatbox#893]
**Bug Description**  
Chatbox's webview crashes when the backend returns a long title to show in the frontend.

**Steps to Reproduce** 
1. Open the Chatbox app
2. Select a conversation and enter some text to get response suggestions 
3. The backend returns a very long (e.g. 200 characters) response title
4. Try to view the response suggestions and the Webview crashes

**Expected Results**  
Webview displays the long title response suggestions normally.

**Actual Results**  
Webview crashes when trying to display the long title, causing the app to crash as well.

**Screenshots**  
N/A

**Desktop (please complete the following information):** 
- Operating System: Windows 10 Home 
- Application Version: Chatbox 0.6.6

**Additional Context**  
This bug seems to only occur when the backend returns a longer (over 100-150 characters) title. Shorter titles display fine.  
This bug makes the app unusable in some situations and needs to be fixed urgently.

**Comment by Bin-Huang** [comment]
Regarding this issue, I have made specific optimizations in the latest version(https://github.com/Bin-Huang/chatbox/releases). Please upgrade and see if the problem is resolved. If the issue persists, feel free to reopen it.
