### ISSUE TITLE
[Feature] Conversation Folders for Organization and Archiving

### ISSUE THREAD

**Issue by hycxnas** [Bin-Huang/chatbox#894]
**Problem Description**
Currently all conversations in Chatbox exist in one long list which becomes difficult to manage when there are a large number of conversations. 

**Proposed Solution** 
Implement conversation archiving/grouping functionality:
- Allow users to create folders or groups to organize conversations
- Users can drag and drop conversations into these folders
- Each conversation can belong to multiple folders
- Folders should have naming, coloring, reordering capabilities
- Browsing and searching foldered conversations is easier

**Additional Context**  
Foldering can help users better organize large amounts of conversations and improve efficiency in finding and managing conversations. It also allows segmenting conversations by project, topic, client etc.
Overall, this feature can significantly optimize user workflow and experience.
For example, folders like "Client A", "Client B" can be created to separate conversations for different clients.

This is a highly demanded feature by many users. Implementing it in the next release would greatly increase user productivity and satisfaction. Please consider adding this capability.

**Comment by Bin-Huang** [comment]
It is already supported in the new version.
https://github.com/Bin-Huang/chatbox/releases
