### ISSUE TITLE
[Feature] Allow Customizable Max Tokens in Context

### ISSUE THREAD

**Issue by hycxnas** [Bin-Huang/chatbox#895]
**Problem Description**
There are projects like Claude API Converter that adapt Claude's API to be compatible with OpenAI's format and allow integrating Claude with services designed for OpenAI. However, Claude supports up to 100,000 max tokens, while Chatbox has a hardcoded limit of 32,000 tokens. This makes integrating Claude inconvenient.

**Proposed Solution**  
Implement an option for users to customize Chatbox's max tokens in context setting to better support Clara and other services. 

- Add "Max Tokens in Context" configuration
- Allow values up to 100,000 to match Claude's limit
- Save user's custom max tokens value
- Use custom value when making API requests

**Benefits**
- Enables smoothly integrating Claude via existing converter projects 
- Allows fully leveraging Claude's higher context capacity
- More flexibility for power users
- Improves extensibility with other services  

**Additional Context** 
Given projects enabling Claude integration, hardcoding the max tokens in Chatbox creates an artificial barrier. Adding this customization would improve compatibility and user experience.

**Comment by ishaan-jaff** [comment]
Hi i'm the maintainer of liteLLM - https://github.com/BerriAI/litellm/ 
We allow you to call claude (and 50+ LLMs) using OpenAI chatGPT inputs/outputs. 

We also provide a liteLLM proxy server, you can send your OpenAI requests to us but for model send 'claude-2', 'command-nightly' etc and we support it for you. 

I'd love to help make an integration if this is useful for this issue !😊

**Comment by Bin-Huang** [comment]
The configurations you mentioned are specifically optimized for the OpenAI API, and I feel that it could be challenging to redesign and modify them while maintaining the current state. However, in the latest version, I have added support for Claude, which might directly address your issue. https://github.com/Bin-Huang/chatbox/releases
