### ISSUE TITLE
[Feature]1、对话气泡左右区分。2、气泡样式区分更明显。3、对话内容内置搜索。

### ISSUE THREAD

**Issue by Fenhy** [Bin-Huang/chatbox#897]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.

**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.

**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.

-----------------------

**问题描述**
1、对话气泡左右区分。 黑夜模式下，我和机器人回答的颜色太近了，经常分不清。 然后只能翻头像。建议像聊天一样，区分左右气泡。
2、气泡样式区分更明显。 黑夜模式下，如果有更明显的样式来区分，就更好。
3、对话内容内置搜索。内置没有搜搜功能，问的多了，找不到之前的。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by Bin-Huang** [comment]
This feature has already been implemented. Give it a try after updating.
https://github.com/Bin-Huang/chatbox/releases
