### ISSUE TITLE
[Feature]输入框新增代码块

### ISSUE THREAD

**Issue by SmallNew2003** [Bin-Huang/chatbox#898]
**问题描述**
希望新增一个类似于slack这种的输入框代码块

**解决思路**
![CleanShot 2023-08-09 at 15 35 40@2x](https://github.com/Bin-Huang/chatbox/assets/51443903/aeee7b5f-5212-4101-8902-a52c3660f659)

**Comment by pandacase** [comment]
maybe u should try `Markdown`

**Comment by Bin-Huang** [comment]
建议在输入框中使用 markdown 格式，发送后会自动渲染。比如插入代码可以是：
```
\`\`\`\javascript
const i = 1;
\`\`\`\
```
