### ISSUE TITLE
[BUG] 关闭 alt + · 快捷键后，依旧被占用

### ISSUE THREAD

**Issue by mad462** [Bin-Huang/chatbox#899]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:
1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**
- Operating System: [e.g. macOS]
- Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

-------------------------------------

**Bug 描述**
alt + · 是我另一个软件的快捷键，当我打开 chatbox 的时候，alt + · 我另一个软件无法正常使用 alt + · ，即使关闭掉快捷键开关依旧无法生效，只有退出 chatbox 才恢复正常。

**桌面端（请填写以下信息）：**
- 操作系统：win10
- 应用程序版本：0.6.6

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
问题已经修复了，试着更新一下
