### ISSUE TITLE
希望能预置更多的prompts

### ISSUE THREAD

**Issue by ossplus** [Bin-Huang/chatbox#9]

**Comment by Bin-Huang** [comment]
你知道哪里可以找到一些高质量的prompts吗？或者你可以分享一些吗？

**Comment by ossplus** [comment]
> 你知道哪里可以找到一些高质量的prompts吗？或者你可以分享一些吗？

https://github.com/PlexPt/awesome-chatgpt-prompts-zh/blob/main/prompts-zh.json json格式，中文，还有 https://github.com/f/awesome-chatgpt-prompts/blob/main/prompts.csv csv格式，英文， 有这俩应该可以了

**Comment by HenMie** [comment]
> 你知道哪里可以找到一些高质量的prompts吗？或者你可以分享一些吗？

https://newzone.top/chatgpt/   这里的也不错，数量挺多，而且有中英文版本

**Comment by fastfading** [comment]
如何自己添加？    system  role 添加不了

**Comment by jiacheo** [comment]
> 

无法直接添加，目前有个方法，就是随便写一条，然后使用编辑功能，把第一条编辑成system role的，再把内容改成你自己的 pre prompt ，保存就好了。其他的再删掉。

**Comment by jiacheo** [comment]
> 如何自己添加？ system role 添加不了

无法直接添加，目前有个方法，就是随便写一条，然后使用编辑功能，把第一条编辑成system role的，再把内容改成你自己的 pre prompt ，保存就好了。其他的再删掉。

**Comment by Bin-Huang** [comment]
很早之前的版本已经实现了，可以更新一下，先关闭了
