### ISSUE TITLE
显示Open AI API Key的部分内容

### ISSUE THREAD

**Issue by imzjy** [Bin-Huang/chatbox#90]
分类：功能优化

Open AI 官网上显示的API Key类似

`sk-...zMOq`

这样的好处是每个应用可以使用不同的Key，方便再遇到问题的时候及时撤回对应API Key.

所以能在下面设置页面，添加同样的API Key Masking就更好了。

![openai_api_key_mask](https://user-images.githubusercontent.com/1628551/226506671-7b7a7e89-398c-4dc4-aab9-9f5a822dfdb2.png)

**Comment by Bin-Huang** [comment]
😊😊This feature has been implemented in the new version v0.6.3.
https://github.com/Bin-Huang/chatbox/releases

😊😊这个功能在新版本 v0.6.3 已经实现
https://github.com/Bin-Huang/chatbox/releases
