### ISSUE TITLE
[BUG]电脑开的全局能访问外网，网页版本也可以正常使用，chatbox里面使用时提示Network Error: Failed to fetch

### ISSUE THREAD

**Issue by OneHourOneMinute** [Bin-Huang/chatbox#903]
**Bug 描述**
MBP 系统10.13.6，安装版本0.6.6；电脑能访问外网，网页版本的https://chat.openai.com/auth/login，登录进去后可以正常使用；手机端也可以正常使用。但是chatbox里面使用时提示Network Error: Failed to fetch，然后使用浏览器访问https://api.openai.com 提示“使用了不受支持的协议 ERR_SSL_VERSION_OR_CIPHER_MISMATCH”

**期望结果**
希望能正常使用，或者弄清楚原因，比如是否因为电脑系统版本太低，SSL协议不一致导致的。

**桌面端（请填写以下信息）：**

-   操作系统：macOS10.13.6 
-   应用程序版本：0.6.6

**Comment by Bin-Huang** [comment]
应该是设置的域名写错了

**Comment by OneHourOneMinute** [comment]
域名是选择了openai之后 默认的https://api.openai.com

**Comment by OneHourOneMinute** [comment]
发现了 如果选择**美国的节点**就会报 “Network Error: Failed to fetch”的错误
但是选择其他的节点又会报API Error: {"error":{"message":"You exceeded your current quota, please check your plan and billing details.","type":"insufficient_quota","param":null,"code":"insufficient_quota"}}
按照你的文档来看，是我账号没绑卡的问题，但是我的免费额度是还有的，而且我的手机端APPStore下载的官方的 是可以正常使用的。

**Comment by Bin-Huang** [comment]
错误信息的意思就是没有额度了。你可能把 150 美金看成免费额度了，那个是你的消费配额，不是免费额度。
