### ISSUE TITLE
[Feature] Smooth scrolling

### ISSUE THREAD

**Issue by not-that-nda** [Bin-Huang/chatbox#904]
One of the most annoying things of working with chat GPT and to some extent with this totally amazing app is that the windows scroll one line at the time making it very hard to keep reading the message as it is generated.

It would be great if the main chat was scrolling smoothly as the chat is being generated even when a line is added it will smoothly catch up, ideally at a steady peace, at worst when a new line appears it will smoothly scroll up, not just scroll a full line.

If not there should be a UI option toggle to turn autoscroll of.

Thanks for this awesome extension!

**Comment by Bin-Huang** [comment]
Regarding this issue, I have made specific optimizations in the latest version(https://github.com/Bin-Huang/chatbox/releases). Please upgrade and see if the problem is resolved. If the issue persists, feel free to reopen it.
