### ISSUE TITLE
[Feature] Improved copying

### ISSUE THREAD

**Issue by not-that-nda** [Bin-Huang/chatbox#905]
I would love to have two things for copying as text is being generated:

1. when the code block is finished even if the bot continues to talk the copy button should appear and be clickable on the top right corner.
2. when the text is being generated you should be able to select any part of the partially generated text to copy paste it. Right now whenever you do this it selects everything from the start of the message every line that is created.

Thanks!

**Comment by Bin-Huang** [comment]
These features were all implemented in the last version. Upgrade and check it out! 😊
