### ISSUE TITLE
搜索功能 [Other]

### ISSUE THREAD

**Issue by SJX1994** [Bin-Huang/chatbox#908]
之前的搜索功能没有了

**Comment by hb-0** [comment]
支持，这功能太重要了，多问几次就很难找到了。

**Comment by gzlboy** [comment]
正要提问，这个搜索经常用，怎么去掉了呢

**Comment by Bin-Huang** [comment]
This feature has already been implemented. Give it a try after updating.
https://github.com/Bin-Huang/chatbox/releases
