### ISSUE TITLE
[Other]请问源码是否有所保留

### ISSUE THREAD

**Issue by wuxiaobu** [Bin-Huang/chatbox#913]
想请教一下。我用[v0.6.6](https://github.com/Bin-Huang/chatbox/releases/tag/v0.6.6) 版本源码本地编译出来的chatbox，对比直接下载的v0.6.6版本chatbox功能少了很多，请问是不是源码有所保留

**Comment by Bin-Huang** [comment]
[#294](https://github.com/Bin-Huang/chatbox/issues/767)
