### ISSUE TITLE
[Feature] Use a custom API endpoint

### ISSUE THREAD

**Issue by boromyr** [Bin-Huang/chatbox#914]
**Problem Description**
Ability to add a custom endpoint API as in BetterChatGPT. This will give much more flexibility for many users to be able to use this app.

**Comment by Bin-Huang** [comment]
<img width="591" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/20723142/b95f4729-c63e-4c45-ae48-0d7204bd1399">
If I understand correctly, you are referring to the configuration of API HOST. This has actually been supported since the early versions of Chatbox.☺️
