### ISSUE TITLE
[Feature] azure openai 支持多个 deployment，实现 gpt3.5/gpt4 同时服务

### ISSUE THREAD

**Issue by chinyajie** [Bin-Huang/chatbox#917]
**问题描述**
目前一旦使用 azure open api 接口，需要指定 deployment，那么要么支持 gpt3.5，要么 gpt4， 不能同时支持两个。

**解决思路**
配置参数的时候支持部署多个 deployment，或者简单的通过 ; 或者 , 支持多个 deployment id

**Comment by Bin-Huang** [comment]
现在应该可以通过会话专属设置来实现？

**Comment by Bin-Huang** [comment]
其实也可以这样，一个会话里设置成 4 的 deployment，一个会话设置成 3.5 的 deployment。我之前也是这么使用的～～

**Comment by chinyajie** [comment]
> 现在应该可以通过会话专属设置来实现？

感谢您的回复。但是我这边看到的 deployment 设置是全局的，如何才能分对话设置不同参数。

**Comment by chinyajie** [comment]
> 可能你的版本比较老，升级到最新版本，然后点击会话标题，打开会话专属设置

学会了。太棒了。谢谢你开发了这么好的产品。
