### ISSUE TITLE
[Feature] Web Version Release

### ISSUE THREAD

**Issue by sam1am** [Bin-Huang/chatbox#918]
Do you have plans to release the web version for self-hosting? 
Thanks.

**Comment by Bin-Huang** [comment]
There are currently no plans to provide a web version of Docker deployment. I understand that some people have the idea of deploying within their teams, but I also found that many people would set up fake websites and spread them on social media (often for the purpose of stealing API keys). Related examples can be seen in other issues. Therefore, I have no plans to provide Docker deployment for the time being, but this may change in the future. For those who need to deploy within their team, you can try other open-source projects, they are doing great.
