### ISSUE TITLE
[Feature] Add support for Open Router

### ISSUE THREAD

**Issue by Ezaki29** [Bin-Huang/chatbox#919]
Open Router (https://openrouter.ai/) is a service that gives you access to LLM models that you normally won’t have access to (GPT-4 32K, Google PaLM, Anthropic, etc.)

**Comment by Bin-Huang** [comment]
In the v1.0.0 version, you can try using the OpenAI Custom Model feature, which actually supports Openrouter as well.

**Comment by Ezaki29** [comment]
I am having trouble getting it to work. Is there a tutorial available? For example, I am trying to use Claude-2. I have already obtained OpenRouter's key and pasted it into the "OpenAI API Key" field. For "API Host," I entered https://openrouter.ai/api/v1/chat/completions. The custom model name is "anthropic/claude-2".

In other chat apps, I usually add custom headers like this:

Authorization: Bearer $OPENROUTER_API_KEY
HTTP-Referer: $SITE_URL
X-Title: $SITE_NAME

**Comment by Bin-Huang** [comment]
Just change the API Host to https://openrouter.ai

**Comment by jerrylususu** [comment]
I know this is an old issue but i recently ran into the same problem. Since Openrouter requires a `HTTP-Referer` header to be set, just changing API Host won't suffice. I have to use a third party tool called `mitmproxy` to modify the outgoing request. Here is what I come up with.

1. In Chatbox, create a new chat, and specify the model to be `provider=openai`, `model=custom`, and set the model name to `my_debug_model` (or some other name you like)
2. Create a file called `openrouter.py` and fill it with the following content
```python
import json
from mitmproxy import http

def request(flow: http.HTTPFlow) -> None:
    if flow.request.host == "api.openai.com" and flow.request.method == "POST" and flow.request.headers.get("content-type", "").startswith("application/json"):
        try:
            request_data = json.loads(flow.request.get_text())
            if request_data.get("model") == "my_debug_model": # the special model name
                flow.request.path = "/api/v1/chat/completions"
                flow.request.host = "openrouter.ai"
                flow.request.headers["authorization"] = "Bearer sk-or-xxxxxxxxxxxxx" # openrouter token
                flow.request.headers["http-referer"] = "http://localhost:8080" # whatever you want

                request_data["model"] = "anthropic/claude-instant-v1"               
                flow.request.set_text(json.dumps(request_data))
                pass
        except json.JSONDecodeError:
            pass

def responseheaders(flow):
    """
    Enables streaming for all responses.
    This is equivalent to passing `--set stream_large_bodies=1` to mitmproxy.
    """
    flow.response.stream = True
```
3. Run the script with the following command (if you don't need upstream proxy, you may delete the related part)
```
mitmweb --mode upstream:http://{upstream_addr} -s openrouter.py
```
4. Set chatbox to use `mitmproxy`'s proxy at `http://localhost:8080`
5. Now use the special chat created in step 1, and the request should be rerouted to openrouter.

**Comment by Bin-Huang** [comment]
@jerrylususu 

😄Thanks for your share. In fact, Chatbox has already taken care of the 'HTTP-Referer' header you mentioned. I believe I added this optimization about five or six versions ago. Therefore, you can directly use Chatbox to connect with OpenRouter. All you need to do is change the API Host to 'https://openrouter.ai'. And remember to pay attention to the prefix of the model name. For instance, if you want to use gpt-4, then on OpenRouter it should be 'openai/gpt-4'. You will need to set this in Chatbox's customized model name.

**Comment by jerrylususu** [comment]
@Bin-Huang 
Thanks for your reply! Indeed, I tried the following setting for OpenRouter and it works:
1. set api endpoint to `https://openrouter.ai/api`
2. fill the api key using OpenRouter's api key
3. set model provider to OpenAI and model name to custom model, then fill the model name using openrouter model id (e.g. `openai/gpt-3.5-turbo`)

From the proxy log, the `HTTP-Referer` header is correctly added with value of `http://localhost:3000`. 

Still, I am wondering which commit or what part of the code implements this behavior. I did some search in the code base, using terms such as `http-referer` and `referer`, yet failed to find related code. Besides, when using other api endpoints beside OpenRouter, the `http-referer` header won't be set (according to my proxy log). I am very curious what is happening here. It would be great if you can guide me to the relevent code.

**Comment by rodion-m** [comment]
@Bin-Huang It'll be great to add an ability to set my own AI providers list. Now if I want to use OpenRouter's Claude model for example, I have to replace an existed configuration of OpenAI provider and when I want to switch back to OpenAI I have to replace settings again, it's not convenient. Please consider moving providers list configuration into separate file for example, like apps like continue do.

**Comment by carstenuhlig** [comment]
If anyone is interested, I also attempted this and was blocked. After researching the issue, I discovered that the correct URL for OpenRouter is now https://openrouter.ai/api/v1/chat/completions. So in general, first check the documentation of any provider (e.g. litellm, together.ai, ...) to see if they offer an OpenAI style API and then determine the correct API endpoint.

**Comment by Bin-Huang** [comment]
For everyone who needs help accessing OpenRouter in Chatbox: Chatbox works well with OpenRouter, and here are the specific steps you can follow:

1. Add a custom model provider in the settings, and you can name it ‘openrouter’.
3. Enter 'https://openrouter.ai' for the api host.
4. Enter '/api/v1/chat/completions' for the api path.
5. Enter your key from OpenRouter in the api key field.
6. Specify the model you need in the model field, like 'gpt-4o'.

<img width="646" alt="2024-07-28 10 39 27" src="https://github.com/user-attachments/assets/f3852b08-f737-45b5-a838-f2758345fe6e">
<img width="631" alt="2024-07-28 10 39 41" src="https://github.com/user-attachments/assets/6f77e1cd-9ad6-44cd-b7f1-011df68b3a84">

**Comment by endolith** [comment]
Can you just add native support for OpenRouter so we don't need to do all this manual setup?  :/

**Comment by attid** [comment]
please add https://openrouter.ai/
or give an opportunity to specify several models in one api, or better that it can get all the models from the server.

**Comment by Bin-Huang** [comment]
> please add https://openrouter.ai/ or give an opportunity to specify several models in one api, or better that it can get all the models from the server.

@attid Actually, You can easily add multiple models in one API - just type in the model name field and you'll see an "add as option" button appear. You can add as many model options as you want to the same model provider.

**Comment by benzntech** [comment]
We add this to code so that we can add only the api key. Here is the reference 
https://github.com/OpenRouterTeam/openrouter-examples

**Comment by kirilligum** [comment]
any way to add a provider? I want to use the non GPU faster one like cerebras groq or sambanova because they are 10x faster sometimes. open router is asking for a provider option

**Comment by alexey-skoblin** [comment]
> * Add a custom model provider in the settings, and you can name it ‘openrouter’.
> * Enter 'https://openrouter.ai' for the api host.
> * Enter '/api/v1/chat/completions' for the api path.
> * Enter your key from OpenRouter in the api key field.
> * Specify the model you need in the model field, like 'gpt-4o'.

Add instruction in readme
https://github.com/chatboxai/chatbox/issues/919#issuecomment-2254321065
