### ISSUE TITLE
[BUG] Chatbox window freezes when maximizing app, until text generation finishes.

### ISSUE THREAD

**Issue by elendil7** [Bin-Huang/chatbox#921]
## Bug Description
During a Chatbox chat text being generated (e.g., chatgpt response being displayed line by line), if I maximize the window or change the window's dimensions, the app will have no visual cues (will freeze) until the text is fully generated. Then, screen gets updated like normal.

## Steps to Reproduce
1. Open Chatbox.
2. Start generating text.
3. While text is generating, click "maximize" button or drag window edge to increase width/height.
4. Program should freeze until text is fully generated. Then goes back to normal.

## Expected Results
Expect application to temporarily stop generating the text (on window resize), then adjust the text scaling so it can keep generating smoothly even with the new window dimensions.

### When clicking on **maximize** button (top right corner of window), app freezes until I undo the maximization by clicking the same button, or the text finishes generating.
![image](https://github.com/Bin-Huang/chatbox/assets/80429382/3dee6303-f901-43d6-840f-85f6cde5b403)

## Desktop 

-   Operating System: Windows 10 Pro
-   Application Version: @latest

**Comment by Bin-Huang** [comment]
Very interesting bug, I'll try to reproduce it.☺️

**Comment by Bin-Huang** [comment]
Does this issue still exist in v1.0.0?

**Comment by elendil7** [comment]
> Does this issue still exist in v1.0.0?

Its been fixed, thank you. Now much more smooth, with only a small amount of lag when dragging the window.
