### ISSUE TITLE
[Feature] Fine tuning and file uploading interfacing.

### ISSUE THREAD

**Issue by davidleebooth** [Bin-Huang/chatbox#923]
Imagine beneath copilots a file upload interface where you can upload/delete files for your organization and then set Copilots to use them. OpenAI just updated fine tuning recently too. An application like chatbox with a fine tuning file-checker/uploading/deletion GUI and the ability for Copilots to use those fine tuned models would be very cool.

**Comment by Bin-Huang** [comment]
File upload is now available in Chatbox! You can start using it right away.
