### ISSUE TITLE
[Feature] Input field to enter the Azure Deployment Name when specifying a specific model for each conversation.

### ISSUE THREAD

**Issue by QuynhVir** [Bin-Huang/chatbox#927]
**Problem Description**
I yearn for the capability to finely adjust the specific model parameters for individual conversations when utilizing Azure OpenAI API as an AI Model Provider. At present, it manifests as a select menu that is exclusively compatible with OpenAI API, lacking a field to input the Azure Deployment Name.

**Proposed Solution**
I aspire to replace the select menu with an input field to enter the Azure Deployment Name when specifying a specific model for each conversation.

**Additional Context**
![Screenshot 2023-08-24 at 11 10 18](https://github.com/Bin-Huang/chatbox/assets/20403550/b78d14b5-fe64-4341-b6fe-4ff75cd9c280)

**Comment by Bin-Huang** [comment]
It seems like a bug and I will fix it soon.

**Comment by Bin-Huang** [comment]
Fixed in v1.0.0
