### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JSCSZZSS** [Bin-Huang/chatbox#929]
网络配置都正常，https://chat.openai.com/，chat官网可以进对话也没问题
但是chatbox报错Network Error: Failed to fetch
网络错误。请检查当前的网络状态，以及与 https://api.openai.com 的连接情况。
![屏幕截图 2023-08-25 025016](https://github.com/Bin-Huang/chatbox/assets/82312229/ac207b04-8b6d-4389-aae5-d4ce7edf829e)

![屏幕截图 2023-08-25 025342](https://github.com/Bin-Huang/chatbox/assets/82312229/50876447-ae5b-492a-87d1-92fdc245127a)
-   操作系统：[win10]
-   应用程序版本：[6.8]

**Comment by Bin-Huang** [comment]
大陆地区需要专门的网络～～～

**Comment by Bin-Huang** [comment]
可能和你的网络工具有关，也许设置里的网络设置可以帮助到你
