### ISSUE TITLE
Problem with search function Ctrl + F

### ISSUE THREAD

**Issue by benkyouu** [Bin-Huang/chatbox#930]
Just wanted to give you a heads up that the Ctrl + F search function in the latest software update seems to be broken. It used to be super handy for finding stuff quickly, but now it's not working at all. Thanks a bunch!

**Comment by Fenhy** [comment]
一样的问题，一样的需求。

**Comment by Flow-sandyu** [comment]
#https://github.com/Bin-Huang/chatbox/issues/881
the same issue, but haven't be solved yet

**Comment by Bin-Huang** [comment]
This feature has already been implemented. Give it a try after updating.
https://github.com/Bin-Huang/chatbox/releases
