### ISSUE TITLE
[Feature] Backup of Chatbox to local file / cloud

### ISSUE THREAD

**Issue by elendil7** [Bin-Huang/chatbox#932]
As per the title, it would be convenient to be able to export chatbox configuration files, and import them on a fresh install if needed.

Config files would include:
- All chatbox settings (AI model, max tokens, max context, display settings, chat settings, etc)
- Custom copilots user has created

Config files would likely need to exclude:
- API keys

**Comment by zxzixuanwang** [comment]
I updated it by yay again uncarefully， i miss all data again. So it will prevent me to update it.

**Comment by Bin-Huang** [comment]
This feature has already been implemented. Give it a try after updating.
https://github.com/Bin-Huang/chatbox/releases

**Comment by elendil7** [comment]
Very nice 🚀
