### ISSUE TITLE
Wish to support multi APIkeys for different chat windows.

### ISSUE THREAD

**Issue by PythonYunfei** [Bin-Huang/chatbox#933]
GPT4 is good at writing codes, while Claude2 is better at writing articles and translating.
So, I Wish to support multi APIkeys for different chat windows. Then, different chat windows could be grouped by different kinds of APIkeys.

**Comment by Bin-Huang** [comment]
Actually, this feature is already available in the previous update. You can now create different model providers for multiple APIs, making it super easy to manage and switch between them.
