### ISSUE TITLE
add voice control and tts

### ISSUE THREAD

**Issue by fastfading** [Bin-Huang/chatbox#94]
https://chrome.google.com/webstore/detail/voice-control-for-chatgpt/eollffkcakegifhacjnlnegohfdlidhn

this externsion used google tts
edge tts is better  https://github.com/rany2/edge-tts

**Comment by JackyWay** [comment]
good suggestion, if the desktop app can caupture our voice(voice input) + TTS, we can start a conversation with AI more smoothly.

**Comment by Bin-Huang** [comment]
Thanks for the info! This issue is already tracked in #1239, so I'll close this to avoid duplicates. Feel free to add more thoughts there!

为了简化管理，后续相关讨论请挪步到 #1239。这条 issue 先关闭了～～
