### ISSUE TITLE
chatboxai.app service down?

### ISSUE THREAD

**Issue by XXXL3J** [Bin-Huang/chatbox#946]
Continuous error with MacOS desktop app and web app: 
Network Error: Failed to fetch
... Check the connection with  https://chatboxai.app

Tried switching networks the problem still exists
Other web services is working fine

**Comment by EricYangCn** [comment]
Network Error: Failed to fetch

网络错误。请检查当前的网络状态，以及与 https://chatboxai.app 的连接情况。

**Comment by XXXL3J** [comment]
The service seems to be restored

**Comment by XXXL3J** [comment]
The service seems to be restored

**Comment by XXXL3J** [comment]
`API Error: {"error":{"code":"system_error","detail":"Server error. Try again later.","status":500,"title":"Server Error"}}`

Again recently

**Comment by Bin-Huang** [comment]
Is the issue still present? I believe it might just be temporarily affected by the deployment.
请问问题还存在吗？我想应该只是短暂受到了发布部署的影响

**Comment by fg0578fg0578** [comment]
Hi @Bin-Huang 
I also faced the same issue today while 1 minute ago it was functionally correct

<img width="575" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/88201416/7e9dcda3-3925-456a-a87d-f029f1e71161">

**Comment by OUCliuxiang** [comment]
Same error running on MacOS(M1), occurs after national day festival.

**Comment by OUCliuxiang** [comment]
> Same error running on MacOS(M1), occurs after national day festival.

Problem resolved @ version 1.0.4
