### ISSUE TITLE
请求增加，批量导入API

### ISSUE THREAD

**Issue by nu0l** [Bin-Huang/chatbox#947]
**问题描述**
APIKEY经常失效

**解决思路**
类似于代理池？批量导入API并检测是否可用？

**附加上下文**

<img width="941" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/54735907/30825a47-ea54-46a3-936e-bab42cfe355c">
<img width="682" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/54735907/3a0c21ba-8528-4a75-8ea2-0317253d17ed">

**Comment by Bin-Huang** [comment]
感觉这不是其他大多数人的需求～～～
