### ISSUE TITLE
[Feature] Shortcut Key to 'Clear Chat History' and Confirmation Dialog

### ISSUE THREAD

**Issue by kaedei** [Bin-Huang/chatbox#949]
**Problem Description**
I frequently need to clear my chat history and reset the state. However, the clear button is located at the top right corner, which can be inconvenient as it requires moving the mouse all the way there to click it.

**Proposed Solution**
I would like to suggest adding a shortcut key to clear the current chat history. Ctrl+D might be a good option for this.
![image](https://github.com/Bin-Huang/chatbox/assets/2949960/04d63942-53a9-4b98-954d-f200a8fb941f)

Currently, the "Clean it up" button in the pop-up window does not support confirmation through the Enter key. It would be great if keyboard shortcuts could be used to operate this button.
![image](https://github.com/Bin-Huang/chatbox/assets/2949960/059cb44d-561f-473e-ab70-c910cd8b610b)

**Comment by Bin-Huang** [comment]
This issue might be outdated with the version update, as you can now use the context cleanup feature.
