### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by spark8899** [Bin-Huang/chatbox#95]
pnpm install

pnpm start:react
`
Failed to compile.

Module not found: Error: Can't resolve 'katex/dist/katex.min.css' in '/Users/packer/Documents/github/chatbox/src'
ERROR in ./src/Block.tsx 19:0-34
Module not found: Error: Can't resolve 'katex/dist/katex.min.css' in '/Users/packer/Documents/github/chatbox/src'

ERROR in ./src/StyledMenu.tsx 5:0-34
Module not found: Error: Can't resolve 'katex/dist/katex.min.css' in '/Users/packer/Documents/github/chatbox/src'

webpack compiled with 2 errors
No issues found.
`

**Comment by JuctTr** [comment]
同样遇到这个问题，安装一下 rust 就可以了
`curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh`
参考链接：[When I install and run Tauri on Mac OS Monterey I get immediate error](https://stackoverflow.com/questions/75013520/when-i-install-and-run-tauri-on-mac-os-monterey-i-get-immediate-error)
