### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by Shuimojiangshan** [Bin-Huang/chatbox#950]
API Error: {"error":{"message":"Incorrect API key provided: : sk-lXk*****************************************8aHE. You can find your API key at https://platform.openai.com/account/api-keys.","type":"invalid_request_error","param":null,"code":"invalid_api_key"}}

遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

**Comment by Bin-Huang** [comment]
你的 key 不正确……

**Comment by Kevin12138-GitHub** [comment]
遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

API Error: Status Code 404, { "error": { "message": "The model `gpt-3.5-turbo-16k-0613` has been deprecated, learn more here: https://**************", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }
![屏幕截图 2024-06-18 211338](https://github.com/Bin-Huang/chatbox/assets/173167452/02d752ee-2fce-4a12-b521-d2a0745ef0b9)
这个怎么解决啊，之前一直都可以使用，用了一年多了？？？？？
