### ISSUE TITLE
[Feature]订阅Chatbox-Al后，给到五台设备使用量，但在服务端无法取消失效设备

### ISSUE THREAD

**Issue by neosun100** [Bin-Huang/chatbox#954]
**Problem Description**
Please describe the issue or difficulty you are experiencing and why it makes using the software difficult or frustrating.
订阅Chatbox-Al后，给到五台设备使用量，但在服务端无法取消失效设备
**Proposed Solution**
Please provide a clear and concise description of what you would like to see in terms of a function or solution.
能够提供在服务端管理设备订阅
**Additional Context**
Please provide any additional context or information that would help better understanding your feature request, such as screenshots, examples, or use cases.
<img width="803" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/13846998/edc7088e-3bac-468c-a8ff-5bf900aa254b">

---

**问题描述**
请描述您遇到的问题或难题，以及为什么这使得使用软件变得困难或令人沮丧。

**解决思路**
请提供一个清晰、简洁的描述，说明您希望看到的功能或解决方案。

**附加上下文**
请提供任何其他上下文或信息，以便更好地理解您的功能请求，例如截图、示例或用例。

**Comment by neosun100** [comment]
<img width="557" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/13846998/992418e5-bcae-41c1-b0a8-730182b82ed1">
点击不生效，无法取消

**Comment by Bin-Huang** [comment]
这个和 lemonsqueezy 平台有关，可以过段时间再试一下？
