### ISSUE TITLE
[BUG] Different model used than selected in the app.

### ISSUE THREAD

**Issue by debitCredit** [Bin-Huang/chatbox#955]
**Bug Description**
With gpt-4 model selected the OpenAI usage shows calls being made to "gpt-4-0613" model instead

**Expected Results**
Expect for the model choice in the app be respected.

**Actual Results**
As above

**Screenshots**
[App](https://i.imgur.com/TlI5s03.png)
[OpenAI](https://i.imgur.com/skpHbjQ.png)

**Desktop (please complete the following information):**

-   Operating System: Windows 
-   Application Version: 1.0.0

**Additional Context**
As above

**Comment by Bin-Huang** [comment]
Actually, these two models are currently equivalent to OpenAI.
