### ISSUE TITLE
[BUG] config save incorrect

### ISSUE THREAD

**Issue by ds6ga6** [Bin-Huang/chatbox#956]
**Bug Description**
When switching models and setting message limits and token quantities, there may be a problem where the message limit and token quantity cannot be saved correctly.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

1. Click on settings (设置)
2. set model from "gpt4" to "gpt-3.5-turbo", set maximum limit of messages (上下文的消息数量上限) to 0
3. click on save, then you would see maximum limit of messages changed to no-limit inteads of 0 (max tokens has the same bug)

**Expected Results**
save maximum limit of messages and max tokens correct

**Actual Results**
![image](https://github.com/Bin-Huang/chatbox/assets/48852355/fa2b61d6-6413-4141-8c53-2f8d36fd26c7)

after click save, and open config again

![image](https://github.com/Bin-Huang/chatbox/assets/48852355/a660e6a2-f4e4-4965-b1fe-e2ede4d146e1)

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**

-   Operating System: [e.g. Windows11]
-   Application Version: [e.g. 1.0.0]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

**Comment by Bin-Huang** [comment]
This has been fixed in version v1.0.2
https://github.com/Bin-Huang/chatbox/releases
