### ISSUE TITLE
[Feature] 多模型切换

### ISSUE THREAD

**Issue by pokerFace233** [Bin-Huang/chatbox#959]
**问题描述**
目前设置中只能去设置一个模型的key信息，如果需要切换模型时不太方便

**解决思路**
可以保存多个模型的信息，提供一个创建会话时的默认模型。并且可以针对单独的会话去修改所用到的模型

**Comment by Bin-Huang** [comment]
点击下标题，应该可以看到会话的模型设置

**Comment by liushuainudt** [comment]
> 下标题，应该可以看到会话的模型设置

因现在模型有gpt3.5  gpt4 gpt4 8k gpt4v等等不同的模型，可否支持比如微软云可以保存多个模型的功能，而无需临时再去修改，只需切换即可

**Comment by songjinghe** [comment]
确实需要，因为在目前大模型快速发展，百花齐放的时期，大家都愿意比较一下，比如同一个输入，看看不同模型的输出是什么。然后挑个最满意的出来~

**Comment by Bin-Huang** [comment]
File upload is now available in Chatbox! You can start using it right away.
