### ISSUE TITLE
The model: `gpt-4-32k-0314` does not exist

### ISSUE THREAD

**Issue by sunyifei83** [Bin-Huang/chatbox#96]
在设定中设置model为gpt-4-32k-0314后因为api没有权限，调整回gpt-3.5-turbo 和尝试reset均报错如下，重打开也无效

报错内容：

API Request Failed:

Error from OpenAI: 404  {
    "error": {
        "message": "The model: `gpt-4-32k-0314` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}

**Comment by sunyifei83** [comment]
删除对应的chat,新建一个chat后输入返回回复正常

**Comment by Bin-Huang** [comment]
可能和设置有关，先关闭了哈
