### ISSUE TITLE
新版1.0.2 自定义OpenAI API突然网络错误

### ISSUE THREAD

**Issue by lxt20180608** [Bin-Huang/chatbox#963]
**Bug 描述**

使用了 [cf-openai-azure-proxy](https://github.com/haibbo/cf-openai-azure-proxy)项目部署在CloudFlare上，在1.0.0版本上使用该自定义api完全没有问题，升级1.0.2之后突然报错：

Network Error: Failed to fetch

网络错误。请检查当前的网络状态，以及与 https://xxxx.*******69.workers.dev 的连接情况

而直接使用Azure OpenAI API没有问题，且经过测试，该自定义API在另一个项目 ChatGPTBox（一款浏览器插件）上没有问题，可以正常使用。麻烦开发大佬查看下是否属于bug？因为Azure OpenAI API没有打字机效果，还是更习惯打字机的效果，所以想使用自定义的API。

感谢。期待回复。

**Comment by wesmile8** [comment]
我也是一样的问题，刚更新1.0.2，显示网络错误，api测试没问题

**Comment by CyanWoods** [comment]
Network Error: Failed to fetch

网络错误。请检查当前的网络状态，以及与 https://api.openai.com 的连接情况。

**Comment by CyanWoods** [comment]
> > Network Error: Failed to fetch
> > 网络错误。请检查当前的网络状态，以及与 https://api.openai.com 的连接情况。
> 
> 已经确认不是网络问题

我的意思是，我也有这种情况。

**Comment by JadeL-Kemo** [comment]
我发生了同样的问题, 在我倒退版本时, 依旧会自动重新更新到最新版, 只能彻底删除后重新安装, 因为不能禁止更新

**Comment by Bin-Huang** [comment]
稍等，马上发布修复版本

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/tag/v1.0.3

大家试试这个修复版本，看看有没有解决问题。 @lxt20180608 @CyanWoods @wesmile8 @JadeL-Kemo 

如果问题解决了也烦请说一声～～～～

**Comment by JadeL-Kemo** [comment]
> https://github.com/Bin-Huang/chatbox/releases/tag/v1.0.3
> 
> 大家试试这个修复版本，看看有没有解决问题。
> 
> 如果问题解决了也烦请说一声～～～～

我的问题得到了很好的解决, 十分感谢

**Comment by CyanWoods** [comment]
> https://github.com/Bin-Huang/chatbox/releases/tag/v1.0.3
> 
> 大家试试这个修复版本，看看有没有解决问题。 @lxt20180608 @CyanWoods @wesmile8 @JadeL-Kemo
> 
> 如果问题解决了也烦请说一声～～～～

现在问题解决了，能正常使用。感谢大佬。

**Comment by lxt20180608** [comment]
> https://github.com/Bin-Huang/chatbox/releases/tag/v1.0.3
> 
> 大家试试这个修复版本，看看有没有解决问题。 @lxt20180608 @CyanWoods @wesmile8 @JadeL-Kemo
> 
> 如果问题解决了也烦请说一声～～～～

已解决，感谢大佬。

**Comment by 20150122041** [comment]
还是不行啊(。・∀・)ノ

**Comment by CMakey** [comment]
this question is happened at day 2024/02/01, I Download the 1.2.2 version and app notice me there is a new version could install, but I couldn't use openapi to get answer .the error came out 'Network Error: Failed to fetch'

After reinstall version 1.2.2 , this question solved .

**Comment by 20150122041** [comment]
收到
