### ISSUE TITLE
chatbox结果出来完毕后仍然有很长一段时间卡顿[Other]

### ISSUE THREAD

**Issue by yuhulian** [Bin-Huang/chatbox#965]
回答结果出来完毕后，仍然有很长一段时间卡顿和锁定，不能复制，也不能在对话框输入，导致使用体验非常糟糕。

希望能够优化这个这个锁定，让整体显得更加的流畅顺滑。

**Comment by kieeo** [comment]
作者没响应啊

**Comment by Bin-Huang** [comment]
指的是回答完毕后的卡顿吗？一般和网路或服务有关，请问你是用的是什么服务？是 OpenAI 官方的还是？

**Comment by yuhulian** [comment]
感觉和网络没有关系，你可以找个电脑实际测试一下，每次token流式输出的时间内，感觉做什么动作都很困难，在答案已经全部输出完毕的一段时间内，整个窗口好像被冻结了一样，非常卡顿，无法操作，想去拷贝一个什么文字，必须要等这个卡顿期结束才行，感觉这个和流式输出有关系，但是应该是可以解决的，因为非常早期的版本就没有该问题。我现在经弃用了chatbox，改用自己搭建的一个开源服务了，因为非常流畅，几乎没有卡顿。

**Comment by yuhulian** [comment]
<img width="1190" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/3038902/eac69829-4eed-47da-966f-0c8ada08a5f3">
问题答案已经出来半天了，但是状态仍然显示在输出，这个状态检查不知道是什么情况没有及时更新，导致后面也无法打字提新的问题。后面的输入框一直锁定，哪怕是输入不锁定，发送按钮锁定，也会好很多。

**Comment by Bin-Huang** [comment]
是什么版本呢？我记得是从来不锁定输入框和发送按钮的。

**Comment by Bin-Huang** [comment]
Looks like this issue might be from an older version. If you're still seeing the problem in the latest release, go ahead and reopen this!

随着版本的更新，这个 issue 可能过时了。如果最新版本依然存在这个问题，请随时重新开启这个 issue
