### ISSUE TITLE
[BUG] 付费的 Chatbox-API，今天使用服务器返回 500

### ISSUE THREAD

**Issue by shengbeiniao** [Bin-Huang/chatbox#967]
**Bug Description**

API Error: {"error":{"code":"system_error","detail":"Server error. Try again later.","status":500,"title":"Server Error"}}

遇到了来自 Chatbox-AI 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

**Screenshots**

![image](https://github.com/Bin-Huang/chatbox/assets/3301995/fe252fd3-6165-4374-97d7-c0c4785f0816)

**Desktop (please complete the following information):**

-   Operating System: [e.g. macOS]
-   Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

---

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：

1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**

-   操作系统：windows 10
-   应用程序版本：1.0.3

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
还有这个问题吗？应该是因为发版本导致的短暂问题
