### ISSUE TITLE
[BUG]API Error

### ISSUE THREAD

**Issue by boohsia** [Bin-Huang/chatbox#969]
更购买了许可证，一直提示API Error: {"error":{"code":"license_inactived","detail":"License Inactived","status":401,"title":"License Inactived"}}

遇到了来自 Chatbox-AI 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，或者[点击这里查看常见问题文档](https://chatboxai.app/redirect_app/faqs/zh-Hans)。

**Comment by OLDDAI** [comment]
我以为就我这样

**Comment by Bin-Huang** [comment]
可以把登记邮箱或者 license 发到 hi@benn.app ，一般是因为过期了。

**Comment by Su-Sly** [comment]
> 可以把登记邮箱或者 license 发到 [hi@benn.app](mailto:hi@benn.app) ，一般是因为过期了。

似乎并不是因为过期了，以为重新买也不行，同一个key用在windows端可以在mac端不行

**Comment by undefine4080** [comment]
> 可以把登记邮箱或者 license 发到 [hi@benn.app](mailto:hi@benn.app) ，一般是因为过期了。

我刚买到一个新 key ，但是也遇到上面的 error message，刚把注册邮箱发到了你指定的地址，期待问题能解决，谢谢！

**Comment by Su-Sly** [comment]
> > 可以把登记邮箱或者 license 发到 [hi@benn.app](mailto:hi@benn.app) ，一般是因为过期了。
> 
> 我刚买到一个新 key ，但是也遇到上面的 error message，刚把注册邮箱发到了你指定的地址，期待问题能解决，谢谢！
没用兄弟，猜你也是Mac平台吧？解决方案就是完整卸载重新安装，再激活key就行了，代价就是失去了所有的对话...很显然，是一个恶性bug

**Comment by undefine4080** [comment]
> > > 可以把登记邮箱或者 license 发到 [hi@benn.app](mailto:hi@benn.app) ，一般是因为过期了。
> > 
> > 
> > 我刚买到一个新 key ，但是也遇到上面的 error message，刚把注册邮箱发到了你指定的地址，期待问题能解决，谢谢！
> 
> 没用兄弟，猜你也是Mac平台吧？解决方案就是完整卸载重新安装，再激活key就行了，代价就是失去了所有的对话...很显然，是一个恶性bug

对，我是 macos，已经收到开发者邮件了，是设置了模型特定设置导致的（一个 bug），只要把特定设置撤销掉就可以用了，不用卸载重装
