### ISSUE TITLE
对话记录消失

### ISSUE THREAD

**Issue by Heiseweiye** [Bin-Huang/chatbox#97]
当我重启电脑后，打开软件，之前的对话记录全部消失了。

**Comment by Bin-Huang** [comment]
你好，请问是什么系统？什么版本？系统有没有安装一些清理软件，或者管理员有没有设置自动重置？Chatbox 所有数据都是存储在本地的，如果本地文件被删除就会导致对话记录丢失。

**Comment by Bin-Huang** [comment]
正常来说是不会的，很多用户从来没有遇到这个问题

**Comment by Heiseweiye** [comment]
升级版本会出现这种现象吗

**Comment by Heiseweiye** [comment]
对，但是升级之前就没了，问题不大，也没有什么重要的对话，之后再看看有没有问题

**Comment by chen987long** [comment]
我的也消失了，而且升级新版本后，每次关闭再打开都需要重新输入key，
win10，没有清理，目前版本0.21

**Comment by imeitu** [comment]
> 我的也消失了，而且升级新版本后，每次关闭再打开都需要重新输入key， win10，没有清理，目前版本0.21

我的也是
