### ISSUE TITLE
[BUG] 上下文的消息数量上限 在重启软件后 被重置

### ISSUE THREAD

**Issue by xinhai-ai** [Bin-Huang/chatbox#971]
**Bug Description**
如题，当我在设置里把上下文的消息数量上限改为0并保存后，配置文件里显示已经记录`openaiMaxContextMessageCount`字段为0，且此时再向模型提问也是正确的数量上限制。
但当我关闭程序再启动后，设置里面的上下文的消息数量上限被重置为无限制，配置文件里`openaiMaxContextMessageCount`字段也被改为999

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

1. 修改设置中openai api上下文的消息数量上限为0
2. 关闭软件再次启动
3. 此时上限被重置为无限制

稳定复现

**Expected Results**
重启后上限仍是0

**Actual Results**
重启后上限重置为无限制

**Desktop (please complete the following information):**

-   Operating System: Windows 11 23H2
-   Application Version: 1.0.3

**Comment by JaminYe** [comment]
The same problem

**Comment by Bin-Huang** [comment]
Looks like this issue might be from an older version. If you're still seeing the problem in the latest release, go ahead and reopen this!

随着版本的更新，这个 issue 可能过时了。如果最新版本依然存在这个问题，请随时重新开启这个 issue
