### ISSUE TITLE
[Feature] Associate model settings with chats

### ISSUE THREAD

**Issue by Alex8421** [Bin-Huang/chatbox#974]
**Problem Description**
I wanna use my API key in a cost-/resource- efficient way. Often I ask simple questions, where I only need one answer and am already satisfied. But sometimes I ask complicated things, where I need to chat ~10 messages around. Or sometimes I even want ChatGPT to know the complete chat dedicated to a certain project. But I can only set on a global level, how many messages/tokens shall be used. For my 100 simple requests, I always use the same chat, it's annoying to always open a new chat here. But I cannot define that those simple requests only take one message, while the complex requests should take more messages.

**Proposed Solution**
These model settings that are currently global (how many tokens/messages to take in) should be associated to each chat. Every chat starts with the settings that were choosen as global default, but in the chat settings, one can specify that this chat only takes in one message, while this one should take in 8, while all other chats should take in 20 for example.

**Additional Context**
Great app, thanks for developing!

**Comment by hyue418** [comment]
+1

**Comment by zhbery** [comment]
+1

**Comment by Bin-Huang** [comment]
With the version update, this issue might be outdated. Those features have been implemented, try the latest version.
