### ISSUE TITLE
[BUG] Tokenizer Estimation is not accurate.

### ISSUE THREAD

**Issue by anogkongda** [Bin-Huang/chatbox#977]
https://github.com/Bin-Huang/chatbox/blob/236f87bc0443e3f4f8599cf99d2384a19cbb181c/src/packages/utils.ts#L29

GPT-3 Tokenizer is deprecated. It needs 2-3 token to encode Chinese characters.

While for the latest GPT-3.5 and GPT-4, they use "cl100k_base", which needs only 1 token for frequent Chinese characters.

<img width="624" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/22041196/ee5bbb3a-1a54-4eb7-97cf-6486430dc659">

For example.

In chatbox, "你叫文心一言" needs 20 token
<img width="207" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/22041196/ffa8aa47-c62c-4090-acc8-86d3f8c81d53">

While use tiktoken, "你叫文心一言" needs 7 token
<img width="582" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/22041196/1f31ff33-40e8-4f31-b401-d927d85a09d5">

**Comment by Bin-Huang** [comment]
Can you please provide a link to your screenshot or some related documentation for reference?

**Comment by anogkongda** [comment]
https://github.com/openai/tiktoken/blob/main/tiktoken/model.py#L21

**Comment by anogkongda** [comment]
Another reference from openAI's documents.
https://platform.openai.com/docs/guides/gpt/managing-tokens
<img width="894" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/22041196/ab429185-08a5-4005-8a9d-317dd083e2ae">

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases
The new version has made relevant improvements, give it a try!
