### ISSUE TITLE
在答案没生成完的时候不能选中需要的部分复制[BUG]

### ISSUE THREAD

**Issue by xueReact** [Bin-Huang/chatbox#978]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**

-   Operating System: [e.g. macOS]
-   Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

---

**Bug 描述**
清晰简洁地描述这个 bug 是什么。

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：

1. 前往 "......"
2. 点击 "......"
3. 滚动到 "......"
4. 发现了这个 bug。

**期望结果**
请清晰简洁地描述预期的行为。

**实际结果**
请清晰简洁地描述实际的行为。

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**

-   操作系统：[例如 macOS]
-   应用程序版本：[例如 2.0.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by hyue418** [comment]
+1

**Comment by kingxiaofire** [comment]
+1

**Comment by lovitus** [comment]
+1

**Comment by Bin-Huang** [comment]
这个问题在新版本中改进了。以前是整条消息在生成过程中都不能复制，现在是除了正在生成的段落、其他已经生成的段落都是可以复制的了。

**Comment by laohubb** [comment]
> 这个问题在新版本中改进了。以前是整条消息在生成过程中都不能复制，现在是除了正在生成的段落、其他已经生成的段落都是可以复制的了。

想问下大佬是怎么解决这个问题的，markdown-it生成出来的html内容通过dangerouslysetinnerhtml来赋值会导致整个盒子重复渲染，想知道处理思路，感谢。

**Comment by Wjling2** [comment]
> > 这个问题在新版本中改进了。以前是整条消息在生成过程中都不能复制，现在是除了正在生成的段落、其他已经生成的段落都是可以复制的了。
> 
> 想问下大佬是怎么解决这个问题的，markdown-it生成出来的html内容通过dangerouslysetinnerhtml来赋值会导致整个盒子重复渲染，想知道处理思路，感谢。

请问怎么解决的呢
