### ISSUE TITLE
[Feature] Support Ollama local LLM

### ISSUE THREAD

**Issue by giacomorebonato** [Bin-Huang/chatbox#979]
**Problem Description**

[Ollama](https://ollama.ai) offers an easy way to run models locally, but not a GUI for conversations.

**Proposed Solution**

Integrate Chatbox GUI with [Ollama](https://ollama.ai) backend.

**Comment by Bin-Huang** [comment]
It is already supported in the new version.
在新版本已经支持了
https://github.com/Bin-Huang/chatbox/releases

**Comment by bradwbradw** [comment]
@Bin-Huang Would you be so kind as to provide an example describing how to integrate with a local Ollama model?
