### ISSUE TITLE
You didn't provide an API key.

### ISSUE THREAD

**Issue by tetryl-boy** [Bin-Huang/chatbox#98]
API Request Failed:

Error from OpenAI: 401  {
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

复制粘贴了API KEY但是还是提示没有。API: sk-XXXXXXXXXXXXXXXXXXX

**Comment by renjieQ** [comment]
setting里，复制粘贴你的api key，save之后，应该就能正常使用了。
