### ISSUE TITLE
[Feature] Sperated config for each conversation

### ISSUE THREAD

**Issue by thtTNT** [Bin-Huang/chatbox#980]
**Problem Description**
Each conversation will have a different requirement. For example, if there is a conversation about translation, it can only consider the latest message I have sent with GPT-4. But for programming assistants, it is better to consider the latest 6 messages with GPT-3.5.

**Proposed Solution**
Is that possible to have a default configuration and some customized configuration for each conversation? It is so helpful to prevent us from changing the params when using different conversations.

**Comment by Bin-Huang** [comment]
These features were implemented quite a while ago. Try upgrading to the latest version, then click on conversation edit to enable special conversation settings. This should be exactly what you're looking for
