### ISSUE TITLE
[Feature] Add timestamps

### ISSUE THREAD

**Issue by donuts-are-good** [Bin-Huang/chatbox#982]
**Problem Description**
There is no problem, but the feature I have in mind would add a timestamp to posts/replies

**Proposed Solution**
Perhaps the timestamp could be located near the token count and model name under the posts, like you see in this photo:

<img width="684" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/96031819/7875f2f8-9a5f-436b-93a3-3335844279c7">

**Comment by Bin-Huang** [comment]
I'm quite curious, under what circumstances would you need the timestamps of messages? ☺️☺️

**Comment by donuts-are-good** [comment]
I have threads with the AI where the conversation spans multiple days. Sometimes I'll look back and want to know when a specific thing was said, but can't find a timestamp for it. This isn't a "vital" feature, it's just "nice to have" for times like this. 

Thank you for the app, you're doing great 😄

**Comment by Bin-Huang** [comment]
It seems that I often encounter similar situations without realizing it. Thank you for your suggestion.

**Comment by donuts-are-good** [comment]
I appreciate your time, thank you for building a really cool app. Have a good weekend.
