### ISSUE TITLE
API Error: {"error":{"message":"Internal server error","type":"auth_subrequest_error","param":null,"code":"internal_error"}}

### ISSUE THREAD

**Issue by sslisen** [Bin-Huang/chatbox#983]
几天遇到API Error: {"error":{"message":"Internal server error","type":"auth_subrequest_error","param":null,"code":"internal_error"}} An error has occurred with OpenAI API, which is usually caused by incorrect settings or account issues. Please check your AI settings and account status, or [click here to view the FAQ document](https://chatboxai.app/redirect_app/faqs/en).问题。
升级前是1.0.4版本，发现这个问题后去升级了1.1.0版本。还是同样的问题，我去openai看了账号状态是正常，APIkey重置了一个，问题还是存在。

**Comment by hrd201** [comment]
我也是，问题是一样的

**Comment by xiaochen0517** [comment]
一样的问题

**Comment by mqhol** [comment]
一样的问题

**Comment by sslisen** [comment]
> 我也是，API Error: {"error":{"code":502,"message":"Bad gateway.","param":null,"type":"cf_bad_gateway"}}
> 
> 遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，问题是一样的

我专门去看了账户状态是正常的，我删除了老的API key，又重新创建了一个，还是报错。

**Comment by sslisen** [comment]
> 我也是，API Error: {"error":{"code":502,"message":"Bad gateway.","param":null,"type":"cf_bad_gateway"}}
> 
> 遇到了来自 OpenAI API 的错误，一般是由错误设置或账户问题引起的。请检查 AI 设置和账户情况，问题是一样的
检查了账户和设置都没问题，KEY也重置了。
![image](https://github.com/Bin-Huang/chatbox/assets/59131974/c2119a74-7c21-4516-97f9-d8f3e6d83ed9)
![image](https://github.com/Bin-Huang/chatbox/assets/59131974/579fbb51-f7b0-4c62-b1a0-d274bc1f8b40)

**Comment by csj5588** [comment]
same question

**Comment by marskzj** [comment]
API Error: {"error":{"code":502,"message":"Bad gateway.","param":null,"type":"cf_bad_gateway"}}

I confirm that there is no problem with my KEY

**Comment by chen4y89** [comment]
openai正在修复该问题
修复进度请移步https://status.openai.com/

**Comment by sslisen** [comment]
> openai正在修复该问题 修复进度请移步https://status.openai.com/

原来是openai的问题，现在等着修复就行了。感谢

**Comment by sslisen** [comment]
openai的问题 等待openai修复API服务即可。感谢 @chen4y89
