### ISSUE TITLE
[BUG]提交数学运算的时候，貌似会吃掉 乘号。

### ISSUE THREAD

**Issue by nonozone** [Bin-Huang/chatbox#984]
<img width="792" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/1277444/a3251c48-9094-4767-9130-0d56c147ad7d">
<img width="828" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/1277444/ae1893ad-6928-45d0-bcd9-f7fc82a1c49a">
如图，这里可能需要转义

**Comment by Bin-Huang** [comment]
只是在显示时被当成 markdown 渲染了，但是 AI 理解上是没有问题的，我看看如何优化

**Comment by pandacase** [comment]
当你手动使用转义符的时候，AI就会跟着你使用转义符，此时就不会被当作markdown渲染

**Comment by Bin-Huang** [comment]
你可以手动添加转义符号，或者在设置中关闭markdown渲染。
