### ISSUE TITLE
[Other]关于Chatbox-AI 3.5

### ISSUE THREAD

**Issue by jhmclean** [Bin-Huang/chatbox#987]
请问 设置-模型 中的Chatbox-AI是版主开发的吗，背后的模型是ChatGPT3.5么
![image](https://github.com/Bin-Huang/chatbox/assets/32117922/68dff274-11e5-4136-8cdf-d5d5b2c48df9)

**Comment by Bin-Huang** [comment]
可以发邮件询问，但应该是你想要的。
