### ISSUE TITLE
[Feature] 联网模式

### ISSUE THREAD

**Issue by QihanZhao** [Bin-Huang/chatbox#989]
仓主好，请问可否增加联网功能，几个月前您说在在路上，是暂时搁置了吗

**Comment by Bin-Huang** [comment]
其实很多功能我都开发实验过了，但是效果都不够好（对用户来说，每次回答的 token 成本过高），这也是所有三方客户端都存在的问题。具体原因我之前发过一条推文： https://x.com/benn_huang/status/1715363282239053943?s=20

目前我也在持续跟进和研究任何潜在的优化方案。
