### ISSUE TITLE
[Other]v1.1.1的markdown展示没旧版好了

### ISSUE THREAD

**Issue by hyue418** [Bin-Huang/chatbox#990]
v1.1.1的markdown呈现的代码高亮和旧版不同了，很多该高亮的代码没有高亮，代码看起来很不方便，旧版的配色和高亮模式就很好

**Comment by JerryWesler** [comment]
是的，我也有这种感受

**Comment by Bin-Huang** [comment]
只是代码高亮吗？还有其他地方吗，比如其他 markdown 元素？

**Comment by hyue418** [comment]
> 只是代码高亮吗？还有其他地方吗，比如其他 markdown 元素？

目前我markdown只用到了代码上，没有发现其他问题
