### ISSUE TITLE
[BUG] 程序最大化后关闭再次启动的窗口大小恢复问题

### ISSUE THREAD

**Issue by ATFmxyl** [Bin-Huang/chatbox#991]
**Bug Description**
Please provide a clear and concise description of what the bug is.

**Steps to Reproduce**
Please provide the steps to reproduce the bug:

1. Go to "..."
2. Click on "..."
3. Scroll down to "..."
4. Observe the bug.

**Expected Results**
Please provide a clear and concise description of what you expected to happen.

**Actual Results**
Please provide a clear and concise description of what actually happened.

**Screenshots**
If possible, please add screenshots to help explain the issue.

**Desktop (please complete the following information):**

-   Operating System: [e.g. macOS]
-   Application Version: [e.g. 2.0.1]

**Additional Context**
Please provide any additional context about the issue, such as interactions with other software or applications.

---

**Bug 描述**
程序的最大化状态不能正确识别

**重现步骤**
1.启动程序
2.点击窗口最大化
3.关闭程序
4.再次启动程序
5.此时无法恢复最大化之前的状态

**期望结果**
在最大化状态下关闭程序后,下一次启动程序应该不能再继续最大化,而是恢复窗口状态

**实际结果**
无法恢复最大化之前的窗口大小

**截图**
如果可行，添加截图以帮助解释问题。

**桌面端（请填写以下信息）：**

-   操作系统：Windows 10 22H2
-   应用程序版本：1.1.1

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by Bin-Huang** [comment]
我试着理解一下，你的意思是：最大化后关闭，下次启动依然是最大化，你希望改成恢复成最大化前的状态，对吗？
如果是这样，我想知道具体的原因是什么？因为我理解下次启动应该恢复成退出前的状态，也就是最大化的状态。

**Comment by ATFmxyl** [comment]
> 我试着理解一下，你的意思是：最大化后关闭，下次启动依然是最大化，你希望改成恢复成最大化前的状态，对吗？ 如果是这样，我想知道具体的原因是什么？因为我理解下次启动应该恢复成退出前的状态，也就是最大化的状态。

我的意思是这样
参考chrome浏览器的操作行为
1.正常启动程序,应该在窗口状态,然后点击最大化后,最大化图标会变成切换回窗口状态,同时程序也会最大化到整个屏幕
2.这个时候关闭掉程序,那么下次启动,程序也还是在最大化状态,且右上角的按钮应该是最小化,窗口化,和关闭按钮,而不是继续是最大化按钮

就是程序的窗口大小是恢复了,但是程序的最大化或者窗口化的状态没有记住和反映到右上角的那个最大化按钮那里

**Comment by ATFmxyl** [comment]
> 我试着理解一下，你的意思是：最大化后关闭，下次启动依然是最大化，你希望改成恢复成最大化前的状态，对吗？ 如果是这样，我想知道具体的原因是什么？因为我理解下次启动应该恢复成退出前的状态，也就是最大化的状态。

行为上大概是这样
我注意到congif.json里面存储了这个信息
```json
	"windowState": {
		"width": 1574,
		"height": 945,
		"x": 541,
		"y": 45
	},
```

那么是否可以再添加一个参数,用于记录当前的窗口状态,然后下一次启动的时候判断存储的状态来进行恢复

下面是逻辑
参数 showstate 记录是 最大化/普通显示 的状态

当点击最大化的时候,记录最大化之前的窗口大小和最大化的状态,关闭程序后的下一次启动则用最大化显示来启动,这个时候再点击最大化按钮(此时叫向下还原按钮)则使用最大化之前的窗口大小和位置来进行恢复

如果启动程序时上一次记录不是最大化状态,则直接用记录的窗口大小和位置进行恢复

**Comment by Bin-Huang** [comment]
It is already supported in the new version.
在新版本已经支持了
https://github.com/Bin-Huang/chatbox/releases

**Comment by ATFmxyl** [comment]
> It is already supported in the new version. 在新版本已经支持了 https://github.com/Bin-Huang/chatbox/releases

感谢😄

**Comment by ATFmxyl** [comment]
> It is already supported in the new version. 在新版本已经支持了 https://github.com/Bin-Huang/chatbox/releases

测试了一下,似乎还是不太正确

在最大化后,属性mode设置成了0

但是同时记录的程序窗口的坐标xy在我这里变成了-8,宽高也发生了变化

然后在最大化状态下启动后,没有办法通过取消最大化来还原原来的窗口位置和大小

应该是要记录并还原最大化前的窗口位置和大小🤔

**Comment by Bin-Huang** [comment]
Windows 吗

**Comment by ATFmxyl** [comment]
> Windows 吗

是的,Windows平台

**Comment by Bin-Huang** [comment]
我在 Windows 是正常的，你方便提供以下视频吗？

**Comment by ATFmxyl** [comment]
> 我在 Windows 是正常的，你方便提供一下视频吗？

好的,大概是这个情况

https://github.com/Bin-Huang/chatbox/assets/33374512/e16c482e-142a-49b1-aa6b-6efc811f2e46

**Comment by xzy111222333** [comment]
我也遇到了相同的bug，最大化无法退出，重启电脑后还是最大化右上角没有X键

**Comment by xzy111222333** [comment]
<img width="1280" alt="image" src="https://github.com/Bin-Huang/chatbox/assets/143894930/6858e239-ea7c-4478-9402-a0fd41bb2573">
