### ISSUE TITLE
[BUG] 渲染 Markdown 内的 URL 图片时请求地址的查询字符串中错误地编码了 `&`

### ISSUE THREAD

**Issue by MurphyLo** [Bin-Huang/chatbox#993]
**Bug 描述**

在Chatbox中，当尝试使用包含多个查询字符串的URL的markdown来渲染图片时（例如，`![600x200像素的占位图，使用了pt-sans字体的文本"PT Sans"](https://placehold.co/600x200?font=pt-sans&text=PT%20Sans)`），应用程序似乎错误地处理了URL。URL中的"&"字符被转义为"\&amp;"，导致形成了如`https://placehold.co/600x200?font=pt-sans&amp;text=PT%20Sans`的错误请求URL。

**重现步骤**

1. 在Chatbox中插入一个包含多个查询字符串的URL的markdown图片，并提交（以前述URL为例）。
2. 观察请求的URL和图片的渲染情况。

**期望结果**

请求的URL应保持查询字符串的原始格式，从而使图片正确渲染。

**实际结果**

URL中的"&"字符被解释为"\&amp;"，导致请求的URL格式错误，图片渲染不正确。因为chatbox错误地编码了查询字符串。

**截图**

<img width="1014" alt="chatboxbug" src="https://github.com/Bin-Huang/chatbox/assets/69335326/8b5e369e-3363-4d07-9974-c465676ed5a0">

**桌面端（请填写以下信息）：**

- 操作系统：macOS 14.0/Windows 11
- 应用程序版本：Chatbox 1.1.1

**其他上下文**

- 此问题似乎与Chatbox渲染markdown时的URL处理和解析有关，可能是字符`&`的HTML实体编码处理不当或重复编码导致的错误。
- 占位图的查询字符串[说明文档](https://placehold.co)

**Comment by Bin-Huang** [comment]
这个问题在新版本中修复了
