### ISSUE TITLE
[Other] 如何通过chatbox 调用dall-e ？

### ISSUE THREAD

**Issue by LightSofa** [Bin-Huang/chatbox#994]
想问下，下图里的这种效果是怎么做到的？

![20231027142531](https://github.com/Bin-Huang/chatbox/assets/2208855/92a5bcc8-1e1c-4bd3-8b3b-0f379e1d3588)

**Comment by Bin-Huang** [comment]
你好，请问你是如何得到了这样的截图？似乎正在使用还未公开的 DALL-E 3 接口？

**Comment by Bin-Huang** [comment]
https://github.com/Bin-Huang/chatbox/releases/
This feature has been updated in the new version.
