### ISSUE TITLE
🔍[BUG]Intermittent Paste Failure in Chatbox 1.1.1 on Windows 11 //// "Chatbox 1.1.1在Windows 11中偶发粘贴故障"🔍

### ISSUE THREAD

**Issue by MontDawgg** [Bin-Huang/chatbox#996]
🔍**Bug Description**
There is an inconsistency in the paste function within the text editor of the Chatbox application.

🔍**Steps to Reproduce**
The steps to reproduce the issue are:

Launch the Chatbox application.
Attempt to edit a system or user message.
Attempt to paste a body of text into the text box.

🔍**Expected Results**
The anticipated result is that the copied text should be successfully pasted into the text box.

🔍**Actual Results**
However, 8 out of 10 times, an attempt to paste results in the dialog box simply closing, with no resultant pasted text.

🔍**Screenshots & Video**
Here is a video showcasing the problem. 

https://github.com/Bin-Huang/chatbox/assets/133587103/bd8fef96-ddb5-418f-8c8a-1976bde17058

🔍**Desktop** (please complete the following information):

Operating System: Windows 11
Application Version: Chatbox 1.1.1

🔍**Additional Context**
There is no additional context provided. This inconsistency has been encountered in both user and system messages. The bug does not allow replication every time; there are instances where the paste function does work properly (approximately 2 out of 10 times). This inability to paste a text consistently hampers the message editing process.🔍

__________________________________________

🔍错误描述
Chatbox应用中的文本编辑器在粘贴功能上存在不一致性。

🔍复现步骤
复现这个问题的步骤如下：

启动Chatbox应用。
尝试编辑系统或用户消息。
尝试将文本粘贴到文本框中。
🔍期望结果
预期的结果是复制的文本应该成功地被粘贴到文本框。

🔍实际结果
然而，10次尝试中有8次，粘贴文本会导致对话框直接关闭，没有粘贴文本的结果。

🔍截屏
🔍错误描述
Chatbox应用中的文本编辑器在粘贴功能上存在不一致性。

🔍复现步骤
复现这个问题的步骤如下：

启动Chatbox应用。
尝试编辑系统或用户消息。
尝试将文本粘贴到文本框中。
🔍期望结果
预期的结果是复制的文本应该成功地被粘贴到文本框。

🔍实际结果
然而，10次尝试中有8次，粘贴文本会导致对话框直接关闭，没有粘贴文本的结果。

🔍桌面（请提供以下信息）：

操作系统：Windows 11
应用程序版本：Chatbox 1.1.1
🔍附加上下文
没有提供附加上下文。这种不一致性在用户和系统消息中都有遇到。这个错误不允许每次都能复制，有时粘贴功能是正常的（大约10次中有2次）。这种不能一致性的粘贴文本妨碍了消息编辑流程。🔍

🔍桌面（请提供以下信息）：

操作系统：Windows 11
应用程序版本：Chatbox 1.1.1
🔍附加上下文
没有提供附加上下文。这种不一致性在用户和系统消息中都有遇到。这个错误不允许每次都能复制，有时粘贴功能是正常的（大约10次中有2次）。这种不能一致性的粘贴文本妨碍了消息编辑流程。🔍

**Comment by Bin-Huang** [comment]
Excellent, detailed feedback❤️️. Also, I've been encountering this issue recently as well. Let me investigate to see what the exact reason might be...

**Comment by Bin-Huang** [comment]
I still remember this bug, and it has been fixed in subsequent versions.
