### ISSUE TITLE
[BUG]订阅到期后，更换license时，点击license输入栏无响应，点击取消激活也无响应。预期，可以删除旧的license更换为新的license

### ISSUE THREAD

**Issue by neao007** [Bin-Huang/chatbox#998]
**Bug 描述**
订阅到期后，更换license时，点击license输入栏无响应，点击取消激活也无响应

**重现步骤**
请提供能够让我们重现这个 bug 的步骤：

1. 前往 "设置-模型-chatAI"
2. 点击 "取消激活"或者点击“license输入框”无响应
3. 发现了这个 bug。

**期望结果**
可以删除旧的license换成新的license。

**实际结果**
点击输入框或者取消激活没反应没办法更换。

**截图**
![image](https://github.com/Bin-Huang/chatbox/assets/149362187/c174d46b-62f9-4fe4-a681-763025240a77)

**桌面端（请填写以下信息）：**

-   操作系统：[macOS  10.15.6]
-   应用程序版本：[1.1.1]

**其他上下文**
在这里提供关于问题的任何其他上下文，例如与其他软件或应用程序的交互等。

**Comment by CallMeR** [comment]
Same here

**Comment by TigerCatRabbit** [comment]
I also discovered this issue and found a way to bypass this bug.
Simply backup a piece of data without an API key&license in the other options in the settings, and then restore the backup data to reset the software. After that, you can fill in the new license. It should be noted that if you do not want to lose previous records, you need to back up data other than the license during backup.
![image](https://github.com/Bin-Huang/chatbox/assets/24245842/484bade7-6614-49f1-aa14-f609ad1a0adf)

**Comment by Bin-Huang** [comment]
Fixed in v1.1.2
