### ISSUE TITLE
[Feature] Folder structure for chats (with tags per folder/chat)

### ISSUE THREAD

**Issue by thijse** [Bin-Huang/chatbox#999]
**Problem Description**
Often, I break up chats different chats, to reduce token usage and for legibility, especially for programming tasks.  I use the ChatBox so often that the list of chats is growing very large!

**Proposed Solution**
I would like to group these chats in different folders (and even subfolders). This is something I have not seen in any other application. For searching through this list of chats, it would be great if I could add tags, or that ChatBox would even auto generate these.

**Comment by Bin-Huang** [comment]
This issue duplicates #676. Closing for better organization. Thank you! 😆
